### ISSUE TITLE
Template module not happy with UTF-8 chars in filenames

### ISSUE THREAD

**Issue by gilou** [ansible/ansible#10110]
Issue Type: Bug Report
Ansible Version: 1.8.2, 1.9 (devel a63e4c595f)
Environment: Ubuntu 14.10
Summary: 
Using template module, if the source file contains UTF-8 characters in its name, it makes it barf.

Steps To Reproduce:
test_utf8.yml

```
- hosts: superserver
  tasks:
    - name: Test utf
      template: src=héhé.txt dest=/tmp/hihi.txt
```

Create héhé.txt, run the playbook.

Expected Results: File copied (and rendered).
Actual Results:

```
fatal: [superserver] => Traceback (most recent call last):
  File "/home/Technique/Code/ansible/lib/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/Technique/Code/ansible/lib/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/Technique/Code/ansible/lib/ansible/runner/__init__.py", line 1063, in _executor_internal_inner
    self.callbacks.on_unreachable(host, result.result)
  File "/home/Technique/Code/ansible/lib/ansible/callbacks.py", line 460, in on_unreachable
    results = utils.to_bytes(results)
  File "/home/Technique/Code/ansible/lib/ansible/utils/__init__.py", line 1284, in to_bytes
    return value.encode('utf-8')
AttributeError: 'dict' object has no attribute 'encode'
FATAL: all hosts have already failed -- aborting
```

Haven't looked a lot further, as I was in a hurry, so I just renamed my files.. It also happens if the directory you're work in has accents in it (I had something like /home/gilles/Technique/Déploiement, and it wouldn't work).
Might get into it deeper if I have time..

**Comment by abadger** [comment]
Ugh, this is happening in part because of a fix I just added I think.  Somewhat strange that this is only triggering with non-ascii though.  Although the code deals with encoding and decoding I would expect that dict vs string would be independent of whether the value was non-ascii.

I'll see if I can reproduce.  If so I should be able to get out a quick fix.

**Comment by abadger** [comment]
Ugh.  Okay, this is going to be a bit harder than I thought.  I was able to fix the initial traceback rather quickly here: https://github.com/ansible/ansible/commit/35321ec642b5f4f1148d5621c6d76d0527a220e9

But that was just hiding the real error:

```
$ ansible-playbook utf8.yml                            *[devel]  (14:16:10)

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Test utf] ************************************************************** 
fatal: [localhost] => {'msg': "UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 29: ordinal not in range(128)", 'failed': True}
fatal: [localhost] => {'msg': "UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 29: ordinal not in range(128)", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/badger/utf8.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by abadger** [comment]
That commit should finish off the fix.  I also tested this in the v2 tree and everything worked as expected there.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by gilou** [comment]
Works on the devel branch for me, thanks ;)

**Comment by L-B** [comment]
Hello,

I'm still having issues with that on 2.5.1, as per #27262 that I opened last year. Anything I can do to help getting it fixed?

Thanks

**Comment by yodatak** [comment]
Same on 2.5.2

**Comment by L-B** [comment]
@yodatak: it's been dealt with in #27262 and the fix has just been released in 2.5.3.
