### ISSUE TITLE
inventory file variables, int vs str, failed with error

### ISSUE THREAD

**Issue by jtktam** [ansible/ansible#11151]
# version info

ansible 2.0.0 (devel d8c8ca11cf) last updated 2015/06/03 12:29:49 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b138411671) last updated 2015/06/02 13:10:38 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 1276420a3a) last updated 2015/05/29 09:20:33 (GMT -400)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/02 13:11:12 (GMT -400)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/02 13:11:44 (GMT -400)
  configured module search path = None
# inventory file

```
[masters]
dev-master-01 ansible_ssh_host=x.x.x.x zookeeper_myid=1
```
# playbook

```

---
- hosts: masters
  remote_user: root

  vars: []

  tasks:

  - name: Set zookeeper myid
    lineinfile: dest=/etc/zookeeper/conf/myid regexp='^(.*)replace this text' line="{{ zookeeper_myid }}"
```
# error output

```
PLAY: ***************************************************************************

TASK [Set zookeeper myid] *******************************************************
fatal: [dev-master-01]: FAILED! => {"msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1433350523.72-134714554218846/lineinfile\", line 2211, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1433350523.72-134714554218846/lineinfile\", line 374, in main\r\n    ins_aft, ins_bef, create, backup, backrefs)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1433350523.72-134714554218846/lineinfile\", line 269, in present\r\n    lines.append(line + os.linesep)\r\nTypeError: unsupported operand type(s) for +: 'int' and 'str'\r\n", "failed": true, "changed": false, "parsed": false, "invocation": {"module_name": "lineinfile", "module_args": {"dest": "/etc/zookeeper/conf/myid", "regexp": "^(.*)replace this text", "line": 1}}}

NO MORE HOSTS LEFT **************************************************************

PLAY RECAP **********************************************************************
dev-master-01              : ok=0    changed=0    unreachable=0    failed=1
```
# how to make it work

changing the inventory file to (zookeeper_myid from 1 to a):

```
[masters]
dev-master-01 ansible_ssh_host=104.236.15.166 zookeeper_myid=a
```
# working output

```
PLAY: ***************************************************************************

TASK [Set zookeeper myid] *******************************************************
changed: [dev-master-01]

PLAY RECAP **********************************************************************
dev-master-01              : ok=0    changed=1    unreachable=0    failed=0
```
# /etc/zookeeper/conf/myid

```
a
```

**Comment by jtktam** [comment]
changing the value of the variable 1 to a shows the variable is being picked up. 

i need to associate the myid to a host so that the playbook can correctly assign the value to the conf file

**Comment by bcoca** [comment]
if you want to use it as a string have you tried?:

```
dev-master-01 ansible_ssh_host=x.x.x.x zookeeper_myid="1"
```

**Comment by bcoca** [comment]
another possible solution:

```
line="{{ zookeeper_myid |str}}"
```

**Comment by jtktam** [comment]
Downgrading to 1.9.1 solved the problem.  tried the above suggestions and they didn't work

**Comment by jimi-c** [comment]
Looking at this issue, I believe devel is doing the correct thing - the value is clearly meant to be an integer and is correctly keeping the type after parsing the inventory. In 1.9.x, it's being brought in as a string, which presents other problems when users expect things to be integers (or other values like booleans, etc.). So to fix this, I'd suggest we make sure it's converted to a string in lineinfile, not anywhere else during the parsing, nor requiring filters.

**Comment by jimi-c** [comment]
Revisiting again, and it appears that this has been resolved as of Ansible 2.1:

<pre>
# cat 11151_source 
hi, replace this text
# cat 11151.yml 
- hosts: localhost
  vars:
  - zookeeper_myid: 1
  tasks:
  - copy: src=11151_source dest=/tmp/11151.txt
  - name: Set zookeeper myid
    lineinfile: dest=/tmp/11151.txt regexp='^(.*)replace this text' line="{{ zookeeper_myid }}"
# ansible-playbook -vv 11151.yml
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: 11151.yml ************************************************************
1 plays in 11151.yml
PLAY [localhost] ***************************************************************
TASK [setup] *******************************************************************
ok: [localhost]
TASK [copy] ********************************************************************
task path: /root/testing/11151.yml:5
ok: [localhost] => {"changed": false, "checksum": "69b9bc86e25bbbd829d14a2ac23d0d373b084e33", "dest": "/tmp/11151.txt", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/tmp/11151.txt", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 22, "state": "file", "uid": 0}
TASK [Set zookeeper myid] ******************************************************
task path: /root/testing/11151.yml:6
changed: [localhost] => {"backup": "", "changed": true, "msg": "line replaced"}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
# cat /tmp/11151.txt 
1
</pre>

As such, we'll go ahead and close this issue now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rajeshvaya** [comment]
There is still an issue if the string begins with "0". There is this very very strange issue where if the variable's value contains all digits where each digit is below 7 and starts with 0 then the entire variable is messed up

See below 3 examples

### Not working - example 1
```yml

- hosts: localhost
  vars:
  - sample: 04123459
  tasks:
  - debug:
      msg: "This is my value {{sample}}"
``` 

```
PLAYBOOK: 11151.yml ************************************************************
1 plays in 11151.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
task path: /Users/rajesh/www/aswat/aswat/ziwo/deployment/ansible-general/11151.yml:5
ok: [localhost] => {
    "msg": "This is my value 1091375"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

---


### Working - example 2

However if the value **doesn't start with "0" then it works fine**


```yml

- hosts: localhost
  vars:
  - sample: 14123457
  tasks:
  - debug:
      msg: "This is my value {{sample}}"
```

```
PLAYBOOK: 11151.yml ************************************************************
1 plays in 11151.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
task path: /Users/rajesh/www/aswat/aswat/ziwo/deployment/ansible-general/11151.yml:5
ok: [localhost] => {
    "msg": "This is my value 14123457"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

---

### Working - example 3

However if the value **starts with "0" but also has a digit above 7 then too it works fine**


```yml

- hosts: localhost
  vars:
  - sample: 04123459
  tasks:
  - debug:
      msg: "This is my value {{sample}}"
```

```
PLAYBOOK: 11151.yml ************************************************************
1 plays in 11151.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
task path: /Users/rajesh/www/aswat/aswat/ziwo/deployment/ansible-general/11151.yml:5
ok: [localhost] => {
    "msg": "This is my value 04123459"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

**Comment by rajeshvaya** [comment]
@jimi-c can you please give your opinion on the above comment?

**Comment by philfry** [comment]
> Not working - example 1
``` yaml
- hosts: localhost
  vars:
  - sample: 04123459
```
I suppose you meant `sample: 04123457`, because 04123457 oct is 1091375 dec.
Python interprets numbers that start with a zero as octal and converts it to decimal. If the octal string contains a numeral > 7 python throws a syntax error. I think ansible tries something like `int()` on the variable, and if that fails, the variable content is interpreted as string and left intact.
```python
>>> print 4123457
4123457
>>> print 04123457
1091375
>>> print 04123459
  File "<stdin>", line 1
    print 04123459
                 ^
SyntaxError: invalid token
```

**Comment by rajeshvaya** [comment]
@philfry thanks! that helps.

I then set the Ansible variable as follows and it works -  `"'04123456'"`
