### ISSUE TITLE
target node disk is full, ansible didn't throw useful message

### ISSUE THREAD

**Issue by linbo** [ansible/ansible#11210]
Hi,

My target node is Ubuntu 1204 64 bit, and ansible version is 1.7.1.

When node disk is full, ansible failed but told useless message.

```
$ ansible target_host -i inventory -m shell -a "pwd"
target_host | FAILED >> {
    "failed": true,
    "msg": "",
    "parsed": false
}
```

after we remove $HOME/.ansible/tmp directory, correct error message could be displayed.

```
$ ansible target_host -i inventory -m shell -a "pwd"
target_host | FAILED => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433819395.41-82744649514542 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433819395.41-82744649514542 && echo $HOME/.ansible/tmp/ansible-tmp-1433819395.41-82744649514542, exited with result 1: mkdir: cannot create directory `/home/yunba/.ansible/tmp': No space left on device
```

**Comment by bennojoy** [comment]
this is fixed in the 1.9 release and would give the error "'No space left on device' so can you please uprade to the latest stable release.

**Comment by clebio** [comment]
Hello, I've been running into this issue (well, more correctly, #12870 ), and tried updating to 1.9.4, but still experience it. I can reproduce it pretty reliably:

I have a three-node Kafka cluster. It seems Kafka doesn't do well if your restart all three at the same time (via an Ansible playbook). I will use `serial: 33%` in the future, but not providing that option seems to send one of the Kafka nodes into an endless failure mode, which works nicely to fill up disk space due to the log file.

At any rate, this gives me a pretty consistent failure mode:

```
$ ansible -i ~/dev/ec2.py $AUTH tag*kafka -m shell -a 'df -h'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 85, in _executor_hook
    return_data = multiprocessing_runner._executor(host, new_stdin)
  File "/Library/Python/2.7/site-packages/ansible/runner/__init__.py", line 595, in _executor
    self.callbacks.on_unreachable(host, msg)
  File "/Library/Python/2.7/site-packages/ansible/callbacks.py", line 396, in on_unreachable
    display("%s | FAILED => %s" % (host, res), stderr=True, color='red', runner=self.runner)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 517: ordinal not in range(128)
172.19.1.72 | success | rc=0 >>
# snip
172.19.3.209 | success | rc=0 >>
# snip

$ ansible --version
ansible 1.9.4
  configured module search path = None
$ ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None
```

Any pointers? Would you like me to open a new issue?
