### ISSUE TITLE
Old-style output in ansible 2.0

### ISSUE THREAD

**Issue by volkhin** [ansible/ansible#11417]
I tried to find any info about changes in output format in v2.0 but failed. Basically what I want is to get the same output (for both playbooks and simple commands) as it was in v1.9 - plaint stdout, without json wrapper around it with such fields as changed, end, stdout, cmd, start, delta, rc, invocation etc. I didn't see any verbose flags turned on and in the same time no flags to make it more compact. Is it just a changed added in v2.0 or I miss something?

**Comment by jimi-c** [comment]
Hi @volkhin, can you provide an example? I know there is a bug wherein tasks using a `with_` loop always output to the screen, however without using an `-v` flags the output should be very simple and plain without JSON. If that is the case, can you verify you do not have the verbosity level set in any ansible.cfg files (either in the local directory or in /etc/ansible)?

**Comment by volkhin** [comment]
@jimi-c Ok, sure!

```
$ ansible 127.0.0.1 -i ~/deployment/production -m shell -a 'ls /'
127.0.0.1 | SUCCESS => {
    "changed": true,
    "end": "2015-06-30 11:55:51.911830",
    "stdout": "bin\nboot\ndev\netc\nhome\ninitrd.img\nlib\nlib64\nlost+found\nmedia\nmnt\nopt\nproc\nroot\nrun\nsbin\nsrv\nsys\ntmp\nusr\nvar\nvmlinuz",
    "cmd": "ls /",
    "start": "2015-06-30 11:55:51.909958",
    "delta": "0:00:00.001872",
    "stderr": "",
    "rc": 0,
    "invocation": {
        "module_name": "command",
        "module_args": {
            "_raw_params": "ls /",
            "_uses_shell": true
        }
    },
    "stdout_lines": [
        "bin",
        "boot",
        "dev",
        "etc",
        "home",
        "initrd.img",
        "lib",
        "lib64",
        "lost+found",
        "media",
        "mnt",
        "opt",
        "proc",
        "root",
        "run",
        "sbin",
        "srv",
        "sys",
        "tmp",
        "usr",
        "var",
        "vmlinuz"
    ],
    "warnings": []
}
```

What I'm expecting is just plain output of ls command (i.e. the content of stdout field of the json).

**Comment by volkhin** [comment]
As for config files: I checked:
- /etc/ansible\* - no files
- ~/.ansible\* - nothing
- ./ansible\* - nothing
  Is there anything else that can turn on such output?

**Comment by volkhin** [comment]
Ansible is built from trunk, commit 9911a947ed7b23bbd47ab776c8c356d6de3be4eb ( . ./hacking/env-setup && sudo make install)

**Comment by bcoca** [comment]
fixed via a6ba149c496d20410f12a74aee3af615e62c4266

```
ansible -m shell -a 'ls /' testhost
testhost | SUCCESS | rc=0 >>
bin
boot
data
dev
etc
home
lib
lib32
lib64
lost+found
media
mnt
opt
proc
root
run
sbin
service
sys
tmp
usr
varbin
boot
data
dev
etc
home
lib
lib32
lib64
lost+found
media
mnt
opt
proc
root
run
sbin
service
sys
tmp
usr
var
```

**Comment by volkhin** [comment]
It's not fixed! Look at the output: your output doubled, each line is printed twice. @bcoca

**Comment by bcoca** [comment]
seems like i attached the stdout once too  many, fixed in 3b9282fb9034a01d38de98f91864d4fcaf2a39f7

**Comment by volkhin** [comment]
@bcoca cool, thanks! I should have noticed it myself:)
