### ISSUE TITLE
ansible_sudo_pass doesn't work any more

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#11500]
Issue Type:

Bug report

Ansible Version:

```
$ ansible --version 
ansible 2.0.0 (devel 2c9d1257ba) last updated 2015/07/06 16:34:30 (GMT +550)
  lib/ansible/modules/core: (detached HEAD ff69ce7912) last updated 2015/07/03 09:43:55 (GMT +550)
  lib/ansible/modules/extras: (detached HEAD 4e48ef9eca) last updated 2015/07/03 09:43:55 (GMT +550)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/09 18:30:45 (GMT +550)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/09 18:32:50 (GMT +550)
```

Ansible Configuration:

Empty configuration file.

Environment:

Debian wheezy

Summary:

ansible_sudo_pass doesn't work any more. If I set it in the inventory (either directly in the hosts file, or in host_vars/hostname.yml, or group_vars/all.yml), it is as if I haven't specified it at all. If I change it to ansible_become_pass instead, it works as expected.

Note that the MAGIC_VARIABLE_MAPPING in lib/ansible/executor/connection.py mentions only ansible_sudo_password (and ansible_su_password) although the documentation mentions only ansible_sudo_pass and ansible_su_pass. In contrast, both ansible_become_password and ansible_become_pass are mentioned here. But adding ansible_sudo_pass as an alias does not fix the problem (or this would be a pull request). Nor does setting ansible_sudo_password in the inventory.

Steps To Reproduce:

hosts:

```
raven ansible_ssh_host=1.2.3.4 ansible_sudo_pass=xxx
```

playbook.yml:

```
- hosts: raven
  tasks:
    - name: Count lines in /etc/passwd
      command: wc -l /etc/shadow
      sudo: true
```

Invocation:

```
ansible-playbook -i hosts playbook.yml
```

Expected Results:

The sudo task succeeds:

```
changed: [raven] => {"changed": true, "end": "2015-07-06 13:15:18.470655", "stdout": "52 /etc/shadow", "cmd": ["wc", "-l", "/etc/shadow"], "start": "2015-07-06 13:15:18.468512", "delta": "0:00:00.002143", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "wc -l /etc/shadow"}}, "stdout_lines": ["52 /etc/shadow"], "warnings": []}
```

(The above was obtained with ansible_become_pass set instead.)

Actual Results:

The sudo task does not succeed:

```
fatal: [raven]: FAILED! => {"msg": "ERROR! Missing sudo password", "failed": true}
```

**Comment by jimi-c** [comment]
Whoops, sorry for that oversight. I've extended the mapping to check for _pass as well as _password for both su and sudo per the above commit, so this should now be resolved.

Thanks!

**Comment by amenonsen** [comment]
It is not resolved. As I noted in the original report: «But adding ansible_sudo_pass as an alias does not fix the problem (or this would be a pull request). Nor does setting ansible_sudo_password in the inventory.»

**Comment by amenonsen** [comment]
In v1/ansible/playbook/task.py, there's the following code:

```
171         # set only if passed in current task data
172         if 'sudo' in ds or 'sudo_user' in ds:
173             self.become_method='sudo'
174 
175             if 'sudo' in ds:
176                 self.become=ds['sudo']
177                 del ds['sudo']
178             else:
179                 self.become=True
180             if 'sudo_user' in ds:
181                 self.become_user = ds['sudo_user']
182                 del ds['sudo_user']
183             if 'sudo_pass' in ds:
184                 self.become_pass = ds['sudo_pass']
185                 del ds['sudo_pass']
186 
```

But I can't find any equivalent code in HEAD, and in lib/ansible/plugins/connections/ssh.py, we only use become_pass:

```
if self._connection_info.become and self._connection_info.become_pass:
```

If I change become_pass to sudo_pass in ssh.py, it actually starts working again. I think this code is expecting the become_pass to be set based on the sudo_pass somewhere earlier.

**Comment by bcoca** [comment]
that code was made obsolete (we actually did the same at several levels), we should be able to pluck all possible hostvars in the connection_info object, I'll revise that and see what we are missing.

**Comment by bcoca** [comment]
so I think a6aedbcc51e870cb662b5ee3f9615daa4316149e finishes the fix

**Comment by amenonsen** [comment]
Works now, thanks!
