### ISSUE TITLE
ansible-playbook --start-at-task="task in some role" broken in v2

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#11692]
Issue type: Bug report
Ansible version: devel
Ansible configuration: NA
Environment: NA
Summary:

With stable-1.9, ansible-playbook --start-at-task="foo bar" works if the task "foo bar" lives in roles/x/tasks/something.yml, but with devel, it doesn't run anything. Note that for a playbook without roles, --start-at-task works as expected in devel too.

Steps to reproduce:

Use --start-at-task with a task defined in a role within a playbook that includes the role.

Expected results:

The playbook starts at the specified task.

Actual results:

It treats it as an empty playbook.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by tetherit** [comment]
This is unfortunately not fixed :(

```
$ ansible-playbook --forks=20 timeboxes.yml --limit guardhome1 --start-at-task='Install video packages'     

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [guardhome1 -> localhost]

PLAY RECAP *********************************************************************
guardhome1                 : ok=1    changed=0    unreachable=0    failed=0   

ansible-playbook --forks=20 timeboxes.yml --limit guardhome1   0.94s user 0.41s system 35% cpu 3.807 total
$ ansible --version
ansible 2.0.0
  config file = /Users/Hackeron/Development/Xanview/xanview-ansible/ansible.cfg
  configured module search path = None
```

This however runs the requested task in Ansible 1.9.4 :( 

I'm using Ansible from git (2015-10-18 02:40 +0100)

**Comment by brandonheller** [comment]
Adding a comment here; the mailing list didn't provide any help, and I can't reopen this one.
https://groups.google.com/forum/#!topic/ansible-project/AZiEHcpANJY

Like hackeron, I don't see the expected behavior, in my case with 2.0.0-stable.

**Comment by deyvsh** [comment]
I'm seeing this problem with 2.0.0.2.

**Comment by tetherit** [comment]
Can confirm same problem in 2.0.0.2 :(

**Comment by dossy** [comment]
I just tested on `ansible-playbook 2.1.0 (devel 35089c305d)` and it appears to work.  You can see my test case here:

https://github.com/dossy/ansible/tree/test_11692

It is extremely simple, but it proves that the `--start-at-task` functionality still works for the simplest case.

**Comment by cdaniluk** [comment]
On 2.0.0.2, I can consistently reproduce this when running a playbook against multiple hosts. The last host starts at the requested task. In fact, once it gets to the requested task, it gathers tasks again for all hosts. Limiting to one host at a time works around the issue.

**Comment by ArekBe** [comment]
I can also confirm this on 2.0.0.2.
It's happening when all my named tasks are in included files (`tasks/main.yml` has only includes). When I place named task directly to `main.yml`\- it's showing when I add `--list-tasks` to ansible-playbook command.

**Comment by rajpan** [comment]
This consistently happens when multiple hosts are being pushed at the same using the START_AT_TASK command on 2.0.0.2. The commit marked as the fix in June 2015 doesnt seem to be part of the current stable.

**Comment by ghost** [comment]
I'm experiencing --start-at-task not working in v 2.0.1.0 ive tried both just the task name and `<role> : <task_name>` both start at the next role after the one my task is in :(

**Comment by mbarcia** [comment]
I can confirm as well, versions 2.0.0.2 and 2.0.1.0 are still affected.

**Comment by one1zero1one** [comment]
Same for ansible 2.1.0 (devel 6a85da7e0c), `--start-at-task` not working for `tasks/main.yml` having only includes.

**Comment by jimi-c** [comment]
We're looking at addressing the --start-at-task issue via static includes. See here for more details: https://groups.google.com/forum/#!topic/ansible-devel/9aJaoVeRdOg

**Comment by pmackay** [comment]
Were dynamic includes added in v2 knowing they would break `start-at-task` (and other things too from reading that thread)? 

Should this issue be opened again?

**Comment by badbishop** [comment]
Still broken in

```
$ ansible --version
ansible 2.0.2.0
```

Installed today on Mac OS X with pip

**Comment by jimi-c** [comment]
@badbishop the fix will be included in 2.1.

**Comment by ashb** [comment]
This is still broken for me in ansible 2.1.0.0 -- it was working fine on 1.9.6

**Comment by jimi-c** [comment]
@ashb are you using a with loop on the includes?

**Comment by ashb** [comment]
@jimi-c No, no looping includes, but I do have templated includes in the playbook (but not in the role I was trying to start the task at.)

**Comment by cdaniluk** [comment]
I don't even have templated includes. Simple but long playbooks with linear includes. I've even tried stripping things out to simplify things. This is simply broke since 2.0 and no one seems to care. This is a big deal.

**Comment by jhawkesworth** [comment]
@cdaniluk - do you have fact gathering set to implict, explicit or smart in your ansible.cfg?

**Comment by cdaniluk** [comment]
Not set at all.. I believe the default is implicit.

**Comment by jimi-c** [comment]
@ashb ahh, so yes in that case the include will remain "dynamic" as the variables used could come from an inventory source. Add `static: yes` to those and they'll be templated early during parsing time (and fail if the var is unavailable, as it would in 1.9.x). Alternatively you can force all includes to be static via your ansible.cfg (there's one config option for task includes and one for handler includes).

**Comment by lime** [comment]
Thanks @jimi-c, that was new information to me. Here are the relevant lines from the [example ansible.cfg](https://github.com/ansible/ansible/blob/v2.1.0.0-1/examples/ansible.cfg#L59-L64):

``` ini
# Determine whether includes in tasks and handlers are "static" by
# default. As of 2.0, includes are dynamic by default. Setting these
# values to True will make includes behave more like they did in the
# 1.x versions.
#task_includes_static = True
#handler_includes_static = True
```

Note that the above vars, as well as `static: yes` on  includes, seem to have arrived in version 2.1.0.0.

I haven't tried it yet, but it sounds like it should help.

**Comment by lime** [comment]
Based on cursory testing, it seems like using either `static: yes` locally, or `task_includes_static = True` globally does indeed fix the issue. That's great news! 🎈 

With that being said, `--start-at-task` still seems horribly broken for the default case. New users get no indication of what might have gone wrong, and `ansible-playbook` just exits successfully without even running `setup`.

Do you think it would help to output a informational message if `--start-at-task` is used but no matching task was found? Something like: `No matching task found. Maybe you misspelled the task name, or the task is inside a dynamically included file. --start-at-task can only follow static includes.` Then they would at least have an idea of what might have gone wrong.

**Comment by jimi-c** [comment]
@lime yes we need to re-enable failures on missing handlers/tasks/tags now that this mechanism is in place for 2.1.

**Comment by ghost** [comment]
> Do you think it would help to output a informational message if --start-at-task is used but no matching task was found? Something like: No matching task found. Maybe you misspelled the task name, or the task is inside a dynamically included file. --start-at-task can only follow static includes. Then they would at least have an idea of what might have gone wrong.

I'm going to bump this as I just found out myself and that message would have saved me a bunch of googling.

**Comment by zoobab** [comment]
Still have the issue with ansible 2.6.2:

```
$ ansible --version
ansible 2.6.2
  config file = /home/centos/soft/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/soft/openshift-ansible/venv/lib/python2.7/site-packages/ansible
  executable location = /home/centos/soft/openshift-ansible/venv/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

$ ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml --start-at-ask="Wait for all control plane pods to become ready" -e openshift_deployment_type=origin
Usage: ansible-playbook [options] playbook.yml [playbook2 ...]

ansible-playbook: error: no such option: --start-at-ask
```

**Comment by amenonsen** [comment]
> ansible-playbook: error: no such option: --start-at-ask

It's --start-at-task, not --start-at-ask
