### ISSUE TITLE
ansible start-at-task and serial bug

### ISSUE THREAD

**Issue by maheus** [ansible/ansible#11715]
Hello, 

  I have a playbook with two roles , first role contains one task, second role contains four tasks and a inventory with three host.
In playbook i add option serial: 2 
When i launch my playbook with option --start-at-task="test2", the first two hosts  start at task test2 but the third starts  at the beginning .

example:

PLAY [test] ******************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [host1]
ok: [host2]
ok: [host3]

TASK: [test2 | test3] ********************************************************\* 
ok: [host1] => {
    "msg": "Hello world!"
}
ok: [host2] => {
    "msg": "Hello world!"
}

TASK: [test2 | test4] ********************************************************\* 
ok: [host1] => {
    "msg": "Hello world!"
}
ok: [host2] => {
    "msg": "Hello world!"
}

TASK: [test | ls | tache de test pour le playbook de test] *******************\* 
changed: [host3]

TASK: [test2 | test2] ********************************************************\* 
ok: [host3] => {
    "msg": "Hello world!"
}

TASK: [test2 | test3] ********************************************************\* 
ok: [host3] => {
    "msg": "Hello world!"
}

TASK: [test2 | test4] ********************************************************\* 
ok: [host3] => {
    "msg": "Hello world!"
}

PLAY RECAP *******************************************************************\* 
host1 : ok=3    changed=0    unreachable=0    failed=0  
host2 : ok=3    changed=0    unreachable=0    failed=0  
host3 : ok=5    changed=1    unreachable=0    failed=0
Hello,

**Comment by jimi-c** [comment]
Hi @maheus, what version of Ansible are you running?

**Comment by maheus** [comment]
test performs on ansible version 1.9.2 and 1.8.2

**Comment by jimi-c** [comment]
Thanks @maheus, I just tested this against the devel branch, and it appears that we have already corrected this problem:

<pre>
# cat 11715.yml
- hosts: all
  connection: local
  gather_facts: no
  serial: 2
  tasks:
  - name: task 1
    debug: msg="hello world, task 1"
  - name: task 2
    debug: msg="hello world, task 2"
  - name: task 3
    debug: msg="hello world, task 3"
  - name: task 4
    debug: msg="hello world, task 4"
# ansible-playbook -vv -i "host1,host2,host3" 11715.yml --start-at-task="task 2"
Using /etc/ansible/ansible.cfg as config file
1 plays in 11715.yml
PLAY ****************************************************************************
TASK [task 2] *******************************************************************
ok: [host1] => {
    "changed": false, 
    "msg": "hello world, task 2"
}
ok: [host2] => {
    "changed": false, 
    "msg": "hello world, task 2"
}
TASK [task 3] *******************************************************************
ok: [host1] => {
    "changed": false, 
    "msg": "hello world, task 3"
}
ok: [host2] => {
    "changed": false, 
    "msg": "hello world, task 3"
}
TASK [task 4] *******************************************************************
ok: [host1] => {
    "changed": false, 
    "msg": "hello world, task 4"
}
ok: [host2] => {
    "changed": false, 
    "msg": "hello world, task 4"
}
PLAY ****************************************************************************
TASK [task 2] *******************************************************************
ok: [host3] => {
    "changed": false, 
    "msg": "hello world, task 2"
}
TASK [task 3] *******************************************************************
ok: [host3] => {
    "changed": false, 
    "msg": "hello world, task 3"
}
TASK [task 4] *******************************************************************
ok: [host3] => {
    "changed": false, 
    "msg": "hello world, task 4"
}
PLAY RECAP **********************************************************************
host1                      : ok=3    changed=0    unreachable=0    failed=0   
host2                      : ok=3    changed=0    unreachable=0    failed=0   
host3                      : ok=3    changed=0    unreachable=0    failed=0   
</pre>

Per our normal policy, we close bug report issues when we see the issue has been corrected in the devel branch, so we will close this issue now.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by maheus** [comment]
ok thanks

**Comment by dcrosta** [comment]
I am still experiencing this issue exactly as described with ansible 2.2.0.0. Exactly the same reproduction steps as @jimi-c posted above still reproduce the bug.

*EDIT* -- @jimi-c showed the bug not reproducing, I now see this:

```
(ansible@develop) dcrosta@dcrosta.local $ cat inventory
[all]
host1
host2
host3
host4
(ansible@develop) dcrosta@dcrosta.local $ cat bug.yml
---
- hosts: all
  connection: local
  gather_facts: no
  serial: 2
  tasks:
  - name: task 1
    debug: msg="hello world, task 1"
  - name: task 2
    debug: msg="hello world, task 2"
  - name: task 3
    debug: msg="hello world, task 3"
  - name: task 4
    debug: msg="hello world, task 4"
(ansible@develop) dcrosta@dcrosta.local $ ansible-playbook -i inventory bug.yml --start-at-task "task 2" | pbcopy

PLAY [all] *********************************************************************

TASK [task 2] ******************************************************************
ok: [host1] => {
    "msg": "hello world, task 2"
}
ok: [host2] => {
    "msg": "hello world, task 2"
}

TASK [task 3] ******************************************************************
ok: [host1] => {
    "msg": "hello world, task 3"
}
ok: [host2] => {
    "msg": "hello world, task 3"
}

TASK [task 4] ******************************************************************
ok: [host1] => {
    "msg": "hello world, task 4"
}
ok: [host2] => {
    "msg": "hello world, task 4"
}

PLAY [all] *********************************************************************

TASK [task 1] ******************************************************************
ok: [host3] => {
    "msg": "hello world, task 1"
}
ok: [host4] => {
    "msg": "hello world, task 1"
}

TASK [task 2] ******************************************************************
ok: [host3] => {
    "msg": "hello world, task 2"
}
ok: [host4] => {
    "msg": "hello world, task 2"
}

TASK [task 3] ******************************************************************
ok: [host3] => {
    "msg": "hello world, task 3"
}
ok: [host4] => {
    "msg": "hello world, task 3"
}

TASK [task 4] ******************************************************************
ok: [host3] => {
    "msg": "hello world, task 4"
}
ok: [host4] => {
    "msg": "hello world, task 4"
}

PLAY RECAP *********************************************************************
host1                      : ok=3    changed=0    unreachable=0    failed=0   
host2                      : ok=3    changed=0    unreachable=0    failed=0   
host3                      : ok=4    changed=0    unreachable=0    failed=0   
host4                      : ok=4    changed=0    unreachable=0    failed=0   
(ansible@develop) dcrosta@dcrosta.local $ ansible-playbook --version
ansible-playbook 2.2.0.0
  config file = /Users/dcrosta/.../ansible/ansible.cfg
  configured module search path = ['./library/']
```
