### ISSUE TITLE
HostVars is not JSON serializable

### ISSUE THREAD

**Issue by leedm777** [ansible/ansible#11877]
For debugging, I've been using `{{ vars | to_nice_json }}` in a template to give a dump of what variables have been defined in a play or role. I've also discovered a similar issue when using `{{ vars | to_yaml }}`.

With Ansible 2 (as of commit e16b24c), this fails with an error.

```
fatal: [XXX]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: ERROR! an unexpected type error occurred. Error was <ansible.vars.hostvars.HostVars object at 0x7f88a72ce8d0> is not JSON serializable"}
```

My code:

``` yaml
# roles/debug-vars/tasks/main.yml
- name: Dump all vars (use --diff to see them)
  action: template src=roles/debug-vars/templates/debug-vars.j2 dest=/dev/null
  tags: debug-vars
```

```
# roles/debug-vars/templates/debug-vars.j2
Module Variables ("vars"):
--------------------------------
{{ vars | to_nice_json }}
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by apollo13** [comment]
@jimi-c The error was not fixed, hostvars is still not JSON serializable… A simple script which does indeed work on ansible v1 and breaks in v2 due to the above error:

```
---
- hosts: localhost
  tasks:
  - name: debug
    debug: msg="{{ hostvars|to_nice_json }}"
```

**Comment by manics** [comment]
See #12615

**Comment by mikedanese** [comment]
Over a chroot connection, with the sinippet:

```
---
- hosts: localhost
  tasks:
  - name: debug
    debug: msg="{{ hostvars|to_nice_json }}"
```

I'm now getting:

```
fatal: [/host_root]: FAILED! => {"failed": true, "msg": "Unexpected templating type error occurred on ({{ hostvars|to_nice_json }}): exceptions must be old-style classes or derived from BaseException, not type"}
```

With a stacktrace:

```
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/share/ansible/plugins/action/jsonnet.py", line 39, in default
    return dict(o)
  File "/opt/ansible/lib/ansible/vars/hostvars.py", line 70, in __getitem__
    raise j2undefined
TypeError: exceptions must be old-style classes or derived from BaseException, not type
```

Could this have broken again?

**Comment by jimi-c** [comment]
@mikedanese that is a different error, could you please open a new issue for it?

Thanks!
