### ISSUE TITLE
Ansible converts strings into booleans without '| bool' filter applied

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#11905]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel (https://github.com/ansible/ansible/commit/e32d88760906da5ed473570218b5831292e0bfa8)
##### Ansible Configuration:

Standard `ansible.cfg`
##### Environment:

Debian, Ubuntu
##### Summary:

Ansible converts strings `"yes"` and `"no"` into booleans `true` and `false` when it is not asked to. This can interfere when user wants to have literal strings `yes` or `no` passed through a variable.
##### Steps To Reproduce:

```

---
- hosts: localhost
  tasks:

    - name: Register fact
      set_fact:
        some_fact: 'yes'

    - name: Show fact as is
      debug: var=some_fact

    - name: Show fact filtered as bool
      debug: msg="{{ some_fact | bool }}"

    - name: Show fact in string
      debug: msg="some_fact is {{ some_fact }}"

    - name: Show fact in string as bool
      debug: msg="some_fact is {{ some_fact | bool }}"

```
##### Expected Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Register fact] ********************************************************* 
ok: [localhost]

TASK: [Show fact as is] ******************************************************* 
ok: [localhost] => {
    "var": {
        "some_fact": "yes"
    }
}

TASK: [Show fact filtered as bool] ******************************************** 
ok: [localhost] => {
    "msg": "True"
}

TASK: [Show fact in string] *************************************************** 
ok: [localhost] => {
    "msg": "some_fact is yes"
}

TASK: [Show fact in string as bool] ******************************************* 
ok: [localhost] => {
    "msg": "some_fact is True"
}

```
##### Actual Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Register fact] ***********************************************************
ok: [localhost]

TASK [Show fact as is] *********************************************************
ok: [localhost] => {
    "changed": false, 
    "some_fact": true
}

TASK [Show fact filtered as bool] **********************************************
ok: [localhost] => {
    "changed": false, 
    "msg": true
}

TASK [Show fact in string] *****************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "some_fact is True"
}

TASK [Show fact in string as bool] *********************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "some_fact is True"
}
```

**Comment by bcoca** [comment]
cc @abadger

**Comment by abadger** [comment]
@feanil does this look like something to do with your changes we merged at
pycon?

I'm on vacation and then at a conference for the rest of this week so I
won't be able to look deeply into this for a bit but maybe you can.

**Comment by feanil** [comment]
Hmm, it shouldn't because the change I made was not to convert string to other types but to retain the types from YAML when rendering templates.  I'll try to do a quick test later today to verify that.

**Comment by feanil** [comment]
@bcoca @abadger I verified that this was not from my template changes.  I undid my changes and ran the test that @drybjed provided and his issue persisted.

**Comment by jimi-c** [comment]
This is something we added almost a year ago in the 1.x code (in a571fd4e):

<pre>
        for k,v in parsed_args.iteritems():
            # convert certain strings to boolean values
            if isinstance(v, basestring) and v.lower() in ('true', 'false', 'yes', 'no'):
                parsed_args[k] = utils.boolean(v)
</pre>

This is specifically limited to the four strings above, and while it could be argued that `yes`/`no` shouldn't be auto-converted, it has been in the code for so long I'm not in favor of changing this now.

**Comment by drybjed** [comment]
In that case I'll try to work around it. Thanks for the explanation.

**Comment by yosefy** [comment]
there is another problem
"true" is converted to "True"

which is a problem as elasticsearch don't get "True"

thanks

**Comment by yuri1969** [comment]
Exactly @yosefy, this is a problem since there are parsers which expect `true` instead of `True`.

**Comment by yosefy** [comment]
thanks @yuri1969 
so what is the future of this issue?
why not to let the user decide?
thanks

**Comment by yuri1969** [comment]
@yosefy I got a workaround :) I wasn't aware that the YAML specification allows an _explicit data type casting_. [The YAML spec](http://yaml.org/spec/1.2/spec.html) allows eg. `!!str` indicator which simply forces the value to be a string. Thus `true` doesn't get transformed to `True`, etc.

Just use the `!!str` indicator everywhere you need to preserve a parameter in its original string form. Really, just spam your default files, roles, etc. with this indicator.

**Comment by vaivars** [comment]
The best workaround for this issue that i have heard (suggested by my colleague) - Just use more explanatory statements. Like 'heck yeah!" and "aww hell no!".

On a bit more serious note - awesome to see that there is an actual solution.. right when i started searching for the issue :D.

**Comment by D3DeFi** [comment]
Hi, issue still persists with ansible 2.2.1.0. I have a bunch of broken postfixes due to smtpd_use_tls: yes, which got transferred to smtpd_use_tls = True in main.cf. 

Possible workaround is to quote yes (e.g. smtpd_use_tls: 'yes'). Still, should be at least documented somewhere.

**Comment by orinciog** [comment]
@yuri1969 I'm having the same problem (ansible converts true to True) and I want to template a JSON where True is not recognized. 
Unfortunately, I don't understand your solution. Where should I use the `!!str` notation? 
Should I use in vars.yml or in jinja template?

In my case, 
in vars.yml I have:
`a: true`

and in jinja template I have
`{
key: {{a}}
}`

Thank you,

LE: I found the solution:
In vars.yml put
`a: !!str true`

Thank you very much for this hack.

**Comment by jdkindy** [comment]
Found this because of a problem with using ansible + cloudformation that changed "On" and "Off" to true and false.  Using the !!str notation did not fix it because the "problem" is in with yaml on the cloudformation side:

Configuration validation exception: Invalid option value: 'true' (Namespace: 'aws:elasticbeanstalk:container:php:phpini', OptionName: 'display_errors'): Value is not one of the allowed values: [On, Off]

in playbook:
php_display_errors: !!str On

in template:
      #### PHP config
      - Namespace: aws:elasticbeanstalk:container:php:phpini
        OptionName: display_errors
        Value: {{ php_display_errors|default('Off') }}

The workaround in this case is to quote the value (see http://yaml.org/type/bool.html):
      #### PHP config
      - Namespace: aws:elasticbeanstalk:container:php:phpini
        OptionName: display_errors
        Value: "{{ php_display_errors|default('Off') }}"

**Comment by IUBitCowboy** [comment]
I came to research this problem. However, messing around I discovered there is an even easier solution which is to quote the string. So in vars.yml both of these should work. Both **a** and **b** will get the value of **yes**.

```
a: !!str yes
b: 'yes'
```

**Comment by aboutyou-bitbucket-mirror** [comment]
Can't confirm that. I have a playbook, with the strings "on" and "off" and both values get transformed to True or False. Doesn't matter if the value is single quoted, double quoted, both or prefixed with !!str...

**Comment by m3philis** [comment]
Can't confirm that. I have a playbook, with the strings "on" and "off" and both values get transformed to True or False. Doesn't matter if the value is single quoted, double quoted, both or prefixed with !!str...

**Comment by irekpelech** [comment]
For me works using single quotation 
b: 'YES'

**Comment by monsoft** [comment]
I had this same issue and I resolved it by adding single quote during variable declaration:

b: 'YES'

**Comment by benburdick** [comment]
> it has been in the code for so long I'm not in favor of changing this now.

That is a terrible reason for not fixing what obviously should be considered a bug :/

**Comment by garbled1** [comment]
This just bit me today, and I think it violates the principal of least surprise.  I did a set_fact thing: "NO" and found it passing "False" to my shell command later in the run.

**Comment by runout-at** [comment]
same issue here and this is not what anybody would expect. i would call it a bug - not a feature.

**Comment by paprickar** [comment]
I love ansible but from my point of view its a bug. Please consider to fix that.

**Comment by ghost** [comment]
I just stumpled upon this issue and cannot believe that this isn't considered a bug.

Seriously, I came over from Chef because I thought that Ansible sticks to the paradigm of least suprise.
Instead I'm encountering a lot of inconsistencies, immature implementations and weird stuff like this.
Another one was the _duplicate key warnings_ when using pretty valid YAML references.

:-(

**Comment by robertobado** [comment]
@drybjed could we revisit this? Still an issue

**Comment by drybjed** [comment]
@robertobado As far as I know, Ansible team doesn't work on "reopened" issues. If you really want, I suggest that you create a new issue with explanation of your use case and the errors you are getting.

**Comment by pmyjavec** [comment]
@jimi-c, is there any chance we can have this revisited? This is a really frustrating bug. How can true|false = True|False ? This particularly blows when working with Jinja template interpolation.

**Comment by wujie1993** [comment]
you can use filter to convert bool to lower string  
`{{ some_fact | lower }}`

**Comment by luisffc** [comment]
This is the only way it could use a `no` string
```
- set_fact:
    somevar: ["no"]

- debug:
    var: somevar[0]
```
