### ISSUE TITLE
ansible-playbook stops execution once it reaches an unreachable host if the serial keyword is defined

### ISSUE THREAD

**Issue by Hoshpak** [ansible/ansible#11997]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 5eeeb87d82) last updated 2015/08/18 20:05:58 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dea5f5d15e) last updated 2015/08/17 19:13:02 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 210ee3febc) last updated 2015/08/17 19:13:06 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/08/17 19:13:09 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/08/17 19:13:13 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
##### Ansible Configuration:

$ source hacking/env-setup
##### Environment:

Debian jessie amd64

$ python -v
Python 2.7.9

$ pip freeze
Cheetah==2.4.4
IPy==0.81
Jinja2==2.8
M2Crypto==0.21.1
MarkupSafe==0.23
Pillow==2.6.1
PyYAML==3.11
Pygments==2.0.1
SOAPpy==0.12.22
Sphinx==1.2.3
ansible==2.0.0
argparse==1.2.1
astroid==1.3.7
chardet==2.3.0
colorama==0.3.2
configobj==5.0.6
croniter==0.3.4
defusedxml==0.4.1
docutils==0.12
ecdsa==0.13
feedparser==5.1.3
html5lib==0.999
httplib2==0.9
logilab-common==1.0.2
lxml==3.4.2
meld==3.12.1
msgpack-python==0.4.2
numpy==1.8.2
paramiko==1.15.2
pep8==1.5.7
pycrypto==2.6.1
pygobject==3.14.0
pylint==1.4.4
python-apt==0.9.3.11
python-dateutil==2.2
python-debian==0.1.27
python-debianbts==1.11
pytz==2012rc0
pyzmq==14.4.0
reportbug==6.6.3
reportlab==3.1.8
requests==2.4.3
roman==2.0.0
salt==2015.5.3
six==1.8.0
smbus==1.1
urllib3==1.9.1
vboxapi==1.0
wsgiref==0.1.2
wstools==0.4.3
wxPython==3.0.1.1
wxPython-common==3.0.1.1
##### Summary:

If the "serial" keyword is defined in a playbook and one of the hosts in the inventory is unreachable, ansible-playbook reports "NO MORE HOSTS LEFT" and doesn't execute the plays on the rest of the hosts.
##### Steps To Reproduce:
1. Clone the ansible git repository and run "source hacking/env-setup".
2. Create several VMs with ssh configured. Write their IP addresses into an inventory file
3. Create a playbook with "serial: x" (the value of x doesn't matter) and several plays (I just used "shell: echo Test" to test this)
4. Run the playbook to test if it works properly: "ansible-playbook -vvv -u root -i inventory test-playbook.yml"
5. Shut down one or more of the VMs so they are no longer reachable
6. Run the playbook again
##### Expected Results:

I expected ansible-playbook to report a fatal error about the unreachable host but continue with the next batch until the tasks are run on all hosts. At least that's the behaviour I get from 1.9.2 and I couldn't find any mention in the changelog that this has been changed on purpose.
##### Actual Results:

Once ansible-playbook encounters the first unreachable host, it will correctly report "fatal: [192.168.x.y]: FAILED!...". However it will only execute the tasks on the hosts that are selected by the current serial "batch" and will stop after that with the message "NO MORE HOSTS LEFT" even if there are more hosts remaining in the inventory. I tried it with different serial values (1-50) and also tried defining a "max_fail_percentage" that is definitely above the percentage one failing host would cause relatively to the "serial" value and even tried inventories with 2000 hosts and raising the serial value. It doesn't seem to make a difference.

**Comment by Hoshpak** [comment]
I did some digging through the code and believe I have found the cause of this issue. The point where the execution is aborted is the if statement in lib/ansible/executor/playbook_executor.py lines 143-144. If one host is unreachable, the result won't equal 0 and the loop will be aborted with the break command. After commenting out these two lines I was able to execute the playbook over all hosts even if one of them was not reachable.

Furthermore I noticed that the message "NO MORE HOSTS LEFT" will only be displayed if "strategy: linear" is specified in the playbook or selected by default. I traced this one back to lib/ansible/plugins/strategies/linear.py and the if statement in the lines 231-235. I don't quite understand the intention behind this block but it leads to the error message being reported when one host has errors.

Again, I'm not familiar enough with the ansible code base to be able to assess what would be the proper way to fix this respectively deal with it. However I hope that this helps to further narrow down the issue and find a solution.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by KarnGusain** [comment]
issue still persists with the ansible 2.2.1.0? is there no permanent fix yet.

**Comment by cjacobsen** [comment]
It still happens in Ansible 2.4.1.0

**Comment by aJetHorn** [comment]
This issue still exists in 2.4.2.0. If serial is set and any host is unreachable, the test will fail after that connection error. If anyone else stumbles here after a desperate Google search, this is the active ticket: #18075
