### ISSUE TITLE
Variable from include_vars in previous role not overridden by vars/main.yml in subsequent role

### ISSUE THREAD

**Issue by dstillman** [ansible/ansible#11996]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.3 (detached HEAD bf5353767e) last updated 2015/08/18 15:05:36 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 1ceac602bb) last updated 2015/08/18 15:05:39 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 2415f4c163) last updated 2015/08/18 15:05:40 (GMT -400)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/08/18 15:05:40 (GMT -400)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/08/18 15:05:40 (GMT -400)
```

Please note that **this appears to be fixed in devel for 2.0**, so feel free to close, but this should obviously be turned into a test case if one doesn't exist.
##### Ansible Configuration:

Default
##### Environment:

Amazon Linux
##### Summary:

If a role A sets a variable using `include_vars` and role B sets the same variable in vars/main.yml, the value from B's vars/main.yml is ignored.
##### Steps To Reproduce:

Create these files:

main.yml:

```
- hosts: 127.0.0.1
  roles:
    - { role: a, dev: true }
    - { role: b }
```

roles/a/vars/main.yml:

```
service: a
```

roles/a/vars/dev.yml:

```
service: a-dev
```

roles/a/tasks/main.yml:

```
- include_vars: dev.yml
  when: dev is defined and dev

- debug: var=service
```

roles/b/vars/main.yml:

```
service: b
another_var: foo
```

roles/b/tasks/main.yml:

```
- debug: var=service
- assert: { that: "service == 'b'" }
```
##### Expected Results:

`service` should be equal to 'b' in role `b`, since it was set in `b/vars/main.yml`, just like `another_var`.
##### Actual Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [a | include_vars dev.yml] ********************************************** 
ok: [127.0.0.1]

TASK: [a | debug var=service] ************************************************* 
ok: [127.0.0.1] => {
    "var": {
        "service": "a-dev"
    }
}

TASK: [b | debug var=another_var] ********************************************* 
ok: [127.0.0.1] => {
    "var": {
        "another_var": "foo"
    }
}

TASK: [b | debug var=service] ************************************************* 
ok: [127.0.0.1] => {
    "var": {
        "service": "a-dev"
    }
}

TASK: [b | assert ] *********************************************************** 
failed: [127.0.0.1] => {"assertion": "service == 'b'", "evaluated_to": false, "failed": true}
```

**Comment by bcoca** [comment]
so this has to do how vars work, when roles get included (not executed), vars/main.yml are read and the vars are defined, if you override that var at any point before role B executes, that is what role B will get. vars/main.yml does not get re-read when a role runs.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

include_vars are meant to override vars/main.yml, not only for the current role but all roles, as role vars have less precedence.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by dstillman** [comment]
Thanks for the explanation, but this behavior differs between 1.9.3 and 2.0, so it seems like there's a bug here either way. Are you saying that the behavior in 2.0 is wrong?

**Comment by dstillman** [comment]
To be clear, if you're saying this isn't a bug in 1.9.3, then this issue should be reopened, because 2.0 doesn't do what you're saying it should.

But the current 2.0 behavior makes much more sense to me and seems much more useful. You use role variables because you want to use them in that role. How can you reason with them if they can be overridden by some unrelated role that 1) happens to run first and 2) uses an include_vars that happens to include a variable with the same name? Does every single role variable need to be prefixed to avoid being unpredictably clobbered?

**Comment by abadger** [comment]
Talked about this today to get clarification.  The bug was introduced in the 1.8.x series and persisted through 1.9.x.  2.0 has fixed this so we consider the present 2.x behaviour to be correct.  Because this has been present in 1.8.x and 1.9.x and it has the potential to be relied upon in people's playbooks we probably won't release a fix in 1.9.x.  I'll update the changeLog with an abbreviated form of this information.

@jimi-c I just noticed the reporter was asking if there's a test case for this in devel's integration tests.  Do you happen to know if that's there already?

**Comment by jimi-c** [comment]
I don't believe so, it would be it in the variable precedence test, which is a single play (not multiple plays).

**Comment by dstillman** [comment]
@abadger: Great, thanks — that's what I was hoping to hear.

Re: tests, this can be discussed elsewhere, but I suggested in my recent [mailing list post](https://groups.google.com/d/msg/ansible-project/4OIuDxRSv0M/RgW8HkuIKQAJ) about all these variable precedence bugs that the integration tests be rearranged into separate directories with top-level playbooks and grouped subdirectories in each. That would make it much easier to, for example, add the test that I provided here (and on all my previous bugs, [one of which](https://github.com/ansible/ansible/issues/9498) has regressed in 2.0).

**Comment by dstillman** [comment]
And this was broken again by 635fa0757b06b560a7812053f8de298fc5fc2c4c, which fixed the regression I referred to in my previous comment.

**Comment by jimi-c** [comment]
@dstillman so you're saying it's now back to 1.9.x behavior?

**Comment by dstillman** [comment]
Yes.

**Comment by jimi-c** [comment]
Ok, so to be clear, #9498 is back to being corrected now, as we had a regression in VariableManager corrected by 635fa07.

**Comment by dstillman** [comment]
Shouldn't this be reopened, if we've agreed that the 1.9.x behavior was incorrect?

**Comment by dstillman** [comment]
Again, this acknowledged bug still exists in 2.0 Beta 1. This issue should be reopened. The 1.9.x behavior doesn't make any sense.
