### ISSUE TITLE
Filter plugins need to reside in dir beside your playbooks

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#12178]
I'm not sure if it's a bug, maybe it should be like this.
Tested with ansible 1.9.2 and devel from 01-09-2015

I **had** the following stucture on my machine with filter_plugins:

~/ansible/

```
  group_vars/
  host_vars/
  hosts/
  roles/
  filter_plugins/
  playbook1.yml
  playbook2.yml
```

As my ansible dir was started cluttering with playbooks, I moved them to different dirs such as 'playbooks' and 'tests':

```
  group_vars/
  host_vars/
  hosts/
  roles/
  filter_plugins/
  playbooks/
  tests/
```

However, running the playbooks resulted in errors such as this:

```
"AnsibleError: ERROR! template error while templating string: no filter named 'split'"
```

So I put filter_plugins inside 'playbooks' dir, and everything went ok.

So is this expected behaviour? It means now that I need to copy my 'filter_plugins' dir to all my playbook dirs and make sure to keep them in sync.

**Comment by amenonsen** [comment]
This is expected (and documented) behaviour: the various plugin directories are relative to `playbook_dir`. You can also set an explicit path e.g. `filter_plugins = /path/to/plugins` in `ansible.cfg`.

**Comment by Tahvok** [comment]
@amenonsen You are right. I missed that sentense: "In addition, plugins can be shipped in a subdirectory relative to a top-level playbook, in folders named the same as indicated above."
Thank you!

**Comment by bcoca** [comment]
also you can put them inside roles, which makes it easier to move around

**Comment by mpetrive** [comment]
So is it the case that I can't specify multiple directories for the filter_plugins variable in ansible.cfg?  If that is true, which I believe to be the case, you are forced to point to a single filter_plugins directory and you must use the approach mentioned above where ansible will implicitly pull from playbook_dir/filter_plugins.  This seems limiting and somewhat arbitrary.

**Comment by Tahvok** [comment]
No, it is not the case. No idea how you got this from this closed issue.
You can put multiple filter_plugins paths with a colon (:) as a separator.

**Comment by mpetrive** [comment]
@Tahvok yes I had my ansible.cfg setup with multiple paths however I was using an environment variable to define the second path (to my repo area).  Using an environment variable in the filter_plugins path does not work.  When I change to a hard coded path everything works fine.  It's interesting the *_plugins ansible.cfg config variables are interpreted differently.  I am running version 1.9.4.

**Comment by Tahvok** [comment]
It is again not related to this issue. Please use the mailing list at  https://groups.google.com/forum/#!forum/ansible-project
or IRC to ask questions

Anyway your issue was already reported by me, and was fixed in ansible 2: https://github.com/ansible/ansible/issues/12180

in 1.9.4 only tilde '~' is supported to expand to your home directory.

Search for closed issues, there are many things fixed in v2.

**Comment by mpetrive** [comment]
Great to hear you reported it and it was fixed.  Thanks for all your help!!

**Comment by keltik85** [comment]
I have put:
```
filter_plugins     = /home/my-user/.ansible/plugins/filter
```
into my `/etc/ansible/ansible.cfg`.

Then I put a Python file into that dir named 
`/home/my-user/.ansible/plugins/filter/my_custom_filters.py`:

```
#!/usr/bin/python
class FilterModule(object):
    def filters(self):
        return {
            'my_xxx_filter': self.my_xxx_filter,
            'another_filter': self.another_filter
        }

    def my_xxx_filter(self, a_variable):
        a_new_variable = a_variable + ' XXX_TEST_XXX'
        return a_new_variable
```

After that, I run my playbook like this:

```
my-user@my-host:~/some-project$ ansible-playbook ansible/playbook.yml
```

But it gives me this error:
```
fatal: [192.168.178.201]: FAILED! => {"msg": "template error while templating string: no filter named 'my_xxx_filter'. String: stdout of my cool custom filter is = {{ some_registered_result.stdout | my_xxx_filter }}"}
```

I have already tried copying the `filter_plugin` folder into the `roles` folder and also into the directory which holds the top-level `playbook.yml` file.

Why does it not pickup the path?

**Comment by strarsis** [comment]
I have a similar issue, I want to use a relative path to get one directory up:
````
[defaults]
callback_plugins = ~/.ansible/plugins/callback_plugins/:/usr/share/ansible_plugins/callback_plugins:lib/trellis/plugins/callback:../lib/trellis/plugins/callback
stdout_callback = output
filter_plugins = ~/.ansible/plugins/filter_plugins/:/usr/share/ansible_plugins/filter_plugins:lib/trellis/plugins/filter:../lib/trellis/plugins/filter
force_color = True
force_handlers = True
inventory = hosts
nocows = 1
roles_path = vendor/roles
vars_plugins = ~/.ansible/plugins/vars_plugins/:/usr/share/ansible_plugins/vars_plugins:lib/trellis/plugins/vars:../lib/trellis/plugins/vars
````
But it doesn't seem to work, the filter is still not found.

Related issue:
https://discourse.roots.io/t/vagrant-up-error-with-new-v-of-trellis/6385/5
