### ISSUE TITLE
nested blocks lose conditions on parent blocks

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#12395]
This is a bug report for devel@2a50957a. I have a playbook like this:

```
- hosts: all
  gather_facts: no
  tasks:
    - block:
        - debug: var=inventory_hostname
        - command: /bin/false
          ignore_errors: y
          register: x
        - block:
            - debug: var=inventory_hostname
            - block:
              - debug: var=inventory_hostname
          when: x|failed
      when: inventory_hostname != 'raven.toroid.org'
```

I run it against an inventory with two hosts:

```
raven.toroid.org
magpie.toroid.org
```

I expected the actions inside the top-most block to be executed only on magpie, but this is what actually happened:

```
TASK [debug var=inventory_hostname] ********************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "magpie.toroid.org"
}

TASK [command] *****************************************************************
skipping: [raven.toroid.org]
The authenticity of host 'magpie.toroid.org (144.76.70.201)' can't be established.
ECDSA key fingerprint is 2a:5a:4c:4b:e0:40:de:8b:9b:e6:0f:90:45:68:89:fc.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001532", "end": "2015-09-16 12:47:24.371083", "failed": true, "rc": 1, "start": "2015-09-16 12:47:24.369551", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [debug var=inventory_hostname] ********************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "magpie.toroid.org"
}

TASK [debug var=inventory_hostname] ********************************************
ok: [raven.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "raven.toroid.org"
}
ok: [magpie.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "magpie.toroid.org"
}
```

Note how the innermost block is executed on raven even though _neither_ of the two conditions on the outer blocks is true on that host.

This effectively makes nested blocks unusable.

**Comment by jimi-c** [comment]
@amenonsen it's actually losing the grand-parent block, I'm guessing because of the way we're serializing things it's not going all the way up the chain. I'll try and track this one down.

**Comment by amenonsen** [comment]
Here's another example that seems to disagree with your analysis:

```
---
- hosts: all
  gather_facts: no
  tasks:
    - block:
        - debug: msg="1. {{inventory_hostname}}"
        - command: /bin/false
          ignore_errors: y
          register: x
        - block:
            - debug: msg="2. {{inventory_hostname}}"
            - block:
              - debug: msg="3. {{inventory_hostname}}"
          when: x|success
      when: inventory_hostname != 'raven.toroid.org'
```

Note that this is substantially the same as the earlier example, except that I changed `x|failed` to `x|success` (which should evaluate to false on magpie). The output is:

```
TASK [debug msg=1. {{inventory_hostname}}] *************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "changed": false, 
    "msg": "1. magpie.toroid.org"
}

TASK [command] *****************************************************************
skipping: [raven.toroid.org]
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001494", "end": "2015-09-16 15:16:58.604416", "failed": true, "rc": 1, "start": "2015-09-16 15:16:58.602922", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [debug msg=2. {{inventory_hostname}}] *************************************
skipping: [magpie.toroid.org]
ok: [raven.toroid.org] => {
    "changed": false, 
    "msg": "2. raven.toroid.org"
}

TASK [debug msg=3. {{inventory_hostname}}] *************************************
ok: [raven.toroid.org] => {
    "changed": false, 
    "msg": "3. raven.toroid.org"
}
ok: [magpie.toroid.org] => {
    "changed": false, 
    "msg": "3. magpie.toroid.org"
}
```

So debug#1 is executed on magpie (fine) and skipped on raven (fine); debug#2 is skipped on magpie (fine) and executed on raven; debug#3 is executed on _both_ magpie and raven. So it looks like each block in this case is looking only at its own conditions.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by srgvg** [comment]
I'm noticing this bug still in 2.0.1 and  2.0.2rc3.

This happens in a 2-level nested block (so no grand-parents?). Following snippet is part of a role tasks/ file:

```
- block:                                                               

    - block:                                                           

    ¦ - name: provision powerdns_api_key as fact                       
    ¦   template:                                                      
    ¦   ¦ src: facts.d/powerdns_api.fact                               
    ¦   ¦ dest: /etc/ansible/facts.d/powerdns_api.fact                 
    ¦   ¦ owner: root                                                  
    ¦   ¦ group: root                                                  
    ¦   ¦ mode: 0440                                                   

    ¦ - name: retrieve powerdns facts                                  
    ¦   setup:                                                         

    ¦ when: >                                                          
    ¦   powerdns_api_enable and (                                      
    ¦   ansible_local is not defined or                                
    ¦   ansible_local.powerdns_api is not defined or                   
    ¦   ansible_local.powerdns_api.api is not defined or               
    ¦   ansible_local.powerdns_api.api.key is not defined )            

    - name: set powerdns_api_key                                       
    ¦ set_fact:                                                        
    ¦   ¦ powerdns_api_key: "{{ ansible_local.powerdns_api.api.key }}" 

  when: powerdns_api_enable                                            
```

I had to add the outer condition to the inner condition to make that work as intended:

```
powerdns_api_enable and (  
..
)
```

**Comment by srgvg** [comment]
Using @amenonsen initial test playbook, I reproduce the issue:

```
 serge  ansible 2.0.1.0 (detached HEAD bb6cadefa2)  ~/tmp  5  ansible-playbook -i hosts test,yml -c local

PLAY ***************************************************************************

TASK [debug] *******************************************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}

TASK [command] *****************************************************************
skipping: [raven.toroid.org]
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.002839", "end": "2016-05-03 08:42:53.592176", "failed": true, "rc": 1, "start": "2016-05-03 08:42:53.589337", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [debug] *******************************************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}

TASK [debug] *******************************************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=4    changed=0    unreachable=0    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
```

And same with his second example:

```
 serge  ansible 2.0.1.0 (detached HEAD bb6cadefa2)  ~/tmp  1  ansible-playbook -i hosts test2.yml -c local

PLAY ***************************************************************************

TASK [debug] *******************************************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "msg": "1. magpie.toroid.org"
}

TASK [command] *****************************************************************
skipping: [raven.toroid.org]
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001622", "end": "2016-05-03 08:45:28.172365", "failed": true, "rc": 1, "start": "2016-05-03 08:45:28.170743", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [debug] *******************************************************************
skipping: [raven.toroid.org]
skipping: [magpie.toroid.org]

TASK [debug] *******************************************************************
skipping: [raven.toroid.org]
skipping: [magpie.toroid.org]

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=2    changed=0    unreachable=0    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by srgvg** [comment]
Even worse, it also fails running from the commit that was supposed to fix this?

```
 serge  ansible 2.0.0 (detached HEAD d91ff0db74)  ~/tmp  ansible-playbook -i hosts test,yml -c local

PLAY ***************************************************************************

TASK [debug var=inventory_hostname] ********************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "magpie.toroid.org"
}

TASK [command] *****************************************************************
skipping: [raven.toroid.org]
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001067", "end": "2016-05-03 08:50:45.961662", "failed": true, "rc": 1, "start": "2016-05-03 08:50:45.960595", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [debug var=inventory_hostname] ********************************************
ok: [magpie.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "magpie.toroid.org"
}
skipping: [raven.toroid.org]

TASK [debug var=inventory_hostname] ********************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "changed": false, 
    "inventory_hostname": "magpie.toroid.org"
}

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=4    changed=0    unreachable=0    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   


serge  ansible 2.0.0 (detached HEAD d91ff0db74)  ~/tmp  ansible-playbook -i hosts test2.yml -c local

PLAY ***************************************************************************

TASK [debug msg=1. {{inventory_hostname}}] *************************************
skipping: [raven.toroid.org]
ok: [magpie.toroid.org] => {
    "changed": false, 
    "msg": "1. magpie.toroid.org"
}

TASK [command] *****************************************************************
skipping: [raven.toroid.org]
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.003263", "end": "2016-05-03 08:48:54.297993", "failed": true, "rc": 1, "start": "2016-05-03 08:48:54.294730", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [debug msg=2. {{inventory_hostname}}] *************************************
skipping: [magpie.toroid.org]
skipping: [raven.toroid.org]

TASK [debug msg=3. {{inventory_hostname}}] *************************************
skipping: [raven.toroid.org]
skipping: [magpie.toroid.org]

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=2    changed=0    unreachable=0    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
```

**Comment by jimi-c** [comment]
Re-closing this, on both devel and stable-2.1 I'm seeing the expected output:

<pre>
# ansible-playbook -vv -i inv test.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: test.yml *************************************************************
1 plays in test.yml
PLAY [all] *********************************************************************
TASK [debug] *******************************************************************
task path: /root/testing/12395/test.yml:5
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}
TASK [command] *****************************************************************
task path: /root/testing/12395/test.yml:6
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [magpie.toroid.org]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.004695", "end": "2016-05-11 21:13:51.552324", "failed": true, "rc": 1, "start": "2016-05-11 21:13:51.547629", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
TASK [debug] *******************************************************************
task path: /root/testing/12395/test.yml:10
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}
TASK [debug] *******************************************************************
task path: /root/testing/12395/test.yml:12
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}
PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=4    changed=0    unreachable=0    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
</pre>

**Comment by srgvg** [comment]
@jimi-c  I'm confused, that is not what I see. What am I doing wrong?

```
 serge  ansible 2.2.0 (devel 0d7530e6da)  ~/tmp  ansible-playbook -vv -i hosts test.yml 
No config file found; using defaults

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test.yml:6
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}

TASK [command] *****************************************************************
task path: /home/serge/tmp/test.yml:7
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [magpie.toroid.org]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test.yml:11
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test.yml:13
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=1    changed=0    unreachable=1    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   

```

```
 serge  ansible 2.1.0.0 (stable-2.1 af257c20da)  ~/tmp  3  ansible-playbook -vv -i hosts test.yml 
No config file found; using defaults

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test.yml:6
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "inventory_hostname": "magpie.toroid.org"
}

TASK [command] *****************************************************************
task path: /home/serge/tmp/test.yml:7
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [magpie.toroid.org]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test.yml:11
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test.yml:13
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=1    changed=0    unreachable=1    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
```

Same with @amenonsen 's second example:

```
serge  ansible 2.1.0.0 (stable-2.1 af257c20da)  ~/tmp  ansible-playbook -vv -i hosts test2.yml 
No config file found; using defaults

PLAYBOOK: test2.yml ************************************************************
1 plays in test2.yml

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test2.yml:6
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "msg": "1. magpie.toroid.org"
}

TASK [command] *****************************************************************
task path: /home/serge/tmp/test2.yml:7
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [magpie.toroid.org]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test2.yml:11
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test2.yml:13
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
    to retry, use: --limit @test2.retry

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=1    changed=0    unreachable=1    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
```

```

 serge  ansible 2.2.0 (devel 0d7530e6da)  ~/tmp  3  ansible-playbook -vv -i hosts test2.yml 
No config file found; using defaults

PLAYBOOK: test2.yml ************************************************************
1 plays in test2.yml

PLAY [all] *********************************************************************

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test2.yml:6
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
ok: [magpie.toroid.org] => {
    "msg": "1. magpie.toroid.org"
}

TASK [command] *****************************************************************
task path: /home/serge/tmp/test2.yml:7
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [magpie.toroid.org]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test2.yml:11
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [debug] *******************************************************************
task path: /home/serge/tmp/test2.yml:13
skipping: [raven.toroid.org] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
    to retry, use: --limit @test2.retry

PLAY RECAP *********************************************************************
magpie.toroid.org          : ok=1    changed=0    unreachable=1    failed=0   
raven.toroid.org           : ok=0    changed=0    unreachable=0    failed=0   
```

For sake of completeness:

```
 serge  ansible 2.2.0 (devel 0d7530e6da)  ~/tmp  3  cat hosts 
raven.toroid.org
magpie.toroid.org
 serge  ansible 2.2.0 (devel 0d7530e6da)  ~/tmp  cat test.yml 
---
- hosts: all
  gather_facts: no
  tasks:
    - block:
        - debug: var=inventory_hostname
        - command: /bin/false
          ignore_errors: y
          register: x
        - block:
            - debug: var=inventory_hostname
            - block:
              - debug: var=inventory_hostname
          when: x|failed
      when: inventory_hostname != 'raven.toroid.org'
 serge  ansible 2.2.0 (devel 0d7530e6da)  ~/tmp  cat test2.yml 
---
- hosts: all
  gather_facts: no
  tasks:
    - block:
        - debug: msg="1. {{inventory_hostname}}"
        - command: /bin/false
          ignore_errors: y
          register: x
        - block:
            - debug: msg="2. {{inventory_hostname}}"
            - block:
              - debug: msg="3. {{inventory_hostname}}"
          when: x|success
      when: inventory_hostname != 'raven.toroid.org'
 serge  ansible 2.2.0 (devel 0d7530e6da)  ~/tmp  
```

I created a gist with those files:
https://gist.github.com/srvg/a39e2380289143a89ccaba4de34741c4

**Comment by jimi-c** [comment]
Same inventory, my playbook is:

<pre>
- hosts: all
  gather_facts: no
  tasks:
    - block:
        - debug: var=inventory_hostname
        - command: /bin/false
          ignore_errors: y
          register: x
        - block:
            - debug: var=inventory_hostname
            - block:
              - debug: var=inventory_hostname
          when: x|failed
      when: inventory_hostname != 'raven.toroid.org'
</pre>

**Comment by jimi-c** [comment]
Well, my inventory is a little different:

<pre>
raven.toroid.org ansible_connection=local
magpie.toroid.org ansible_connection=local
</pre>

So I'm forcing local connections.

**Comment by srgvg** [comment]
:facepalm: to myself. Sorry!
