### ISSUE TITLE
ansible_ssh_user not available as variable in become expr

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#12437]
##### Issue Type:

Bug Report
##### Ansible Version:

devel
##### Summary:

ansible_ssh_user cannot be used in become expressions
##### Steps To Reproduce:

This playbook:

```

---
- hosts: all
  gather_facts: no
  tasks:
  - name: whoami
    shell: id -u && echo {{ ansible_ssh_user }}
    become: "{{ ansible_ssh_user != 'root' }}"
```

errors out with:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'ansible_ssh_user' is undefined"}
```

If you remove the become line it properly prints your user…

@jimi-c: The promised issue as followup to the become/sudo discussions from yesterday

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by ahelal** [comment]
This issue is still present in the devel and stable-2.0 branch

**Comment by magnus-lycka** [comment]
It's still in 2.1 as far as I understand.
