### ISSUE TITLE
Variables expansion issues in role metadata

### ISSUE THREAD

**Issue by indrajitr** [ansible/ansible#12602]
Issue Type:
Bug Report

Ansible Version:
ansible 2.0.0 (devel 3705d54485) last updated 2015/10/01 18:26:52 (GMT -500)

Ansible Configuration:
- roles/myrole1/meta/min.yml

```

---
dependencies:
  - 'roles/{{ os_family }}'  # This doesn't work :(
  - { role: 'roles/{{ os_family }}' }  # But this does work :)
  - { role: 'roles/{{ ansible_os_family }}' }  # This doesn't work either :(
```
- site.yml

```

---
- name: Test role expansion
  hosts: all
  vars:
    - os_family: debian
  roles:
    - myrole1
```

Environment:

N/A

Summary:

For role `dependencies`, variable expansion doesn't work for shorthand form (viz., `- roles/{{ os_family }}`) but it does work when listed as `dict` like so: `- { role: 'roles/{{ os_family }}'  }`.

FWIW, there was a related fix for the `dict` form recently (cf. 79e364d).

While at it, would it make sense to support fact expansion for role dependencies as well to stay consistent with fact expansion support in `include`? (having `- include: '{{ ansible_os_family }}.yml'`in 'tasks/main.yml' works as expected after all).

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by indrajitr** [comment]
Templating role name works for `vars`, but still doesn't work for `facts`.
Is this to be expected?

``` yaml
---
dependencies:
  - 'roles/{{ os_family }}'  # This now works!
  - { role: 'roles/{{ os_family }}' }  # But this does work :)
  - { role: 'roles/{{ ansible_os_family }}' }  # This still doesn't work :(
```

**Comment by jimi-c** [comment]
@indrajitr Yes, because roles are still evaluated as a pre-processor statement, so they're expanded before inventory variables are present. You can, however, use task includes with inventory variables in 2.0, as they are now dynamic. For example:

<pre>
tasks:
- include: "{{ansible_os_family}}.yml"
</pre>

Or you could do the above inside your role's `tasks/main.yml`.

Hope that helps!

**Comment by indrajitr** [comment]
@jimi-c thanks for clarifying!

Yes, I use `- include: "{{ ansible_os_family }}.yml"` type pattern often in 2.0 these days. The request to have same treatment for role evaluation was simply for consistency. But after looking at the code just now I realize your point that it won't really work out.

I think the current arrangement is fine. Thanks for making Ansible awesome :)
