### ISSUE TITLE
SSH host key prompts trample over each other

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#13318]
This is a known problem, for which I had submitted a patch with #12276. Although that PR was merged, the actual locking part was rejected because it (unavoidably) waited too long if ssh timed out trying to connect to unreachable hosts.

@bcoca said on IRC that he may be prepared to reconsider this for v2, because otherwise it's painful to deal with any number of newly-provisioned hosts.

I'm creating this just to keep track of the decision. If the feature is definitely wanted for v2.0, then I'll go back and rebase [https://gist.github.com/amenonsen/a2ecbea86b468e780608](the patch that I had originally submitted) (which worked fine, but by now needs rebasing, and can also be slightly improved upon).

**Comment by amenonsen** [comment]
P.S. For anyone who isn't already familiar with the problem: http://toroid.org/ansible-ssh-locking explains it.

**Comment by bcoca** [comment]
I attempted to recreate the locking but you can probably do it faster as you rewrote most of it and I have not caught up with the new code yet.

**Comment by amenonsen** [comment]
I pushed another commit to add the requested locking in the existing PR #13297 (which fixes a real problem, and should be merged).

**Comment by amenonsen** [comment]
I'm closing this because the associated PR was rejected and an alternative solution adopted for v2.

**Comment by matjam** [comment]
clearly the solution doesn't work because this is still a problem.
