### ISSUE TITLE
become-method parameter of ansible-playbook ignored

### ISSUE THREAD

**Issue by 8191** [ansible/ansible#13447]
The `--become-method` parameter of `ansible-playbook` seems to be ignored:

**test.yml:**

``` yaml

---
- hosts: all
  gather_facts: False
  tasks:
    - command: /usr/bin/whoami
      become: True
```

**test.inv:**

```
hanoi ansible_python_interpreter=/usr/local/bin/python2.7
```

**Execution with `--become-method=su`:**

```
% ansible-playbook -i test.inv --ask-become-pass --become-method=su -vvv test.yml 
No config file found; using defaults
SU password: 
1 plays in test.yml

PLAY ***************************************************************************

TASK [command] *****************************************************************
task path: /home/mf/cm/test/test.yml:5
<hanoi> ESTABLISH SSH CONNECTION FOR USER: None
<hanoi> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mf/.ansible/cp/ansible-ssh-%h-%p-%r -tt hanoi ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1449348191.12-203077495271763 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1449348191.12-203077495271763 )" )
<hanoi> PUT /tmp/tmpqMSBTZ TO /home/mf/.ansible/tmp/ansible-tmp-1449348191.12-203077495271763/command
<hanoi> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mf/.ansible/cp/ansible-ssh-%h-%p-%r [hanoi]
<hanoi> ESTABLISH SSH CONNECTION FOR USER: None
<hanoi> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/mf/.ansible/cp/ansible-ssh-%h-%p-%r -tt hanoi /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=vglqbfzadxvziicziaoiepgbxdskubpq] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vglqbfzadxvziicziaoiepgbxdskubpq; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/local/bin/python2.7 /home/mf/.ansible/tmp/ansible-tmp-1449348191.12-203077495271763/command; rm -rf "/home/mf/.ansible/tmp/ansible-tmp-1449348191.12-203077495271763/" > /dev/null 2>&1'"'"''
fatal: [hanoi]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"_raw_params": "/usr/bin/whoami"}, "module_name": "command"}, "msg": "/bin/sh: sudo: not found\r\n", "parsed": false}
```

Why does ansible execute `SSH: EXEC ssh -C -q (...) -tt hanoi /bin/sh -c 'sudo -H -S`?

When using `ansible_become_method=su` within the inventory, or `become_method: su` within the play, ansible works as expected.

Using ansible f89f906f87c2c4d850702404f70cfabaa63be351

**Comment by 8191** [comment]
Workaround: pass `-e ansible_become_method=<method>` instead of `--become-method=<method>`.

**Comment by 8191** [comment]
Fixed in 9557102

**Comment by jforman** [comment]
Have we confirmed this works? I'm trying using ansible-playbook 2.0.0.2 and still see the become-method on the command like being considered:

jforman@oyster:/tank/git/ansible-configs$ ansible-playbook --version
ansible-playbook 2.0.0.2
  config file = /tank/git/ansible-configs/ansible.cfg
  configured module search path = Default w/o overrides

jforman@oyster:/tank/git/ansible-configs$ ansible-playbook --ask-become-pass --become-method=doas -i hosts -l openbsd-test1.local site.yml 
DOAS password: 
.....
PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [openbsd-test1.local]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "/bin/sh: sudo: not found\r\n", "msg": "MODULE FAILURE", "parsed": false}
