### ISSUE TITLE
ansible docs search is broken

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13676]
As mentioned at:

   https://groups.google.com/forum/#!topic/ansible-project/X-Gon4Say5Y

I've tried:

   http://docs.ansible.com/ansible/index.html?query=inventory&siteurl=docs.ansible.com%2Fansible%2Findex.html&ref=docs.ansible.com%2F&ss=1154j182296j9

but basically any keyword entered in the "Google Custom Search" box followed by
<Enter> would return the current page.

Also confirmed on IRC:

   Dec-24,2015 02:25 < smkr> anyone else having troubles with the search 
   function at http://docs.ansible.com/ansible/index.html? try searching for 
   anything will come back with the current page
   Dec-24,2015 02:32 < apix> smkr: indeed

Thanks a bunch.

**Comment by ian-kelling** [comment]
Broken for me too.

**Comment by dragomirr** [comment]
Broken for me too.

**Comment by bcoca** [comment]
There was an issue with the service provider, it was solved shortly afterwards.

**Comment by dragomirr** [comment]
Still having issue. Tried from different locations, computers, mobile phones. I'm not sure how this can be service provider issue, can you explain please?

**Comment by ghost** [comment]
This is still not working (or is broken again).  Makes it very hard to use the docs...

**Comment by dragomirr** [comment]
Working :) And it is better implemented search then before. Great job.

**Comment by docschick** [comment]
Awesome to hear the feedback @dragomirr! Glad you're happy with it!

**Comment by ghost** [comment]
Unfortunately the new search doesn't play well with  Vimperator soI  won't be able to take advantage of this improvement. Nonetheless I do appreciate that docs are part of the project as 'grep' in the 'rst' directory works great. Thanks Ansible folks for keeping them open.

**Comment by docschick** [comment]
@smkr Sorry to hear it doesn't work with Vimperator. I wasn't familiar with that one. But thanks for finding the silver lining with 'grep' -- very cool of you. :)
