### ISSUE TITLE
changes to ansible shell wrapper breaks setup & ping modules (bug report regression in 2.0.0rc3)

### ISSUE THREAD

**Issue by dch** [ansible/ansible#13745]
# Issue Type:
- Bug Report
- Regression between 1.9.4 and 2.0.0rc3
# Ansible Version:
- master on OSX managing FreeBSD 10.2R amd64
# Summary:
- setup's inventory fails in 2.0 to run on FreeBSD 10.2-RELEASE due to removing `/bin/sh -c` as a wrapper from mkdir shell command. NB default shell on FreeBSD is /bin/csh.
- demonstrated using setup module but ping module also fails
- issue appears to be in ansible itself, `lib/ansible/plugins/shell/sh.py`
- possibly broken by this commit https://github.com/ansible/ansible/commit/26520442bd0fe231abc0a4432c6f2943b61f8fb8
- works on `brew switch ansible 1.9.4_1`
- fails on `brew switch ansible 2.0.0-0.8.rc3_1`
# Steps To Reproduce:
- `vagrant init freebsd/FreeBSD-10.2-RELEASE && vagrant up`
- add the ip/hostname to your ansible inventory file
- switch to 1.9.4
- `ansible all -l tenrtwo -i ./bootstrap -u root -m setup -vvvv` should work
- switch to 2.0.0-rc3 & repeat above command
# Expected Results:
# as seen in 1.9.4

```
$ brew switch ansible 1.9.4_1
Cleaning /usr/local/Cellar/ansible/1.9.4_1
Cleaning /usr/local/Cellar/ansible/2.0.0-0.8.rc3_1
12 links created for /usr/local/Cellar/ansible/1.9.4_1
$ ansible --version
ansible 1.9.4
  configured module search path = None
$ ansible all -l tenrtwo -i ./bootstrap -u root -m setup -vvvv
<172.16.213.224> ESTABLISH CONNECTION FOR USER: root
<172.16.213.224> REMOTE_MODULE setup
<172.16.213.224> EXEC ssh -C -tt -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o IdentityFile="ed25519_ansible_20140919" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 172.16.213.224 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1452128902.44-116747526463177 && echo $HOME/.ansible/tmp/ansible-tmp-1452128902.44-116747526463177'
<172.16.213.224> PUT /var/folders/rv/8w04tcb13kqbxcyqprhrvvfm0000z9/T/tmpmQxtaA TO /root/.ansible/tmp/ansible-tmp-1452128902.44-116747526463177/setup
<172.16.213.224> EXEC ssh -C -tt -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o IdentityFile="ed25519_ansible_20140919" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 172.16.213.224 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python2 /root/.ansible/tmp/ansible-tmp-1452128902.44-116747526463177/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1452128902.44-116747526463177/ >/dev/null 2>&1'
tenrtwo | success >> {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "172.16.213.224"
        ],...
```
# Actual Results:

```
brew switch ansible 2.0.0-0.8.rc3_1 $ brew switch ansible 2.0.0-0.8.rc3_1
Cleaning /usr/local/Cellar/ansible/1.9.4_1
Cleaning /usr/local/Cellar/ansible/2.0.0-0.8.rc3_1
12 links created for /usr/local/Cellar/ansible/2.0.0-0.8.rc3_1
$ ansible --version
ansible 2.0.0
  config file = /projects/skunkwerks/ansible/ansible.cfg
  configured module search path = Default w/o overrides
$ ansible all -l tenrtwo -i ./bootstrap -u root -m setup -vvvv
Using /projects/skunkwerks/ansible/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<172.16.213.224> ESTABLISH SSH CONNECTION FOR USER: root
<172.16.213.224> SSH: EXEC ssh -C -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="ed25519_ansible_20140919"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -tt 172.16.213.224 mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452128974.83-96980828063899 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452128974.83-96980828063899 )"
tenrtwo | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1452128974.83-96980828063899 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1452128974.83-96980828063899 )\", exited with result 1: Illegal variable name.\r\n",
    "unreachable": true
}
$
```

**Comment by bcoca** [comment]
check against current devel, i fixed several issues with shell quoting there (and it should be in upcoming rc4)

**Comment by dch** [comment]
thanks @bcoca, I just tested against 2.0.0.-9_rc4 and the issue still occurs, also in HEAD sha#2e29993729fd72a4c61c0856d7ae1bad990a53ad

```
dch 🍺  /r/v ❯❯❯ansible all -l tenrtwo -u root -m setup -vvvv
Using /Volumes/ramdisk/v/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<172.16.213.226> ESTABLISH SSH CONNECTION FOR USER: root
<172.16.213.226> SSH: EXEC ssh -C -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o 'IdentityFile="nsible_20140919"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -tt 172.16.213.226 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452203004.06-96620070364646 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452203004.06-96620070364646 )"'
tenrtwo | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1452203004.06-96620070364646 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1452203004.06-96620070364646 )\", exited with result 1: Illegal variable name.\r\n",
    "unreachable": true
}
dch 🍺  /r/v ❯❯❯ansible --version                                                                                                           ⏎
ansible 2.0.0
  config file = /Volumes/ramdisk/v/ansible.cfg
  configured module search path = Default w/o overrides
dch 🍺  /r/v ❯❯❯which ansible
/usr/local/bin/ansible
dch 🍺  /r/v ❯❯❯l /usr/local/bin/ansible
lrwxr-xr-x  1 dch  admin    45B  7 Jan 22:26 /usr/local/bin/ansible@ -> ../Cellar/ansible/2.0.0-0.9.rc4_1/bin/ansible
```

NB if I change the root shell of FreeBSD to /bin/sh (default is /bin/csh) then this works:

```
dch 🍺  /r/v ❯❯❯ansible all -l tenrtwo -u root -m setup -vvvv
Using /Volumes/ramdisk/v/ansible.cfg as config file
Loaded callback minimal of type stdout, v2.0
<172.16.213.226> ESTABLISH SSH CONNECTION FOR USER: root
<172.16.213.226> SSH: EXEC ssh -C -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o 'IdentityFile="ansible_20140919"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -tt 172.16.213.226 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452203085.58-156715175684107 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452203085.58-156715175684107 )"'
<172.16.213.226> PUT /var/folders/rv/8w04tcb13kqbxcyqprhrvvfm0000z9/T/tmphFIQEf TO /root/.ansible/tmp/ansible-tmp-1452203085.58-156715175684107/setup
<172.16.213.226> SSH: EXEC sftp -b - -C -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o 'IdentityFile="ansible_20140919"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 '[172.16.213.226]'
<172.16.213.226> ESTABLISH SSH CONNECTION FOR USER: root
<172.16.213.226> SSH: EXEC ssh -C -vvv -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o 'IdentityFile="ansible_20140919"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -tt 172.16.213.226 'LANG=en_NZ.UTF-8 LC_ALL=en_NZ.UTF-8 LC_MESSAGES=en_NZ.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1452203085.58-156715175684107/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1452203085.58-156715175684107/" > /dev/null 2>&1'
...
```

**Comment by bcoca** [comment]
Can you set ansible_shell_type=csh ? it is required to support csh shells

**Comment by dch** [comment]
@bcoca yes I can, & that does fix the issue.

However it's still a regression between 1.9.x and 2.0 so needs documenting somewhere, either in CHANGELOG, http://docs.ansible.com/ansible/intro_bsd.html or both, I will add them just let me know where you want it.

**Comment by bcoca** [comment]
1.9 also needed this variable set to properly function with csh

**Comment by bcoca** [comment]
adding a mention to the BSD page does seem appropriate, this is documented elswhere but 90% of those hitting it are using root on FreeBSD.

**Comment by mike-pt** [comment]
Jsut upgrade to 2.0 and I'm getting the same but adding `ansible_shell_type=csh` or cahnging to /bin/sh

-m raw works fine, I'm just seeing this for setup

EDIT: And only fails for remote hosts, I just tried with "local" and  works fine

**Comment by problame** [comment]
Can confirm the bug is present on FreeBSD 10.2-RELEASE.
Setting `ansible_shell_type=csh` fixes the issue for me.

Without `ansible_shell_type=csh`

```
$ ansible -i staging -vvvv mailhost -m setup
Loaded callback minimal of type stdout, v2.0
<192.168.122.185> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.122.185> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/cs/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.122.185 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453066661.0-187888834093705 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453066661.0-187888834093705 )"'
mailhost | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1453066661.0-187888834093705 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1453066661.0-187888834093705 )\", exited with result 1: Illegal variable name.\r\n", 
    "unreachable": true
}
```

With `ansible_shell_type=csh` the normal output is printed.

**Comment by mike-pt** [comment]
hum,  is ansible_shell_type defined in .cfg or in the hosts file?  

I was assuming ansible.cfg but maybe that's wrong cause I'm not seening changes.

**Comment by bcoca** [comment]
executable (which sets the shell) is settable in ansible.cfg, but ansible_shell_type is a per host variable.

closing this in favor of #13882 as this is all the same issue

**Comment by vbotka** [comment]
For the record. Example of working hosts file with fresh droplet FreBSD 10.3 on digitalocean (change the IP).

[do-bsd-test]
123.123.123.123

[do-bsd-test:vars]
ansible_shell_type=csh
ansible_connection=ssh
ansible_user=freebsd
ansible_python_interpreter=/usr/local/bin/python2
ansible_perl_interpreter=/usr/local/bin/perl

**Comment by bcoca** [comment]
you should not set ansible_shell_type unless you are restricted to csh, which would also require you to set 'executable' to /bin/csh.

**Comment by vbotka** [comment]
Thank you for the comment.  As a first step in FreeBSD I change the login shell for ansible_user to /bin/sh . Then all is right.

```
ansible  do-bsd-test -e 'ansible_shell_type=csh ansible_shell_executable=/bin/csh' -a 'sudo pw usermod freebsd -s /bin/sh'
```
