### ISSUE TITLE
Error set_fs_attributes_if_different() when using Module  'file state=link'

### ISSUE THREAD

**Issue by DANic-git** [ansible/ansible#13973]
**OS CentOS7**
**ansible --version
ansible 2.0.0.2**

**Step to Install ansible:**
1. git clone git://github.com/ansible/ansible.git --recursive
2. cd ansible
3. git checkout tags/v2.0.0.2-1 -b v2.0.0.2-1
4. make rpm
###### 

Ansible RPM is built:
    rpm-build/ansible-2.0.0.2-0.git201601142217.7de237c.headsv20021.el7.centos.noarch.rpm
###### 
1. rpm -Uvh rpm-build/ansible-2.0.0.2-0.git201601142217.7de237c.headsv20021.el7.centos.noarch.rpm

**Step to reproduce bug**
1. Login to CentOS for root via ssh
2. ansible localhost -m file -a "state=link src=/usr/share/zoneinfo/Europe/Moscow dest=/etc/localtime" -vvv

**Actual result:**

Using /etc/ansible/ansible.cfg as config file
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438 )" )
127.0.0.1 PUT /tmp/tmpjn9vqm TO /root/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438/file
127.0.0.1 EXEC LANG=ru_RU.UTF-8 LC_ALL=ru_RU.UTF-8 LC_MESSAGES=ru_RU.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438/file; rm -rf "/root/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438/file", line 2363, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1453190767.59-51621343552438/file", line 394, in main
    changed = module.set_fs_attributes_if_different(file_args, changed, diff)
TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)

localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "file"
    },
    "parsed": false
}

**NOT reproduce on ansible 1.9.4**

**Comment by jimi-c** [comment]
I just tried this on my system (Fedora 23, so similar but not exact), and didn't get the same result:

<pre>
# ansible localhost -m file -a "state=link src=/usr/share/zoneinfo/America/New_York dest=/etc/localtime" -vvv 
Using /etc/ansible/ansible.cfg as config file
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453318459.98-173920577922090 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453318459.98-173920577922090 )" )
127.0.0.1 PUT /tmp/tmpesYQb5 TO /root/.ansible/tmp/ansible-tmp-1453318459.98-173920577922090/file
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453318459.98-173920577922090/file; rm -rf "/root/.ansible/tmp/ansible-tmp-1453318459.98-173920577922090/" > /dev/null 2>&1
localhost | SUCCESS => {
    "changed": true, 
    "dest": "/etc/localtime", 
    "diff": {
        "after": {
            "path": "/etc/localtime"
        }, 
        "before": {
            "path": "/etc/localtime"
        }
    }, 
    "gid": 0, 
    "group": "root", 
    "invocation": {
        "module_args": {
            "_ansible_check_mode": false, 
            "_ansible_debug": false, 
            "_ansible_diff": false, 
            "_ansible_no_log": false, 
            "_ansible_verbosity": 3, 
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "dest": "/etc/localtime", 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "mode": null, 
            "original_basename": null, 
            "owner": null, 
            "path": "/etc/localtime", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/usr/share/zoneinfo/America/New_York", 
            "state": "link", 
            "validate": null
        }, 
        "module_name": "file"
    }, 
    "mode": "0777", 
    "owner": "root", 
    "secontext": "unconfined_u:object_r:etc_t:s0", 
    "size": 36, 
    "src": "/usr/share/zoneinfo/America/New_York", 
    "state": "link", 
    "uid": 0
}
</pre>

You might want to check your system for old pyc/egg files, which could be getting picked up incorrectly. When checking out different tags I typically find myself running `find ./ -name "*.pyc" -delete` to clean out my source tree of old files (especially when switching between devel and stable-1.9).

**Comment by dmacbride** [comment]
I reproduced a similiar error.
- install clean VM from ISO yesterday (CentOS v7)
- install EPEL
  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  rpm -Uhv epel-release-latest-7.noarch.rpm
- yum -y install ansible
  # Ansible 1.9 is installed, with all defined dependencies
- cd ~
- git clone git://github.com/ansible/ansible.git --recursive
- cd ansible
- git checkout stable-2.0.0.1
- make rpm
- rpm -Uvh rpm-build/ansible-2.0.0.2-0.git201601142217.7de237c.stable2001.el7.centos.noarch.rpm
- run playbook containing task with file module, like:
  file: dest=/some/dir/name mode=755 state=directory

Result:
fatal: [db1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453404299.2-236569534393728/file\", line 2363, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453404299.2-236569534393728/file\", line 318, in main\r\n    changed = module.set_fs_attributes_if_different(file_args, changed, diff)\r\nTypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)\r\n", "msg": "MODULE FAILURE", "parsed": false}

[Edit]
I went back to the source dir, did:
- find ./ -name "*.pyc" -delete
- make clean
- git checkout stable-2.0
- make rpm
- rpm -e ansible-2.0.0.2-0.git201601142217.7de237c.stable2001.el7.centos.noarch
- rpm -Uvh rpm-build/ansible-2.0.0.0-0.git201601211553.92579eb.stable20.el7.centos.noarch.rpm

Reran the play with the mentioned file module task, and the issue recurred:  

An exception occurred during task execution. The full traceback is:
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1453407114.13-184790152457146/file", line 2376, in <module>
        main()
      File "/root/.ansible/tmp/ansible-tmp-1453407114.13-184790152457146/file", line 276, in main
        changed = module.set_fs_attributes_if_different(file_args, changed, diff)
    TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)

[Edit 2]:
The attached file.zip contains the mentioned 'file' script that generated the error.  

Line 276 is calling it like so:
changed = module.set_fs_attributes_if_different(file_args, changed, diff)

The method signature is like so: 
def set_fs_attributes_if_different(self, file_args, changed):

I'm not proficient in Python, but I read that in Python the 'self' argument is implicit so callers of this method should only pass two. The names of the args suggest that the argument named 'diff' isn't expected.  Also, other callers in the same file only pass two arguments.  I suspect that the 'diff' arg isn't expected and is causing the problem.

[file.zip](https://github.com/ansible/ansible/files/99847/file.zip)

**Comment by dmacbride** [comment]
If my analysis above is right then it looks like this was introduced with commit 48bd80c9cbf0bf9b0b81bdeb158b7f6338b2a11a.  

See the 'diff' param added in a few of the calls to set_fs_attributes_if_different()

https://github.com/ansible/ansible-modules-core/commit/48bd80c9cbf0bf9b0b81bdeb158b7f6338b2a11a#diff-ec997744320cc294d6e1d2a1e1b68938

**Comment by jimi-c** [comment]
@dmacbride yes, looks like we accidentally pointed the stable-2.0 submodules at the devel branches instead of the corresponding stable-2.0 branches. This should be resolved now.

**Comment by gpthome** [comment]
We're running into this issue as well.  Can you be more clear where the fix is?  We built tag ansible-2.0.0.2-0 (CentOs7) and we're still experiencing "TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)".  Perhaps a different problem?

**Comment by jimi-c** [comment]
@gpthome there is no tag by that name in our tags, can you detail how you're installing Ansible and running into this? The problem was that the stable-2.0 branch for ansible was pointing at the devel branch for ansible-modules-core. This was corrected, so using the stable-2.0 branch from git shouldn't be seeing this error anymore.

**Comment by dcfsc** [comment]
@jimi-c (working with @gpthome) we first built 

```
git clone git://github.com/ansible/ansible.git --recursive ansible-rpm
cd ansible-rpm/
git checkout stable-2.0
make rpm
scp ansible-2.0.0.0-0.git201601262306.a0b7620.stable20.el7.centos.noarch.rpm  root@ourmachine.com
```

That rpm showed the problem.
Then we tried the latest tag (see that at https://github.com/ansible/ansible/tree/v2.0.0.2-1)

```
git checkout v2.0.0.2-1
make clean
make rpm
scp ansible-2.0.0.2-0.git201601142217.7de237c.HEAD.el7.centos.noarch.rpm root@ourmachine.com
```

This also has the issue.

I was a little nervous about using the devel branch. Do you have a 2.0-ish branch we can build in which the issue is fixed?  Any idea when the RPM for EPEL will be updated? -- maybe we are doing something wrong in the rpm build. Thanks.

**Comment by jimi-c** [comment]
Here is your problem, you're not running `git submodule update` after your checkouts, so the submodules are still pointing at the devel branches (where the new code lives).

**Comment by slapers** [comment]
I had the problem when installing ansible 1.9.4-1 using pip with the command, just wanted to note that it can sneak into 1.9.4-1 as well. (perhaps the command i used is not ok?) 

```
pip install git+https://github.com/ansible/ansible@v1.9.4-1
```

After cloning 1.9.4-1 from source and updating the submodules the issue was solved.

**Comment by jimi-c** [comment]
Ahh, I guess pip is not intelligent enough to update the submodule pointers either, or there is some other option required there.

Based on the above though, I'm going to go ahead and close this issue. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
