### ISSUE TITLE
Ansible 2.X setup module no longer works on RHEL5.10 (python 2.4)

### ISSUE THREAD

**Issue by ttbigc** [ansible/ansible#14026]
After upgrading to Ansible 2.1.0 from Ansible 1.9.4 I can no longer manage RHEL5.10 hosts due to issue with Ansible's fact collection module setup:

```
[root@tesseract ntp]# ansible orb.xxxxxx.com -m setup
SSH password:
orb.xxxxxx.com | FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453315204.23-193961227391593/setup\", line 5192, in ?\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453315204.23-193961227391593/setup\", line 140, in main\r\n    data = run_setup(module)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453315204.23-193961227391593/setup\", line 84, in run_setup\r\n    facts = ansible_facts(module)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453315204.23-193961227391593/setup\", line 5127, in ansible_facts\r\n    facts.update(Facts().populate())\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453315204.23-193961227391593/setup\", line 2284, in __init__\r\n    self.get_service_mgr_facts()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453315204.23-193961227391593/setup\", line 2684, in get_service_mgr_facts\r\n    proc_1 = os.path.basename(get_file_content('/proc/1/comm'))\r\n  File \"/usr/lib64/python2.4/posixpath.py\", line 112, in basename\r\n    return split(p)[1]\r\n  File \"/usr/lib64/python2.4/posixpath.py\", line 77, in split\r\n    i = p.rfind('/') + 1\r\nAttributeError: 'NoneType' object has no attribute 'rfind'\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}
```

Client details:

```
[root@orb ~]# python -V
Python 2.4.3
[root@orb ~]# rpm -q python-simplejson
python-simplejson-2.0.9-8.el5
[root@orb ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.10 (Tikanga)
```

**Comment by sivel** [comment]
It looks like this is due to https://github.com/ansible/ansible/commit/83069a38d5c2acd4537f940bd7fbd3c37766d752

We probably need an intermediate step, instead of passing the return of `get_file_content` directly into `os.path.basename`, since `get_file_content` can return `None`.

cc @bcoca

**Comment by sivel** [comment]
Perhaps something like:

``` diff
diff --git a/lib/ansible/module_utils/facts.py b/lib/ansible/module_utils/facts.py
index a214b6b..ec1c679 100644
--- a/lib/ansible/module_utils/facts.py
+++ b/lib/ansible/module_utils/facts.py
@@ -559,9 +559,11 @@ class Facts(object):
         # also other OSs other than linux might need to check across several possible candidates

         # try various forms of querying pid 1
-        proc_1 = os.path.basename(get_file_content('/proc/1/comm'))
+        proc_1 = get_file_content('/proc/1/comm')
         if proc_1 is None:
             rc, proc_1, err = module.run_command("ps -p 1 -o comm|tail -n 1", use_unsafe_shell=True)
+        else:
+            proc_1 = os.path.basename(proc_1)

         if proc_1 == 'init' or proc_1.endswith('sh'):
             # many systems return init, so this cannot be trusted, if it ends in 'sh' it probalby is a shell in a container
```

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by ttbigc** [comment]
Thanks Sivel - Verified fix does indeed correct issue. Do you know when this fix will pushed upstream?

**Comment by sivel** [comment]
@ttbigc this change is now in devel.  The issue was only in devel and not in any released versions.

**Comment by ttbigc** [comment]
Matt / @sivel - Getting another issue now only on my RHEL5 box, possible it is related?
failed: [orb.xxxxxx.com] => (item=[u'ntp']) => {"failed": true, "item": ["ntp"], "module_stderr": "", "module_stdout": "{\"msg\": \"\", \"invocation\": {\"module_args\": {\"_ansible_check_mode\": false, \"name\": [\"ntp\"], \"disable_gpg_check\": false, \"_ansible_debug\": false, \"list\": null, \"_ansible_verbosity\": 0, \"conf_file\": null, \"install_repoquery\": true, \"state\": \"present\", \"disablerepo\": null, \"update_cache\": false, \"enablerepo\": null, \"exclude\": null, \"validate_certs\": true, \"_ansible_diff\": false, \"_ansible_no_log\": false}}, \"changed\": false, \"results\": [\"ntp-4.2.2p1-18.el5_11.x86_64 providing ntp is already installed\"], \"rc\": 0}\r\nException exceptions.AttributeError: \"'NoneType' object has no attribute 'unshare_data'\" in <bound method YumBase.__del__ of <yum.YumBase object at 0x2492410>> ignored\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by sivel** [comment]
That appears to be coming from the yum module.  I'd open a new issue for that.

**Comment by julienvey** [comment]
@sivel Can you link the new issue you opened. I just had the problem with ansible 2.0.0.2

**Comment by sivel** [comment]
This issue was resolved with the commits referenced above.  No issue was created.

See https://github.com/ansible/ansible/commit/d49b11e9962df4bde4b8f3d61029305af4115748

**Comment by afunix** [comment]
The issue is still there in ansible 2.0.1.0.
I'm surprised that a bug can be closed until the fix is in stable release...
How ansible can be used in any production environment with such a policy??

**Comment by afunix** [comment]
The patch for 2.0.1.0 changed:

```
--- ansible-baseline/lib/ansible/module_utils/facts.py  2016-03-06 16:03:50.000000000 +0300
+++ ansible/lib/ansible/module_utils/facts.py   2016-03-06 16:03:20.000000000 +0300
@@ -562,7 +562,7 @@ class Facts(object):
         # also other OSs other than linux might need to check across several possible candidates

         # try various forms of querying pid 1
-        proc_1 = os.path.basename(get_file_content('/proc/1/comm'))
+        proc_1 = get_file_content('/proc/1/comm')
         if proc_1 is None:
             rc, proc_1, err = module.run_command("ps -p 1 -o comm|tail -n 1", use_unsafe_shell=True)
         else:
```
