### ISSUE TITLE
ansible 2.0 file state=link bug

### ISSUE THREAD

**Issue by usterk** [ansible/ansible#14048]
I have a problem with running: 

```
- file: src=/tmp/a dest=/tmp/b state=link force=yes
```

I'm getting: 

```
fatal: [foo.bar.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1453384563.99-224596106487991/file\", line 2376, in <module>\r\n    main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1453384563.99-224596106487991/file\", line 394, in main\r\n    changed = module.set_fs_attributes_if_different(file_args, changed, diff)\r\nTypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

I'm running ansible from OSX. Target system is ubuntu 14.04.

**Comment by ktaragorn** [comment]
Hey, If you are on `devel` branch could you try fetching the latest? I see the fourth argument (per the error) was added very recently

**Comment by usterk** [comment]
It works on `devel`. It does not work on `stable-2.0`.

**Comment by ktaragorn** [comment]
The commit in question is likely 6f2f7a79

**Comment by ktaragorn** [comment]
@bcoca Could you take a look here? I dont think that commit is included in either the stable-2.0 or stable-2.0.0.1 branches

**Comment by jimi-c** [comment]
This should be resolved, as we had accidentally pointed the stable-2.0 branch at the devel submodules. Can you please confirm that this was only when checking out the stable-2.0 branch from git?

**Comment by usterk** [comment]
Yes. It is in version from github. I still have this error in latest `stable-2.0` (`cd0812a`).

**Comment by dagwieers** [comment]
I cannot reproduce this with the following playbook:

``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - file: src=/tmp/a dest=/tmp/b state=link force=yes
```

With the following output:

```
[dag@moria ansible.dag]$ ansible-playbook test56.yml

PLAY ***************************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   

[dag@moria ansible.dag]$ ansible-playbook test56.yml

PLAY ***************************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by usterk** [comment]
Maybe I'm testing it in the wrong way.

Here is what I'm doing:

```
git clone git://github.com/ansible/ansible.git --recursive
cd ansible
git checkout origin/stable-2.0
source ./hacking/env-setup
```

and then:

```
$ ansible-playbook a.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY ***************************************************************************

TASK [file] ********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: set_fs_attributes_if_different() takes exactly 3 arguments (4 given)
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @a.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by dagwieers** [comment]
@usterk I have tested with 2.0.0.2 only, I will come back with some more tests with the devel branch.

**Comment by jimi-c** [comment]
Ok,this is due to you not updating submodules when checking out the new branch. Any time you switch from devel to one of the stable branches, you will need to run `git submodule update` afterwards, otherwise the submodules will still be pointing at devel's version. Unfortunately, I'm not aware of any option or setting which makes git automatically execute that update when switching branches (maybe someone else does?).

**Comment by jimi-c** [comment]
Also note you may have to update submodules any time you re-pull or switch back to devel.

I've also found that switching from stable-1.9 to the newer branches (or vice versa) causes python to fail due to old pyc/egg files being found. Not sure why python isn't smart enough to notice it's out of date, but my work flow is usually: `git checkout <branch>; git submodule update; find . -name "*.pyc" -delete`

**Comment by bcoca** [comment]
i added .pyc to 'make clean' target, but you need to source having/env-setup again afterwards

**Comment by jimi-c** [comment]
As this is resolved, I'll go ahead and close this now.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
