### ISSUE TITLE
Copy module "Calculating checksum failed unusually" script module "Permission denied

### ISSUE THREAD

**Issue by Brian-Williams** [ansible/ansible#14215]
Issue Type:
Bug Report
Ansible Version: ansible 1.9.4 and ansible 2.0.0

Ansible Configuration:
[ssh_connection]
scp_if_ssh=True

Environment:
Mac [Darwin engwifi-230-23.wal.actifio.com 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64] managing Centos [Linux augusta 2.6.32-358.14.1.5.sanvc_7_2_0_1.x86_64 #1 SMP PREEMPT Thu Sep 24 11:43:41 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux]

Summary:
Copy module is giving "Calculating checksum failed unusually" although files are correctly being sent even when module reports failure. In a related problem script module doesn't function against that set of hosts (Centos machine with IBM SVC installed). When running script module I recieve stdout: bash: /home/root/.ansible/tmp/ansible-tmp-1452900006.99-249090233060510/version.sh: Permission denied. However /home/root (.ansible location) isn't mounted with noexec.

Additional info on script execution [here](https://groups.google.com/forum/#!msg/ansible-project/k0T4DkshLpU/8OFs9JO7BgAJ).

Steps To Reproduce:

**From role:**
### qa_release/tasks/main.yml

```

---
  - name: copy over scripts
    copy: src={{ item }} dest=/home/root/ owner=root group=root mode="u=rwx,g=r,o=r"
    with_items:
      - version.sh
      - rpm_check.sh
```

[omitted plays that execute scripts, they aren't reached]

**From play:**

```

---
- hosts: cds
  gather_facts: no

  vars_prompt:
    - name: "sky_rpm_manifest"
      prompt: "Link to sky manifest file"
      private: no

  roles:
    - { role: qa_release-checks, sky_rpm_manifest: "{{ sky_rpm_manifest }}" }
```

Expected Results:

Files copy over successfully and report pass. Files aren't on machine in case of failures.

Actual Results:
Following from 2.0.0 executions
**Output:**

```
PLAY ***************************************************************************

TASK [qa_release-checks : copy over scripts] ***********************************
changed: [augusta.sqa.actifio.com] => (item=version.sh)
changed: [augusta.sqa.actifio.com] => (item=rpm_check.sh)
changed: [tigh] => (item=version.sh)
changed: [tigh] => (item=rpm_check.sh)
 [WARNING]: Calculating checksum failed unusually, please report this to the list so it can be fixed command: rc=flag; [ -r /home/root/version.sh ] || rc=2; [ -f /home/root/version.sh ] || rc=1; [ -d
/home/root/version.sh ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home/root/version.sh && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher =
hashlib.sha1(); afile = open("'/home/root/version.sh'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:         hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile = open("'/home/root/version.sh'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:
hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/home/root/version.sh) ---- output: {'stdout_lines': [], 'stdout': u'', 'stderr':
u'', 'rc': 255} ----
```

**Output after first run when scripts haven't been removed:**

```
PLAY ***************************************************************************

TASK [qa_release-checks : copy over scripts] ***********************************
ok: [tigh] => (item=version.sh)
ok: [tigh] => (item=rpm_check.sh)
ok: [augusta.sqa.actifio.com] => (item=version.sh)
ok: [augusta.sqa.actifio.com] => (item=rpm_check.sh)
 [WARNING]: Calculating checksum failed unusually, please report this to the list so it can be fixed command: rc=flag; [ -r /home/root/version.sh ] || rc=2; [ -f /home/root/version.sh ] || rc=1; [ -d
/home/root/version.sh ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home/root/version.sh && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher =
hashlib.sha1(); afile = open("'/home/root/version.sh'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:         hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile = open("'/home/root/version.sh'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:
hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/home/root/version.sh) ---- output: {'stdout_lines': [], 'stdout': u'', 'stderr':
u'', 'rc': 255} ----

 [WARNING]: Calculating checksum failed unusually, please report this to the list so it can be fixed command: rc=flag; [ -r /home/root/rpm_check.sh ] || rc=2; [ -f /home/root/rpm_check.sh ] || rc=1; [ -d
/home/root/rpm_check.sh ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/home/root/rpm_check.sh && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher =
hashlib.sha1(); afile = open("'/home/root/rpm_check.sh'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:         hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile = open("'/home/root/rpm_check.sh'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:
hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/home/root/rpm_check.sh) ---- output: {'stdout_lines': [], 'stdout': u'',
'stderr': u'', 'rc': 255} ----
```

**Comment by lenar** [comment]
Happens to me too. Just a bit annoying.

**Comment by hyperized** [comment]
Happening here too, seems to be more present under 2.0 than earlier versions. It's not affecting one file, but several across several servers at seemingly random.

**Comment by hyperized** [comment]
I also checked if it made a difference wether SCP or SFTP was used (due to potential unreliable SCP transfers) however this was not the case.

**Comment by jkarneges** [comment]
I received a similar warning the other day. I've only ever seen it once. Using 2.0.0.2. Here's the output:

```
 [WARNING]: Calculating checksum failed unusually, please report this to the
list so it can be fixed command: rc=flag; [ -r /lib/systemd/system/whs-
publisher.service ] || rc=2; [ -f /lib/systemd/system/whs-publisher.service ] ||
rc=1; [ -d /lib/systemd/system/whs-publisher.service ] && rc=3; python -V
2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/lib/systemd/system
/whs-publisher.service && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536;
hasher = hashlib.sha1(); afile = open("'/lib/systemd/system/whs-
publisher.service'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:
hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE =
65536; hasher = sha.sha(); afile = open("'/lib/systemd/system/whs-
publisher.service'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:
hasher.update(buf)         buf = afile.read(BLOCKSIZE) afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/lib/systemd/system/whs-
publisher.service) ---- output: {'stdout_lines': [], 'stdout': u'', 'stderr':
u'', 'rc': 0} ----
```

**Comment by bcoca** [comment]
can you test against current devel branch? we just merged a revamp of the checksum code that should solve this issue

**Comment by TerryHowe** [comment]
I just udated to 2.0.1.0 and I'm still seeing this.  Is there a work around?

**Comment by bcoca** [comment]
fix is in current devel, did not make it to 2.0.1

**Comment by TerryHowe** [comment]
Yeh, I installed from devel and it works.  Sorry, not familiar with how you guys release.

**Comment by hyperized** [comment]
When can we expect this to be in the stable branch? I don't want to switch production to devel and we still have a lot of failing runs due to this issue.

**Comment by bcoca** [comment]
once i get confirmation this actually solves the issue, its a big change to push to stable w/o it (i don't have reproducer).

**Comment by TerryHowe** [comment]
Solved the issue for me.

**Comment by Brian-Williams** [comment]
It did not solve the issue for me. Tested with and without scp_if_ssh. Script module runs fine, but copy still returns checksum failed. Tried several changes to copy play, none made a difference. Script module continues to function as expected.

```
$ ansible-playbook test.yml -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [172.16.201.28] ***********************************************************

TASK [test delegate script] ****************************************************
task path: /Users/brianwilliams/Projects/ansible/test.yml:7
<172.16.201.28> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 172.16.201.28
<172.16.201.28> EXEC /bin/sh -c 'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456808891.84-114592804329132 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456808891.84-114592804329132 `"'
<172.16.201.28> PUT /Users/brianwilliams/Projects/ansible/test.sh TO /root/.ansible/tmp/ansible-tmp-1456808891.84-114592804329132/test.sh
<172.16.201.28> EXEC /bin/sh -c 'chmod +rx /root/.ansible/tmp/ansible-tmp-1456808891.84-114592804329132/test.sh'
<172.16.201.28> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /root/.ansible/tmp/ansible-tmp-1456808891.84-114592804329132/test.sh '
<172.16.201.28> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1456808891.84-114592804329132/ > /dev/null 2>&1'
changed: [172.16.201.28] => {"changed": true, "invocation": {"module_args": {"_raw_params": "test.sh"}, "module_name": "script"}, "rc": 0, "stderr": "", "stdout": "hello ymir\r\n", "stdout_lines": ["hello ymir"]}

TASK [copy] ********************************************************************
task path: /Users/brianwilliams/Projects/ansible/test.yml:10
<172.16.201.28> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 172.16.201.28
<172.16.201.28> EXEC /bin/sh -c 'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456808892.94-260208976397385 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456808892.94-260208976397385 `"'
<172.16.201.28> PUT /var/folders/yq/p2rh02yx6x7fh0m9kdnp5z140000gn/T/tmpc4TTbf TO /root/.ansible/tmp/ansible-tmp-1456808892.94-260208976397385/stat
<172.16.201.28> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1456808892.94-260208976397385/stat; rm -rf "/root/.ansible/tmp/ansible-tmp-1456808892.94-260208976397385/" > /dev/null 2>&1'
<172.16.201.28> EXEC /bin/sh -c 'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456808894.16-129317382115918 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456808894.16-129317382115918 `"'
<172.16.201.28> PUT /Users/brianwilliams/Projects/ansible/test.sh TO /root/.ansible/tmp/ansible-tmp-1456808894.16-129317382115918/source
<172.16.201.28> EXEC /bin/sh -c 'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456808894.4-259613448856613 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456808894.4-259613448856613 `"'
<172.16.201.28> PUT /var/folders/yq/p2rh02yx6x7fh0m9kdnp5z140000gn/T/tmp9MaaVF TO /root/.ansible/tmp/ansible-tmp-1456808894.4-259613448856613/copy
<172.16.201.28> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1456808894.4-259613448856613/copy; rm -rf "/root/.ansible/tmp/ansible-tmp-1456808894.4-259613448856613/" > /dev/null 2>&1'
fatal: [172.16.201.28]: FAILED! => {"changed": false, "checksum": "91139076872bb4bad8125403aed9a53af4218647", "failed": true, "invocation": {"module_args": {"backup": false, "content": null, "delimiter": null, "dest": "/home/root/version.sh", "directory_mode": null, "follow": false, "force": true, "group": "root", "mode": "u=rwx,g=r,o=r", "original_basename": "test.sh", "owner": "root", "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/root/.ansible/tmp/ansible-tmp-1456808894.16-129317382115918/source", "validate": null}}, "msg": "Destination directory /home/root does not exist"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
172.16.201.28              : ok=1    changed=1    unreachable=0    failed=1   

$ ansible --version
ansible 2.1.0 (devel 201bd8c0b5) last updated 2016/02/29 23:43:49 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 0bbb7ba38d) last updated 2016/02/29 23:43:52 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 39e4040685) last updated 2016/02/29 23:43:54 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
$ cat test.yml 
---

- hosts: 172.16.201.28
  gather_facts: no

  tasks:
  - name: test delegate script
    script: test.sh

  - copy: src=test.sh dest=/home/root/version.sh owner=root group=root mode="u=rwx,g=r,o=r"

  - shell: /home/root/test.sh
    changed_when: false
```

**Comment by bcoca** [comment]
@Brian-Williams so the error seems to have changed to 'missing a directory' which is not the original checksum failed.

I'm going to close this issue as fixed and push the fix to stable (2.0.2 and 2.1 will have it)
