### ISSUE TITLE
delegate_to doesn't recognize hosts from dynamic inventory

### ISSUE THREAD

**Issue by adeck** [ansible/ansible#14422]
**Issue Type:** Bug report
**Ansible version:** tested on both version 2.0.0.1 and 2.0.0.2

Here's the 2.0.0.1 output (it's the same for both. Except for the final digit, of course).

```
ansible 2.0.0.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Ansible Configuration:** Default. Nothing special.
**Environment:** Not relevant.
**Summary:**

`delegate_to` doesn't realize when you're specifying a host that's in the inventory IFF you use dynamic inventory, whereas that functionality works fine for a static inventory.

**Steps To Reproduce:**

The file `inventory/dynamic.sh` simply contains `cat inventory/hosts.json`.

Contents of `inventory/hosts.ini`:

```
test_host ansible_ssh_user=root ansible_ssh_host=192.168.56.121
```

Contents of `inventory/hosts.json`:

```
{
  "null": ["test_host"]
  ,"_meta": { "hostvars" : {
      "test_host" : {
          "ansible_ssh_host" : "192.168.56.121"
          ,"ansible_ssh_user": "root"
      } 
    } }
}
```

This is my `site.yml` file:

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: test delegation
      ping:
      delegate_to: "{{ item }}"
      with_items:
        - 192.168.56.121
        - test_host
```

Simply run:

```
ansible-playbook -i inventory/dynamic.sh -vvv -Kk site.yml
ansible-playbook -i inventory/hosts.ini -vvv -Kk site.yml
```

**Expected Results:**

I expect that the playbook will behave identically whether or not the inventory is dynamic. Specifically, I expect that ansible will figure out if I'm delegating to a host within the inventory, and behave accordingly.

**Actual Results:**

(Some irrelevant + redundant output omitted for brevity.)

When I run `ansible-playbook -i inventory/dynamic.sh -vvv -Kk site.yml` I get:

```
PLAY ***************************************************************************

TASK [test delegation] *********************************************************
task path: /var/devel/sandbox/test_delegate_to/site.yml:7
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s 
-o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.56
.121 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136642.93-59373194126
289 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136642.93-59373194126289 )" )'
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.56.121 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136644.88-138271673646011 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136644.88-138271673646011 )" )'
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"item": "192.168.56.121", "msg": "ERROR! Authentication failure.", "unreachable": true}, {"item": "test_host", "msg": "ERROR! Authentication failure.", "unreachable": true}]}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0
```

When I run `ansible-playbook -i inventory/hosts.ini -vvv -Kk site.yml` I get:

```
PLAY ***************************************************************************

TASK [test delegation] *********************************************************
task path: /var/devel/sandbox/test_delegate_to/site.yml:7
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.56.121 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136652.03-238224503374773 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136652.03-238224503374773 )"'
<192.168.56.121> PUT /tmp/tmpoio5rb TO /root/.ansible/tmp/ansible-tmp-1455136652.03-238224503374773/ping
<192.168.56.121> SSH: EXEC sshpass -d14 sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.56.121]'
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.56.121 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1455136652.03-238224503374773/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1455136652.03-238224503374773/" > /dev/null 2>&1'
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.56.121 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136653.04-111160372669856 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455136653.04-111160372669856 )"'
<192.168.56.121> PUT /tmp/tmpB_5Zxy TO /root/.ansible/tmp/ansible-tmp-1455136653.04-111160372669856/ping
<192.168.56.121> SSH: EXEC sshpass -d14 sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.56.121]'
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.56.121 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1455136653.04-111160372669856/ping; rm -rf "/root/.ansible/tmp/ansible-tmp-1455136653.04-111160372669856/" > /dev/null 2>&1'
ok: [127.0.0.1 -> None] => (item=192.168.56.121) => {"changed": false, "invocation": {"module_args": {"data": null}, "module_name": "ping"}, "item": "192.168.56.121", "ping": "pong"}
ok: [127.0.0.1 -> None] => (item=test_host) => {"changed": false, "invocation": {"module_args": {"data": null}, "module_name": "ping"}, "item": "test_host", "ping": "pong"}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0
```

I know the issue is host variable inference because of the line `ESTABLISH SSH CONNECTION FOR USER: None` in the first output.

**Comment by adeck** [comment]
Upon further testing, to see if the issue might be that I'm using `ansible_ssh_*` variables rather than `ansible_*` variables, I discovered that removing the `ssh_` gets me slightly closer to a solution (at least using 2.0.0.2):

```
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "result
s": [{"item": "192.168.56.121", "msg": "ERROR! Authentication failure.", "unreachable": true},
 {"_ansible_delegated_vars": {"ansible_host": "192.168.56.121"}, "_ansible_no_log": false, "ch
anged": false, "invocation": {"module_args": {"data": null}, "module_name": "ping"}, "item": "
test_host", "ping": "pong"}]}
```

And it makes four requests instead of two; for each item in the list, it first tries to connect with user None / no username specified, then root.

```
<192.168.56.121> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.56.121> SSH: EXEC sshpass -d14 ssh -C -q -o ControlMaster=auto -o ControlPersist=60
s -o User=root -o ConnectTimeout=10 -o ControlPath=/var/devel/.ansible/cp/ansible-ssh-%h-%p-%r
 -tt 192.168.56.121 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455138309.73-3514941601
6181 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455138309.73-35149416016181 )"'
```

Still fails overall, though.

**Comment by adeck** [comment]
...Aaaaand it also fails if the variables are defined in `host_vars` rather than the `.ini` file itself. On the most recent version. Regardless of whether or not you use `ansible_ssh_user` or `ansible_user` (although again, as above, it does behave slightly differently if you specify `ansible_user`).

**Comment by kmagnc** [comment]
Seeing the same issue (2.0.0.2)

/bump

**Comment by piffey** [comment]
This is also an issue when using the add_host module to add hosts dynamically.

**Comment by adeck** [comment]
Worth pointing out that this is a regression from functionality that worked in 1.9.x.

Speaking of...
- does ansible aim for backwards-compatibility with playbooks targeting older versions? And, if not...
- is there an Ansible, Inc. support EOL planned for version 1.9.x?

**Comment by bcoca** [comment]
So i believe #15024 should fix this and apply the correct vars

**Comment by adeck** [comment]
Thanks, @bcoca . :)

I'll run the above M.W.E. with your patch later today or tomorrow and close this issue iff it works as expected (assuming the issue hasn't already been closed by someone else by then).

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by juanvalino** [comment]
Bug is not fixed. Seems that one of the lasts versions introduced this problem again. 

Dynamic inventory created by add_host is not used by delegate_to.

**Comment by thorus90** [comment]
```
 # ansible --version
ansible 2.6.3
```
Don't know if this is related but I changed my dynamic inventory so that the variable "ansible_host" does not get set in the group "all" with an variable but for every host static. That fixed it for me.
