### ISSUE TITLE
regression: do-until loop doesn't fail after the last iteration in Ansible 2

### ISSUE THREAD

**Issue by gyurco** [ansible/ansible#14461]
Do-until loops in Ansible 1.x fail when the individual tasks are succeed, but the 'until' condition never reached. In Ansible 2.0.0.2, this kind of loop is a success.

Example playbook:

```
- hosts: localhost
  tasks:
    - command: echo "never be"
      register: test_result
      until: test_result.stdout == 'the same'
```

Running in Ansible 1.9.4:

```
TASK: [command echo "never be"] *********************************************** 
failed: [localhost] => {"attempts": 3, "changed": true, "cmd": ["echo", "never be"], "delta":  "0:00:00.004458", "end": "2016-02-13 11:04:45.683758", "failed": true, "rc": 0, "start": "2016-02-13 11:04:45.679300", "warnings": []}                                                                                                                                                        
stdout: never be                                                                                                                                                                              
msg: Task failed as maximum retries was encountered                                                                                                                                           

FATAL: all hosts have already failed -- aborting                                                                                                                                              
```

In Ansible 2.0.0.2:

```
TASK [command] *****************************************************************
FAILED - RETRYING: TASK: command (2 retries left). Result was: {u'changed': True, u'end': u'2016-02-13 11:03:21.066814', u'stdout': u'never be', u'cmd': [u'echo', u'never be'], u'rc': 0, u'start': u'2016-02-13 11:03:21.062301', u'stderr': u'', u'delta': u'0:00:00.004513', 'invocation': {'module_name': u'command', u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'echo "never be"', u'removes': None, u'warn': True, u'_uses_shell': False}}, 'stdout_lines': [u'never be'], u'warnings': []}
FAILED - RETRYING: TASK: command (1 retries left). Result was: {u'changed': True, u'end': u'2016-02-13 11:03:26.210281', u'stdout': u'never be', u'cmd': [u'echo', u'never be'], u'rc': 0, u'start': u'2016-02-13 11:03:26.206958', u'stderr': u'', u'delta': u'0:00:00.003323', 'invocation': {'module_name': u'command', u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u'echo "never be"', u'removes': None, u'warn': True, u'_uses_shell': False}}, 'stdout_lines': [u'never be'], u'warnings': []}
changed: [localhost]
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by sadams** [comment]
Problem still occurs in ansible 2.0.1.0 - which release did this go into?

**Comment by drew-russell** [comment]
I am seeing this in 2.0.1.0 as well. Any more information on a fix?

**Comment by jimi-c** [comment]
@sadams this will be included in 2.0.2, it didn't make the cutoff for 2.0.1.
