### ISSUE TITLE
Tasks in subsequent plays are not executed if a host in the first play failed.

### ISSUE THREAD

**Issue by stacywsmith** [ansible/ansible#14665]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
user@h0$ ansible-playbook --version
ansible-playbook 2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

Installed from GitHub at approximately:
Thu Feb 25 18:43:33 UTC 2016
##### Ansible Configuration:

No configuration file modifications
##### Environment:

Debian 8

```
user@h0$ uname -a
Linux h0 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```
##### Summary:

Given a playbook with multiple plays run against two target hosts (host1 and host2). If a task in the first play fails for host2, but succeeds for host1, subsequent tasks (and handlers) in the same play are executed on host1, but tasks in subsequent plays are NOT executed on host1. The message "NO MORE HOSTS LEFT" is printed even though host1 has not had any failed tasks.

This is different than the behavior observed on version 1.9.4. On 1.9.4, the tasks in subsequent plays are executed for host1. The behavior also appears to conflict with the documentation and I haven't found any record that this change was intentional.
##### Steps To Reproduce:

```
user@h0$ cat two_plays.pb.yaml 

---
- name: Play 1
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Task 1
      command: /bin/true
      failed_when: "'host2' in inventory_hostname"
      notify: Handler 1
    - name: Task 2
      command: /bin/true
  handlers:
    - name: Handler 1
      command: /bin/true

- name: Play 2
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Task 3
      command: /bin/true
```
##### Expected Results:

I expect the same result as seen on version 1.9.4 in the output below.

```
user@h0$ ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None

user@h0$ ansible-playbook two_plays.pb.yaml 

PLAY [Play 1] ***************************************************************** 

TASK: [Task 1] **************************************************************** 
failed: [host2] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.004436", "end": "2016-02-25 12:04:28.139206", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-02-25 12:04:28.134770", "warnings": []}
changed: [host1]

TASK: [Task 2] **************************************************************** 
changed: [host1]

NOTIFIED: [Handler 1] ********************************************************* 
changed: [host1]

PLAY [Play 2] ***************************************************************** 

TASK: [Task 3] **************************************************************** 
changed: [host1]

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/user/two_plays.pb.yaml.retry

host1                      : ok=4    changed=4    unreachable=0    failed=0   
host2                      : ok=0    changed=0    unreachable=0    failed=1   
```
##### Actual Results:

Instead, Task 3 from Play 2 is not executed on host1. The message "NO MORE HOSTS LEFT" is displayed.

```
user@h0$ ansible-playbook --version
ansible-playbook 2.1.0
  config file = 
  configured module search path = Default w/o overrides

user@h0$ ansible-playbook two_plays.pb.yaml 

PLAY [Play 1] ******************************************************************

TASK [Task 1] ******************************************************************
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.006471", "end": "2016-02-25 12:08:15.874254", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-02-25 12:08:15.867783", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
changed: [host1]

TASK [Task 2] ******************************************************************
changed: [host1]

RUNNING HANDLER [Handler 1] ****************************************************
changed: [host1]

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
host1                      : ok=3    changed=3    unreachable=0    failed=0   
host2                      : ok=0    changed=0    unreachable=0    failed=1   
```

```
user@h0$ ansible-playbook --version
ansible-playbook 2.1.0
  config file = 
  configured module search path = Default w/o overrides

user@h0$ ansible-playbook -vvv two_plays.pb.yaml 
No config file found; using defaults

PLAYBOOK: two_plays.pb.yaml ****************************************************
2 plays in two_plays.pb.yaml

PLAY [Play 1] ******************************************************************

TASK [Task 1] ******************************************************************
task path: /home/user/playbooks/two_plays.pb.yaml:7
ESTABLISH LOCAL CONNECTION FOR USER: user
host1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.4-181448891920162 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.4-181448891920162 `" )'
ESTABLISH LOCAL CONNECTION FOR USER: user
host2 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.41-67699306413194 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.41-67699306413194 `" )'
host1 PUT /tmp/tmp_1kdGb TO /home/user/.ansible/tmp/ansible-tmp-1456427335.4-181448891920162/command
host1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1456427335.4-181448891920162/command; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1456427335.4-181448891920162/" > /dev/null 2>&1'
host2 PUT /tmp/tmpeUisOu TO /home/user/.ansible/tmp/ansible-tmp-1456427335.41-67699306413194/command
host2 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1456427335.41-67699306413194/command; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1456427335.41-67699306413194/" > /dev/null 2>&1'
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.005199", "end": "2016-02-25 12:08:55.458196", "failed": true, "failed_when_result": true, "invocation": {"module_args": {"_raw_params": "/bin/true", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-02-25 12:08:55.452997", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
NOTIFIED HANDLER Handler 1
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.008875", "end": "2016-02-25 12:08:55.466677", "failed": false, "failed_when_result": false, "invocation": {"module_args": {"_raw_params": "/bin/true", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-02-25 12:08:55.457802", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [Task 2] ******************************************************************
task path: /home/user/playbooks/two_plays.pb.yaml:11
ESTABLISH LOCAL CONNECTION FOR USER: user
host1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.51-149718488385002 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.51-149718488385002 `" )'
host1 PUT /tmp/tmpatPQZV TO /home/user/.ansible/tmp/ansible-tmp-1456427335.51-149718488385002/command
host1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1456427335.51-149718488385002/command; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1456427335.51-149718488385002/" > /dev/null 2>&1'
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.005788", "end": "2016-02-25 12:08:55.568887", "invocation": {"module_args": {"_raw_params": "/bin/true", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-02-25 12:08:55.563099", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [Handler 1] ****************************************************
ESTABLISH LOCAL CONNECTION FOR USER: user
host1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.6-154968896387882 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456427335.6-154968896387882 `" )'
host1 PUT /tmp/tmpoh615S TO /home/user/.ansible/tmp/ansible-tmp-1456427335.6-154968896387882/command
host1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1456427335.6-154968896387882/command; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1456427335.6-154968896387882/" > /dev/null 2>&1'
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.005483", "end": "2016-02-25 12:08:55.646776", "invocation": {"module_args": {"_raw_params": "/bin/true", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-02-25 12:08:55.641293", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
host1                      : ok=3    changed=3    unreachable=0    failed=0   
host2                      : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by rohitkothari** [comment]
We were also facing the same issue using one of our playbooks. Therefore I tried to re-create the issue from above steps using the Steps to reproduce, and was able to re-create with Ansible Version: 2.0.0.2

Ansible Version:

```
user@devhost:~$ ansible --version
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```

Following are the results of running my original (not the above sample) playbook:

Expected Results:

```
PLAY [Play 1] ******************************************************************

TASK [Include Vars] ************************************************************
ok: [localhost]

TASK [assert] ******************************************************************
ok: [localhost]

PLAY [Play 2] ******************************************************************

TASK [Task 1 in Play 2] ********************************************************
ok: [host1]
ok: [host2]

TASK [Task 2 in Play 2] ********************************************************
ok: [host1]
ok: [host2]

TASK [Task 3 in Play 2] ********************************************************
ok: [host1]
fatal: [host2]: FAILED! => {"changed": false, "failed": true, "msg": "Error"}

TASK [Task 4 in Play 2] ********************************************************
skipping: [host1]

TASK [Task 5 in Play 2] ********************************************************
changed: [host1]

TASK [Task 6 in Play 2] ********************************************************
ok: [host1]

PLAY [Play 3] ******************************************************************

TASK [Task 1 in Play 3] ********************************************************
ok: [host1]


PLAY RECAP *********************************************************************
host2                      : ok=7    changed=0    unreachable=0    failed=1   
host1                      : ok=17   changed=3    unreachable=0    failed=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0 
```

However, following is the stdout of my playbook execution -

Actual Results:

```

PLAY [Play 1] ******************************************************************

TASK [Include Vars] ************************************************************
ok: [localhost]

TASK [assert] ******************************************************************
ok: [localhost]

PLAY [Play 2] ******************************************************************

TASK [Task 1 in Play 2] ********************************************************
ok: [host1]
ok: [host2]

TASK [Task 2 in Play 2] ********************************************************
ok: [host1]
ok: [host2]

TASK [Task 3 in Play 2] ********************************************************
ok: [host1]
fatal: [host2]: FAILED! => {"changed": false, "failed": true, "msg": "Error"}

TASK [Task 4 in Play 2] ********************************************************
skipping: [host1]

TASK [Task 5 in Play 2] ********************************************************
changed: [host1]

TASK [Task 6 in Play 2] ********************************************************
ok: [host1]

PLAY RECAP *********************************************************************
host2                      : ok=7    changed=0    unreachable=0    failed=1   
host1                      : ok=16   changed=2    unreachable=0    failed=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

Note that I had many plays and tasks in my original output, but I have shortened the output by removing few tasks for demo purpose here.

The purpose of this comment is to acknowledge that we are also observing the same behavior mentioned in above comment - If a task in a play fails for a host, subsequent tasks in the same play are executed on other hosts, but tasks in subsequent plays are NOT executed for any host at all. Also, I do not even get any message regarding subsequent plays (like "NO MORE HOSTS LEFT" in above comment). Looking at the output, it almost feels as if no subsequent play existed.

**Comment by ssawtell** [comment]
I just upgraded from 1.9.4 to 2.0.1.0 and I am seeing the same problem with one of my playbooks. The same playbook worked under 1.9.4, so the issue seems to be related to whatever changes were made in 2.x.

I have three plays in the playbook, each with multiple tasks. For me, the most likely failure will be in the first or second task in the second play. The second play will continue as expected, running subsequent tasks in the play on those hosts which have not experienced a failure. However, a failure of any host in the second play will cause the third play to not run at all, and I'll get the "NO MORE HOSTS LEFT *****..." message instead of the third play.

It seems like the list of successful hosts is passed from task to task within a play, but is not correctly passed to subsequent plays in the playbook when even a single host had a failure.

**Comment by jimi-c** [comment]
I believe this may be a duplicate of https://github.com/ansible/ansible/pull/13750.

**Comment by hkariti** [comment]
this is linked to https://github.com/ansible/ansible/issues/15395
if one host fails, then the subsequent plays will not run, UNLESS one other host is unreachable, then https://github.com/ansible/ansible/issues/15395 's case will happen - the subsequent play will run and will include the failed host.

**Comment by hkariti** [comment]
this still exists in 2.1-rc2. this (and #15395) are major bugs imho, they make ansible unusable for playbooks with >1 plays.

**Comment by jeremypruitt** [comment]
+1 this is a brutal bug for folks targeting multiple hosts using multiple plays. I check every one of these bugs every single day hoping for a light at the end of the tunnel :) I'd be willing to help but not sure where to start with this one.

**Comment by ktosiek** [comment]
@jeremypruitt I think this is a duplicate of the bug I'm fixing in #13750, so the only thing left is nagging the developers until they fix it. If by any chance you find a less buggy CM system give me a heads up :-)

**Comment by jeremypruitt** [comment]
@ktosiek Ya I saw that. I think I am subscribed to 3 issues related to this (including this one).

**Comment by jimi-c** [comment]
@stacywsmith I believe the feature branch based on @vroy's work here addresses this problem:
https://github.com/ansible/ansible/compare/vroy_backward-compatible-executor

Using this feature branch, I get the following output using your example playbook:

<pre>
[root@jimi 14665]# ansible-playbook -vv test.yml -i inv
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: test.yml *************************************************************
2 plays in test.yml
PLAY [Play 1] ******************************************************************
TASK [Task 1] ******************************************************************
task path: /root/testing/14665/test.yml:6
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.005962", "end": "2016-05-17 15:40:35.797809", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-05-17 15:40:35.791847", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
NOTIFIED HANDLER Handler 1
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.003483", "end": "2016-05-17 15:40:35.797914", "failed": false, "failed_when_result": false, "rc": 0, "start": "2016-05-17 15:40:35.794431", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
TASK [Task 2] ******************************************************************
task path: /root/testing/14665/test.yml:10
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.002739", "end": "2016-05-17 15:40:35.970314", "rc": 0, "start": "2016-05-17 15:40:35.967575", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
RUNNING HANDLER [Handler 1] ****************************************************
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.003456", "end": "2016-05-17 15:40:36.097160", "rc": 0, "start": "2016-05-17 15:40:36.093704", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
NO MORE HOSTS LEFT *************************************************************
PLAY [Play 2] ******************************************************************
TASK [Task 3] ******************************************************************
task path: /root/testing/14665/test.yml:21
changed: [host1] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.002879", "end": "2016-05-17 15:40:36.235461", "rc": 0, "start": "2016-05-17 15:40:36.232582", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
NO MORE HOSTS LEFT *************************************************************
PLAY RECAP *********************************************************************
host1                      : ok=4    changed=4    unreachable=0    failed=0   
host2                      : ok=0    changed=0    unreachable=0    failed=1   
</pre>

This appears to match the output of 1.9.x. If you could please confirm this, I'll close this issue when I merge that branch in.

**Comment by sherbang** [comment]
Using the vroy_backward-compatible-executor branch, still fails if Play 2 doesn't include the failing host.

two_plays.pb.yaml:

```
- name: Play 1
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Task 1
      command: /bin/true
      failed_when: "'host2' in inventory_hostname"
      notify: Handler 1
    - name: Task 2
      command: /bin/true
  handlers:
    - name: Handler 1
      command: /bin/true

- name: Play 2
  hosts: [play2]
  connection: local
  gather_facts: no
  tasks:
    - name: Task 3
      command: /bin/true
```

two_plays.hosts:

```
host2

[play2]
host1
```

Result:

```
$ ansible-playbook -i two_plays.hosts two_plays.pb.yml 

PLAY [Play 1] ******************************************************************

TASK [Task 1] ******************************************************************
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.000865", "end": "2016-05-25 14:57:32.512081", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-05-25 14:57:32.511216", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
changed: [host1]

TASK [Task 2] ******************************************************************
changed: [host1]

RUNNING HANDLER [Handler 1] ****************************************************
changed: [host1]

NO MORE HOSTS LEFT *************************************************************

PLAY [Play 2] ******************************************************************
ERROR! invalid host (host2) specified for playbook iteration
```

**Comment by hkariti** [comment]
can confirm this on 2.1 :\

**Comment by ayush-sharma** [comment]
I can confirm this on 2.1. When is this issue getting resolved? Kind of destroys the whole concept of rolling upgrades.

**Comment by jimi-c** [comment]
@sherbang / @hkariti that issue has been addressed in fa368934bd26600104f72f9d8f0591c0fd68e958 (also cherry-picked to stable-2.1, so it will be included in 2.1.1).

**Comment by jimi-c** [comment]
^ also @ayush-sharma

**Comment by abhivijay89** [comment]
The issue still persists in 2.1.1 rc1. If one of the hosts is unreachable in a particular task, Ansible moves on the next 2-3 plays and then randomly quits. Can you please help to take a look?

Alternatively, is there a way to ignore fatal errors?
Using a combination of "any_errors_fatal' & "max_fail_percentage" options doesn't seem to work either. 

Tried: https://github.com/ansible/ansible/compare/vroy_backward-compatible-executor too, but no, luck. Any other alternatives?

**Comment by dekimsey** [comment]
2.1.1.0-RC1 does not appear to have addressed this issue. Is there any kind of debugging information that might be helpful?

**Comment by dekimsey** [comment]
[Attached gist](https://gist.github.com/dekimsey/d1f6630df899797256cb989610b4c0a3) is a small test case of two error cases I've identified related to play execution.

In short, a group consisting of only failed hosts causes the run to abort at the given play. Interestingly, when any failures occur, all subsequent plays (successful or not) begin to emit the "NO MORE HOSTS LEFT" message at the end of their plays. This suggests an uncleared state between plays.

### no-hosts-remaining.yml

After a failure, all subsequent plays now have a "NO MORE HOSTS LEFT" message emitted.

```
[dkimsey]$ ansible-playbook -i hosts no-hosts-remaining.yml

PLAY [Play 0 (all is good)] ****************************************************

TASK [Task 1 -- Runs OK] *******************************************************
changed: [host2]
changed: [host1]

PLAY [Play 1 (all, creates some failures)] *************************************

TASK [Task 1 -- Creates Failure OK] ********************************************
changed: [host1]
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["date"], "delta": "0:00:00.002360", "end": "2016-06-20 17:02:11.796482", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-06-20 17:02:11.794122", "stderr": "", "stdout": "Mon Jun 20 17:02:11 CDT 2016", "stdout_lines": ["Mon Jun 20 17:02:11 CDT 2016"], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY [Play 2 (all, spams NO HOSTS LEFT)] ***************************************

TASK [command] *****************************************************************
changed: [host1]

NO MORE HOSTS LEFT *************************************************************

PLAY [Play 3a (group with only failures)] **************************************

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'no-hosts-remaining.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
host1                      : ok=3    changed=3    unreachable=0    failed=0
host2                      : ok=1    changed=1    unreachable=0    failed=1

```

### failed-equals-batch-kills-playbook.yml

In this example, if there is a play that targets only failed hosts (Play 2) then the whole run aborts. Play 3 never gets executed.

```
[dkimsey]$ ansible-playbook -i hosts failed-equals-batch-kills-playbook.yml

PLAY [Play 0 (all is good)] ****************************************************

TASK [Task 1 -- Runs OK] *******************************************************
changed: [host2]
changed: [host1]

PLAY [Play 1 (all, creates some failures)] *************************************

TASK [Task 1 -- Creates Failure OK] ********************************************
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["date"], "delta": "0:00:00.002749", "end": "2016-06-20 17:00:53.765133", "failed": true, "failed_when_result": true, "rc": 0, "start": "2016-06-20 17:00:53.762384", "stderr": "", "stdout": "Mon Jun 20 17:00:53 CDT 2016", "stdout_lines": ["Mon Jun 20 17:00:53 CDT 2016"], "warnings": []}
changed: [host1]

NO MORE HOSTS LEFT *************************************************************

PLAY [Play 2 (group with only failures)] ***************************************

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'failed-equals-batch-kills-playbook.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
host1                      : ok=2    changed=2    unreachable=0    failed=0
host2                      : ok=1    changed=1    unreachable=0    failed=1
```

**Comment by bmalynovytch** [comment]
Hi,
I can confirm what @stacywsmith reported, adding one more information: in my case, the second play was related to different hosts, but I obtain the same `ERROR: invalid host (xxxxxxx) specified for playbook iteration`, even though the failed host IS NOT in the group concerned by the second play.

**Comment by dekimsey** [comment]
@bmalynovytch Have you tested with v2.1.1.0-RC1? That version fixes the error you are describing on my box.

**Comment by jimi-c** [comment]
I believe this is the same issue as reported in #16364, for which a fix was merged in to devel/stable-2.1.

Testing @dekimsey's examples above, I see play 3 work properly now:

```
PLAY [Play 3 (all, NEVER GETS RUN)] ********************************************

TASK [Task 3] ******************************************************************
task path: /root/testing/14665/dekimsey/test.yml:38
changed: [host1] => {"changed": true, "cmd": ["date"], "delta": "0:00:00.002916", "end": "2016-06-22 09:31:38.101369", "rc": 0, "start": "2016-06-22 09:31:38.098453", "stderr": "", "stdout": "Wed Jun 22 09:31:38 CDT 2016", "stdout_lines": ["Wed Jun 22 09:31:38 CDT 2016"], "warnings": []}
```

I see the "NO HOSTS LEFT" message is still printed, which is a minor annoyance and for which we're holding https://github.com/ansible/ansible/pull/13750 open.

Based on the above however, we're going to go ahead and close this now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bmalynovytch** [comment]
Currently testing `stable-2.1` branch freshly pulled.
I'll update the issue if I can confirm the bug is gone (I shouldn't have hosts unreachable, so the bug shouldn't trigger)

**Comment by dekimsey** [comment]
Confirmed, the change fixes the issues we were having.

**Comment by bmalynovytch** [comment]
I can't confirm as the `stable-2.1` seems to have introduced another bug which make my playbook completely unusable (module get_url).
Trying to investigate.

**Comment by jimi-c** [comment]
@bmalynovytch if so, please open a separate issue for that.

**Comment by memelet** [comment]
So what was the fix? I see this exact problem with 2.1.

**Comment by jimi-c** [comment]
@memelet the fix was mentioned in https://github.com/ansible/ansible/issues/16364, and will be included in 2.1.1 (please go test rc3!).

**Comment by smcracraft** [comment]
Hi, I have version 2.1.0.0.

It is getting a "NO MORE HOSTS" when running the site master with ansible-playbook.

In the actual playbook area of the site master iml, it calls out a host with a fully qualified name
for which there is no problem it all. It says

ERROR! invalid host (fully.qualified.host.name) specified for playbook iteration

and then stops operation of the site master entirely long before it is normally done.
Earlier in the run it gets a

  fatal: [fully.qualified.host.name]: FAILED! => {"changed": false, "failed": true, "msg": failed to lock apt for exclusive operation"}

and yes I do have become: true and become_user:root and not sudo: true

If this requires an Ansible upgrade, please list the least impactful commands to the server
for the upgrade.

Or anything else you might think of.

Thanks, A Fellow Ansible User

**Comment by smcracraft** [comment]
I resolved this by upgrading to Ansible 2.1.1 with minimal changes with:

ansible --version
ansible-playbook --version
apt-get install software-properties-common
apt-add-repository ppa:ansible/ansible
(apt-get update)   <= left this out on purpose
 apt-get install ansible
 ansible --version
 ansible-playbook --version

**Comment by goldyfruit** [comment]
Hi guys,

I'm still having this issue.

```
root@uoi-installer:~# ansible-playbook --version
ansible-playbook 2.1.1.0
  config file = /root/ansible.cfg
  configured module search path = Default w/o overrides
```

```
root@uoi-installer:~# ansible --version
ansible 2.1.1.0
  config file = /root/ansible.cfg
  configured module search path = Default w/o overrides
```

```
TASK [ansible-nova : Installing packages needed by Nova] ***********************
ok: [cmpt02.uoi.io] => (item=[u'gcc', u'git', u'libffi-devel', u'libxslt-devel', u'python-devel', u'python-greenlet-devel', u'python-ldap', u'python-lxml', u'python-pip', u'python-setuptools', u'python-virtualenv', u'openldap-devel', u'openssl-devel', u'sqlite-devel', u'postgresql-devel', u'MariaDB-devel'])
ok: [cmpt03.uoi.io] => (item=[u'gcc', u'git', u'libffi-devel', u'libxslt-devel', u'python-devel', u'python-greenlet-devel', u'python-ldap', u'python-lxml', u'python-pip', u'python-setuptools', u'python-virtualenv', u'openldap-devel', u'openssl-devel', u'sqlite-devel', u'postgresql-devel', u'MariaDB-devel'])
ok: [cmpt01.uoi.io] => (item=[u'gcc', u'git', u'libffi-devel', u'libxslt-devel', u'python-devel', u'python-greenlet-devel', u'python-ldap', u'python-lxml', u'python-pip', u'python-setuptools', u'python-virtualenv', u'openldap-devel', u'openssl-devel', u'sqlite-devel', u'postgresql-devel', u'MariaDB-devel'])

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/srv/data/ansible/playbooks/uoi001/main.retry

PLAY RECAP *********************************************************************
ceph01.uoi.io              : ok=6    changed=0    unreachable=0    failed=0   
ceph02.uoi.io              : ok=6    changed=0    unreachable=0    failed=0   
ceph03.uoi.io              : ok=6    changed=0    unreachable=0    failed=0   
cmpt01.uoi.io              : ok=20   changed=0    unreachable=0    failed=1   
cmpt02.uoi.io              : ok=20   changed=0    unreachable=0    failed=1   
cmpt03.uoi.io              : ok=20   changed=0    unreachable=0    failed=1   
ctrl01.uoi.io              : ok=7    changed=0    unreachable=0    failed=0   
ctrl02.uoi.io              : ok=7    changed=0    unreachable=0    failed=0   
ctrl03.uoi.io              : ok=7    changed=0    unreachable=0    failed=0  
```

**Comment by ktosiek** [comment]
To anyone reporting it's still an issue: the Ansible team doesn't look at closed issues too often.
If you can reproduce the problem on current or development version, report it as a separate issue.
