### ISSUE TITLE
test_template test failing

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#14893]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 923548f6d5) last updated 2016/03/10 17:09:41 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD c86a0ef84a) last updated 2016/03/10 17:10:12 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 33a557cc59) last updated 2016/03/10 17:10:12 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

test_template tests no longer work because `dest` is no longer included in `template` output.

I tracked this down to a particular commit 80b10bd using git bisect, but `git log -p 80b10bd` suggests it shouldn't actually be responsible (but running it with the commit before does work) 
##### Steps To Reproduce:

```
cd test/inventory;  ansible-playbook non_destructive.yml --tags test_template -i inventory -e @integration_config.yml -vv -f1 -b --ask-become-pass
```
##### Expected Results:

```
TASK [test_template : fill in a basic template] ********************************
task path: /home/wthames/src/ansible/test/integration/roles/test_template/tasks/main.yml:19
changed: [testhost] => {"changed": true, "checksum": "2ae9ab1816acdbb8a4a47835236fb8badff8a32a", "dest": "/root/ansible_testing/foo.templated", "gid": 0, "group": "root", "md5sum": "3166c58a15412a6d6fe73740cb7af0b1", "mode": "0644", "owner": "root", "secontext": "system_u:object_r:admin_home_t:s0", "size": 136, "src": "/home/wthames/.ansible/tmp/ansible-tmp-1457591738.44-62175960242880/source", "state": "file", "uid": 0}

TASK [test_template : assert] **************************************************
task path: /home/wthames/src/ansible/test/integration/roles/test_template/tasks/main.yml:23
ok: [testhost] => {"changed": false, "msg": "all assertions passed"}

```
##### Actual Results:

```
TASK [test_template : fill in a basic template] ********************************
task path: /home/wthames/src/ansible/test/integration/roles/test_template/tasks/main.yml:19
ok: [testhost] => {"changed": false, "diff": {"after": {"path": "/root/ansible_testing/foo.templated"}, "before": {"path": "/root/ansible_testing/foo.templated"}}, "failed": false, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/root/ansible_testing/foo.templated", "secontext": "system_u:object_r:admin_home_t:s0", "size": 136, "state": "file", "uid": 0}

TASK [test_template : assert] **************************************************
task path: /home/wthames/src/ansible/test/integration/roles/test_template/tasks/main.yml:23
fatal: [testhost]: FAILED! => {"assertion": "'dest' in template_result", "changed": false, "evaluated_to": false, "failed": true}

```

**Comment by willthames** [comment]
I'm not sure whether the bug is that `template` no longer outputs `dest` or that `test_template` needs to be updated to reflect that it should use `path` rather than `dest`. I'd love to see the actual commit behind the code change that changes this behaviour.

**Comment by bcoca** [comment]
fixed via 1c1f5e9f990f0fbddd063777860c9fe693ab0ecf

**Comment by willthames** [comment]
@bcoca this is not fixed. The test_template role still fails.
