### ISSUE TITLE
remote_tmp filling up since upgrading to ansible 2

### ISSUE THREAD

**Issue by starkers** [ansible/ansible#14917]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2 (ubuntu 14.04 : *ppa:ansible/ansible*)
```
##### Ansible Configuration:

```
[defaults]
host_key_checking = False
fact_caching   = memory
gathering      = smart
remote_user    = root
hostfile       = /etc/ansible/hosts
library        = /usr/share/ansible
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 5
poll_interval  = 15
transport      = smart
remote_port    = 22
nocows         = 1
log_path       = /var/log/ansible.log
roles_path     = /etc/ansible/roles
ansible_managed = Ansible managed: {file} @ %Y-%m-%d %H:%M:%S (%Z)
retry_files_enabled = False
no_log = True
no_target_syslog = True
[ssh_connection]
pipelining      = True
ssh_args        = -o ForwardAgent=yes
```
##### Environment:

Ubuntu LTS (trusty)
##### Summary:

I have many servers which run ansible (like ansible-pull ) on themselves. (they often don't even have internet). Anyway they run ansible from cron at regular times.

Today I was alerted when to the disk usage on my dev servers (dev run ansible on localhost much more frequently than production).

There was over 8Gb of disk being used under _$HOME/.ansible/tmp_

A quick examination of dpkg logs and the timestamps (on 3 hosts) confirms that this started immediately after leaving ansible 1.9
##### Steps To Reproduce:

I just run ansible and it drops lots of files. I'm afraid that its a massive codebase but I'll try to isolate if its a specific module when I find time.

```
root hostname ~/.ansible/tmp # ls -ld *| wc -l
28877
root hostname ~/.ansible/tmp # du -sh ./
334M  ./
root hostname ~/.ansible/tmp # ls -ltr | head
total 0
drwxr-xr-x 2 root root 20 Jan  7 16:35 ansible-tmp-1452184545.57-4067534433910
drwxr-xr-x 2 root root 29 Jan 14 14:34 ansible-tmp-1452782097.64-275060088292169
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559507.68-75405176251432
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559510.74-196306534308392
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559511.03-274782368435943
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559511.35-176576225059611
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559511.49-191884790350210
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559511.58-19466108554057
drwxr-xr-x 2 root root  6 Feb 15 18:05 ansible-tmp-1455559511.63-28439722806966
root hostname ~/.ansible/tmp # grep ansible /var/log/dpkg.log* | sort -n
/var/log/dpkg.log.1:2016-02-15 17:17:44 status half-configured ansible:all 1.9.4-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:44 status half-installed ansible:all 1.9.4-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:44 status unpacked ansible:all 1.9.4-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:44 upgrade ansible:all 1.9.4-1ppa~trusty 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:45 status half-installed ansible:all 1.9.4-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:45 status unpacked ansible:all 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:45 status unpacked ansible:all 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:55 conffile /etc/ansible/ansible.cfg keep
/var/log/dpkg.log.1:2016-02-15 17:17:55 conffile /etc/ansible/hosts keep
/var/log/dpkg.log.1:2016-02-15 17:17:55 configure ansible:all 2.0.0.2-1ppa~trusty <none>
/var/log/dpkg.log.1:2016-02-15 17:17:55 status half-configured ansible:all 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:55 status installed ansible:all 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:55 status unpacked ansible:all 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:55 status unpacked ansible:all 2.0.0.2-1ppa~trusty
/var/log/dpkg.log.1:2016-02-15 17:17:55 status unpacked ansible:all 2.0.0.2-1ppa~trusty

```

**Comment by starkers** [comment]
I can confirm that **template** doesn't remove the tmp directory (but it does at least remove the tmp file).. still I'd like to avoid having this many empty directories left over.

There are other modules that I will test which are leaving directories with files (even with changed=0)

```
root hostname /var/lib/ansible/baseos devel # cat hosts
[pull_mode_hosts]
localhost

[pull_mode_hosts:vars]
ansible_connection=local
root hostname /var/lib/ansible/baseos devel # cat test
just a test file
root hostname /var/lib/ansible/baseos devel # cat test.yml
---
- hosts: pull_mode_hosts
  no_log: False
  gather_facts: False
  tasks:
    - name: template an example file
      template:
        src: test
        dest: /tmp/test
        owner: root
        group: root

root hostname /var/lib/ansible/baseos devel # rm -rf ~/.ansible/tmp /tmp/test
root hostname /var/lib/ansible/baseos devel # ansible-playbook test.yml -vvv
Using /var/lib/ansible/baseos/ansible.cfg as config file
1 plays in test.yml

PLAY ***************************************************************************

TASK [template an example file] ************************************************
task path: /var/lib/ansible/baseos/test.yml:6
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935 )"
localhost EXEC rc=flag; [ -r /tmp/test ] || rc=2; [ -f /tmp/test ] || rc=1; [ -d /tmp/test ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc}  "/tmp/test && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();
afile = open("'/tmp/test'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
  hasher.update(buf)
  buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();
afile = open("'/tmp/test'", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
  hasher.update(buf)
  buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/tmp/test)
localhost PUT /tmp/tmptnmrIg TO /root/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935/source
localhost EXEC mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1457694473.98-159452289105954 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1457694473.98-159452289105954 )"
localhost PUT /tmp/tmpbhG_Lk TO /root/.ansible/tmp/ansible-tmp-1457694473.98-159452289105954/copy
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1457694473.98-159452289105954/copy; rm -rf "/root/.ansible/tmp/ansible-tmp-1457694473.98-159452289105954/" > /dev/null 2>&1
changed: [localhost] => {"changed": true, "checksum": "f654010dde7d49d1c3972abe747d97bc5eb23d75", "dest": "/tmp/test", "gid": 0, "group": "root", "invocation": {"module_args": {"_ansible_no_log": true, "backup": false, "content": null, "delimiter": null, "dest": "/tmp/test", "directory_mode": null, "follow": true, "force": true, "group": "root", "mode": null, "original_basename": "test", "owner": "root", "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/root/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935/source", "validate": null}}, "md5sum": "dba53da8e6443fd17d45403b3d5812d4", "mode": "0644", "owner": "root", "size": 17, "src": "/root/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935/source", "state": "file", "uid": 0}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

root hostname /var/lib/ansible/baseos devel # find ~/.ansible/tmp
/root/.ansible/tmp
/root/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935
root hostname /var/lib/ansible/baseos devel # find ~/.ansible/tmp -type d
/root/.ansible/tmp
/root/.ansible/tmp/ansible-tmp-1457694473.97-128656913368935
root hostname /var/lib/ansible/baseos devel # find ~/.ansible/tmp -type f
```

**Comment by jhawkesworth** [comment]
The problem with template leaving behind empty directories has been fixed in latest devel: https://github.com/ansible/ansible/issues/14867 by commit: https://github.com/ansible/ansible/commit/5cbdaff9fddc6a4bd4042edc6edfe1619514bc10

**Comment by starkers** [comment]
Ahh good to know thanks!
I'll try to isolate whats leaving the files next

**Comment by jhawkesworth** [comment]
The culprit was the template action plugin in that case.
I ran some of the windows integration tests and found a tmp dir was getting
left behind this morning but not yet had a chance to investigate which task
was leaving the dir behind.

**Comment by starkers** [comment]
..just freed up around 100-300Gb of ansible temp files across my work places infrastructure lol

**Comment by jhawkesworth** [comment]
nice.  worth fixing then.

So I'm running the test_win_template integration tests which leave 1 dir behind.

It looks as though the copy action plugin creates a temp dir, then copies the payload into that dir with the name 'source', then it creates another tmp dir and copies the win_copy.ps1 module over to the second temp dir.  Then it runs the win_copy.ps1 and clears up the second tmp dir, and removes the file called 'source', but doesn't delete the dir that 'source' was in.

I suspect the copy task would be behaving in the same way as they both share the same action plugin code.  

Seeing if I can identify what needs to change now.

**Comment by bcoca** [comment]
cc @jimi-c

**Comment by jimi-c** [comment]
We pushed a fix for this yesterday, if anyone would like to confirm it?

**Comment by jimi-c** [comment]
Note, this was to devel, not merged over to stable-2.0 yet.

**Comment by starkers** [comment]
I'm running a devel run now, a few bad actors, will hone in on some now

**Comment by starkers** [comment]
ok.. so I'm on devel:

```
ansible 2.1.0 (devel 286d91d722) last updated 2016/03/11 18:08:24 (GMT +000)
  lib/ansible/modules/core: (detached HEAD c86a0ef84a) last updated 2016/03/11 18:10:05 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 33a557cc59) last updated 2016/03/11 18:10:09 (GMT +000)
  config file = /var/lib/ansible/baseos/ansible.cfg
  configured module search path = /usr/share/ansible
```

I've removed the tmp directory, run ansible with **-vvv** and searched the output to locate the modules of anything left over.

Left over we have two directories, one with a file.

```
find ~/.ansible/tmp
/root/.ansible/tmp
/root/.ansible/tmp/ansible-tmp-1457720052.08-101278404570984
/root/.ansible/tmp/ansible-tmp-1457720059.96-277606065265578
/root/.ansible/tmp/ansible-tmp-1457720059.96-277606065265578/source
```

The first one (empty dir) was **copy**

```
- name: write pdagent GPG signature out
  copy: src=apt_repo_pdagent.gpg
    dest=/tmp/uvB9mp8Y7xe3h
  changed_when: false
```

```
# grep /root/.ansible/tmp/ansible-tmp-1457720052.08-101278404570984 /tmp/output
localhost PUT /etc/ansible/roles/pdagent/files/apt_repo_pdagent.gpg TO /root/.ansible/tmp/ansible-tmp-1457720052.08-101278404570984/source
ok: [localhost] =>
{
  "uid": 0,
  "state": "file",
  "src": "/root/.ansible/tmp/ansible-tmp-1457720052.08-101278404570984/source",
  "size": 6128,
  "owner": "root",
  "changed": false,
  "checksum": "e598f31e5e1a37be2516732afe250ac577e81693",
  "dest": "/tmp/uvB9mp8Y7xe3h",
  "gid": 0,
  "group": "root",
  "invocation": {
    "module_args": {
      "validate": null,
      "src": "/root/.ansible/tmp/ansible-tmp-1457720052.08-101278404570984/source",
      "seuser": null,
      "group": null,
      "force": true,
      "follow": false,
      "directory_mode": null,
      "dest": "/tmp/uvB9mp8Y7xe3h",
      "delimiter": null,
      "content": null,
      "backup": false,
      "mode": null,
      "original_basename": "apt_repo_pdagent.gpg",
      "owner": null,
      "regexp": null,
      "remote_src": null,
      "selevel": null,
      "serole": null,
      "setype": null
    }
  },
  "md5sum": "c2555e3f7c242acbfc9a8bda6de0df95",
  "mode": "0644"
}

```

The second one is **unarchive**
(just some .vimrc/.aliases etc)

Task:

```
- name: upgrade roots experience
  unarchive:
    src:  root_home.tar.bz2
    dest: /root/
    owner: root
    group: root
```

I'm not going to paste the full output with stdout as its large..
Seems to complain about every Uid and Gid (which it always does anyway)

```
ok: [localhost] =>
{
  "uid": 0,
  "state": "directory",
  "src": "/root/.ansible/tmp/ansible-tmp-1457720059.96-277606065265578/source",
  "size": 4096,
  "owner": "root",
  "changed": false,
  "check_results": {
    "unarchived": true,
    "rc": 1,
    "out": "./.foobar: Uid differs\n",
    "err": "",
    "cmd": "/bin/tar -C \"/root/\" --diff -f \"/root/.ansible/tmp/ansible-tmp-1457720059.96-277606065265578/source\""
  },
  "dest": "/root/",
  "gid": 0,
  "group": "root",
  "handler": "TarArchive",
  "invocation": {
    "module_args": {
      "src": "/root/.ansible/tmp/ansible-tmp-1457720059.96-277606065265578/source",
      "seuser": null,
      "setype": null,
      "serole": null,
      "selevel": null,
      "follow": false,
      "directory_mode": null,
      "dest": "/root/",
      "delimiter": null,
      "creates": null,
      "copy": true,
      "content": null,
      "backup": null,
      "force": null,
      "group": "root",
      "list_files": false,
      "mode": null,
      "original_basename": "root_home.tar.bz2",
      "owner": "root",
      "regexp": null,
      "remote_src": null
    }
  },
  "mode": "0750"
}
```

just do be sure checked the source file md5sum also

```
md5sum ./ansible-tmp-1457720059.96-277606065265578/source /etc/ansible/roles/core/files/root_home.tar.bz2 
86c03cc3cc11119b31a6f9f37a8770b0  ./ansible-tmp-1457720059.96-277606065265578/source
86c03cc3cc11119b31a6f9f37a8770b0  /etc/ansible/roles/core/files/root_home.tar.bz2
```

HTH

**Comment by jimi-c** [comment]
Thanks @starkers, the ones we fixed yesterday were template and assemble, so apparently the two above also suffer from the same problem. We'll get those fixed as well.

**Comment by kozchris** [comment]
Unarchive is still leaving files in the tmp directory.
This was closed as a dup as part of this thread but I still see the issue: https://github.com/ansible/ansible/issues/14078
I'm using Ansible 2.1.0

**Comment by jimi-c** [comment]
@kozchris please open a new issue for this.

**Comment by kozchris** [comment]
New issue created.

https://github.com/ansible/ansible-modules-core/issues/4648

**Comment by fvalt** [comment]
Hello,
I am using ansible 2.1.2.0, and when using the copy module with remote_src: True , the copy file created in the $HOME/.ansible/tmp on the remote host is not cleaned up, is this a normal behaviour ?
I also have the $HOME/.ansible_async directory that is not removed on the remote host, when running the shell module with the async option.

Regards
