### ISSUE TITLE
ESTABLISH SSH CONNECTION FOR USER: None

### ISSUE THREAD

**Issue by Delivion-GmbH** [ansible/ansible#14955]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.1.0
##### Ansible Configuration:

[defaults]
remote_tmp = /tmp
ssh_args = -v
host_key_checking = False
callback_plugins = plugins
callback_whitelist = profile_tasks

[ssh_connection]
control_path=%(directory)s/a%%h-%%p-%%r
ssh_args = -o StrictHostKeyChecking=no
##### Environment:

CentOS-7.2.3
##### Summary:

Want to push a configfile with delegate_to as another user.
##### Steps To Reproduce:

Try any playbook that has a task that uses "delegate_to"

[https://gist.github.com/DevOPS-Delivion/299475e316f17e3d8eeb](https://gist.github.com/DevOPS-Delivion/299475e316f17e3d8eeb)
##### Expected Results:

ESTABLISH SSH CONNECTION FOR USER: bareos
##### Actual Results:

ESTABLISH SSH CONNECTION FOR USER: none

Additional Information:

I already found related bug reports here:

[https://github.com/ansible/ansible/issues/12127](https://github.com/ansible/ansible/issues/12127)

and here:

[https://github.com/ansible/ansible/commit/1f5584aa5b9d1142e67fed209bbeea1ca99fc307](https://github.com/ansible/ansible/commit/1f5584aa5b9d1142e67fed209bbeea1ca99fc307)

We updated our ansible to 2.0.1.0 and its still not working since it should be fixed?

**Comment by jimi-c** [comment]
High @DevOPS-Delivion, can you also included some details about your inventory?

**Comment by bcoca** [comment]
this might already have been fixed by #15024, please test and confirm

**Comment by bcoca** [comment]
closing via merged #15024

**Comment by CogumelosMaravilha** [comment]
Using ansible 2.2.0.0. Still have the same problem.
 ansible -s -vvv -m command -a 'fdisk -l' cassandra01.olaeu.prv
Using /etc/ansible/ansible.cfg as config file
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/commands/command.py
<cassandra01.olaeu.prv> ESTABLISH SSH CONNECTION FOR USER: None
<cassandra01.olaeu.prv> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/jonas/.ansible/cp/ansible-ssh-%h-%p-%r cassandra01.olaeu.prv '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763 `" && echo ansible-tmp-1484252393.06-239945704109763="` echo $HOME/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763 `" ) && sleep 0'"'"''
<cassandra01.olaeu.prv> PUT /tmp/tmpMfzEYB TO /home/joaos/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763/command.py
<cassandra01.olaeu.prv> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/jonas/.ansible/cp/ansible-ssh-%h-%p-%r '[cassandra01.olaeu.prv]'
<cassandra01.olaeu.prv> ESTABLISH SSH CONNECTION FOR USER: None
<cassandra01.olaeu.prv> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/jonas/.ansible/cp/ansible-ssh-%h-%p-%r cassandra01.olaeu.prv '/bin/sh -c '"'"'chmod u+x /home/joaos/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763/ /home/joaos/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763/command.py && sleep 0'"'"''
<cassandra01.olaeu.prv> ESTABLISH SSH CONNECTION FOR USER: None
<cassandra01.olaeu.prv> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/jonas/.ansible/cp/ansible-ssh-%h-%p-%r -tt cassandra01.olaeu.prv '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ndrickwaivousoszkllrbfemgqryrsmn; /usr/bin/python /home/joaos/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763/command.py; rm -rf "/home/joaos/.ansible/tmp/ansible-tmp-1484252393.06-239945704109763/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
cassandra01.olaeu.prv | FAILED | rc=0 >>
MODULE FAILURE

**Comment by CogumelosMaravilha** [comment]
Solved:
 ansible all -s --ask-sudo-pass -m raw -a "fdisk -l"
