### ISSUE TITLE
setfacl is not available on OpenBSD

### ISSUE THREAD

**Issue by frenkel** [ansible/ansible#16758]
##### ISSUE TYPE
- Bug Report
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/frank/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

OpenBSD.
##### SUMMARY

OpenBSD doesn't have the setfacl command, so calls in plugins/shell/**init**.py fail.
##### RESOLUTION

I'm willing to make a pull request for this, but what would be the best way to work around this? Is it easy to detect the OS in the plugin and run chown instead?

**Comment by jctanner** [comment]
@frenkel are you saying that the acl module does not work on openbsd? Just need some clarification.

**Comment by abadger** [comment]
I believe this was fixed in a later commit.  however, that might be in
2.1.1, not in 2.1.0.  We have 2.1.1rc3 available for testing right now on:
http://releases.ansible.com/ansible/ if you'd like to confirm.

**Comment by frenkel** [comment]
@jctanner Sorry, my report wasn't very clear. I meant that the setfactl command does not exist on OpenBSD.

@abadger I still see the setfacl command in that release, so I guess it won't work.

**Comment by solomongifford** [comment]
setfacl is not always installed on ubuntu 14 either.  (apt-get install acl).

I don't think that this dependency is in the spirit of ansible being able to install any remote dependencies it needs.

You can see that it is still a command in use:

https://github.com/ansible/ansible/search?utf8=%E2%9C%93&q=setfacl

**Comment by abadger** [comment]
@frenkel, @solomongifford please either test with the latest 2.1.0rc, stable-2.1 checkout, devel checkout or let me know of a good test case.  We committed fixes for this and in the limited testing I just did (removing setfacl from a box and running it) things worked as expected.

Note that expected doesn't necessarily mean works.  If you're going from unprivileged user to unprivileged user and you don't have setfacl then you'd have to set the flag that's mentioned in the docs that are pointed to in the error message.  If you aren't getting a good error message then that could be a different bug.  But I'd need to see what output you're getting in your failing run to know that.

**Comment by frenkel** [comment]
Using the 2.1 stable branch it fails with this message indeed:

```
fatal: [example.com]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

Too bad we couldn't just add a workaround for this when OpenBSD is detected (I believe there is no setfacl available, even not from packages).
I'll just enable pipelining in my config then.

**Comment by abadger** [comment]
@frenkel Cool, glad it's doing the right thing there.  And yes, it would be nice if there was a secure way to do that by default on platforms without POSIX acls.  Unfortunately, pipelining breaks on some systems and world-readable-temp-dirs has security implications so we decided users should have to enable it explicitly.

**Comment by solomongifford** [comment]
@abadger  - I tested against an ubuntu 14 box with the stable-2.1 branch and it still failed.

```
ansible testmachine.blackmesh.com -m ping -i 'testmachine.blackmesh.com,' -u unpriviledged_user -k -b --become-method=su --become-user=privileged_user --ask-become-pass
```

Please note that privileged_user above has id=0 but is NOT named root.

```
    "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"
```

**Comment by frenkel** [comment]
@solomongifford The problem cannot be solved in an automated way, that's why there is now a message explaining the issue instead of a crash.

**Comment by solomongifford** [comment]
@frenkel 

My bigger issue is that the acl module is now a hard dependency on remote machines for this type of escalation and ansible will hard fail without the allow_world_readable_tmpfiles=True.   This breaks upgrade paths.

I think allow_world_readable_tmpfiles=True should be the default if not set (even if the default ansible.cfg set its to False) that way upgrades do not bork the process.

**Comment by bcoca** [comment]
This was a hard decision as it does break 'usability' but the other option is to keep allowing insecure file copying. We were aware that not all target machines have or enable ACLs, but that this would still cover a majority of cases transparently. The risk is small, but not something we want to take on users' behalf, so we default to the 'secure way'.

The message informs the user and brings attention to this problem, you can either allow the unsafe path 'consciously' or install acl tools to allow Ansible to operate securely. We felt that this was the best option we had.

To clarify, ACLs are not required for Ansible's operation, they are just used in corner cases 'become into unprivileged user' to share files in a secure manner that is not possible through chmod. 

If you are not using any sensitive data in these cases (or you are fine with the risk) you can enable this setting.
