### ISSUE TITLE
with_fileglob does not handle a `*` to match a directory

### ISSUE THREAD

**Issue by rbauduin** [ansible/ansible#17136]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

with_fileglob
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel bd31cc096a) last updated 2016/08/18 15:46:34 (GMT +200)
  lib/ansible/modules/core: (detached HEAD ff2eae0729) last updated 2016/08/18 15:46:38 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7ba5f340c0) last updated 2016/08/18 15:46:38 (GMT +200)
  config file = /home/rbauduin/gits/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ansible.cfg:

```ini
[default]
forks=20

[ssh_connection]
ssh_args = -F ssh-config 
scp_if_ssh = True
pipelining = False

[privilege_escalation]
become=True

```
##### OS / ENVIRONMENT

Ubuntu 14.04 to Centos 7.2
##### SUMMARY

with_fileglob does not seem to handle a `*` to match a directory in the glob.
I think this worked with a 1.X version of ansible.
##### STEPS TO REPRODUCE

This debug task finds the file located at ./downloaded_files/client/root/.ssh/id_rsa.pub

```yaml
  tasks:
  - name: "locate base dir"
    debug: msg="file is {{item}}"
    with_fileglob:
            - ../downloaded_files/client/root/.ssh/id_rsa.pub
```

This one doesn't:

```yaml
  tasks:
  - name: "locate base dir"
    debug: msg="file is {{item}}"
    with_fileglob:
            - ../downloaded_files/*/root/.ssh/id_rsa.pub
```

But these do:

```yaml
  tasks:
  - name: "locate base dir"
    debug: msg="file is {{item}}"
    with_fileglob:
            - ../downloaded_files/client/root/.ssh/*
```

```yaml
  tasks:
  - name: "locate base dir"
    debug: msg="file is {{item}}"
    with_fileglob:
            - ../downloaded_files/client/root/.ssh/*.pub*
```
##### EXPECTED RESULTS

Debug output with the file path.
##### ACTUAL RESULTS

No file is found by the fileglob with a `*` matching directories in the path glob.

```
TASK [locate base dir] *********************************************************

PLAY RECAP *********************************************************************
```

**Comment by nitzmahone** [comment]
Hmm, seems to work fine for me (tested on Ubuntu 14.04) - `with_fileglob` is just calling Python's `glob.glob()`, and creating a sample dir structure similar to yours and globbing with \* in a dir component works fine. The only thing I might suggest is that the ".." might not be resolving to the right place, but if your sample works as you say, that can't be it either (ie, it works as expected without the *). Can you try with an absolute path, just for grins?

**Comment by rbauduin** [comment]
I have tried with an absolute path, to no avail.
I am using python 2.7.6, and I tried the same glob with `glob.glob()`, and in that case it correctly returns all items. 

I tried with absolute paths, and it doesn't work either:

```yaml
    with_fileglob:  "/home/rb/ansible-playbooks/downloaded_files/*/root/.ssh/id_rsa.pub"
```

However, this syntax it worked:

```yaml
    with_items: "{{'/home/rb/ansible-playbooks/downloaded_files/*/root/.ssh/id_rsa.pub' | fileglob}}"
```

This also works with a relative path, but in that case I need to use `downloaded_files/blah`and not `../downloaded_files/blah`. The 2 syntaxes seem to be using 2 different code paths, which might explain the different behaviour?

**Comment by dagwieers** [comment]
The **fileglob** lookup plugin only returns a list of files, not directories. That is why it is called **file**glob :-)

So a wildcard can match a directory, as long as it is part of a filename. Not if the match is a directory.

If you want to get more than just files, you can use the **filetree** lookup plugin, but this has not shipped with Ansible v2.1. It is expected for Ansible v2.2 !

**Comment by nitzmahone** [comment]
dagwieers: I don't think he's trying to pick up directories- IIUC he's trying to use a wildcard in a directory slot in the path and saying it's not matching as it should, but I'm unable to reproduce.

**Comment by dagwieers** [comment]
@nitzmahone Oh right. That should work indeed.

**Comment by charlienewey** [comment]
I'm having a problem similar to this myself - matching multiple directories with a file glob.

I think this should work; some testing in various UNIX shells (bash, sh, zsh) and in the Python `glob` module itself seems to show that the following glob pattern:

```
some/path/*/
```

will *just* match directories under `some/path`. Oddly, Ansible doesn't seem to reflect this behaviour.

**Comment by jctanner** [comment]
!needs_info

**Comment by charlienewey** [comment]
OK, so it seems there's some confusion here about what I'm trying to do. I am trying to match *only* directories using a fileglob. Numerous people have mentioned that "it's a *file*glob", but it stands that the default behaviour of file globs in most shells (sh, bash, zsh, etc) allows one to match *only* directories by using the following syntax:

```
/path/to/some/directory/*/
```

Note the trailing slash. This glob will match *only* directories, and not files. This behaviour is apparent in Python's `glob.glob()` method too, but for some reason appears to be absent from the Ansible `with_fileglob` component.

**Comment by dagwieers** [comment]
@charlienewey The implementation of the **fileglob** lookup plugin *only* returns files, not directories. That's how it was implemented as the aim is to iterate over files. If the lookup plugin would return files and directories, it would not be obvious what would be a file or a directory. So this behaviour is on purpose. And that is why it is called **fileglob**, and not just **glob**.

If you are interested in listing directories, you can make use of the **filetree** lookup plugin, it does return a list of files/directories/symlinks using a recursive scan, and it does provide you with additional information (like whether a *file* is a directory, symlink or regular file).

**Comment by charlienewey** [comment]
@dagwieers Oops, sorry - I realised that I had accidentally commented on the wrong issue (I have opened [a similar issue myself](https://github.com/ansible/ansible/issues/17269) and confused the two) and deleted my previous comment before I saw yours.

Anyway, if the intended behaviour of the **fileglob** plugin is only to match **files**, this brings up another issue - there are two ways of using **fileglob** in Ansible that have conflicting behaviour (this is shown by @rbauduin above):

```yaml
# fileglob will return nothing
with_fileglob:  "/home/rb/ansible-playbooks/downloaded_files/*/"

# fileglob will return directories only
with_items: "{{'/home/rb/ansible-playbooks/downloaded_files/*/' | fileglob}}"
```

**Comment by dagwieers** [comment]
Ok, so there is a mismatch between the `fileglob` lookup plugin, and the `fileglob` filter plugin (jinja2).
I guess we have to fix the filter plugin (jinja2) to work exactly as we expect for the lookup plugin.

Thanks for reporting, fix under way !

**Comment by charlienewey** [comment]
Awesome :smile: I am happy to write a `glob` or `dirglob` filter plugin for J2 and/or a lookup plugin for Ansible, if that functionality would be useful.

**Comment by dagwieers** [comment]
Did you know there is an Ansible **find** module ? Could be useful to iterate over directories.

**Comment by charlienewey** [comment]
Yeah, I guess it's possible to do something like this, perhaps?

``` yaml
- find: paths="{{ some_path }}" type=directory
  register: file_paths
```

Alternatively, I have (very quickly) written a `glob` module (almost the same code as `fileglob`, but with normal shell glob behaviour) -  just trying to figure out if I should make any unit tests/doc changes before making a PR.

**Comment by dagwieers** [comment]
Correct, and you can add `connection: local` to perform it on the controller, instead of on the remote targets. Which basically gives you everything you may want :-)

**Comment by charlienewey** [comment]
Excellent, thanks for that - and good idea, I will use that for the time being :smile:. Also, on the off chance that anyone might find it useful, I've opened #17483.

**Comment by luto** [comment]
re: "affects_2.1"

``` yml
---
- name: list files
  hosts: localhost
  tasks:
    - name: create test dirs
      file: state=directory path={{ item }}
      with_items:
        - /tmp/foo
        - /tmp/bar

    - name: create test files
      file: state=touch path={{ item }}
      with_items:
        - /tmp/foo/some.conf
        - /tmp/bar/some.conf

    - debug: var=item
      with_fileglob: "/tmp/*/some.conf"
```

This sample works using 2.1.3, but does not using 2.2.0 on my machine.

2.1.3

```
TASK [debug] *******************************************************************
ok: [localhost] => (item=/tmp/bar/some.conf) => {
    "item": "/tmp/bar/some.conf"
}
ok: [localhost] => (item=/tmp/foo/some.conf) => {
    "item": "/tmp/foo/some.conf"
}
```

2.2.0

```
TASK [debug] *******************************************************************
 [WARNING]: Unable to find '/tmp/*' in expected paths.
```

**Comment by bmalynovytch** [comment]
I've got something similar as @luto with `..../*/*.cfg` glob, which was working prior 2.2.0.0 and not anymore since.

**Comment by smalleni** [comment]
Works with 2.1.3, fails with 2.2.0

**Comment by luto** [comment]
@bcoca the MR, which introduced this behavior is https://github.com/ansible/ansible/pull/16630. Was this intended?

**Comment by anmolnagpal** [comment]
Getting same..!!!

Unable to find '../../../ssl/*' in expected paths.

Works with 2.1.3, fails with 2.2.0

**Comment by jkilpatr** [comment]
Was a fix merged for this and backported? I can not reproduce on 2.2.0 or 2.2.1

**Comment by luto** [comment]
@jkilpatr I can still reproduce my testcase in `devel`, `2.2.0` and `2.2.1`.

**Comment by gbolo** [comment]
I can confirm this still doesn't work in `ansible 2.2.1.0`. hopefully #19297 gets merged soon...

**Comment by gundalow** [comment]
Alternative fix proposed in https://github.com/ansible/ansible/pull/23265

**Comment by luto** [comment]
@bcoca @abadger
This issue was initially raised in August of 2016. A number of test cases, as well as (still) unanswered questions were added by me in November of 2016. Finally, in December we proposed a fix. It has not even seen a review or substantial comment up until now (5 months later). The only piece of actual feedback is one snarky and frankly very rude comment in IRC, which I am not going to quote here.
Instead - 5 months after our fix - you, @bcoca, proposed an alternative one, which has no tests and doesn't seem to handle all cases. Still, not making a single comment why our fix is incomplete or why it can't be used.
There are several people, who have opened issues in their own projects depending on the resolution of this. A number of people have included our patch in their ansible forks, so they can continue to work with ansible.
We understand that things are busy at ansible and redhat. But could you _please_ give us any kind of direction we need to go to get some kind of fix for this into the ansible mainline? What is your plan of action with regard to this issue?

**Comment by bcoca** [comment]
Since we are unsure of the direction, it is hard to give you one.

I wrote my version of the fix because I was doing a poor job of explaining what I was expecting as a feature in contrast to yours. It has helped us define the alternate scenarios that can be covered and narrow down the decision we need to make.  

I'm not trying to cover all cases, in fact I don't think some of those cases should be covered by this plugin, but there is currently a split on this issue, hence the delay.

I have made many comments about your fix, but mostly in the 'core meetings' I have not been good about updating the ticket (and for that I apologize), this is still scheduled for more discussion, please drop by the core meetings to add your input, maybe you can help with the current impasse.

**Comment by UnitedMarsupials-zz** [comment]
FWIW, here is what I'm doing -- relying on `find(1)` and `with_lines` instead of on `with_fileglob`:
```yaml
- name: Process all templates
  template:
    src: "{{ item }}"
    dest: "/{{ item | replace('.j2', '') | replace(role_path + '/templates/', '') }}"
  with_lines:
    - "find {{ role_path }}/templates -type f -name '*.j2'"
```
Maybe, it will help others until this problem is fixed.

**Comment by DanyC97** [comment]
@UnitedMarsupials for me it does in `2.2.1.0`
```yaml
- name: Process templates
   template:
     src: "{{ item }}"
     dest: "{{ generated_dir }}/{{ item | basename | regex_replace('.j2','') }}"
   with_fileglob:
     - "templates/*.yaml.j2"
   register: p8


```

**Comment by UnitedMarsupials-zz** [comment]
@DanyC97, yes, using the fileglob in one directory works -- your example does not have template-characters (like `*`) in the directory-name(s). This must be, how the developers tested it in the first place...

Also, you don't need `regex_replace` to get rid of a simple string like `.j2` -- a simpler `replace` would do :-)

**Comment by dagwieers** [comment]
FYI You could also use `{{ (path | splitext)[0] }}`.

**Comment by caillette** [comment]
For me this bug unveiled when upgrading from 2.1 to 2.4. `with_fileglob` used to work fine.
I eventually found a workaround that nobody should especially proud of, but every other approach failed. I pipe `filetree` output to a regex match. I'm pasting my code verbatim, somebody might find it useful:

```yaml
  - name: 'Create links to Distribution files in Maven repository {{ distributions_dir }}'
    file:
      src: '../{{ item.path | regex_replace( "^.*/((?:(?:\d+\[.]\d+\[.]\d+)|dev-SNAPSHOT))/.*$", "\1" ) }}'
      state: link
      dest: '{{ distributions_dir }}/all/{{ item.path | basename }}'
    with_filetree: '{{ distributions_dir }}'
    when:
    - <some other condition>
    - item.state == 'file'
    - item.path | match( "((\d+[.]\d+[.]\d+)|dev-SNAPSHOT)/MySoftware-distribution-(.+|dev-SNAPSHOT)[.]zip" )
    connection: local
    run_once: true
```

**Comment by dagwieers** [comment]
As a community I think we need to do a better job in raising regressions like this one. And closing them as soon as possible. Anyone with an interest can raise an issue during a core meeting by putting it on the agenda. But it would be nice if we could tag issues as regressions so they get special attention, maybe ?

**Comment by rupran** [comment]
I think this issue was on the Core Meeting agena at least 3 or 4 times, before @bcoca proposed https://github.com/ansible/ansible/pull/23265 as an alternative solution to my initial pull request (https://github.com/ansible/ansible/pull/19297).

The general discussion with @abadger and @bcoca then got to a place where everyone couldn't agree what the desired behaviour really was (see also this comment: https://github.com/ansible/ansible/issues/17136#issuecomment-297068417), which seemed to be the end of it.

**Comment by dagwieers** [comment]
@rupran It was reported on August 2016, and I can find references from meetings in March this year. So a better/faster way to identify and respond to regressions would be useful IMO.

**Comment by geerlingguy** [comment]
I ran into this today as well, and am using @UnitedMarsupials' workaround (https://github.com/ansible/ansible/issues/17136#issuecomment-324112974 - works nice, feels pretty maintainable); though it would be awesome to use with_fileglob with * for dirs!

**Comment by AvnerCohen** [comment]
I couldn't get any suggestion to run correctly.
I find it very confusing that the documentation would say:
```
Matches all files in a single directory, non-recursively, that match a pattern. It calls Python’s “glob” library
```

And if i run:
```py
import glob
print(glob.glob(PATTERN))
```
It works fine, but file_glob would not behave the same.

Plain old glob would be really great to have.

**Comment by monoflo** [comment]
I agree with https://github.com/ansible/ansible/issues/17136#issuecomment-365531723

I am trying to copy fonts over to my remote system using the following task:

```yaml
- name: Copy .ttf font files
  copy:
    src: "{{ item }}"
    dest: /usr/local/share/fonts
  with_fileglob: "{{ role_path }}/files/fonts/**/*.ttf
```
This results in the following message:

`[WARNING]: Unable to find '/<path>/roles/role/files/fonts/**' in expected paths (use
-vvvvv to see paths)`

However, if I use Python's `glob`, I get the desired result:

```python
import glob
glob.glob("/<path>/roles/role/files/fonts/**/*.ttf")
```
[This example illustrates the functionality I'm seeking.](http://www.globtester.com/#p=eJzT19LS19IrKUkDAAl0Alk%3D&r=eJyzScksU0jOSSwutlXKTSxJzlCys8EU0k%2FLzysp1k9OzMlMKsqE0bo5mekZJXolJWk2%2BkA9JGhMSSzKRuiDKirJzE2FksSbjKyJoKn5JWl6QGyTVAQzDNW3QF5SkR3USmRFAMEqaCk%3D&)

To me, it doesn't make sense that fileglob's `run` leverages `find_file_in_search_path` because my query raises an `AnsibleFileNotFound`.

### Relevant Source

https://github.com/ansible/ansible/blob/2d0891e0897159d0010afa9be18d1421fcab47c2/lib/ansible/plugins/lookup/fileglob.py#L54-L63

https://github.com/ansible/ansible/blob/1c157a8cf125e17bed5f6dbf9fb4441f67f4335e/lib/ansible/plugins/lookup/__init__.py#L111-L128

**Comment by bcoca** [comment]
closing as fileglob was not meant to handle directory globbing and the new 'filetree' provides this functionality (also 'pipe' or 'lines' with find).

**Comment by ssbarnea** [comment]
Did anyone found a workaround for checking presence of a folder on controller using lookup? I hate having to add an extra task only for that purpose.
