### ISSUE TITLE
Passing variables via nested include_role doesn't work

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#17686]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel cc9ef78597) last updated 2016/09/21 19:44:14 (GMT +550)
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

If you use `include_role` with `vars:` in a top-level playbook, it works (but is no different from using `roles:` in this respect). If, however, the `include_role` is from inside another role, the variables don't get passed through correctly.
##### STEPS TO REPRODUCE

```
kea:~/ansible $ find -type f|xargs -n 1 -t cat
cat ./a.yml 

---
- hosts: localhost
  gather_facts: no
  roles:
    - role: a
      a: 111
    - role: b
      vars:
        b: 333
  post_tasks:
    - include_role: name=a
      vars:
        a: 42
    - include_role: name=b
      vars:
        b: 222

cat ./roles/a/tasks/main.yml 

---

- debug: var=a
- include_role: name=b
  vars:
    b: "{{ a+1 }}"

cat ./roles/b/meta/main.yml 

---

allow_duplicates: yes

cat ./roles/b/tasks/main.yml 

---

- debug: var=b
```

##### EXPECTED RESULTS

I expected `b` to be defined inside roles/b in every case (i.e., even when it's invoked from role a, where it's showing undefined below).
##### ACTUAL RESULTS

```
TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "a": 111
}

TASK [b : debug] ***************************************************************
ok: [localhost] => {
    "b": "VARIABLE IS NOT DEFINED!"
}

TASK [b : debug] ***************************************************************
ok: [localhost] => {
    "b": 333
}

TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "a": 42
}

TASK [b : debug] ***************************************************************
ok: [localhost] => {
    "b": "VARIABLE IS NOT DEFINED!"
}

TASK [b : debug] ***************************************************************
ok: [localhost] => {
    "b": 222
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
```

**Comment by prutseltje** [comment]
**removed as it was unrelated**

**Comment by bcoca** [comment]
@prutseltje  this is totally unrelated to the current ticket, please open a new one.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jmoraleda** [comment]
I believe variable resolution in nested add_role is still not working properly. For example if we change the example above such that instead of the line
 b: "{{ a+1 }}" 
in ./roles/a/tasks/main.yml where (a is a variable that was passed to the add_role) we had instead
 b: "{{a_defaults_var}}"
where a_defaults_var was a variable _not passed_ to the add_role. (It was for example defined in roles/a/defaults/main.yml) then we get a a_defaults_var not defined.

**Comment by DanyC97** [comment]
@jimi-c i'm afraid this issues is not closed and is same with #18217 and #18540

**Comment by h3po** [comment]
@jimi-c I'm still experiencing this issue in v2.4.1.0

**Comment by dkorel-copperleaf** [comment]
I think I'm seeing this in 2.5, upgraded to 2.6 devel and same result.

**Comment by Jerome-mi** [comment]
same issue with ansible 2.7

**Comment by StephaneBunel** [comment]
Same issue with ansible 2.7.8
