### ISSUE TITLE
Documentation of relative directories in roles_path

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#18067]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

roles_path
##### ANSIBLE VERSION

```
ansible 2.2.0.0 (stable-2.2 5bf850568a) last updated 2016/10/17 08:34:53 (GMT +100)
  lib/ansible/modules/core: (detached HEAD ec4eebc92a) last updated 2016/10/17 08:35:00 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 2b7385d15e) last updated 2016/10/17 08:35:00 (GMT +100)
  config file =
  configured module search path = ['/Users/brian/git/ansible/library']
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Behaviour of roles_path with relative paths is not clear in [documentation](http://docs.ansible.com/ansible/intro_configuration.html#roles-path)
##### STEPS TO REPRODUCE

Use case: a 'shared' roles directory alongside one or more other playbook directories.

```
==> foo/foo.yml <==
- hosts: localhost
  roles:
    - one
    - two

==> foo/roles/one/tasks/main.yml <==
- debug: msg="In task one"

==> shared/roles/two/tasks/main.yml <==
- debug: msg="In task two"
```
##### EXPECTED RESULTS

If you set `roles_path = ../shared/roles" in config, it's not clear what this would be relative to. Seems likely it would have been relative to the playbook directory, or to the current working directory.
##### ACTUAL RESULTS

As far as I can tell from experimentation, the directories searched are relative to whichever directory contains `ansible.cfg`

You can test this by setting ANSIBLE_CONFIG to point to some file which contains

```
[defaults]
roles_path = ../wibble/bibble
```

and then looking for the error message. e.g.

> ANSIBLE_CONFIG=**/Users/brian/tmp/ansible/y.cfg ansible-playbook** tmp/ansible/foo/foo.yml
> 
> ERROR! the role 'two' was not found in /Users/brian/tmp/ansible/foo/roles:**/Users/brian/tmp/wibble/bibble**:/Users/brian/tmp/ansible/foo

This is reasonable behaviour (given that the definition of roles_path is made in `ansible.cfg` itself), but I can't find this documented.

**Comment by AlexAkulov** [comment]
I have this problem begin from version ansible-2.1.1.0, in 2.1.0.0 all work correctly.
Please fix this bug, this very important feature for me!

ansible.cfg

```
roles_path    = ./local_roles
```

run on version 2.1.1.0

```
ansible-playbook -i staging storages.yml --tags=docker
ERROR! the role 'graphite-common' was not found in /opt/TeamCityAgent/work/1ae2fe6e805f2bde/roles:/opt/TeamCityAgent/work/1ae2fe6e805f2bde:/etc/ansible/local_roles
```

**Comment by scottsb** [comment]
It seems that as of 2.4 the location of `roles_path` is longer treated relative to the `ansible.cfg` file. It is now treated relative to the working directory, wherever that may be. It's not clear to me whether this is a bug or an intended change.

**Comment by scottsb** [comment]
Seems like a bug that was fixed yesterday in #31533.

**Comment by bcoca** [comment]
closed by fix as per above

**Comment by candlerb** [comment]
This ticket was about documentation of the behaviour of `roles_path` with relative paths, and in particular, what it's searched relative *to*.  I am still unable to find this documented anywhere.

Via Google, I can find mentions of `roles_path` in:

* [configuration settings](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-roles-path).  It just says: "Colon separated paths in which Ansible will search for Roles."
* [playbooks_reuse_roles](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html) - mention in passing
* [ansible container](https://docs.ansible.com/ansible-container/roles/access.html) - mention in passing

None of these gives the semantics of the setting, although I may have overlooked something.

**Comment by scottsb** [comment]
@bcoca I concur with @candlerb. My comment was confusing. When I said "it" was fixed, I meant my original comment about the behavior regression in 2.4, not the original issue here.
