### ISSUE TITLE
UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

### ISSUE THREAD

**Issue by tfendt** [ansible/ansible#18166]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes to default ansible.cfg
##### OS / ENVIRONMENT

Ubuntu

Directory Structure:

```
devops
  ansible
    farscape
      group_vars
        all
        qa
        qa-ui
      inventories
        ec2.ini
        ec2.py
        qa

security
  keys
    platform
      qa
        key.pem

qa-ui
  ansible
    site.yml
    roles
      qa-ui
```
##### SUMMARY

Ansible can't connect to host after upgrading from 2.1.0.0 to 2.1.2.0.
##### STEPS TO REPRODUCE

```
site.yml:

- name: Test Ping
  hosts: "{{ hosts }}"
  gather_facts: no
  tags: test
  tasks:
    - name: Test Ping
      ping:

qa group var file:

ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ../../../security/keys/platform/qa/key.pem


Executed from the devops -> ansible -> farscape directory (see directory structure above):

ansible-playbook -i inventories/ ../../../qa-ui/ansible/site.yml -t test -e "hosts=qa-ui"
```
##### EXPECTED RESULTS

Successful connection and ping result.
##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: site.yml *************************************************
2 plays in ../../../qa-ui/ansible/site.yml

PLAY [Test Ping] ***************************************************************

TASK [Test Ping] ***************************************************************
task path: /opt/teamcity-agent/work/56ef8995252d7315/qa-ui/ansible/site.yml:6
<10.2.10.13> ESTABLISH SSH CONNECTION FOR USER: None
<10.2.10.12> ESTABLISH SSH CONNECTION FOR USER: None
<10.2.10.13> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/ansible-ssh-%h-%p-%r 10.2.10.13 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1477325466.67-100845165082436 `" && echo ansible-tmp-1477325466.67-100845165082436="` echo $HOME/.ansible/tmp/ansible-tmp-1477325466.67-100845165082436 `" ) && sleep 0'"'"''
<10.2.10.12> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/ansible-ssh-%h-%p-%r 10.2.10.12 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1477325466.67-37577927945882 `" && echo ansible-tmp-1477325466.67-37577927945882="` echo $HOME/.ansible/tmp/ansible-tmp-1477325466.67-37577927945882 `" ) && sleep 0'"'"''
fatal: [10.2.10.13]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [10.2.10.12]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}


PLAY RECAP *********************************************************************
10.2.10.12                 : ok=0    changed=0    unreachable=1    failed=0   
10.2.10.13                 : ok=0    changed=0    unreachable=1    failed=0 
```

This error happens across all our ansible tasks after upgrading from 2.1.0.0 to 2.1.2.0.

**Comment by geraldcor** [comment]
I am similarly affected. Downgrading fixes the issue. On macOS 10.11.6 python 2.7.12.

**Comment by kuenishi** [comment]
For me (macOS 10.11.6, Python 2.7.12, OpenSSH_7.2p2, LibreSSL 2.4.1), adding `-c ssh --ask-pass -u <remote-user-name>` explicitly, with `sshpass` installed solved the issue. IMO this is related to the behavior of smart connector, described in [the official document](http://docs.ansible.com/ansible/intro_configuration.html#transport) like this:

> This is the default transport to use if “-c <transport_name>” is not specified to /usr/bin/ansible or /usr/bin/ansible-playbook. The default is ‘smart’, which will use ‘ssh’ (OpenSSH based) if the local operating system is new enough to support ControlPersist technology, and then will otherwise use ‘paramiko’. 

But this behavior is quite different from choosing explicitly `-c ssh` or `-c paramiko`, and hard to find out workaround like adding `--ask-pass` or `-u <username>`. I'd like these message to be more close to resolution.

**Comment by resmo** [comment]
This could probably be fixed with 49ce0c8baccbec45156b8a1ecb5c1d496180ed43 in 2.1.3 
dublicate_of #17869

**Comment by gundalow** [comment]
duplicate_of #17869

**Comment by tfendt** [comment]
I am still getting an unable to connect with version 2.2.0. The error message has changed slightly.

fatal: [10.2.10.13]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).\r\n", "unreachable": true}

2.1.0.0 still works.
