### ISSUE TITLE
meta: clear_host_errors not working on tasks

### ISSUE THREAD

**Issue by mikekrasn** [ansible/ansible#19673]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`plugins/strategy/__init__.py`

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Fresh install

##### OS / ENVIRONMENT

RHEL
##### SUMMARY

`meta: clear_host_errors`   is not working as expected

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: no
  tasks:

  - name: dummy check 1
    changed_when: no
    failed_when: no
    ignore_errors: yes
    shell: uname

  - meta: clear_host_errors

  - name: dummy check 2
    changed_when: no
    failed_when: no
    ignore_errors: yes
    shell: uname -n


```

##### EXPECTED RESULTS

$ ansible-playbook -i localhost,google.com  dummy.yml

PLAY [all] *********************************************************************

TASK [dummy check 1] ***********************************************************
ok: [localhost]
fatal: [google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host google.com port 22: Connection timed out\r\n", "unreachable": true}

TASK [dummy check 2] ***********************************************************
ok: [localhost]
fatal: [google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host google.com port 22: Connection timed out\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
google.com                 : ok=0    changed=0    unreachable=2    failed=0
localhost                  : ok=2    changed=0    unreachable=0    failed=0

##### ACTUAL RESULTS

Expected to use unreachable host in the subsequent task. As per  https://github.com/ansible/ansible/pull/18127/files 
 "Connection failures set hosts as 'UNREACHABLE', which will remove them from the list of active hosts for the run. To recover from these issues you can use `meta: clear_host_errors` to have all currently flagged hosts reactivated, so subsequent tasks can try to use them again."

```
$ ansible-playbook -i localhost,google.com  dummy.yml

PLAY [all] *********************************************************************

TASK [dummy check 1] ***********************************************************
ok: [localhost]
fatal: [google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host google.com port 22: Connection timed out\r\n", "unreachable": true}

TASK [dummy check 2] ***********************************************************
ok: [localhost]
        to retry, use: --limit @/root/dummy.retry

PLAY RECAP *********************************************************************
google.com                 : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

**Comment by berney** [comment]
`clear_host_errors` was introduced in 2.1 according to the docs. Does this bug affect 2.1.x? 

I'm having trouble finding which releases have fixed the bug, doing `git tag --contains 08ef0ae` I don't see any, I was hoping it would show what releases have the fix. I'm not confident I'm doing things right because `git tag --contains b339d4c` doesn't show anything either. And `git branch --contains $commit` for either commit doesn't show any release/stable branches.

**Comment by ghost** [comment]
Hello, 

The same bug seems to be in the version 2.3.1.0.
I use the same steps to reproduce as mentioned above and the play does not go the "dummy check 2"
```
PLAY [all] *******************************************************************************************************************************************

TASK [dummy check 1] *********************************************************************************************************************************
fatal: [google.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host google.com port 22: Connection timed out\r\n", "unreachable": true}
	to retry, use: --limit @/tmp/test-ansible/test.retry

PLAY RECAP *******************************************************************************************************************************************
google.com                 : ok=0    changed=0    unreachable=1    failed=0 
```
OS: ubuntu 17.04
Ansible version: 2.3.1.0

**Comment by jimi-c** [comment]
@badr-badri I believe this was fixed in 2.3.2, but if not please open a new issue.

Thanks!

**Comment by UnitedMarsupials-zz** [comment]
I'm pretty sure, I still have this problem with 2.5.5. The role's first three tasks:
```yaml
- name: Add keys
  authorized_key:
    user:   "{{ ansible_ssh_user }}"
    key:    "{{ hostvars['localhost'].pubkeys.stdout }}"
    exclusive:      true
  register: first
  ignore_errors: true
- meta: clear_host_errors
- name: Dump hostvars
  debug:
    var: first
```
The output:
```
TASK [Collect ssh public keys] *******************************************************************************************************************
ok: [localhost]

PLAY [all] ***************************************************************************************************************************************

TASK [homedir : Add keys] ************************************************************************************************************************
fatal: [R00RPMN0C]: UNREACHABLE! => {"changed": false, "msg": "Authentication failure.", "unreachable": true}
        to retry, use: --limit @/mi/A/playbooks/access.retry

PLAY RECAP ***************************************************************************************************************************************
R00RPMN0C                  : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
As you can see, the debug-task is never performed after the "Add keys" task fails...

**Comment by samuelharmer** [comment]
@UnitedMarsupials You might be experiencing the same thing as reported on #26362 which @bcoca wrote up as a [Possible Misunderstanding][1]. I am also here because I read [the documentation][2] and also [formed the same misunderstanding][3].

I think the description (copied below for convenience) would be better if it explained that if all hosts are unreachable (if I'm understanding @bcoca correctly) the processing halts **immediately** and therefore a `- meta: clear_host_errors` would never get a chance to run. I still think this counts as a `bug` because it's not intuitive to me that clearing host errors depends on there being at least one successful host.

> Connection failures set hosts as ‘UNREACHABLE’, which will remove them from the list of active hosts for the run. To recover from these issues you can use meta: clear_host_errors to have all currently flagged hosts reactivated, so subsequent tasks can try to use them again.

However I have come up with a workaround which works in my case which is to use [`wait_for_connection`][4] on a short timeout. I can use that to register a variable which I can then test against in subsequent tasks. Probably won't help in all cases but here it is.

```yaml
- name: Check if we can connect with the default username and password
  wait_for_connection:
    connect_timeout: 1
    timeout: 3
  register: connection
  ignore_errors: yes
  vars:
    ansible_ssh_user: pi
    ansible_ssh_pass: raspberry
- name: Print results
  debug:
    msg: "Connection {% if connection.failed %}failed{% else %}succeeded{% endif %}"
```

With a single host defined, if it still has the default username and password I receive the following.

```yaml
TASK [raspbian-common : Check if we can connect with the default username and password]
ok: [raspberrypi]

TASK [raspbian-common : Print results]
ok: [raspberrypi] => {
    "msg": "Connection succeeded"
}
```

If I change the password, I receive the following instead. 

```yaml
TASK [raspbian-common : Check if we can connect with the default username and password]
fatal: [raspberrypi]: FAILED! => {"changed": false, "elapsed": 7, "msg": "timed out waiting for ping module test success: Authentication failure."}
...ignoring

TASK [raspbian-common : Print results]
ok: [raspberrypi] => {
    "msg": "Connection failed"
}
```

_I did notice [SSH connection caching][5] whilst testing this though so be careful._

_Edit: just noticed you have localhost defined too. I wonder if because that comes before your play it doesn't 'solve' the single host failure?_

[1]: https://github.com/ansible/ansible/issues/26362#issuecomment-312726099
[2]: https://docs.ansible.com/ansible/2.6/user_guide/playbooks_error_handling.html#resetting-unreachable-hosts
[3]: https://www.xkcd.com/1984/
[4]: https://docs.ansible.com/ansible/2.6/modules/wait_for_connection_module.html
[5]: https://man.openbsd.org/ssh_config.5#ControlMaster
