### ISSUE TITLE
s3 module: 'function' object has no attribute 'urlparse'

### ISSUE THREAD

**Issue by sebastianneubauer** [ansible/ansible#20820]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - S3 module

##### ANSIBLE VERSION
ansible 2.3.0 (devel 9bc4a12ae5) last updated 2017/01/30 11:55:55 (GMT +200)
  config file =
  configured module search path = Default w/o overrides

ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides

##### CONFIGURATION
--

##### OS / ENVIRONMENT
```
python --version
Python 2.7.11
```
and
```
python --version
Python 3.5.2
```

##### SUMMARY
Using the s3 module with either fakes3 or RGW an error occurs:
"Failed to connect to S3: 'function' object has no attribute 'urlparse'"
This seems to be related to #16191 
 
##### STEPS TO REPRODUCE
`ansible -vvv localhost -i inventory -m s3 -a "bucket=tets mode=list rgw=true s3_url=http://bla.blubb"`

##### EXPECTED RESULTS

? something like: list of you bucket

##### ACTUAL RESULTS

```
localhost | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "bucket": "tets",
            "dest": null,
            "ec2_url": null,
            "encrypt": true,
            "expiry": "600",
            "headers": null,
            "marker": null,
            "max_keys": "1000",
            "metadata": null,
            "mode": "list",
            "object": null,
            "overwrite": "always",
            "permission": [
                "private"
            ],
            "prefix": null,
            "profile": null,
            "region": null,
            "retries": 0,
            "rgw": true,
            "s3_url": "http://bla.blubb",
            "security_token": null,
            "src": null,
            "validate_certs": true,
            "version": null
        },
        "module_name": "s3"
    },
    "msg": "Failed to connect to S3: 'function' object has no attribute 'urlparse'"
}
```

**Comment by ryansb** [comment]
What python interpreter is Ansible using? Is this happening on Python 3?

**Comment by sebastianneubauer** [comment]
tested with python 2.7.11, and python 3.5.2

**Comment by sebastianneubauer** [comment]
fixed by #20836

**Comment by jrandall** [comment]
Despite this being a bugfix, it does not seem to have been included in the 2.2 release candidates. Is it scheduled for inclusion in the next one? This bug is still present in v2.2.2.0-0.2.rc2
