### ISSUE TITLE
Don't blindly accept any parameter in file module

### ISSUE THREAD

**Issue by mmoya** [ansible/ansible#2135]
Hello

Using version 81d426de. At least modules `file`, `template`, `user`, `group` and `lineinfile` silently accepts an arbitrary parameter, for example `nonexistentparam=someval`. In my opinion this behaviour renders playbooks error prone and hinders playbook QA.

I came to this specifically using the `file` module for creating a directory with a given owner. By mistake I used `file: name=/etc/rails user=deploy` instead of correct `owner` parameter. The error got caught later by manual check. I honestly was expecting `ansible-playbook` to report a syntax error. It's a **syntax error**.

At least `apt` module properly reports an unexpected parameter. 

Granted, I should pay more attention when I read `file` module documentation to avoid type `user` instead of `owner`. Anyway, how is it supposed I'll catch a typo in my playbook?  Should I enter the remote system after each `ansible-playbook` run to make sure the intended state is in place and I don't have a hidden syntax error in the `.yml`? Suppose I have only one typo in a +100 lines `.yml`, say  `groupp` instead of `group`.

I was told in IRC this wouldn't be fixed. Please reconsider it.

Thanks,
maykel

**Comment by dhozac** [comment]
I definitely agree this should be fixed. Should really only be a one-line change of removing check_invalid_arguments=False from library/file.

As for the other modules, I can't reproduce your issue. They all bail out if they receive an unknown argument. file is the only one that doesn't, due to how it used to be implemented.

**Comment by mmoya** [comment]
[oops, sorry for the open/close, still getting accustomed to GH]

Confirmed only `file`, `template` and `copy` fails in both latest `devel` and `v1.0`.

Removing `check_invalid_arguments=False` is not enough. Without it `file` bails out but `template` and `copy` still accept any parameter (including the correct ones, of course). @dhozac can you confirm this?

**Comment by mpdehaan** [comment]
template and copy don't actually call the file module anymore, they use the server side copy module that contains various routines that the file copy uses.   Basically the copy module should explicitly list the parameters the file module takes and then we should be able to remove the above invalid arg check also.

In other words, your fix is fine, there is just more to fix too.

**Comment by mpdehaan** [comment]
I am not going to be working on this soon.  Patches would be accepted.

**Comment by mmoya** [comment]
I'll look at it.
