### ISSUE TITLE
Roles cannot find resources within their own role if not using main.yml as task list

### ISSUE THREAD

**Issue by wltjr** [ansible/ansible#21735]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Template module, but I think this is a core issue effecting all

##### ANSIBLE VERSION
Does not work
ansible 2.2.1.0
  config file = /sites/site1/ansible/ansible.cfg
  configured module search path = Default w/o overrides

ansible 2.3.0
  config file = /sites/site1/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Works in 
ansible 2.1.4.0
  config file = /sites/site1/ansible/ansible.cfg
  configured module search path = Default w/o override

##### CONFIGURATION
```
$ cat ansible.cfg 
[defaults]
inventory=hosts
pipelining=True
remote_user=ro
```
##### OS / ENVIRONMENT
Gentoo

##### SUMMARY
Roles cannot find files/templates in the roles own directories

##### STEPS TO REPRODUCE

Same with ansible 2.2.1.0 and 2.3.0, works with 2.1.4.0

mkdir -p roles/test/tasks roles/test/templates

$ cat test.yaml 
```yaml
---
- name: Test the test role
  hosts: ws
  roles:
   - test
```

$ cat roles/test/tasks/main.yaml 
```yaml
- name: Install test template from role
  template:
    src: templates/empty.j2
    dest: /tmp/empty.j2
```

$ cat roles/test/templates/empty.j2

## Versions 2.1.4.0 ##

$ ansible-playbook test.yaml 

PLAY [Test the test role] ******************************************************

TASK [setup] *******************************************************************
ok: [ws]

TASK [test : Install test template from role] **********************************
changed: [ws]

PLAY RECAP *********************************************************************
ws                         : ok=2    changed=1    unreachable=0    failed=0   

## Versions 2.2.1.0 and 2.3.0 ##

$ ansible-playbook test.yaml 

PLAY [Test the test role] ******************************************************

TASK [Gathering Facts] *********************************************************
ok: [ws]

TASK [test : Install test template from role] **********************************
fatal: [ws]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'templates/empty.j2' in expected paths."}
        to retry, use: --limit @/sites/site1/ansible/test.retry

PLAY RECAP *********************************************************************
ws                         : ok=1    changed=0    unreachable=0    failed=1

**Comment by wltjr** [comment]
Seems this may be specific to the templates module. Previous behavior was
role_path, now it seems to be role_path/templates, so when I add templates to the path, it ends up as role_path/templates/templates and fails. Not sure if other modules are doing this as well.

**Comment by jctanner** [comment]
@wltjr I'm unable to reproduce this on any of the versions you've specified. I did notice this line in your description though ...

```
mkdir -p roles/test/tasks roles/tests/templates
```

Did you make a typo in the description or did you accidentally create a "test" and a "tests" role?

needs_info

**Comment by wltjr** [comment]
Yes that was a typo, sorry I will edit and correct. I got someone else who was on 2.2.0 to replicate. They discovered that it worked when templates was not part of the path. I attached a archive of the test.
[ansible_role_test.zip](https://github.com/ansible/ansible/files/794077/ansible_role_test.zip). Not sure what else I can do to help replicate.

**Comment by wltjr** [comment]
@jctanner What version of python are  you using? I wonder if it is an issue in that. I am on 2.7. The person running 2.2.0 that had it fail is also on python 2.7.

**Comment by fia5000** [comment]
I am able to replicate this with 2.2.1.0.

**Comment by jctanner** [comment]
[test.txt](https://github.com/ansible/ansible/files/804402/test.txt)

@wltjr my test results from your zipfile are attached. I still don't seen any issue.

```
[jtanner@fedmac AP-21735]$ uname -a
Linux fedmac.lab.net 4.9.9-200.fc25.x86_64 #1 SMP Thu Feb 9 17:28:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[jtanner@fedmac AP-21735]$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
[jtanner@fedmac AP-21735]$ python --version
Python 2.7.13
```

Please re-run on your machine with -vvvv so we can see if there's anything related to the connection method(s).

needs_info

**Comment by wltjr** [comment]
I see that it worked for you... I can see about getting a log from the person who said it failed on 2.2.0. Here the requested output. I should have provided initially.
[ansible-test-2.1.4.0.txt](https://github.com/ansible/ansible/files/804951/ansible-test-2.1.4.0.txt)
[ansible-test-2.2.1.0.txt](https://github.com/ansible/ansible/files/804952/ansible-test-2.2.1.0.txt)

I am on the same version of python
```bash
# python2 --version
Python 2.7.13
```

The system python is 3, but Ansible uses 2.7
```bash
[ebuild   R    ] app-admin/ansible-2.2.1.0::gentoo  USE="-keyczar {-test}" PYTHON_TARGETS="python2_7"
```
Really cannot explain. I have even tried using role_path in ansible.cfg and no change. Given I have a role that uses role_path variable for an included task from another role. That works but then the following tasks that use the roles own path like this test fail. Its strange.

```yaml
---
- include: roles/firewall/tasks/firewall_extra_file.yaml
  vars:
    - { path: "{{ role_path }}/files" }

- name: Create bind directories
  tags: bind
  file: path=/etc/bind/{{ item.zone }} state=directory mode=0755
  with_items: "{{ zones }}"

- name: Configure bind zones
  tags: bind
  template:
    src: templates/etc/bind/zones/pri.{{ item[1] }}.j2
    dest: /etc/bind/{{ item[0].zone }}/pri.{{ item[1] }}
    mode: 0644
    backup: yes
  notify: Restart named
  with_nested:
    - "{{ zones }}"
    - "{{ domains }}"

- name: Configure bind
  tags: bind
  template:
    src: templates/etc/bind/named.conf.j2
    dest: /etc/bind/named.conf
    mode: 0644
    backup: yes
  notify: Restart named
```
In that, the include task works using role_path variable. But then the last 2 tasks configuring bind fail. With those being in the same location. I tried removing the top entry and had no effect. The remaining ones failed. That is for the templates directory in that role. role_path is clearly populated just not in use when not specified. The above works as the test does in 2.1.4.0, but fails in 2.2.1.0 just as the test in this issue.

**Comment by jctanner** [comment]
@wltjr grasping at straws here:

1. can you describe how you install ansible and how you tests across different versions? 
2. What is in your inventory?

needs_info

**Comment by wltjr** [comment]
Install only one of the following, first builds, 2nd uses pre-built binary, 3rd pulls in specific pre-built binary version.
```
emerge  -qv ansible
emerge -qkv ansible
emerge -qkv =ansible-2.1.4.0
```
I may need to rebuild as I do make binaries and install those since I am running multiple systems. Thought I doubt rebuilding will have any effect, not like this is a binary package really, no compiling, linking. Any python libraries will be same between versions of ansible.

Inventory is pretty basic, but I thought maybe a system or group name may conflict with role. But I have no tests systems or groups. I ruled that out with dns creating a bind role/symlink, and other tests.

Inventory is pretty basic. In this example ws is a workstation/desktop. Just a entry in host, and it has a var file for IP address and other host specific stuff. Pretty basic stuff. I have more complex hosts but in same format. Nothing that should effect role paths.

hosts.yaml
```yaml
[lan]
dev
ws
wlt
```

host_vars/ws
```
---
hostname: ws
ipv4: 0.0.0.0
ipv6: "::"
lan: 
ula: 
zone: New_York
profile: default/linux/amd64/13.0/desktop/plasma
```

**Comment by wltjr** [comment]
More info, ran it through strace. I will start with the most interesting as the rest seems to confirm the same.
```bash
wlt@ws /sites/site1/ansible
$ grep templates /tmp/output
wlt@ws /sites/site1/ansible
$ grep empty.j2 /tmp/output
wlt@ws /sites/site1/ansible
```
When I grep the file for templates, there is no output. In fact the file is never even attempted to be opened or referenced. This bit of the strace output, [strace.txt](https://github.com/ansible/ansible/files/815369/strace.txt). Shows it looking into the right directory. But no attempt at templates.
```
lstat("/sites/site1/ansible", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
lstat("/sites/site1/ansible/roles", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
lstat("/sites/site1/ansible/roles/test", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
stat("/sites/site1/ansible/roles/test", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
stat("/sites/site1/ansible/roles/test/action_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/cache_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/callback_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/connection_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/filter_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/lookup_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/library", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/shell_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/strategy_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/test_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/vars_plugins", 0x7ffda5930390) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/meta", 0x7ffda592ff90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/tasks", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
stat("/sites/site1/ansible/roles/test/tasks", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffda592fd90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/tasks/main.yaml", {st_mode=S_IFREG|0644, st_size=104, ...}) = 0
stat("/sites/site1/ansible/roles/test/tasks/main.json", 0x7ffda592fd90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/tasks/main", 0x7ffda592fd90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffda592fd90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/tasks/main.yaml", {st_mode=S_IFREG|0644, st_size=104, ...}) = 0
stat("/sites/site1/ansible/roles/test/tasks/main.yaml", {st_mode=S_IFREG|0644, st_size=104, ...}) = 0
stat("/sites/site1/ansible/roles/test/tasks/main.yaml", {st_mode=S_IFREG|0644, st_size=104, ...}) = 0
stat("/sites/site1/ansible/roles/test/tasks/main.yaml", {st_mode=S_IFREG|0644, st_size=104, ...}) = 0
open("/sites/site1/ansible/roles/test/tasks/main.yaml", O_RDONLY) = 6
stat("/sites/site1/ansible/roles/test/handlers", 0x7ffda592ff90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/vars", 0x7ffda592ff90) = -1 ENOENT (No such file or directory)
stat("/sites/site1/ansible/roles/test/defaults", 0x7ffda592ff90) = -1 ENOENT (No such file or directory)
getcwd("/sites/site1/ansible", 1024)    = 21
```

**Comment by wltjr** [comment]
I forgot to add -f to strace so it was not tracking forked processes. Now that I added that, here is the differences. The 2.1.4.0 output is via grep empty.j2. The 2.2.1.0 output is raw, consecutive lines. It does not seem to look anywhere for the file other than the one path. 2.1.4.0, seems to search other paths.

Full output, consecutive lines
2.2.1.0
```
31147 lstat("/sites", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
31147 lstat("/sites/site1", {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
31147 lstat("/sites/site1/ansible", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
31147 lstat("/sites/site1/ansible/roles", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
31147 lstat("/sites/site1/ansible/roles/test", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
31147 lstat("/sites/site1/ansible/roles/test/tasks", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
31147 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
31147 stat("/sites/site1/ansible/roles/test/tasks/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
31147 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
31047 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=1000} <unfinished ...>
31147 stat("/sites/site1/ansible/templates/empty.j2", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
```

grep empty.j2 /tmp/ansible_2.1.4.0.out
2.1.4.0
```
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2",  <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2",  <unfinished ...>
30628 stat("/sites/site1/ansible/templates/templates/empty.j2",  <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2",  <unfinished ...>
30628 open("/sites/site1/ansible/roles/test/templates/empty.j2", O_RDONLY <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
30628 read(14, "oebHTBempty.j2", 14)    = 14
30628 read(14, "dest\": \"/tmp/empty.j2\", \"checksu"..., 46) = 46
30628 read(14, "\"original_basename\": \"empty.j2\","..., 106) = 106
```

**Comment by wltjr** [comment]
More from 2.1.4.0 output, search path before it finds file. There was more output between each of these lstat/stat lines. 2.1.4.0 is much noisier than 2.2.1.0 wrt to strace output. Even in looking at the path. The 2.2.1.0 output from previous comment, does not have additional output between lines.
```
30628 lstat("/sites/site1",  <unfinished ...>
30628 lstat("/sites/site1/ansible", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
30628 lstat("/sites/site1/ansible/roles", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
30628 lstat("/sites/site1/ansible/roles/test",  <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffc333b9720) = -1 ENOENT (No such file or directory)
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2",  <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2",  <unfinished ...>
30628 stat("/sites/site1/ansible/templates/templates/empty.j2",  <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2",  <unfinished ...>
30628 open("/sites/site1/ansible/roles/test/templates/empty.j2", O_RDONLY <unfinished ...>
```

Example of full output difference from 2.1.4.0
```
30628 lstat("/sites/site1",  <unfinished ...>
30565 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100} <unfinished ...>
30628 <... lstat resumed> {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
30628 lstat("/sites/site1/ansible", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
30628 lstat("/sites/site1/ansible/roles", {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
30628 lstat("/sites/site1/ansible/roles/test",  <unfinished ...>
30565 <... select resumed> )            = 0 (Timeout)
30628 <... lstat resumed> {st_mode=S_IFDIR|S_ISGID|0755, st_size=4096, ...}) = 0
30565 poll([{fd=6, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
30565 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=100} <unfinished ...>
30628 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffc333b9720) = -1 ENOENT (No such file or directory)
```

**Comment by bcoca** [comment]
looks like the problem is here:
```
31147 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
31147 stat("/sites/site1/ansible/roles/test/tasks/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
31147 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
```

it tries to detect 'am i in role' but is unable to find the files, so it won't add 'role dirs' to the search path

**Comment by wltjr** [comment]
You think? I think this shows the issue. The paths before this include roles/test, but all the sudden for templates, drops back down to ansible root folder. Then fails.
```
31147 stat("/sites/site1/ansible/roles/test/tasks/main.yml", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
31047 select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=1000} <unfinished ...>
31147 stat("/sites/site1/ansible/templates/empty.j2", 0x7ffeed9cd540) = -1 ENOENT (No such file or directory)
```
 2.1.4.0, has an odd search order. If you look, it tries a less path before more, except when it gets to templates. It tries a longer path. You can see it did not do that with tasks, it tried tasks/main.yml before tasks/tasks/main.yml. But at least 2.1.4.0 can find the file. 2.2.1.0 doesn't even seem to try other paths.
```
30628 lstat("/sites/site1"
30628 lstat("/sites/site1/ansible"
30628 lstat("/sites/site1/ansible/roles"
30628 lstat("/sites/site1/ansible/roles/test"
30628 stat("/sites/site1/ansible/roles/test/tasks/main.yml"
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2"
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2"
30628 stat("/sites/site1/ansible/templates/templates/empty.j2"
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2"
30628 open("/sites/site1/ansible/roles/test/templates/empty.j2"
```

**Comment by wltjr** [comment]
The main tasks file is main.yaml not main.yml. Yes I should switch to yml, but its pretty moot on *nix. But it does find that file. Otherwise would not even look for the templates, as the task is what refers to the templates. 2.2.1.0 definitely finds the main.yaml file, roles/test/tasks/main.yaml. It has issues with template paths after. Seems to fall back to ansible root folder and never tries other paths.

**Comment by wltjr** [comment]
2.1.4.0 is also dropping down to root before it tries the proper location.
```
30628 stat("/sites/site1/ansible/roles/test/templates/templates/empty.j2"
30628 stat("/sites/site1/ansible/templates/templates/empty.j2"
30628 stat("/sites/site1/ansible/roles/test/templates/empty.j2"
30628 open("/sites/site1/ansible/roles/test/templates/empty.j2"
```

IMHO that order like the rest should be
```
"/sites/site1/ansible/roles/test/tasks/main.yml"
"/sites/site1/ansible/roles/test/templates/empty.j2"
"/sites/site1/ansible/roles/test/templates/templates/empty.j2"

```

This is odd, and the ordering is, as before and after this it is in roles/test but jumps down to ansible root folder and adds on templates. 2.2.1.0 seems to start with root path, but does not add on templates. It still goes from roles/test directory back to ansible root directory. Both 2.1.4.0 and 2.2.1.0 do that. Just 2.2.1.0 does not seem to search any other paths.
```
30628 stat("/sites/site1/ansible/templates/templates/empty.j2"
```

**Comment by sivel** [comment]
The code in `ansible.parsing.dataloader.DataLoader.path_dwim_relative` *explicitly* looks for `main.yml`, not `main.yaml`.  As such, if it doesn't find a `main.yml` it does not set that it is in a role.

There is a comment which leads me to believe this should however be fixed:

> #FIXME: this role detection will not work with alternate/missing main.yml

I do actually see another issue in adjacent code for `path_dwim_relative` where we seem to have `isrole` and `is_role`, and I think there may be some problems as a result.

**Comment by bcoca** [comment]
@sivel, just added those and was looking on how to push that data down the stack vs having that flawed 'detection'

**Comment by wltjr** [comment]
Ok, so this issue is caused by roles/test/tasks/main.yaml instead of main.yml. I just confirmed that. Pretty strange. It does find the main.yaml file. In others the ```{{ role_path }}``` variable does work in both, so not sure why that variable would be populated if its not in a role.

Also interesting, regardless of main.yml vs main.yaml, if in the task I change templates/empty.j2 to just empty.j2 it finds it in the roles/test/templates directory. Seems like this is some bug triggered by the file name extension.

**Comment by wltjr** [comment]
FYI 
Is there an official extension for YAML files?
Please use ".yaml" when possible.
http://www.yaml.org/faq.html

Thus ansible should behave the same regardless if yaml or yml is used. yml is really more a Windows requirement, 3 char limit.

**Comment by bcoca** [comment]
nope, there is not even a requirement for extension 'tasks/main' should workTM, the detection in the code has always been flawed, it was just obscured by the big hammer of making 'all paths searchable' vs the actual 'inherited paths' part of the search.

**Comment by wltjr** [comment]
Cool no worries, at least its found, known, and a work around is very simple :) Thanks for the patience with all the noise.

**Comment by bcoca** [comment]
@wltjr the PR above should fix your case, still need better solution for when role is not using main at all

**Comment by wltjr** [comment]
This has been fixed in 2.3.0.0. Feel free to close or leave open for 2.2.

**Comment by wltjr** [comment]
I am going to close this as it has been fixed in 2.3. Anyone running into this should upgrade to 2.3 or newer.

**Comment by MaxRuas** [comment]
I have ansible version above 2.3 as you can see below but I still have this problem, any suggestion would be much appreciated.

[root@localhost mongodb]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]



TASK [Create the file to initialize the mongod Shard] ***************************************************************************************************************************
failed: [mongo1 -> mongo1] (item=mongo1) => {"changed": false, "item": "mongo1", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo1 -> mongo2] (item=mongo2) => {"changed": false, "item": "mongo2", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo2 -> mongo1] (item=mongo1) => {"changed": false, "item": "mongo1", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo2 -> mongo2] (item=mongo2) => {"changed": false, "item": "mongo2", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo3 -> mongo1] (item=mongo1) => {"changed": false, "item": "mongo1", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo3 -> mongo2] (item=mongo2) => {"changed": false, "item": "mongo2", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo4 -> mongo1] (item=mongo1) => {"changed": false, "item": "mongo1", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
failed: [mongo4 -> mongo2] (item=mongo2) => {"changed": false, "item": "mongo2", "msg": "Could not find or access 'shard_init.j2'\nSearched in:\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/roles/mongod/tasks/shard_init.j2\n\t/root/ansible-examples/mongodb/templates/shard_init.j2\n\t/root/ansible-examples/mongodb/shard_init.j2"}
	to retry, use: --limit @/root/ansible-examples/mongodb/site.retry

PLAY RECAP **********************************************************************************************************************************************************************
mongo1                     : ok=38   changed=1    unreachable=0    failed=1   
mongo2                     : ok=35   changed=1    unreachable=0    failed=1   
mongo3                     : ok=28   changed=1    unreachable=0    failed=1   
mongo4                     : ok=21   changed=1    unreachable=0    failed=1
