### ISSUE TITLE
Roles are ran multiple times if both referenced as dependency and from playbook

### ISSUE THREAD

**Issue by wouterh-dev** [ansible/ansible#22169]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Playbooks/Roles

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
`nowcows=1`

##### OS / ENVIRONMENT
N/A (Ubuntu)

##### SUMMARY
When a role is invoked through a playbook and also referenced as a dependency it is executed twice.

##### STEPS TO REPRODUCE
```yaml
==> playbook.yml <==
---
- hosts: localhost

  roles:
    - role: A
    - role: B
    - role: C

==> roles/A/tasks/main.yml <==
---
- debug: msg=A

==> roles/B/meta/main.yml <==
dependencies:
  - name: A

==> roles/B/tasks/main.yml <==
---
- debug: msg=B

==> roles/C/meta/main.yml <==
dependencies:
  - name: A

==> roles/C/tasks/main.yml <==
---
- debug: msg=C
```

##### EXPECTED RESULTS
Have roles A, B, C each execute once.

##### ACTUAL RESULTS
Role A runs twice, then role B and C run.

```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: playbook.yml *********************************************************
1 plays in playbook.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035 `" && echo ansible-tmp-1488405550.52-260200123218035="` echo ~/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpF6ZqnV TO /home/ubuntu/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035/ /home/ubuntu/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035/setup.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1488405550.52-260200123218035/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [A : debug] ***************************************************************
task path: /home/ubuntu/demo-ansible-multiple_role-bug/roles/A/tasks/main.yml:2
ok: [localhost] => {
    "msg": "A"
}

TASK [A : debug] ***************************************************************
task path: /home/ubuntu/demo-ansible-multiple_role-bug/roles/A/tasks/main.yml:2
ok: [localhost] => {
    "msg": "A"
}

TASK [B : debug] ***************************************************************
task path: /home/ubuntu/demo-ansible-multiple_role-bug/roles/B/tasks/main.yml:2
ok: [localhost] => {
    "msg": "B"
}

TASK [C : debug] ***************************************************************
task path: /home/ubuntu/demo-ansible-multiple_role-bug/roles/C/tasks/main.yml:2
ok: [localhost] => {
    "msg": "C"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```

**Comment by alikins** [comment]
Can you duplicate this with the devel version of ansible?

If more than 2 roles use the dep, does it get execute more than twice? 

http://docs.ansible.com/ansible/playbooks_roles.html#role-dependencies

> Roles dependencies are always executed before the role that includes them, and are recursive. By default, roles can also only be added as a dependency once - if another role also lists it as a dependency it will not be run again. This behavior can be overridden by adding allow_duplicates: yes to the meta/main.yml file. For example, a role named ‘car’ could add a role named ‘wheel’ to its dependencies as follows:

If I understand correctly, role 'A' is a dep of Role 'B' and 'C', so A_as_dep will run once before B and C.
So order would be A_plain, A_as_dep_from_B_C, B, C.

**Comment by wouterh-dev** [comment]
> Can you duplicate this with the devel version of ansible?

Yes, when installed with `pip install git+git://github.com/ansible/ansible.git@devel`

> If more than 2 roles use the dep, does it get execute more than twice?

No.

> If I understand correctly, role 'A' is a dep of Role 'B' and 'C', so A_as_dep will run once before B and C.
> So order would be A_plain, A_as_dep_from_B_C, B, C.

This seems to be the behavior I'm seeing, but it doesn't match my interpretation of the docs (or what I would expect).

What I would expect is that a role with identical inputs is only ever executed once unless otherwise specified with `allow_duplicates: yes`. Regardless of whether that role is a dependency of another role, or a dependency of the playbook.

**Comment by noplanman** [comment]
Any update on this? It is still an issue on version 2.3.

**Comment by kraduk** [comment]
not a fix per say but i always have this in my role main.yml. The advantage of this is I can stop the tasks in a role executing multiple times across plays as well as within them.

```
- include: tasks.yml
  when: " done_somerole|default(0) < 1"
  tags: somerole

- set_fact: done_somerole=1
```

**Comment by alikins** [comment]
Similar bugs:


https://github.com/ansible/ansible/issues/14582 - regression: duplicate role dependencies
https://github.com/ansible/ansible/issues/20169 - Role dependency is run multiple times
https://github.com/ansible/ansible/issues/21885 - allow_duplicates=false fails to detect duplicate when role is conditional
https://github.com/ansible/ansible/issues/31751 - Roles consisting of skipped tasks only are not deduplicated 

(roles and role deps duplication related but possibly not directly related to the same issue
https://github.com/ansible/ansible/issues/16792 - incorrect documentation for role dependencies
https://github.com/ansible/ansible/issues/17661 - role dependency doesn't work as expected
https://github.com/ansible/ansible/issues/23031 - allow_duplicates handlers broken
https://github.com/ansible/ansible/issues/23379 - Included role is erroneously skipped, when the including role depends on another role whose unrelated dependency is skipped
https://github.com/ansible/ansible/issues/23733 - include_role and meta dependencies: strange behaviour on conditionals
https://github.com/ansible/ansible/issues/25136 - include_role skips all tasks if a conditional role in the dependencies is not included due to the conditon
https://github.com/ansible/ansible/issues/25194 - Duplicate role skipped in playbook
https://github.com/ansible/ansible/issues/29052 - Wrong behavior using dynamic task included in role dependency 


(include_role related)
https://github.com/ansible/ansible/issues/24326 - include_role is duplicated via dependencies 
https://github.com/ansible/ansible/issues/31071 - include_role: role handler not found 

(related feature requests)
https://github.com/ansible/ansible/issues/16359 - Dependencies ran after role

**Comment by jmcgrath207** [comment]
Still seeing this issue in ansible 2.4.1.0

**Comment by aldanor** [comment]
Ditto, still seeing this.

**Comment by jeremycornett** [comment]
This problem is compounded for me because I introduced variables to overwrite the defaults in the dependent role. The first time the role is run, it uses the default values, then the second time it's run, it uses the variable overrides. This causes a state "loop" each time I run my ansible playbook, flip flopping from incorrect to correct every run.

**Comment by dcarrith** [comment]
This seems to happen when roles are defined in playbooks using the "newer syntax".  But, not when roles are defined in playbooks using the "classic syntax".  @alikins - Yes, when using the newer syntax, they do get run more than twice if more than two roles use the same dependency.  This is the case even when the arguments to the roles are the same.

I'm running ansible v2.4.3.0.

**Comment by dcarrith** [comment]
`- hosts: all
  tasks:
  - include_role:
      name: yum
    tags:
    - initial
    - update
    - yum
  - include_role:
      name: openssl
    tags:
    - initial
    - common
  - include_role:
      name: pcre
    tags:
    - initial
    - common
  - include_role:
      name: libssh
    tags:
    - initial
    - common
  - include_role:
      name: openssh
    tags:
    - initial
    - common
  - include_role:
      name: curl
    tags:
    - initial
    - common
`

**Comment by dcarrith** [comment]
Using the below "newer syntax" in my playbook causes openssl to get installed multiple times.
```yaml
- hosts: all
  tasks:
  - include_role:
      name: yum
    tags:
    - initial
    - update
    - yum
  - include_role:
      name: openssl
    tags:
    - initial
    - common
  - include_role:
      name: pcre
    tags:
    - initial
    - common
  - include_role:
      name: libssh
    tags:
    - initial
    - common
  - include_role:
      name: openssh
    tags:
    - initial
    - common
  - include_role:
      name: curl
    tags:
    - initial
    - common
```

**Comment by dcarrith** [comment]
However, using this classic syntax, the deduplication of dependencies works as documented (i.e. no dependencies are run more than once - i.e. openssl is only installed once):
```yaml
- hosts: all
  roles:
    - { role: yum, tags: [ initial, update, yum ] }
    - { role: openssl, tags: [ initial, common ] }
    - { role: pcre, tags: [ initial, common ] }
    - { role: libssh, tags: [ initial, common] }
    - { role: openssh, tags: [ initial, common ] }
    - { role: curl, tags: [ initial, common ] }
```

**Comment by dcarrith** [comment]
For example, openssl is a dependency for 4 of the roles:
```shell
grep -n -R "role: openssl" roles/
roles/libssh/meta/main.yml:61:  - { role: openssl, tags: [ initial, common ] }
roles/curl/meta/main.yml:61:  - { role: openssl, tags: [ initial, common ] }
roles/pcre/meta/main.yml:61:  - { role: openssl, tags: [ initial, common ] }
roles/openssh/meta/main.yml:61:  - { role: openssl, tags: [ initial, common ] }
```
So, in the [above example playbook ](https://github.com/ansible/ansible/issues/22169#issuecomment-364006604)that uses the newer syntax, openssl is installed 5 times.  But, in the [example playbook](https://github.com/ansible/ansible/issues/22169#issuecomment-364007014) that uses the classic syntax, openssl is only installed once.

**Comment by wookietreiber** [comment]
@dcarrith Your difference between "classic" and "new" syntax is not what I (we) care about, though. What I (we) *do* care about is adding roles as dependencies of other roles and having *them* not run more than once, granted their configuration stays the same.

I (we) do *not* want to define all the roles in the top-level playbooks, be it "classic" or "new" syntax, because I (we) would have to *carefully manage the dependencies by myself*, which is awfully tedious. In contrast, using role dependencies automatically takes care of the role dependencies and execution order. *That* is the issue and *that* should be fixed.

**Comment by dcarrith** [comment]
@wookietreiber - lol, I'm not sure how to respond.  Are you an Ansible developer or a user who has also encountered OPs issue and would like to see IT fixed.  My initial response was assuming the former.  But, then I realized that you might be an Ansible user.  Perhaps I should file a new bug report against 2.4.3.0 since it is specific to using new syntax.  And, OPs issue doesn't seem to be an issue in 2.4.3.0 as long as parameters to the roles are the same.

**Comment by wookietreiber** [comment]
@dcarrith I'm an Ansible user who loves to use role dependencies and who is annoyed that these are executed more than once. Admittedly, my previous comment was a bit narcissistic and provocative, and I apologize for that. I guess, the problems we are reporting here in this issue are all (more or less) different symptoms of the same problem. I don't know, if it is worth reporting them as separate issues. I guess, the Ansible team knows by now, what the root cause is and can fix it.

**Comment by jmauntel** [comment]
@dcarrith I'd like to echo what @wookietreiber is saying.  We have a very modular library of roles for our infrastructure, each defining its own dependencies.  When our systems are built, many of these roles get executed several times, which doubles, and sometimes triples the build time.

I don't think this is how it was intended to work, and I'm hoping a fix in in progress.  I REALLY don't want to have to resort to some of the workarounds that I've seen, but our teams are started to take issue with the extra time it's taking to complete builds.

**Comment by dchsueh** [comment]
The [first comment](https://github.com/ansible/ansible/issues/22169#issuecomment-284537676)'s cited page is no longer available, and the quote only discusses dependency roles.

The doc page is https://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html now, and now says:

[Role Duplication and Execution](https://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html#role-duplication-and-execution):
> Ansible will only allow a role to execute once, even if defined multiple times, if the parameters defined on the role are not different for each definition.

[Role Dependencies](https://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html#role-dependencies) 
> Role dependencies are always executed before the role that includes them, and may be recursive. Dependencies also follow the duplication rules specified above. If another role also lists it as a dependency, it will not be run again based on the same rules given above.

(The "above" didn't make a distinction between direct and dependency roles.)

I interpret this as same-parameter roles execute once, regardless of direct or dependency status.

--
edit: links seem to have changed between writing and submission!  links updated

**Comment by sivel** [comment]
This issue was resolved in 0d35a69f0eea191f423ba6b0120ffffcbd6d9ed1 and included in the v2.5.0 release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by kay73** [comment]
Issue is still present. *b* and *c* inherit *a*, which gets executed twice.

```ansible --version```
```ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/kay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 13:05:56) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

```
=============> ./b.yml
---
- hosts: b
  gather_facts: no
  roles:
    - b

=============> ./c.yml
---
- hosts: c
  gather_facts: no
  roles:
    - c

=============> ./hosts.yml
---
all:
  hosts:
    this-machine:
      ansible_host: localhost
      ansible_connection: local
      ansible_become: false
  children:
    b:
      hosts:
        this-machine:
    c:
      hosts:
        this-machine:

=============> ./roles/a/tasks/main.yml
---
- name: a
  shell: 'echo a'

=============> ./roles/b/meta/main.yml
---
dependencies:
  -  name: a

=============> ./roles/b/tasks/main.yml
---
- name: b
  shell: 'echo b'

=============> ./roles/c/meta/main.yml
---
dependencies:
  - name: a

=============> ./roles/c/tasks/main.yml
---
- name: c
  shell: 'echo c'

=============> ./site.yml
---
- import_playbook: b.yml
- import_playbook: c.yml
```

```ansible-playbook -i hosts.yml site.yml -v```
```
Using /etc/ansible/ansible.cfg as config file

PLAY [b] ************************************************************************************

TASK [a : a] ********************************************************************************
changed: [this-machine] => {"changed": true, "cmd": "echo a", "delta": "0:00:00.010331", "end": "2018-09-04 15:40:31.165658", "rc": 0, "start": "2018-09-04 15:40:31.155327", "stderr": "", "stderr_lines": [], "stdout": "a", "stdout_lines": ["a"]}

TASK [b : b] ********************************************************************************
changed: [this-machine] => {"changed": true, "cmd": "echo b", "delta": "0:00:00.011439", "end": "2018-09-04 15:40:31.514000", "rc": 0, "start": "2018-09-04 15:40:31.502561", "stderr": "", "stderr_lines": [], "stdout": "b", "stdout_lines": ["b"]}

PLAY [c] ************************************************************************************

TASK [a : a] ********************************************************************************
changed: [this-machine] => {"changed": true, "cmd": "echo a", "delta": "0:00:00.010189", "end": "2018-09-04 15:40:31.862526", "rc": 0, "start": "2018-09-04 15:40:31.852337", "stderr": "", "stderr_lines": [], "stdout": "a", "stdout_lines": ["a"]}

TASK [c : c] ********************************************************************************
changed: [this-machine] => {"changed": true, "cmd": "echo c", "delta": "0:00:00.010639", "end": "2018-09-04 15:40:32.203709", "rc": 0, "start": "2018-09-04 15:40:32.193070", "stderr": "", "stderr_lines": [], "stdout": "c", "stdout_lines": ["c"]}

PLAY RECAP **********************************************************************************
this-machine               : ok=4    changed=4    unreachable=0    failed=0
```

**Comment by kay73** [comment]
Hello @sivel, unfortunately this issue is still present in Ansible 2.6.3. I have found no mention that it is addressed or fixed in Ansible 2.6.4. This issue is causing significant trouble for my company. Please also see my previous comment.

**Comment by tdmdema** [comment]
@sivel , same issue here. Reopen the issue/bug, or we have to open a new one

**Comment by benohara** [comment]
I see this in 2.6.5

**Comment by ghost** [comment]
We workaround this:

### Dependencies

Every role must set a fact at the end of its execution, this way we can handle dependencies in other roles.

Set `{{ role_name }}_was_executed` at the end of main file:

```yaml
- name: "Define role executed var {{ role_name }}_was_executed"
  set_fact:
    "{{ role_name }}_was_executed": true
    cacheable: true
```

Declare dependencies at `meta` directory inside the other role:

```yaml
---

dependencies:
  - role: common
    when: set_role_was_executed is not defined
```

**Comment by ghost** [comment]
It would be nice that Ansible manages this transparently.

**Comment by kay73** [comment]
Issue also present in 2.7.0. A fix would be highly appreciated. @sivel

**Comment by belidzs** [comment]
> - name: "Define role executed var {{ role_name }}_was_executed" set_fact: "{{ role_name }}_was_executed": true cacheable: true

This is unfortunately not perfect as it stops handlers from running

**Comment by AgilDat** [comment]
@belidzs, What handlers do you say? I mean, I don't miss any task since we use that workaround.

**Comment by ghost** [comment]
Yes, totally correct, we must add `meta: flush_handlers` at the end of the role.

**Comment by kay73** [comment]
> > * name: "Define role executed var {{ role_name }}_was_executed" set_fact: "{{ role_name }}_was_executed": true cacheable: true
> 
> This is unfortunately not perfect as it stops handlers from running

IMHO it is far from perfect because it does not take into account if parameters differ along redundant assignments. 

This whole workaround is a no-go for my company because it would introduce even more complexity into our playbook suite and would be a net of tripwires for all colleagues, who do not know about this workaround.

**Comment by juanvalino** [comment]
I'm also impacted by this bug.  Any progress with this? 

Without a solution the ansible output is very confusing because of the dupplicated role execution.

**Comment by Lonni93** [comment]
Yep, +1 here... very frustrating seeing same roles executed multiple times.

w8 4 any progress on this bug.

**Comment by eastwoo** [comment]
this issue also exists in ansible --version
ansible 2.7.1

**Comment by synek317** [comment]
affects 2.6.4 as well.
Very frustrating, lots of time invested in creating roles and playbooks and now it just doesn't work as expected.

**Comment by brydoncheyney** [comment]
issue still exists in ansible 2.7.2

**Comment by kay73** [comment]
...and in 2.7.4

**Comment by BarbzYHOOL** [comment]
and in 2.7.5, who the hell closed this???

**Comment by bcoca** [comment]
FYI, we don't normally see comments in closed issues, the one detailed here was fixed as the output below shows:

```
PLAY [localhost] *********************************************************************************************************************************

TASK [a : debug] *********************************************************************************************************************************
ok: [localhost] => {
    "msg": "A"
}

TASK [b : debug] *********************************************************************************************************************************
ok: [localhost] => {
    "msg": "B"
}

TASK [c : debug] *********************************************************************************************************************************
ok: [localhost] => {
    "msg": "C"
}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0
```
Since i can test the issue continues to be solved, this ticket will remain closed.

If you have a similar issue please open a new bug with a reproducer we can test against, adding comments without a reproducer in this ticket does not help you nor us solve this issue, which is why I'm going to lock further comments. 

@kay73 your case is different than original, as deduplication is PER PLAY and not PER RUN so your example shows that difference, the original bug the duplicate was executing in the same play.

@dcarrith include_role is exempt from duplicate matching (dependencies are not, but direct use is).
