### ISSUE TITLE
make deb fails - *** ERROR: CORE MODULE MISSING DOCUMENTATION: rabbitmq_parameter ***

### ISSUE THREAD

**Issue by l0neranger** [ansible/ansible#2265]
The debian packaging does not succeed for the latest pull from dev branch - git SHA: 7ac5e462efbc850dd39ce5746accf3012530ed98

Looks like the missing documentation for the rabbitmq_parameter core plugin does not let the package creation to proceed? make docs fails. Should lack of documentation break the actual package build? I could see both sides of the argument.

Output here:

$ make deb
Cleaning up distutils stuff
rm -rf build
rm -rf dist
Cleaning up byte compiled python stuff
find . -type f -regex "._.py[co]$" -delete
Cleaning up editor backup files
find . -type f ( -name "_~" -or -name "#_" ) -delete
find . -type f ( -name "_.swp" ) -delete
Cleaning up manpage stuff
find ./docs/man -type f -name "_.xml" -delete
find ./docs/man -type f -name "_.asciidoc" -delete
find ./docs/man/man3 -type f -name "_.3" -delete
Cleaning up output from test runs
rm -rf test/test_data
Cleaning up RPM building stuff
rm -rf MANIFEST rpm-build
Cleaning up Debian building stuff
rm -rf debian
rm -rf deb-build
rm -rf docs/json
rm -rf docs/js
PYTHONPATH=./lib hacking/module_formatter.py -A 1.1 -t man -o docs/man/man3/ --module-dir=library --template-dir=hacking/templates
 processing module source ---> library/add_host
 processing module source ---> library/apt
 processing module source ---> library/apt_key
 processing module source ---> library/apt_repository
 processing module source ---> library/assemble
 processing module source ---> library/async_status
 processing module source ---> library/async_wrapper
 processing module source ---> library/authorized_key
 processing module source ---> library/cloudformation
 processing module source ---> library/command
 processing module source ---> library/copy
 processing module source ---> library/cron
 processing module source ---> library/debug
 processing module source ---> library/django_manage
 processing module source ---> library/easy_install
 processing module source ---> library/ec2
 processing module source ---> library/ec2_facts
 processing module source ---> library/ec2_vol
 processing module source ---> library/facter
 processing module source ---> library/fail
 processing module source ---> library/fetch
 processing module source ---> library/file
 processing module source ---> library/fireball
 processing module source ---> library/gem
 processing module source ---> library/get_url
 processing module source ---> library/git
 processing module source ---> library/group
 processing module source ---> library/group_by
 processing module source ---> library/hg
 processing module source ---> library/ini_file
 processing module source ---> library/lineinfile
 processing module source ---> library/lvol
 processing module source ---> library/macports
 processing module source ---> library/mail
 processing module source ---> library/mongodb_user
 processing module source ---> library/mount
 processing module source ---> library/mysql_db
 processing module source ---> library/mysql_user
 processing module source ---> library/nagios
 processing module source ---> library/ohai
 processing module source ---> library/opkg
 processing module source ---> library/pacman
 processing module source ---> library/pause
 processing module source ---> library/ping
 processing module source ---> library/pip
 processing module source ---> library/pkgin
 processing module source ---> library/postgresql_db
 processing module source ---> library/postgresql_user
 processing module source ---> library/rabbitmq_parameter
*_\* ERROR: CORE MODULE MISSING DOCUMENTATION: rabbitmq_parameter ***
 processing module source ---> library/rabbitmq_plugin
 processing module source ---> library/rabbitmq_user
 processing module source ---> library/rabbitmq_vhost
 processing module source ---> library/raw
 processing module source ---> library/script
 processing module source ---> library/seboolean
 processing module source ---> library/selinux
 processing module source ---> library/service
 processing module source ---> library/setup
 processing module source ---> library/shell
 processing module source ---> library/slurp
 processing module source ---> library/subversion
 processing module source ---> library/supervisorctl
 processing module source ---> library/svr4pkg
 processing module source ---> library/sysctl
 processing module source ---> library/template
 processing module source ---> library/uri
 processing module source ---> library/user
 processing module source ---> library/virt
 processing module source ---> library/wait_for
 processing module source ---> library/yum
 processing module source ---> library/zfs
(cd docsite; make docs)
make[1]: Entering directory `/opt/ansible/docsite'
rm -f .buildinfo
rm -f *.inv
rm -rf *.doctrees
Cleaning up byte compiled python stuff
find . -regex ".*\.py[co]$" -delete
Cleaning up editor backup files
find . -type f \( -name "*~" -or -name "#*" \) -delete
find . -type f \( -name "*.swp" \) -delete
../hacking/module_formatter.py -t rst --template-dir=../hacking/templates --module-dir=../library -o rst/modules/ --includes-file=rst/modules/_list.rst
 processing module source ---> ../library/add_host
Traceback (most recent call last):
  File "../hacking/module_formatter.py", line 347, in <module>
    main()
  File "../hacking/module_formatter.py", line 299, in main
    doc, examples = ansible.utils.module_docs.get_docstring(fname, verbose=options.verbose)
ValueError: too many values to unpack
make[1]: *** [modules] Error 1
make[1]: Leaving directory`/opt/ansible/docsite'
make: **\* [webdocs] Error 2

**Comment by mpdehaan** [comment]
I'll investigate the doc error shortly, but because this is used to make the manpages, it should in fact effect the build.

**Comment by l0neranger** [comment]
Thought that was the reason. Thanks Michael!

I was trying to build a fresh deb to resolve this: https://github.com/ansible/ansible/issues/2165 which I ran into today. Surprisingly though the bug referenced does not seem to happen if I call the module from a playbook. Only when I run it from the command-line using ansible <host> -m cron

**Comment by mpdehaan** [comment]
Hmm, perhaps a case of what server you ran it on, maybe, I just pushed a
fix for the docs, thanks for the heads up!

**Comment by mpdehaan** [comment]
fixed in 4132f8953e3a2e56a601e78aff889e52ba471f75

**Comment by l0neranger** [comment]
make deb still fails with the latest output. I'm doing some debugging if I can find out why.

$ make deb
Cleaning up distutils stuff
rm -rf build
rm -rf dist
Cleaning up byte compiled python stuff
find . -type f -regex "._.py[co]$" -delete
Cleaning up editor backup files
find . -type f ( -name "_~" -or -name "#_" ) -delete
find . -type f ( -name "_.swp" ) -delete
Cleaning up manpage stuff
find ./docs/man -type f -name "_.xml" -delete
find ./docs/man -type f -name "_.asciidoc" -delete
find ./docs/man/man3 -type f -name "_.3" -delete
Cleaning up output from test runs
rm -rf test/test_data
Cleaning up RPM building stuff
rm -rf MANIFEST rpm-build
Cleaning up Debian building stuff
rm -rf debian
rm -rf deb-build
rm -rf docs/json
rm -rf docs/js
PYTHONPATH=./lib hacking/module_formatter.py -A 1.1 -t man -o docs/man/man3/ --module-dir=library --template-dir=hacking/templates
 processing module source ---> library/add_host
 processing module source ---> library/apt
 processing module source ---> library/apt_key
 processing module source ---> library/apt_repository
 processing module source ---> library/assemble
 processing module source ---> library/async_status
 processing module source ---> library/async_wrapper
 processing module source ---> library/authorized_key
 processing module source ---> library/cloudformation
 processing module source ---> library/command
 processing module source ---> library/copy
 processing module source ---> library/cron
 processing module source ---> library/debug
 processing module source ---> library/django_manage
 processing module source ---> library/easy_install
 processing module source ---> library/ec2
 processing module source ---> library/ec2_facts
 processing module source ---> library/ec2_vol
 processing module source ---> library/facter
 processing module source ---> library/fail
 processing module source ---> library/fetch
 processing module source ---> library/file
 processing module source ---> library/fireball
 processing module source ---> library/gem
 processing module source ---> library/get_url
 processing module source ---> library/git
 processing module source ---> library/group
 processing module source ---> library/group_by
 processing module source ---> library/hg
 processing module source ---> library/ini_file
 processing module source ---> library/lineinfile
 processing module source ---> library/lvol
 processing module source ---> library/macports
 processing module source ---> library/mail
 processing module source ---> library/mongodb_user
 processing module source ---> library/mount
 processing module source ---> library/mysql_db
 processing module source ---> library/mysql_user
 processing module source ---> library/nagios
 processing module source ---> library/ohai
 processing module source ---> library/opkg
 processing module source ---> library/pacman
 processing module source ---> library/pause
 processing module source ---> library/ping
 processing module source ---> library/pip
 processing module source ---> library/pkgin
 processing module source ---> library/postgresql_db
 processing module source ---> library/postgresql_user
 processing module source ---> library/rabbitmq_parameter
 processing module source ---> library/rabbitmq_plugin
 processing module source ---> library/rabbitmq_user
 processing module source ---> library/rabbitmq_vhost
 processing module source ---> library/raw
 processing module source ---> library/script
 processing module source ---> library/seboolean
 processing module source ---> library/selinux
 processing module source ---> library/service
 processing module source ---> library/setup
 processing module source ---> library/shell
 processing module source ---> library/slurp
 processing module source ---> library/subversion
 processing module source ---> library/supervisorctl
 processing module source ---> library/svr4pkg
 processing module source ---> library/sysctl
 processing module source ---> library/template
 processing module source ---> library/uri
 processing module source ---> library/user
 processing module source ---> library/virt
 processing module source ---> library/wait_for
 processing module source ---> library/yum
 processing module source ---> library/zfs
(cd docsite; make docs)
make[1]: Entering directory `/opt/ansible/docsite'
rm -f .buildinfo
rm -f *.inv
rm -rf *.doctrees
Cleaning up byte compiled python stuff
find . -regex "._.py[co]$" -delete
Cleaning up editor backup files
find . -type f ( -name "_~" -or -name "#_" ) -delete
find . -type f ( -name "_.swp" ) -delete
../hacking/module_formatter.py -t rst --template-dir=../hacking/templates --module-dir=../library -o rst/modules/ --includes-file=rst/modules/_list.rst
 processing module source ---> ../library/add_host
Traceback (most recent call last):
  File "../hacking/module_formatter.py", line 347, in <module>
    main()
  File "../hacking/module_formatter.py", line 299, in main
    doc, examples = ansible.utils.module_docs.get_docstring(fname, verbose=options.verbose)
ValueError: too many values to unpack
make[1]: *_\* [modules] Error 1
make[1]: Leaving directory `/opt/ansible/docsite'
make: **\* [webdocs] Error 2

**Comment by mpdehaan** [comment]
thanks, I'm alternating between platforms lately.

make rpm seems to be good
