### ISSUE TITLE
copy and template modules do not expand vars in dest argument

### ISSUE THREAD

**Issue by sfllaw** [ansible/ansible#2324]
Issue #2310 was closed but I've tested the latest commit ca16a91da1 and it's still broken. I can only assume it was closed by accident. :smiley: 
## Reproduction steps

Here is a sample playbook that fails:

``` yaml
# playbook.yaml

---
- hosts: all
  tasks:
    - action: template
      args:
        src: template.txt
        dest: ${filename}
        mode: ${filemode}
```

The `$filename` and `$filemode` variables are defined in an inventory:

``` ini
# inventory.ini
[all]
photon

[all:vars]
filename = hello.txt
filemode = 0700
```

For reference, the `template.txt` file is unimportant but contains:

```
Hello world!
```
## Expected result

Copies (and does Jinja2 expansion) on `template.txt` and uploads it to the value in `$filename`.
## Bug

```
$ ansible-playbook -i inventory.ini playbook.yaml -vvv

PLAY [all] ********************* 

GATHERING FACTS ********************* 
<photon> ESTABLISH CONNECTION FOR USER: sfllaw on PORT 22 TO photon
<photon> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1362623892.65-215548586877575 && chmod a+rx $HOME/.ansible/tmp/ansible-1362623892.65-215548586877575 && echo $HOME/.ansible/tmp/ansible-1362623892.65-215548586877575'
<photon> REMOTE_MODULE setup 
<photon> PUT /tmp/tmpJIITPj TO /home/sfllaw/.ansible/tmp/ansible-1362623892.65-215548586877575/setup
<photon> EXEC /bin/sh -c ' /usr/bin/python /home/sfllaw/.ansible/tmp/ansible-1362623892.65-215548586877575/setup; rm -rf /home/sfllaw/.ansible/tmp/ansible-1362623892.65-215548586877575/ >/dev/null 2>&1'
ok: [photon]

TASK: [template] ********************* 
<photon> ESTABLISH CONNECTION FOR USER: sfllaw on PORT 22 TO photon
<photon> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1362623894.07-206170587973740 && chmod a+rx $HOME/.ansible/tmp/ansible-1362623894.07-206170587973740 && echo $HOME/.ansible/tmp/ansible-1362623894.07-206170587973740'
<photon> EXEC /bin/sh -c 'rc=0; [ -r "${filename}" ] || rc=2; [ -f "${filename}" ] || rc=1; [ -d "${filename}" ] && rc=3; (/usr/bin/md5sum ${filename} 2>/dev/null) || (/sbin/md5sum -q ${filename} 2>/dev/null) || (/usr/bin/digest -a md5 ${filename} 2>/dev/null) || (/sbin/md5 -q ${filename} 2>/dev/null) || (/usr/bin/md5 -n ${filename} 2>/dev/null) || (/bin/md5 -q ${filename} 2>/dev/null) || (echo "${rc}  ${filename}")'
```

As you can see, the template module is not interpolating the variables. The `EXEC /bin/sh -c '[ -r "${filename}" ]' is a dead giveaway, because expansion usually happens before that.

I believe this may be because the interpolation isn't being done by the virtual module and the action plugin on the other side can't do the interpolation.

**NOTE:** This also applies to the copy module, which appears to have the same behaviour.

**Comment by mpdehaan** [comment]
Ok, so with the previous ticket closed, it would be better to comment on that ticket rather than reopening a new bug.   

That all being said, using the one line form was working completely fine for me.

I see your problem when you switch to the "args:" method of expressing things, and only then.

**Comment by mpdehaan** [comment]
Fix pushed in fe8547c ... let me know if this works for you.

Thanks!

**Comment by sfllaw** [comment]
You're right, the one-line mode works.

However, this is still broken with `dest: ${filename}` and `dest: $filename`:

```
TASK: [copy] ********************* 
<photon> ESTABLISH CONNECTION FOR USER: sfllaw on PORT 22 TO photon
<photon> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1362632995.3-217716421418057 && chmod a+rx $HOME/.ansible/tmp/ansible-1362632995.3-217716421418057 && echo $HOME/.ansible/tmp/ansible-1362632995.3-217716421418057'
<photon> EXEC /bin/sh -c 'rc=0; [ -r "${filename}" ] || rc=2; [ -f "${filename}" ] || rc=1; [ -d "${filename}" ] && rc=3; (/usr/bin/md5sum ${filename} 2>/dev/null) || (/sbin/md5sum -q ${filename} 2>/dev/null) || (/usr/bin/digest -a md5 ${filename} 2>/dev/null) || (/sbin/md5 -q ${filename} 2>/dev/null) || (/usr/bin/md5 -n ${filename} 2>/dev/null) || (/bin/md5 -q ${filename} 2>/dev/null) || (echo "${rc}  ${filename}")'
```

**Comment by mpdehaan** [comment]
Have you tried the above referenced commit?

This fixed the problem for me.

**Comment by sfllaw** [comment]
@mpdehaan — Ah yes, my response left out the fact that it works for template, but not for **copy**, which uses a similar mechanism.

**Comment by mpdehaan** [comment]
Ok, I'm a little confused.   Copy doesn't work for complex args now, with
that very latest commit, or at all?

**Comment by mpdehaan** [comment]
ok, I see what needs to be done to copy now.

**Comment by sfllaw** [comment]
Sorry, I'm being unclear.

Copy doesn't work for complex args. You'll want to do the same thing for `copy.py` as you did for `template.py`:

``` diff
 lib/ansible/runner/action_plugins/copy.py |    3 +++
 1 file changed, 3 insertions(+)

diff --git a/lib/ansible/runner/action_plugins/copy.py b/lib/ansible/runner/acti
index 60e29ff..f6a2293 100644
--- a/lib/ansible/runner/action_plugins/copy.py
+++ b/lib/ansible/runner/action_plugins/copy.py
@@ -36,6 +36,9 @@ class ActionModule(object):
         if complex_args:
             options.update(complex_args)
         options.update(utils.parse_kv(module_args))
+        options = utils.template(self.runner.basedir, options, inject)
+        module_args = self.runner._complex_args_hack(options, '')
+
         source  = options.get('src', None)
         dest    = options.get('dest', None)
```

**Comment by mpdehaan** [comment]
Right, that's what I was referring to in the previous comment.   Done!

**Comment by mpdehaan** [comment]
ok see ffbd4b5

**Comment by sfllaw** [comment]
Looks good now! Thanks a lot and I hope you feel better soon.

**Comment by mpdehaan** [comment]
Oh I'm good :)

Sorry we didn't catch this one earlier.   Thanks for bearing with us and my
confusion with the earlier report!
