### ISSUE TITLE
Folder named '$HOME' created when Ansible invoked by cloud-init

### ISSUE THREAD

**Issue by greggilbert** [ansible/ansible#23665]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Core

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
# ansible.cfg
[defaults]
log_path = /var/log/ansible.log
host_key_checking = False
```

##### OS / ENVIRONMENT
```
Python 2.7.12
```

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

##### SUMMARY

When invoking a playbook from cloud-init, a folder named `$HOME` gets created.

##### STEPS TO REPRODUCE

This is my cloud-init:
```
#!/bin/bash
source /etc/environment
doit() {
  aws s3 cp s3://dev.tar.gz /tmp/s3-push.tar.gz
  mkdir -p /app/deploy
  tar -C /app/deploy -zxvf /tmp/s3-push.tar.gz
  cd /app/deploy
  ansible-playbook -i "localhost," -c local -e "first_run=true" master.yml
}
doit
```

```
# master.yml
  - hosts: all
    remote_user: ubuntu
    become: yes
    become_user: root

    tasks:

      - name: Start splash.service
        systemd: state=restarted name=splash daemon_reload=yes
```

Start an instance with that configuration and I end up with a folder in `/app/deploy` called `$HOME`. The only thing in the folder is `.ansible/tmp`.

##### EXPECTED RESULTS

Not to have a folder named `$HOME`.

##### ACTUAL RESULTS

There is a `$HOME` folder in `/app/deploy`, in other words `/app/deploy/$HOME`.

This is pretty closely related to #16032, but I'm not sure why that ticket was closed. The merge there doesn't seem to have made a difference for 2.2.0.

**Comment by sivel** [comment]
This should be resolved in ansible v2.3.0.  Can you confirm by upgrading the ansible v2.3.0?

**Comment by greggilbert** [comment]
I actually can't; I'm blocked on the upgrade to 2.3.0 by #21562.

**Comment by greggilbert** [comment]
So I managed to get Ansible 2.3 on a new instance and I can confirm that it does fix the `$HOME` thing as you mentioned; I am, however, still unable to upgrade to 2.3 across the board due to the issue I linked.

**Comment by sivel** [comment]
In the meantime, you should be able to update your `ansible.cfg` file, to include:

```
[defaults]
remote_tmp     = ~/.ansible/tmp
local_tmp      = ~/.ansible/tmp
```

The fix is also in the `stable-2.2` branch, but not yet in any v2.2 release.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
