### ISSUE TITLE
gather_timeout from ansible.cfg is ignored when running a playbook.

### ISSUE THREAD

**Issue by i1caro** [ansible/ansible#23753]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Timeout Module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/maximus/work/server-recipes/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Apr  2 2015, 15:33:21) [GCC 4.9.2]
```

##### CONFIGURATION
```
[defaults]
hostfile = hosts
remote_user = root
private_key_file = ~/.ssh/myne
host_key_checking = False
force_handlers = True
forks = 50
inventory = inventory
timeout = 10
gather_timeout = 300
```
##### OS / ENVIRONMENT
Ubuntu 15

##### SUMMARY
The variable `gather_timeout` is being ignored. This changed from Ansible 2.2 to 2.3 since after the upgrade some servers started to timeout. In order to debug I changed the ansible code to spit the following line by. Changing facts to.

```
GATHER_TIMEOUT=None

class TimeoutError(Exception):
    pass

def timeout(seconds=None, error_message="Timer expired"):
    if seconds is None:
        seconds = globals().get('GATHER_TIMEOUT') or 10
    def decorator(func):
        def _handle_timeout(signum, frame):
            raise TimeoutError(
                error_message +
                ' global timer %s, seconds %s' % (
                    globals().get('GATHER_TIMEOUT'),
                    seconds
                )
            )
```

Output:
```
fatal: [server.something.com]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "failed": true, "msg": "Timer expired global timer 300, seconds 10", "rc": 257}
```
This means that on the instantiation of the decorator `globals().get('GATHER_TIMEOUT')` is either `None` or `10`. On a brief look I would say `None` and then it's changed to the configuration value. I would say here:

```
def get_all_facts(module):

    setup_options = dict(module_setup=True)

    # Retrieve module parameters
    gather_subset = module.params['gather_subset']

    global GATHER_TIMEOUT
    GATHER_TIMEOUT = module.params['gather_timeout']
```
Which at this point is to late since the decorator was timeout was already set to 10.

##### STEPS TO REPRODUCE
Set `gather_timeout` in ansible.cfg 

##### EXPECTED RESULTS
Expect timeout to match `gather_timeout` value.

##### ACTUAL RESULTS
Timeout is always 10.

**Comment by snowsky** [comment]
Looks like the function get_mount_facts timed out.

**Comment by snowsky** [comment]
Or probably it failed to run lsblk command. Could you run this command manually on the host?
```
/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2
```

**Comment by snowsky** [comment]
It is a bug. The root cause is the variable from ansible.cfg didn't take effect, but the variable from command can:
```
bin/ansible localhost -m setup -a "gather_timeout=20"
```

**Comment by snowsky** [comment]
Dup https://github.com/ansible/ansible/issues/17316

**Comment by abadger** [comment]
I believe @i1caro 's initial analysis is correct and this is a new bug.  Looking for a fix now.

**Comment by abadger** [comment]
@i1caro Please give https://github.com/ansible/ansible/pull/23826 a try.  I think I fixed the issue and added a unittest that should cover your case to keep it from regressing.

**Comment by oorabona** [comment]
Hello,

I tried with
```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
And `/etc/ansible/ansible.cfg` as below : 
```
# cat /etc/ansible/ansible.cfg
[defaults]
gather_timeout=20
```

I still reproduce this error. So it appears that `gather_timeout=20` in `/etc/ansible/ansible.cfg` seems not be taken into account, the 10s timeouts remains and the only working fix is by calling `ansible` with `-a "gather_timeout=20"`.

Any ideas ?
