### ISSUE TITLE
pywinrm fails to authenticate from centos 7 host to windows 2012 R2 client

### ISSUE THREAD

**Issue by mmercer-apixio** [ansible/ansible#23843]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
winrm

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/mmercer/projects/packer/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION
Nothing specific.

##### OS / ENVIRONMENT
```
Ansible Host: CentOS Linux release 7.3.1611 (Core)
Windows Client: Windows Server 2012 R2 configured via ansible remoting ps1 + CredSSP flag

Pip Information:
ansible (2.3.0.0)
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.42)
pywinrm (0.2.2)
requests-credssp (0.0.2)
```

##### SUMMARY
CredSSP authentication from CentOS7 to Windows Server 2012 R2 fails authentication with TLS error

##### STEPS TO REPRODUCE
Install clean CentOS 7 machine
Install clean Windows S2012R2 machine

Ansible Host:  pip install above packages
Windows Host:  Execute AnsibleRemoting.ps1 -EnableCredSSP

Configure ansible to use winrm + credssp, also set ignorecert in config

Test:
```
ansible -i inventoryfile all -m win_ping
```

##### EXPECTED RESULTS
It works.

##### ACTUAL RESULTS
```
10.99.3.164 | UNREACHABLE! => {
    "changed": false, 
    "msg": "credssp: 'module' object has no attribute 'TLSv1_2_METHOD'", 
    "unreachable": true
}
```

**Comment by rpathak-ains** [comment]
I am having the same issue with Windows 2k8 R2 as well as Windows 2k12 R2 server.  Any updates on this issue?

**Comment by darioems** [comment]
Hello,

In my environment, the problem was pyOpenSSL. When updating pyOpenSSL to a new version using pip, some olders files were left in the directory.

I removed the package via pip uninstall, removed the directory in /usr/lib[64]/python2.7/site-packages/OpenSSL/ and then reinstalled pyopenssl.

Dário Estevão

**Comment by jhawkesworth** [comment]
I think its likely this is caused by mixing platform libraries with ones from pip.
I run winrm (although not credssp) on EL 7 boxes but pick up as many dependencies from pip, rather than yum.

**Comment by dagwieers** [comment]
Yes, I can confirm that this is related to the OS pyOpenSSL package (that is required by rhnlib for one). This is going to be a deal-breaker for using winrm with credssp on RHEL7 in Enterprise environments :-(

**Comment by ghost** [comment]
Had the same issue. Fixed by uninstalling pyOpenSSL completely (cleaning folders like @darioems suggested), then instead of installing pyOpenSSL itself I did `pip install pywinrm pywinrm[credssp] requests-credssp` and it installed pyOpenSSL as well.

Now I have different error: "credssp: the specified credentials were rejected by the server" >_< 
Fixed here, broken there :rofl:

**Comment by jborean93** [comment]
@0-d that sounds like an authentication issue and hopefully not something wrong with the library, are you able to share details of your environment by running on the Windows box

```
winrm get winrm/config/service
winrm e winrm/config/Listener
```

Are you also able to share your host vars. Are you trying to connect with a domain or local account?

**Comment by ghost** [comment]
@jborean93 thanks for your reply! Already fixed it. HTTPS listener was not present on the Windows machine and I was trying to connect to 5985 port instead of 5986.
Created listener and now it works.
Also I edited my comment: added `requests-credssp` as a required package for pywinrm to work.

**Comment by dagwieers** [comment]
@0-d What could we improve in the documentation so that you would not have had this (second) issue, or would have fixed it yourself ? Since you have the experience of being in that situation (and it is still fresh in memory) you could probably make the right fixes to ensure others have an easier time with this.

**Comment by ghost** [comment]
@dagwieers In my opinion first of all in your [Windows Support article](http://docs.ansible.com/ansible/latest/intro_windows.html) you should move "Windows System Prep" section to the top. That's the essential thing for ansible to work with windows. And to this section you should add specific requirements for the windows side to support ansible connections:

- (only if you plan to use basic auth) Enable basic auth in WinRM `winrm set winrm/config/client/auth @{Basic="true"}`.
- One of the following:
  - Enable unencrypted auth on port 5985: `winrm set winrm/config/service @{AllowUnencrypted="true"}` and use 5985 port in ansible config.
  - Create HTTPS listener on port 5986 with firewall rule and etc and use 5986 in ansible.

I mean there should be specific requirements for what is needed to be done and why. Not only the script that automates it.

**Comment by dagwieers** [comment]
@0-d Can you make the required changes as a PR to the documentation ? You don't need any prior knowledge of Git, as you can edit the documentation directly in Github to make a pull-request. This way we have context to your changes, and can discuss each individually as a team.

In itself I agree with what you are saying, but I'd like others to chime in and make suggestions to improve it even further.

**Comment by ghost** [comment]
@dagwieers will try to find some time on this week. Forked ansible and created a task in my outlook for that :rofl:

**Comment by jborean93** [comment]
Closing issue as it has been solved by re-installing pyOpenSSL due to conflicts between the built in version and what is installed by pip.

**Comment by techduderavi** [comment]
This issue is still present. Tried uninstalling/cleaning folders and re-installing as suggested by @darioems , but it's still not working. Not an issue with listeners though, choosing ntlm works fine on port 5985 and 5986.

Any help would be appreciated.

**Comment by jhawkesworth** [comment]
@rtk88 - closed tickets aren't often monitored, I saw this one by chance, it is best to open a new issue with full details.

Assuming you are seeing 
 "msg": "credssp: 'module' object has no attribute 'TLSv1_2_METHOD'", 
I suggest checking what pyOpenSSL version you have, and also ensuring the targets you are managing can support TLS 1.2 - as the documentation says here: http://docs.ansible.com/ansible/latest/intro_windows.html#credssp

" 
CredSSP and TLS 1.2

CredSSP requires the remote host to have TLS 1.2 configured or else the connection will fail. TLS 1.2 is installed by default from Server 2012 and Windows 8 onwards. For Server 2008, 2008 R2 and Windows 7 you can add TLS 1.2 support by:

    Installing the TLS 1.2 update from Microsoft
    Adding the TLS 1.2 registry keys as shown on this page

"

**Comment by ravi-pmp** [comment]
Hi guys, 

I had the same error. Realized that ansible tower bundle (ansible-tower-setup-bundle-3.2.3-1.el7) comes built in with ansible 2.4x engine. Once i upgrade the ansible to 2.5, remove pyopenssl, remove files from site-packages as suggested by darioems, and reinstall pyopenssl, all goes well. I didnt have to touch the winrm[credssp] package (i had installed it before the upgrade to ansible 2.5). My ansible host file looks as under:

[windows]
x.x.x.x
[windows:vars]
ansible_user= administrator
ansible_password = xxxxxxx
ansible_connection = winrm
ansible_winrm_transport = credssp
ansible_winrm_server_cert_validation = ignore

I run the following command to check:

ansible windows -m win_ping

I get the following reply:

x.x.x.x | SUCCESS => {
    "changed": false, 
    "ping": "pong"
