### ISSUE TITLE
SSH connection sharing is broken

### ISSUE THREAD

**Issue by cadavre** [ansible/ansible#26359]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
SSH connection plugin

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
Default configuration.

##### OS / ENVIRONMENT
Ubuntu 14.04.5
Kernel 3.13.0-83-generic
Ansible installed via pip

##### SUMMARY
Looks like SSH connection sharing is broken. I have one single server defined in inventory twice – with the same hostname, but different alias.

##### STEPS TO REPRODUCE
1. Any playbook.
2. Inventory like:
```
server.io-8721 ansible_host=server.io
server.io-d4f2 ansible_host=server.io
```

##### EXPECTED RESULTS
Setup task success.

##### ACTUAL RESULTS
On `setup` task I get:
```
TASK [setup] *******************************************************************
fatal: [server.io-8721]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to server.io closed.\r\n", "unreachable": true}

msg: Failed to connect to the host via ssh: Shared connection to server.io closed.

fatal: [server.io-d4f2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to server.io closed.\r\n", "unreachable": true}

msg: Failed to connect to the host via ssh: Shared connection to server.io closed.
```

**Comment by jctanner** [comment]
@cadavre please provide the -vvvv output for the playbook.

needs_info

**Comment by cadavre** [comment]
Actually first playbook call is ended with SUCCESS.

But if I make a call after some time (apparently after ControlPersist=60s) I get this:
```
$ ansible-playbook ansible/test.yml -vvvv
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yml *************************************************************
1 plays in ansible/test.yml

PLAY [all:!localhost] **********************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<server.io> ESTABLISH SSH CONNECTION FOR USER: ubuntu
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<server.io> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<server.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r server.io '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1499095012.05-8776658641297 `" && echo ansible-tmp-1499095012.05-8776658641297="` echo /tmp/ansible-tmp-1499095012.05-8776658641297 `" ) && sleep 0'"'"''
<server.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r server.io '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1499095012.05-230045014151772 `" && echo ansible-tmp-1499095012.05-230045014151772="` echo /tmp/ansible-tmp-1499095012.05-230045014151772 `" ) && sleep 0'"'"''
<server.io> PUT /tmp/tmpN82G4A TO /tmp/ansible-tmp-1499095012.05-8776658641297/setup.py
<server.io> PUT /tmp/tmpDE2mfx TO /tmp/ansible-tmp-1499095012.05-230045014151772/setup.py
<server.io> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[server.io]'
<server.io> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[server.io]'
<server.io> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<server.io> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<server.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r server.io '/bin/sh -c '"'"'setfacl -m u:ci:r-x /tmp/ansible-tmp-1499095012.05-8776658641297/ /tmp/ansible-tmp-1499095012.05-8776658641297/setup.py && sleep 0'"'"''
<server.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r server.io '/bin/sh -c '"'"'setfacl -m u:ci:r-x /tmp/ansible-tmp-1499095012.05-230045014151772/ /tmp/ansible-tmp-1499095012.05-230045014151772/setup.py && sleep 0'"'"''
<server.io> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<server.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt server.io '/bin/sh -c '"'"'sudo -H -S -n -u ci /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qluzzomdqsglohjjtflhsxhfiiyoooay; /usr/bin/python /tmp/ansible-tmp-1499095012.05-230045014151772/setup.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<server.io> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<server.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="server.io-ssh.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt server.io '/bin/sh -c '"'"'sudo -H -S -n -u ci /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-bfieprxcazdouyuhxczqqmdsrizsbvdu; /usr/bin/python /tmp/ansible-tmp-1499095012.05-8776658641297/setup.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [server.io-6af1]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 36\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 4\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nShared connection to server.io closed.\r\n", 
    "unreachable": true
}

msg: Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 36
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 4
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Control master terminated unexpectedly
Shared connection to server.io closed.

fatal: [server.io-c7d2]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 36\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 3\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nShared connection to server.io closed.\r\n", 
    "unreachable": true
}

msg: Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 36
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 3
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Control master terminated unexpectedly
Shared connection to server.io closed.

    to retry, use: --limit @/builds/seweryn.zeman/ci-testing/ansible/test.retry

PLAY RECAP *********************************************************************
server.io-6af1              : ok=0    changed=0    unreachable=1    failed=0   
server.io-c7d2              : ok=0    changed=0    unreachable=1    failed=0   

ERROR: Job failed: exit code 1
```

`/etc/ssh/ssh_config` has nothing more for `Host *` than:
```
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
```

**Comment by sterfield** [comment]
Hi,

I have the same issue. Connecting to my hosts (Ubuntu 16.04.02) is impossible using ansible 2.3.1.0 or 2.3.0.0. I have a `read header failed: Broken pipe` on every ssh socket.

Downgrading to 2.2.3.0 fix it.

Server is macOs Sierra 10.12.5, client are Ubuntu 16.04.

The command executed is a very simple `ansible -m ping`

**Comment by cadavre** [comment]
I fixed this with increasing ControlPersist to 30m.
```
[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=30m
```

**Comment by sterfield** [comment]
Nope, still not working with Ansible last version and you ssh_args command.

My configuration is a little bit more specific: I'm using a jumphost that is configured in my ssh configuration, using `ControlMaster=auto` and a specific value for storing all the socket files.

Also worth to note that I still have a bunch of `Broken pipe` using ansible 2.2.3.0, but it somehow manage to handle it better than 2.3.

```
<10.233.33.111> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=30m -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/gloetscher/.ansible/cp/ansible-ssh-%h-%p-%r 10.233.33.111 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/gloetscher/.ansible/tmp/ansible-tmp-1500369662.42-103249713897213 `" && echo ansible-tmp-1500369662.42-103249713897213="` echo /home/gloetscher/.ansible/tmp/ansible-tmp-1500369662.42-103249713897213 `" ) && sleep 0'"'"''
 87206 1500369664.41736: stderr chunk (state=2):
>>>OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/gloetscher/.ssh/config
<<<

 87206 1500369664.41759: stderr chunk (state=3):
>>>debug1: /Users/gloetscher/.ssh/config line 134: Applying options for 10.233.33.*
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Setting implicit ProxyCommand from ProxyJump: ssh -vvv -W %h:%p bastion1
<<<

 87206 1500369664.41783: stderr chunk (state=3):
>>>debug1: auto-mux: Trying existing master
<<<

 87206 1500369664.41795: stderr chunk (state=3):
>>>debug2: fd 3 setting O_NONBLOCK
<<<

 87206 1500369664.41814: stderr chunk (state=3):
>>>debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 87216
<<<

 87206 1500369664.41827: stderr chunk (state=3):
>>>debug3: mux_client_request_session: session request sent
<<<

 87206 1500369664.57656: stderr chunk (state=3):
>>>debug1: mux_client_request_session: master session id: 2
<<<

 87206 1500369664.89682: stdout chunk (state=3):
>>>ansible-tmp-1500369662.42-103249713897213=/home/gloetscher/.ansible/tmp/ansible-tmp-1500369662.42-103249713897213
<<<

 87206 1500369664.89720: stderr chunk (state=3):
>>>debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
<<<

 87206 1500369664.89818: stdout chunk (state=3):
>>><<<

 87206 1500369664.89828: stderr chunk (state=3):
>>><<<

 87206 1500369664.89848: _low_level_execute_command() done: rc=0, stdout=ansible-tmp-1500369662.42-103249713897213=/home/gloetscher/.ansible/tmp/ansible-tmp-1500369662.42-103249713897213
, stderr=OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/gloetscher/.ssh/config
debug1: /Users/gloetscher/.ssh/config line 134: Applying options for 10.233.33.*
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Setting implicit ProxyCommand from ProxyJump: ssh -vvv -W %h:%p bastion1
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 87216
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0

 87206 1500369664.89878: transferring module to remote /home/gloetscher/.ansible/tmp/ansible-tmp-1500369662.42-103249713897213/ping.py
```

I have `Broken pipe` at each step, but ansible manage to get through it.

**Comment by mcamack** [comment]
I had very similar errors trying to run ansible v2.4.0.0 from ubuntu 16.04 to a host on sles10sp3. The host machine had python 2.4.2 installed, and this issue goes away when upgrading to python 2.7. This is confusing because I didn't think Ansible cared about the host's python version for the SSH connection.

**Comment by anthonygreen** [comment]
Similar issue 

Host
OS X: 10.11.6
Ansible: 2.4.3.0 
Python: 2.7.10

Destination VM
Ubuntu 16.04.3 LTS

    localhost> (0, ' 
    {"started": 1, "invocation": {"module_args": {"jid": "391783402491.7383", "mode": "status"}}, "finished": 0,     "ansible_job_id": "391783402491.7383"} 
    ', 'OpenSSH_6.9p1, LibreSSL 2.1.8 
    debug1: Reading configuration data /etc/ssh/ssh_config 
    debug1: /etc/ssh/ssh_config line 21: Applying options for * 
    debug1: auto-mux: Trying existing master 
    debug2: fd 3 setting O_NONBLOCK 
    debug2: mux_client_hello_exchange: master version 4 
    debug3: mux_client_forwards: request forwardings: 0 local, 0 remote 
    debug3: mux_client_request_session: entering 
    debug3: mux_client_request_alive: entering 
    debug3: mux_client_request_alive: done pid = 15818 
    debug3: mux_client_request_session: session request sent 
    debug1: mux_client_request_session: master session id: 2 
    debug3: mux_client_read_packet: read header failed: Broken pipe 
    debug2: Received exit status from master 0 
    Shared connection to localhost closed. 
    ')

**Comment by strarsis** [comment]
I had a similar issue, I was able to 'fix' it by setting 
`pipelining` option in `ansible.cfg` from `True` to `False`, 
running the playbook again (this time successfully) and then setting `pipelining` back 
to `True` which caused subsequent playbook to run correctly, too.

**Comment by russellvt** [comment]
This seems to hit, particularly, when going from a newer host (read: newer SSH) / newer Ansible to an older machine (read: older SSH). I've been able to consistently reproduce on Linux Cinnamon 17 and 18, as well as CentOS 7.x... both going to RHEL5.x).

Downgrading to Ansible 2.2.3.0 fixes the problem, but it breaks in the 2.4.x and 2.5.x versions.

**Comment by mxkle** [comment]
ansible machine:
```
ansible --version
ansible 2.4.1.0  config file = /mnt/it/ansible/ansible.cfg  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']  ansible python module location = /usr/lib/python2.7/site-packages/ansible  executable location = /usr/bin/ansible  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
uname -a
Linux alpine-test 4.9.65-1-virthardened #2-Alpine SMP Mon Nov 27 15:53:30 GMT 2017 x86_64 Linux
apk info openssh
openssh-7.5_p1-r8 description:
Port of OpenBSD's free SSH release
```


remote machine:
```
uname -a
Linux alpine 4.9.65-1-virthardened #2-Alpine SMP Mon Nov 27 15:53:30 GMT 2017 x86_64 Linux
apk info openssh
openssh-7.5_p1-r8 description:
Port of OpenBSD's free SSH release
```

Getting this error when `gather_facts: yes` is set in the playbook.

```
fatal: [alpine]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "OpenSSH_7.5p1-hpn14v4, LibreSSL 2.6.3\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 2607\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 2\r\nShared connection to alpine closed.\r\n",
    "module_stdout": "/bin/sh: syntax error: unexpected \"(\"\r\n",
    "msg": "MODULE FAILURE",
    "rc": 2
}
```


edit: nvm, python wasnt installed per default in the new image. stupid me

**Comment by mzabaluev** [comment]
Looks like a duplicate of #17935.

**Comment by RuslanZavacky** [comment]
I've got the same error as a topic starter, tried to add 

```
[ssh_connection]
retries=3
pipelining=False
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
```

but no luck :(

if there are any other solutions for this, I would appreciate it, as for now, my introduction to ansible ended with this error unfortunately :(

**Comment by bossjones** [comment]
@RuslanZavacky do you mind posting your logs ? Just dealt w/ this issue and it turns out it was something completely unrelated to ansible, it was my /etc/hosts file. Not saying that will be the same for you, but will to help out if you're still looking for guidance of any kind.

**Comment by alkarp** [comment]
Similar issue with raw module when attempt to connect to a remote network appliance over SSH.

Although, first connection attempt output is different to consequent connection made while TCP sessions is still open.

Initial connection:
```
fatal: [target-appliance-name.domain.com]: UNREACHABLE! => {
    "changed": false,
    "msg": "Invalid/incorrect password: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/a0cfa42683\" does not exist\r\ndebug2: resolving \"target-appliance-name.domain.com\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to target-appliance-name.domain.com [172.16.119.20] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 9999 ms remain after connect\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_rsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_rsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_dsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_ecdsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_ecdsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_ed25519 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /root/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.4\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.4\r\ndebug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to target-appliance-name.domain.com:22 as 'opak'\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from target-appliance-name.domain.com\r\ndebug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-ed25519,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: curve25519-sha256 need=64 dh_need=64\r\ndebug1: kex: curve25519-sha256 need=64 dh_need=64\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:yGzyenCWZLEp4RoCJmWH4tvpneRhw9J1p5Y9q30W87M\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from target-appliance-name.domain.com\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from 172.16.119.20\r\ndebug1: Host 'target-appliance-name.domain.com' is known and matches the ECDSA host key.\r\ndebug1: Found key in /root/.ssh/known_hosts:1\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug2: key: /root/.ssh/id_rsa ((nil))\r\ndebug2: key: /root/.ssh/id_dsa ((nil))\r\ndebug2: key: /root/.ssh/id_ecdsa ((nil))\r\ndebug2: key: /root/.ssh/id_ed25519 ((nil))\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password,keyboard-interactive\r\ndebug3: start over, passed a different list publickey,password,keyboard-interactive\r\ndebug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: keyboard-interactive,password\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /root/.ssh/id_rsa\r\ndebug3: no such identity: /root/.ssh/id_rsa: No such file or directory\r\ndebug1: Trying private key: /root/.ssh/id_dsa\r\ndebug3: no such identity: /root/.ssh/id_dsa: No such file or directory\r\ndebug1: Trying private key: /root/.ssh/id_ecdsa\r\ndebug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory\r\ndebug1: Trying private key: /root/.ssh/id_ed25519\r\ndebug3: no such identity: /root/.ssh/id_ed25519: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug3: authmethod_lookup keyboard-interactive\r\ndebug3: remaining preferred: password\r\ndebug3: authmethod_is_enabled keyboard-interactive\r\ndebug1: Next authentication method: keyboard-interactive\r\ndebug2: userauth_kbdint\r\ndebug3: send packet: type 50\r\ndebug2: we sent a keyboard-interactive packet, wait for reply\r\ndebug3: receive packet: type 60\r\ndebug2: input_userauth_info_req\r\ndebug2: input_userauth_info_req: num_prompts 1\r\ndebug3: send packet: type 61\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password,keyboard-interactive\r\ndebug2: userauth_kbdint\r\ndebug3: send packet: type 50\r\ndebug2: we sent a keyboard-interactive packet, wait for reply\r\ndebug3: receive packet: type 60\r\ndebug2: input_userauth_info_req\r\ndebug2: input_userauth_info_req: num_prompts 1",
    "unreachable": true
}
```

Second attempt while TCP session is still open:

```
fatal: [target-appliance-name.domain.com]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 8459\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 255\r\nShared connection to target-appliance-name.domain.com closed.",
    "unreachable": true
}
```

**Comment by jctanner** [comment]
Per https://github.com/ansible/ansible/issues/26359#issuecomment-316004134 the issue described in the original description has been resolved by increasing the controlpersist timeout. If other have similar issues, those should be filed as separate bugs.
