### ISSUE TITLE
[DEPRECATION WARNING]: None. This feature will be removed in version 2.8.

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#28583]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel cd8c1c1108) last updated 2017/08/23 22:03:37 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Management host macOS 10.12.5
Managed host Windows 6

##### SUMMARY

[DEPRECATION WARNING]: None.
This feature will be removed in version 2.8.

##### STEPS TO REPRODUCE

Variables 
```yaml
installers:
  - {
      file: "Installer2017-1-2-2.zip",
      url: "http://www.real-time.com/Releases",
      dest: "{{ ansible_env['USERPROFILE'] }}\\Downloads"
    }
  - {
      file: "InstallerDataInterface.zip",
      url: "http://www.real-time.com/Releases",
      dest: "{{ ansible_env['USERPROFILE'] }}\\Downloads" 
    }
```
Play
```yaml
- name: unzip 2017 installers
  win_unzip:
    src: "{{ item.dest }}\\{{ item.file }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ installers }}"
```

##### EXPECTED RESULTS

No DEPRECATION warning

##### ACTUAL RESULTS

```
[DEPRECATION WARNING]: None.
This feature will be removed in version 2.8.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
```

**Comment by nrwahl2** [comment]
Do you happen to have `$skip_certificate_validation` specified anywhere? This is the only relevant instance of the string `2.8` I can find for Windows.

`win_get_url.ps1`:
```
# If skip_certificate_validation was specified, use validate_certs
if ($skip_certificate_validation -ne $null) {
    Add-DeprecationWarning -obj $result -msg "The parameter 'skip_vertificate_validation' is being replaced with 'validate_certs'" -version 2.8
    $validate_certs = -not $skip_certificate_validation
}

if (-not $validate_certs) {
    [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
}
```

Not sure why it wouldn't be displaying the `msg` parameter if this is what it's hitting. But, I don't know Powershell.

EDIT: I see why it's not displaying the actual warning. Instead of `msg`, it needs to be using `message`:

```
[ansible@nrwahl1 ansible]$ grep -R 'Add-DeprecationWarning' * | grep version
modules/windows/win_feature.ps1:    Add-DeprecationWarning -obj $result -message "The 'restart' parameter causes instability. Use the 'win_reboot' action conditionally on 'reboot_required' return value instead" -version 2.6
modules/windows/win_get_url.ps1:    Add-DeprecationWarning -obj $result -msg "The parameter 'skip_vertificate_validation' is being replaced with 'validate_certs'" -version 2.8
modules/windows/win_iis_webapppool.ps1:        Add-DeprecationWarning -obj $result -message "Using a string for the attributes parameter is deprecated, please use a dict instead" -version 2.6
modules/windows/win_regedit.ps1:    Add-DeprecationWarning -obj $result -message "Please use path: HKCC:\... instead of path: $path" -version 2.6
module_utils/powershell/Ansible.ModuleUtils.Legacy.psm1:Function Add-DeprecationWarning($obj, $message, $version = $null)
```

**Comment by basictheprogram** [comment]
Oh? It's from the play above! And yes, I have a win_get_url call and  skip_certificate_validation true, removing skip_certificate_validation and the warning goes away.

**Comment by nrwahl2** [comment]
Edited to explain why it's not showing the warning message.

**Comment by nrwahl2** [comment]
Also, if you replace `skip_certificate_validation = true` with `validate_certs = false`, you should get to keep the behavior you want without warnings.

**Comment by basictheprogram** [comment]
Confirmed. Thanks.

**Comment by dagwieers** [comment]
So this is now fixed. Thanks everyone !

**Comment by bcoca** [comment]
The deprecation warning is still incorrect, it should not be `None` but the actual feature deprecated

**Comment by nrwahl2** [comment]
@bcoca Look at PR #28585. I created a separate issue #28584 for the warning being None instead of the correct string, and fixed it in a PR. Dag merged it.

Or, I presume I fixed it. Again, I have no Windows box to test on. Death to all but Linux.

**Comment by bcoca** [comment]
hmm, tempted to say the fix is on the common code using `message` vs `msg` which is the standard on the controller code

**Comment by dagwieers** [comment]
@bcoca Yes, unfortunately these interfaces did not take into account existing names in the python modules. That's why this error occurred in the first place. There is friction between the Powershell-style and Python-style (I would rather call it Ansible-style) interfaces. (e.g. fail_json vs Fail-Json)

But we cannot easily change this, or we have to implement and maintain both. Designing means thinking about interfaces, and sometimes it seems only functionality was taken into account.

**Comment by bcoca** [comment]
im not going to push on this, as long as the interfaces are 'consistent' within the language, I'm fine.

**Comment by jborean93** [comment]
@nitzmahone is working on the .NET utils so it should be something we want to enforce on the new version when it comes through. This is the "legacy" setup so probably don't want to change this.
