### ISSUE TITLE
Ansible gather_facts cannot correctly populate service_mgr fact

### ISSUE THREAD

**Issue by rahul0705** [ansible/ansible#31095]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- gathering_facts

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/******/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

Empty

##### OS / ENVIRONMENT

Running ansible on macOS High Sierra
Deploying to travis-ci 14.04 with sudo and 16.04 personal server

##### SUMMARY

When gathering fact or running the setup ad-hoc command ansible cannot properly populate the ansible_service_mgr fact. Instead of populating it with the correct service manager, it get populated with "service"
```
"ansible_service_mgr": "service",
```

##### STEPS TO REPRODUCE

```yaml
ansible -i production -m setup <host> --ask-vault-pass
```

##### EXPECTED RESULTS

ansible_service_mgr is set to upstart for 14.04 and systemd for 16.04

##### ACTUAL RESULTS

```
"ansible_service_mgr": "service",
```

**Comment by alikins** [comment]
Should be fixed in stable-2.4.0 branch (future 2.4.1) and devel/

95abc1d82e4c40832c802253107ad3f9aeebc68d should be the commit to fix it.

**Comment by rahul0705** [comment]
Is this fix in pip 2.4.0.0?

**Comment by aabdnn** [comment]
I've just downloaded and installed ansible-2.4.1.0-0.4.rc2.tar.gz. However, it's still failing to detect the service manager properly on one of our CentOS 6 hosts:

```
ansible centos6.host -bK -m setup -a filter=ansible_service_mgr
SUDO password: 
centos6.host | SUCCESS => {
    "ansible_facts": {
        "ansible_service_mgr": "service"
    }, 
    "changed": false, 
    "failed": false
}
```

**Comment by mkrizek** [comment]
Fixed in https://github.com/ansible/ansible/pull/32086.
