### ISSUE TITLE
The file module with state=link should not try to validate src

### ISSUE THREAD

**Issue by lalinsky** [ansible/ansible#3229]
Ansible currently tries to validate that the `src` path exists when creating a symbolic link with the `file` module. This causes two problems:
- In check mode, if trying to create link to a file that would otherwise be created earlier in the playbook, fails because it can't find the source file.
- Symbolic link might point to a non-existant file for valid reasons, e.g. link on a shared NFS volume that points to files on local mounts that exist on servers that need to read the link, but not on the server that has write access to NFS. Ansible should allow that use case.

I think that Ansible should simply not try to validate the `src` parameter.

**Comment by bcoca** [comment]
I'm in the middle of writing a patch that both enables this and relative
links.

two new options:

allow_relative=true|false (default)
validate_link_src=true (default)|false

they keep 'current' behavior by default, so as to not break existing
playbooks.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
this should have been fixed in  c9b6f0d0f29b1cd1234d5b803ad56bf348ade5ad

**Comment by mpdehaan** [comment]
Closing per above, thanks!

**Comment by nigelm** [comment]
Looking at that patch, it does not remove the absolute path check for link or include the changes suggested by bcoca.

Still seeing this as an issue in 10de5c8fe3f8cb2000ecae9ac2beb7a51b3b5675

**Comment by mgcrea** [comment]
Just encountered the same issue, patch above does not solve the `absolute paths are required` error.
