### ISSUE TITLE
copy module "changed" status not showing during execution on branch stable-2.4 (working on stable-2.3)

### ISSUE THREAD

**Issue by AceSlash** [ansible/ansible#32347]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy module, maybe other, I didn't test them.

##### ANSIBLE VERSION
branch stable-2.4 from github

##### CONFIGURATION
ANSIBLE_PIPELINING(/home/username/.ansible.cfg) = True
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/username/git/enterprise_name/IT/ansible/prod']
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/username/git/external/ansible-xml']
DEFAULT_VAULT_PASSWORD_FILE(/home/username/.ansible.cfg) = /home/username/.ansible_vault_pass.txt
RETRY_FILES_ENABLED(/home/username/.ansible.cfg) = False

##### OS / ENVIRONMENT
OS you are running Ansible from = Fedora 26 (Workstation Edition)

##### SUMMARY
Running a very simple playbook which copy a file, I noticed that when the file is changed (either in check mode or not) I see the following:

 ```
ASK [firewall : copy some file] *********************************************************************************************************************************************
ok: [host] => (item=ip6tables.save)
PLAY RECAP ********************************************************************************************************************************************************************************************************
host               : ok=7    changed=1    unreachable=0    failed=0   
```

So during execution, I only see "OK" and the summary shows "changed=1". After double checking, the summary is right, not the execution.

Rollbacking to branch  `stable-2.3` gives the correct output:
 ```
ASK [firewall : copy some file] *********************************************************************************************************************************************
changed: [host] => (item=ip6tables.save)
PLAY RECAP ********************************************************************************************************************************************************************************************************
host               : ok=7    changed=1    unreachable=0    failed=0   
```

**Comment by ktosiek** [comment]
Same here with the `template` module, on freshly compiled `stable-2.4`. Also, I don't see the difference when running with `--diff`.

**Comment by ktosiek** [comment]
Bisected this to b61bfc87b85776a633ba27198a1587048079d60e

**Comment by ktosiek** [comment]
It's also broken on 01b6c7c9c6b7459a3cb53ffc2fe02a8dcc1a3acc (which is a cherry-pick of b61bfc87b85776a633ba27198a1587048079d60e), but fixed on devel

**Comment by ktosiek** [comment]
aaand it was fixed in the, aptly named, 21cdddce744c56b0a1f844297b3e04b4467b8d64. This should get backported to stable-2.4 too :-)

**Comment by bcoca** [comment]
fixed by #31812, cherry picked  into stable-2.4 for 2.4.2 release

**Comment by ktosiek** [comment]
It's still broken on current stable-2.4 (b2f3dc90528c9dcb475ce37044fe4c4ea428d516)

**Comment by opoplawski** [comment]
Yeah, I can't find any evidence that this commit was cherry-picked into stable-2.4

**Comment by ktosiek** [comment]
it's there now (fa289a022c8b5702decf5ca89e9df3aef66b1b2c), I'll try to test tomorrow
