### ISSUE TITLE
copy module destroys selinux contexts

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#3412]
The following happened after upgrading to ansible 1.2 from Ubuntu PPA - ansible machine is ubuntu 12.04, target is CentOS 6.4. I don't think anything like this happened with 1.1, but I have not tried to replicate it with 1.1

Issue: pushing out configurations to a fresh CentOS 6.4 box using the "copy"
module, I had serious breakage due to files losing their selinux markings.

The relevant ansible configs are:

```
tasks:
  - name: install /etc/security/limits.conf
    action: copy src=files/limits.conf dest=/etc/security/limits.conf mode=644

tasks:
  - action: copy src=files/storage/centos/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600
    notify: restart iptables
handlers:
  - name: restart iptables
    action: service name=iptables state=restarted~~~
```
### Updating /etc/security/limits.conf

After updating, ansible-playbook stopped at this point:

```
TASK: [install /etc/security/limits.conf]
*************************************
changed: [storage6.int.example.com]

TASK: [yum name=strace state=installed]
***************************************
fatal: [storage6.int.example.com] => failed to open a SFTP connection
(EOF during negotiation)

FATAL: all hosts have already failed -- aborting

PLAY RECAP
********************************************************************
           to retry, use: --limit
@/var/tmp/ansible/storage-centos.yaml.retry

storage6.int.example.com : ok=23   changed=17   unreachable=1    failed=0
```

After this, I was completely unable to login to the target box either by ssh
or at the console, even after a reboot, either as a normal user or root.

Logging in at the console, I briefly saw a flash of

"Error in service module"

before the screen cleared and showed the login prompt again.

I was able to fix the problem by rebooting into single-user mode and running

```
restorecon -v /etc/security/limits.conf
```
### Updating /etc/sysconfig/iptables

Restarting the playbook after fixing the above, another problem arose:

```
TASK: [copy src=files/storage/centos/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600] ***
changed: [storage6.int.example.com]

...

NOTIFIED: [restart iptables]
**************************************************
failed: [storage6.int.example.com] => {"failed": true, "item": ""}
msg: Can't open /etc/sysconfig/iptables: Permission denied
```

Again I was able to fix the problem using restorecon. This time I took a
note of the selinux tags before and after:

```
[root@storage6 ~]# ls -Z /etc/sysconfig/iptables
-rw-------. root root unconfined_u:object_r:admin_home_t:s0 /etc/sysconfig/iptables
[root@storage6 ~]# restorecon -v /etc/sysconfig/iptables
restorecon reset /etc/sysconfig/iptables context unconfined_u:object_r:admin_home_t:s0->unconfined_u:object_r:system_conf_t:s0
[root@storage6 ~]# ls -Z /etc/sysconfig/iptables
-rw-------. root root unconfined_u:object_r:system_conf_t:s0 /etc/sysconfig/iptables
```

My guess is that ansible's copy module is copying the file under a new name
and mv'ing it into place, and so it is losing the selinux tagging of the
original file.

**Comment by bcoca** [comment]
this was a problem after updating copy/file/template to be atomic, but it
WAS fixed at one point, long before 1.2 release, please check you don't
have older modules/libraries laying around from 1.1.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by candlerb** [comment]
```
# dpkg-query -L ansible | grep /usr/share/ansible | sort >a
# find /usr/share/ansible | sort >b
# diff -u a b
--- a   2013-07-02 19:45:48.130016845 +0100
+++ b   2013-07-02 19:45:50.042023983 +0100
@@ -1,4 +1,8 @@
 /usr/share/ansible
+/usr/share/ansible/apt_repository.patched
+/usr/share/ansible/authorized_key.new
+/usr/share/ansible/authorized_key.orig
+/usr/share/ansible/authorized_key.orig2
 /usr/share/ansible/cloud
 /usr/share/ansible/cloud/cloudformation
 /usr/share/ansible/cloud/ec2
```

OK, so I've removed those now. The problem is still repeatable:

```
# ssh storage6 ls -Z /etc/sysconfig/iptables
-rw-------. root root unconfined_u:object_r:system_conf_t:s0 /etc/sysconfig/iptables
# ansible-playbook storage-centos.yaml --tags iptables --limit storage6.int.example.com

PLAY [configure centos storage server] ****************************************

GATHERING FACTS ***************************************************************
ok: [storage6.int.example.com]

TASK: [copy src=files/storage/centos/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600] ***
changed: [storage6.int.example.com]

NOTIFIED: [restart iptables] **************************************************
failed: [storage6.int.example.com] => {"failed": true, "item": ""}
msg: Can't open /etc/sysconfig/iptables: Permission denied


PLAY RECAP ********************************************************************
           to retry, use: --limit @/var/tmp/ansible/storage-centos.yaml.retry

storage6.int.example.com : ok=2    changed=1    unreachable=0    failed=1

# ssh storage6 ls -Z /etc/sysconfig/iptables-rw-------. root root unconfined_u:object_r:admin_home_t:s0 /etc/sysconfig/iptables
```

`ansible-playbook -v` doesn't give any more info except:

```
changed: [storage6.int.example.com] => {"changed": true, "dest": "/etc/sysconfig/iptables", "gid": 0, "group": "root", "md5sum": "83d320f8fa2f05ec7ebdeb4db006353c", "mode": "0600", "owner": "root", "size": 609, "src": "/root/.ansible/tmp/ansible-1372791419.71-257871303718793/source", "state": "file", "uid": 0}
```

**Comment by candlerb** [comment]
With `-v -v -v`:

```
TASK: [copy src=files/storage/centos/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600] ***
<storage6.int.example.com> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO storage6.int.example.com
<storage6.int.example.com> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1372795044.62-172299394675722 && echo $HOME/.ansible/tmp/ansible-1372795044.62-172299394675722'
<storage6.int.example.com> EXEC /bin/sh -c 'rc=0; [ -r "/etc/sysconfig/iptables" ] || rc=2; [ -f "/etc/sysconfig/iptables" ] || rc=1; [ -d "/etc/sysconfig/iptables" ] && rc=3; (/usr/bin/md5sum /etc/sysconfig/iptables 2>/dev/null) || (/sbin/md5sum -q /etc/sysconfig/iptables 2>/dev/null) || (/usr/bin/digest -a md5 /etc/sysconfig/iptables 2>/dev/null) || (/sbin/md5 -q /etc/sysconfig/iptables 2>/dev/null) || (/usr/bin/md5 -n /etc/sysconfig/iptables 2>/dev/null) || (/bin/md5 -q /etc/sysconfig/iptables 2>/dev/null) || (echo "${rc}  /etc/sysconfig/iptables")'
<storage6.int.example.com> PUT /root/ansible/files/storage/centos/iptables TO /root/.ansible/tmp/ansible-1372795044.62-172299394675722/source
<storage6.int.example.com> PUT /tmp/tmpJXjiTe TO /root/.ansible/tmp/ansible-1372795044.62-172299394675722/copy
<storage6.int.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1372795044.62-172299394675722/copy; rm -rf /root/.ansible/tmp/ansible-1372795044.62-172299394675722/ >/dev/null 2>&1'
changed: [storage6.int.example.com] => {"changed": true, "dest": "/etc/sysconfig/iptables", "gid": 0, "group": "root", "md5sum": "83d320f8fa2f05ec7ebdeb4db006353c", "mode": "0600", "owner": "root", "size": 609, "src": "/root/.ansible/tmp/ansible-1372795044.62-172299394675722/source", "state": "file", "uid": 0}

NOTIFIED: [restart iptables] **************************************************
<storage6.int.example.com> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO storage6.int.example.com
<storage6.int.example.com> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1372795046.72-193907414250325 && echo $HOME/.ansible/tmp/ansible-1372795046.72-193907414250325'
<storage6.int.example.com> REMOTE_MODULE service name=iptables state=restarted
<storage6.int.example.com> PUT /tmp/tmpMf92QQ TO /root/.ansible/tmp/ansible-1372795046.72-193907414250325/service
<storage6.int.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1372795046.72-193907414250325/service; rm -rf /root/.ansible/tmp/ansible-1372795046.72-193907414250325/ >/dev/null 2>&1'
failed: [storage6.int.example.com] => {"failed": true, "item": ""}
msg: Can't open /etc/sysconfig/iptables: Permission denied
```

**Comment by c0rner** [comment]
I believe this might related to #3408 in which you should use 'context=default' to have the default context being reset. In your case it most likely is a bug where copy actually does a 'move' of the new file into its destination, this was as bcoca noted due to the operation having to be atomic, and the context should have been preserved without adding 'context=default' in any case.

**Comment by candlerb** [comment]
Thanks. I just tried adding "context=default" but it is indeed rejected as per #3408:

```
msg: unsupported parameter for module: context
```

**Comment by mpdehaan** [comment]
can you please share the output of ansible --version ?

**Comment by mpdehaan** [comment]
another question is do you have python-selinux installed?  I'm wondering if it is not copying attributes over for that reason.

If so, we should make error detection around python-selinux absense stronger.

**Comment by candlerb** [comment]
```
# ansible --version
ansible 1.2
```

After doing "yum install libselinux-python" on the target machine (this pulled in libselinux and libselinux-utils as dependencies) the problem has now gone away, so that's the problem.

`ansible -v -v -v output` appears to be identical

I concur that there should be an error shown, perhaps fatal if selinux is in enforcing mode.

**Comment by mpdehaan** [comment]
Excellent, I am thinking it should be fatal too.

**Comment by bcoca** [comment]
not really, as it would also affect system that don't have selinux enabled
(which is the majority afaik).

On Wed, Jul 3, 2013 at 9:45 AM, Michael DeHaan notifications@github.comwrote:

> Excellent, I am thinking it should be fatal too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/3412#issuecomment-20416005
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
This might be better solved by documentation and/or a 'enforce selinux' configuration flag to make the error fatal.

**Comment by mpdehaan** [comment]
(A) Yes, I'm suggesting this become fatal.

(B)  I'm wondering if your atomic rename fixes (still not applied, need to
test) improve some of this scenario.

**Comment by bcoca** [comment]
Not really, selinux stuff should work 'the same as before', I moved it so
it is clearer and always applys.

My issue with making selinux missing a fatal errors is that then you cannot
use file, template, copy, etc unless you have selinux. In the atomic move
we are not asking for it explicitly, just trying to add it implicitly if
possible.

I'm all for failing fatally if using one of the selinux= properties in a
task, but not implicitly as it would break everyone not using selinux.

On Sun, Jul 14, 2013 at 10:52 PM, Michael DeHaan
notifications@github.comwrote:

> ondering if your atomic rename fixes (still not applied, need to
> test) improve some of this scenario.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by bcoca** [comment]
not to say that adding a ansible.cfg enforce_selinux=true (default false)
might work for those that use it in their systems (ansible_selinux_enforce
host/group level var?).

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by candlerb** [comment]
I would suggest that if it's not set, then the error be fatal _if_ selinux is enabled in enforcing mode on the target. (That is, /selinux/enforce exists and when read it returns "1")

**Comment by mpdehaan** [comment]
If someone wants to verify SELinux is set, use the fail module with when,
etc.

This is about failing module calls if enabled without tools needing to
apply context.

**Comment by mpdehaan** [comment]
fixed per above, thank you Brian!
