### ISSUE TITLE
-e vars are not taking precedence over variables defined in the role

### ISSUE THREAD

**Issue by jarv** [ansible/ansible#3974]
Behavior observed in ansible 1.2 and 1.3

Variables defined in  <role>/vars/main.yml seem to take precedence over variables passed into -e except when they are used in jinja templates.  Here is a very simple example:

test.yml play:

```

---
- hosts: localhost
  roles:
    - test
```

roles/test/vars/main.yml:

```

---
config: "inrole"
```

roles/test/tasks/main.yml:

```

---
- name: test
  debug: msg="{{ config }}"
- template: src=config.json.j2 dest=/var/tmp/config.json mode=640
```

roles/test/templates/config.json.j2:

```
{{ config | to_nice_json }}
```

Now when you run this role:

```
$ ansible-playbook -vvv -c local --limit "localhost," ./test.yml -i "localhost," -e "config=cmdline"
TASK: [test] ****************************************************************** 
ok: [localhost] => {"item": "", "msg": "inrole"}
                                                      ^ value assigned in roles/test/vars/main.yml
$ cat /var/tmp/config.json 
"cmdline"
   ^ value passed into the command line
```

**Comment by jimi-c** [comment]
I just pushed up commits today that should fix this. Can you give it a try with the latest checkout from devel?

**Comment by jarv** [comment]
With ansible-playbook 1.3 (devel 6f6efa268b) last updated 2013/08/30 10:32:58 (GMT -400)  I'm still seeing the same behavior where the debug msg prints `inrole` but config.json has `cmdline`.

**Comment by jimi-c** [comment]
I just tested this, and am not able to reproduce it:

<pre>
$ ansible-playbook -vvv -c local --limit "localhost," ./test_3974.yml -i "localhost," -e "config=cmdline"
PLAY [localhost] ************************************************************** 
GATHERING FACTS *************************************************************** 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1377876673.82-70285217127063 && echo $HOME/.ansible/tmp/ansible-1377876673.82-70285217127063']
<localhost> REMOTE_MODULE setup 
<localhost> PUT /tmp/tmppxtTOr TO /root/.ansible/tmp/ansible-1377876673.82-70285217127063/setup
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /root/.ansible/tmp/ansible-1377876673.82-70285217127063/setup; rm -rf /root/.ansible/tmp/ansible-1377876673.82-70285217127063/ >/dev/null 2>&1']
ok: [localhost]
TASK: [test] ****************************************************************** 
ok: [localhost] => {"item": "", "msg": "cmdline"}
TASK: [template src=config.json.j2 dest=/var/tmp/config.json mode=640] ******** 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1377876674.5-3894932272639 && echo $HOME/.ansible/tmp/ansible-1377876674.5-3894932272639']
<localhost> EXEC ['/bin/sh', '-c', u'rc=0; [ -r "/var/tmp/config.json" ] || rc=2; [ -f "/var/tmp/config.json" ] || rc=1; [ -d "/var/tmp/config.json" ] && rc=3; (/usr/bin/md5sum /var/tmp/config.json 2>/dev/null) || (/sbin/md5sum -q /var/tmp/config.json 2>/dev/null) || (/usr/bin/digest -a md5 /var/tmp/config.json 2>/dev/null) || (/sbin/md5 -q /var/tmp/config.json 2>/dev/null) || (/usr/bin/md5 -n /var/tmp/config.json 2>/dev/null) || (/bin/md5 -q /var/tmp/config.json 2>/dev/null) || (echo "${rc}  /var/tmp/config.json")']
<localhost> PUT /tmp/tmpiGLIa1 TO /root/.ansible/tmp/ansible-1377876674.5-3894932272639/source
<localhost> PUT /tmp/tmpjILQKE TO /root/.ansible/tmp/ansible-1377876674.5-3894932272639/copy
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /root/.ansible/tmp/ansible-1377876674.5-3894932272639/copy; rm -rf /root/.ansible/tmp/ansible-1377876674.5-3894932272639/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "dest": "/var/tmp/config.json", "gid": 0, "group": "root", "item": "", "md5sum": "f6a9342b3dc013f3470c29da19c33664", "mode": "0640", "owner": "root", "secontext": "unconfined_u:object_r:admin_home_t:s0", "size": 10, "src": "/root/.ansible/tmp/ansible-1377876674.5-3894932272639/source", "state": "file", "uid": 0}
PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
$ cat /var/tmp/config.json 
"cmdline"
</pre>

Are you running via hacking/env-setup or are you installing it? If you're installing it, you might want to remove the site-packages/ansible directory and reinstall to make sure there's no cruft.

**Comment by jarv** [comment]
I was using env-setup, I'll try again.

**Comment by jimi-c** [comment]
Any follow-up? I've been testing this pretty extensively with the new role defaults patch and cannot reproduce it.

**Comment by jarv** [comment]
Just re-tested, looks good.
