### ISSUE TITLE
systemctl bug in systemd service management 

### ISSUE THREAD

**Issue by uggedal** [ansible/ansible#4147]
7c8aa66 introduced a bug where one can no longer enable nor start templated systemd services.

When checking if a templated service is available (for instance `dhcpd@eth0.service`) `systemctl list-unit-files` is used and one have to compare it against the generic name (for instance `dhcpd@.service`). In 7c8aa66 this name used for lookup is also set to `this.name` and therefore no actions on the service with `systemctl` will resolve since it will use the generic name.

This issue is actualy fixed in the devel branch by the "unrelated" 72eaa05 commit.

The smallest patch which will resolve the issue for 1.3.x is:

``` diff
diff --git a/library/system/service b/library/system/service
index bf214bc..69d31f4 100644
--- a/library/system/service
+++ b/library/system/service
@@ -397,7 +397,7 @@ class LinuxService(Service):
             # adjust the service name to account for template service unit files
             index = name.find('@')
             if index != -1:
-                self.name = name = name[:index+1]
+                name = name[:index+1]

             look_for = "%s.service" % name
             for line in out.splitlines():
```

I think this regression warrants a 1.3.2 release since it renders ansible useless for most users on systemd based systems.

**Comment by mpdehaan** [comment]
Hi, can you please supply steps to reproduce per https://github.com/ansible/ansible/blob/devel/CONTRIBUTING.md ?

**Comment by mpdehaan** [comment]
Also, what OS are you using?

**Comment by uggedal** [comment]
I'm on ArchLinux.

``` sh
$ ansible --version
ansible 1.3.1
```

Steps to reproduce:

``` sh
$ ansible hostname -u root -i ../inventory/hosts -m service -a 'name=dhcpcd@eth0.service state=running enabled=yes'                                                                                 
phosphorus.uggedal.com | FAILED >> {
    "failed": true, 
    "msg": "Failed to issue method call: Unit name dhcpcd@.service is not valid.\n"
}
```

Expected result (after applying patch):

``` sh
$ ansible hostname -u root -i ../inventory/hosts -m service -a 'name=dhcpcd@eth0.service state=running enabled=yes'
phosphorus.uggedal.com | success >> {
    "changed": false, 
    "enabled": true, 
    "name": "dhcpcd@eth0.service", 
    "state": "started"
}
```

**Comment by mpdehaan** [comment]
Thanks!

**Comment by jimi-c** [comment]
This interesting, since that is essentially what the code was doing originally, I just moved it up a few lines. I'll take a look into this, though it may be resolved by another patch I already applied to devel regarding services that don't end in .service.

**Comment by uggedal** [comment]
@jimi-c If you read my original comment I refer to your commit on devel which resolves the issue.

**Comment by jimi-c** [comment]
Oh, yes sorry I missed that.

**Comment by jimi-c** [comment]
So this is fixed, however I'd like a little more testing time on that follow-up patch so it was not included in 1.3.2. If we end up doing a 1.3.3 after a period of time I may include this in that release, but I'm going to close this for now. Please let me know if you run into any other issues regarding these changes, and we can open a new issue. Thanks!

**Comment by andreasf** [comment]
This seems to be broken. 72eaa0570e29a87908f8e185b574b812826eafe0 fixes the service lookup in `get_service_tools()`, but not the original issue of setting a name that doesn't resolve. It still cuts off the part after the @ and stores that as the systemd unit name, only the variable name is changed from self.name to self.__systemd_unit. Try this:

```
tasks:
    - service: name=serial-getty@ttyS0.service state=started
```

Output:

```
msg: Failed to issue method call: Unit name serial-getty@.service is not valid.
```

It fails, because `get_service_tools()` sets the unit name to `serial-getty@.service`, instead of `serial-getty@ttyS0.service`. Patch suggestion:

```
diff --git a/library/system/service b/library/system/service
index 5180a14..6a7b7c4 100644
--- a/library/system/service
+++ b/library/system/service
@@ -410,13 +410,14 @@ class LinuxService(Service):
             rc, out, err = self.execute_command("%s list-unit-files" % (location['systemctl']))

             # adjust the service name to account for template service unit files
+            look_for = name
             index = name.find('@')
             if index != -1:
-                name = name[:index+1]
+                look_for = name[:index+1]

             self.__systemd_unit = None
             for line in out.splitlines():
-                if line.startswith(name):
+                if line.startswith(look_for):
                     self.__systemd_unit = name
                     return True
             return False
```

**Comment by jimi-c** [comment]
@andreasf could you please open a new issue for this? Thanks!
