### ISSUE TITLE
authorized_key fails to accept keys with comments

### ISSUE THREAD

**Issue by Daemoen** [ansible/ansible#4596]
We have 40 keys, 36 of which have no comment, 4 of which have comments specified.  After searching, bug https://github.com/ansible/ansible/issues/4513 was discovered.  It appears as a result of fixing this bug, the opposite scenario was created, and now technically accurate keys are failing:

ansible 1.4 (devel 7b6d64d98c) last updated 2013/10/18 16:42:02 (GMT -700)

Key does not work:
itops@control:~/itops/ansible/roles/common/files/ssh$ cat asteel.bak
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTboL9bhtPElJaQ05oMbIK5Bmh5UXsYVZp1HfdTvVzJRjkmB3HjZ/32scQ8eQpVub4oDnugfcItJ33tawGvPMJ3nHT/ZJh7u+eRf6zrSQF/NP6NTyy8Qq6AVOsCk4dyhwyG34/ejaB6X6EeS8ClXq3fL089S7PhU2R/GnneAqH16z4RGYUC49er7epqM0sCvtazaepec6nlRagRWe9IHe6cWlmG4fQ4OBvxEbimR6K2PTu2opwwOVF1hng9pn8iDDnIpW8i/wmDahnKUmsksaEv559zr+ffeQMHsSvmp5V7aM4Jb6ozEUGvZ6y15xQTLP/ldSdGiamqapa/Nk4bWnK1Nxn5gV6MqncEM4L9GnqVsCw6dWBgpOG/nFjly3hglduL8pJaheG7rxUw8lZGOvhcvLFZcraxTj4KF6cpi/AHvySL+mu28PPjDkA22lPvKBAU9RUfiDSBvPVxGSzx4aIwEWyGLofbi0wN00dBdRt/skMmzd6ecpIDRts+As78wed32QRDi7kEy2LT3RFk2l2FDxjQ6GgXRu6xmdiPo/srD/qMvg2t7ciDKBcPKJrhI4lGefm7qhIk96XfOnjUyD/dYF6XMLL2QX1ZB/UULBdw4jWbDIxsXnxnFisVqeRwwNGWts4ckca5ozUlQrP9U/+OIZv+pY0RkiQTeMci52xhw== Andrew Steele, Engineer - Quantifind

Key does work:
itops@control:~/itops/ansible/roles/common/files/ssh$ cat asteele.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTboL9bhtPElJaQ05oMbIK5Bmh5UXsYVZp1HfdTvVzJRjkmB3HjZ/32scQ8eQpVub4oDnugfcItJ33tawGvPMJ3nHT/ZJh7u+eRf6zrSQF/NP6NTyy8Qq6AVOsCk4dyhwyG34/ejaB6X6EeS8ClXq3fL089S7PhU2R/GnneAqH16z4RGYUC49er7epqM0sCvtazaepec6nlRagRWe9IHe6cWlmG4fQ4OBvxEbimR6K2PTu2opwwOVF1hng9pn8iDDnIpW8i/wmDahnKUmsksaEv559zr+ffeQMHsSvmp5V7aM4Jb6ozEUGvZ6y15xQTLP/ldSdGiamqapa/Nk4bWnK1Nxn5gV6MqncEM4L9GnqVsCw6dWBgpOG/nFjly3hglduL8pJaheG7rxUw8lZGOvhcvLFZcraxTj4KF6cpi/AHvySL+mu28PPjDkA22lPvKBAU9RUfiDSBvPVxGSzx4aIwEWyGLofbi0wN00dBdRt/skMmzd6ecpIDRts+As78wed32QRDi7kEy2LT3RFk2l2FDxjQ6GgXRu6xmdiPo/srD/qMvg2t7ciDKBcPKJrhI4lGefm7qhIk96XfOnjUyD/dYF6XMLL2QX1ZB/UULBdw4jWbDIxsXnxnFisVqeRwwNGWts4ckca5ozUlQrP9U/+OIZv+pY0RkiQTeMci52xhw==

Only difference, the one that works has the comment removed, its the same key.

**Comment by mpdehaan** [comment]
Is this a failure pushing a key or reading the file?

Can you share the playbook and output when this occurs?

Thanks!

**Comment by Daemoen** [comment]
Hit the wrong button, apologies.

Here is a sample of the error, which occurs as the keys are being deployed to remote machines:

failed: [dhd0.quantifind.com] => (item={'comment': 'Andrew Steele', 'shell': '/bin/bash', 'name': 'asteele', 'home': '/home/asteele', 'password': u'$6$Kc8iGUKA$knj5E9Ezx2P/eDmiNdiHdk0lAPNNdLT8T0jGKl678sYJUyg7sCmoTFvFp77ybFpGnFr9K78HgLEvf6E3naJ250', 'id': 2039}) => {"failed": true, "item": {"comment": "Andrew Steele", "home": "/home/asteele", "id": 2039, "name": "asteele", "password": "$6$Kc8iGUKA$knj5E9Ezx2P/eDmiNdiHdk0lAPNNdLT8T0jGKl678sYJUyg7sCmoTFvFp77ybFpGnFr9K78HgLEvf6E3naJ250", "shell": "/bin/bash"}}
msg: invalid key specified: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTboL9bhtPElJaQ05oMbIK5Bmh5UXsYVZp1HfdTvVzJRjkmB3HjZ/32scQ8eQpVub4oDnugfcItJ33tawGvPMJ3nHT/ZJh7u+eRf6zrSQF/NP6NTyy8Qq6AVOsCk4dyhwyG34/ejaB6X6EeS8ClXq3fL089S7PhU2R/GnneAqH16z4RGYUC49er7epqM0sCvtazaepec6nlRagRWe9IHe6cWlmG4fQ4OBvxEbimR6K2PTu2opwwOVF1hng9pn8iDDnIpW8i/wmDahnKUmsksaEv559zr+ffeQMHsSvmp5V7aM4Jb6ozEUGvZ6y15xQTLP/ldSdGiamqapa/Nk4bWnK1Nxn5gV6MqncEM4L9GnqVsCw6dWBgpOG/nFjly3hglduL8pJaheG7rxUw8lZGOvhcvLFZcraxTj4KF6cpi/AHvySL+mu28PPjDkA22lPvKBAU9RUfiDSBvPVxGSzx4aIwEWyGLofbi0wN00dBdRt/skMmzd6ecpIDRts+As78wed32QRDi7kEy2LT3RFk2l2FDxjQ6GgXRu6xmdiPo/srD/qMvg2t7ciDKBcPKJrhI4lGefm7qhIk96XfOnjUyD/dYF6XMLL2QX1ZB/UULBdw4jWbDIxsXnxnFisVqeRwwNGWts4ckca5ozUlQrP9U/+OIZv+pY0RkiQTeMci52xhw== Andrew Steele, Engineer - Quantifind

Looking at the code, I believe it is messing up due to the comma in the comment, see /library/system/authorized_key:

``` python
def parseoptions(options):
    '''
    reads a string containing ssh-key options
    and returns a dictionary of those options
    '''
    options_dict = {}
    if options:
        options_list = options.strip().split(",")
        for option in options_list:
            if option.find("=") != -1:
                (arg,val) = option.split("=", 1)
            else:
                arg = option
                val = None
            options_dict[arg] = val
    return options_dict
```

**Comment by Daemoen** [comment]
Confirmed that https://gist.github.com/jimi-c/154048f2a6eafc4e00d2 will fix the issue, but potentially causes a new issue as well, new ticket: https://github.com/ansible/ansible/issues/4599

**Comment by jctanner** [comment]
@Daemoen Try your test with this patch instead:

https://gist.github.com/jctanner/7087720

<pre>
diff --git a/library/system/authorized_key b/library/system/authorized_key
index 2649426..d9d6160 100644
--- a/library/system/authorized_key
+++ b/library/system/authorized_key
@@ -199,27 +199,43 @@ def parsekey(raw_key):
     of ssh-key options at the beginning
     '''
 
+    VALID_SSH2_KEY_TYPES = [
+        'ecdsa-sha2-nistp256',
+        'ecdsa-sha2-nistp384',
+        'ecdsa-sha2-nistp521', 
+        'ssh-dss',
+        'ssh-rsa',
+    ]
+
+    key = None          # encrypted key string
+    options = None      # connection options
+    key_type = None     # type of ssh key
+    type_index = None   # index of keytype in key string|list
+
     key_parts = shlex.split(raw_key)
-    if len(key_parts) == 4:
-        # this line contains options
-        (options,type,key,comment) = key_parts
-    elif len(key_parts) == 3:
-        # this line is just 'type key user@host'
-        (type,key,comment) = key_parts
-        options = None
-    elif len(key_parts) == 2:
-        # assuming just a type/key with no comment
-        (type,key) = key_parts
-        comment = ""
-        options = None
-    else:
-        # invalid key, maybe a comment?
-        return None
+    for i in range(0, len(key_parts)):
+        if key_parts[i] in VALID_SSH2_KEY_TYPES:
+            type_index = i
+            key_type = key_parts[i]
 
-    if options:
+    # check for options
+    if type_index is None:
+        return None
+    elif type_index == 1:
         # parse the options and store them
+        options = key_parts[0]
         options = parseoptions(options)
-    return (key, type, options, comment)
+    else:
+        options = None
+
+    # get key after the type index
+    key = key_parts[(type_index + 1)]
+
+    # set comment to everything after the key
+    if len(key_parts) > (type_index + 1):
+        comment = " ".join(key_parts[(type_index + 2):])
+
+    return (key, key_type, options, comment)
 
 def readkeys(filename):
</pre>

**Comment by jctanner** [comment]
Tested with:

<pre>
- hosts: el6.lab.net
  gather_facts: False
  tasks:
    - authorized_key: user=root
                      key="ssh-rsa AAAAB1...=="
    - authorized_key: user=root
                      key="ssh-rsa AAAAB2...== comma, separated, comment"
    - authorized_key: user=root
                      key='from="x.lab.net",no-port-forwarding,no-pty ssh-rsa AAAA3...== some,stuff and \#more stuff'
    - authorized_key: user=root
                      key='from="x.lab.net",no-port-forwarding,no-pty ssh-rsa AAAA4...== some, stuff and \#more stuff'
    - authorized_key: user=root
                      key='from="x.lab.net",no-port-forwarding,no-pty ssh-rsa AAAA5...== \#comment'
    - authorized_key: user=root
                      key='from="x.lab.net",no-port-forwarding,no-pty ssh-rsa AAAA6...== some,stuff and \#more stuff'
</pre>

**Comment by jimi-c** [comment]
@jctanner I'm not even sure the patch above is required, I can run your test cases above after merging in @mscherer's patches without error, and the md5 of the generated file is identical every time.

**Comment by jimi-c** [comment]
This should be fixed now, thanks!

**Comment by KamilLelonek** [comment]
Still doesn't work. Removing full name from the public key fixed the problem.

**Comment by abadger** [comment]
Could you open a new bug report with a reproducer and such?  This ticket has been closed for almost a year so the underlying problem this time may well be different.  Thanks!
