### ISSUE TITLE
synchonize module: does not appear to work with localhost ssh connections

### ISSUE THREAD

**Issue by leximayfield** [ansible/ansible#5240]
Simply put, if you attempt to use the synchronize module to a local SSH port, such as when you are trying to use synchronize over Vagrant, the rsync command does not appear to work correctly.  Of course, rsyncing with Vagrant is unnecessary since one can simply mount a shared folder, but if you are using Vagrant to test a deployment script, you probably would prefer things to work the same way.

Here is the sample of my playbook file:

```
  - name: Rsync site to the destination machine
    synchronize: >
      src=../sitedir
      dest=/srv/www/{{ name }}/
      archive=no
      recursive=yes
```

Here is an example of what happens when I attempt to synchronize:

```
TASK: [Rsync site to the destination machine] ****************************
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1386703159.57-189216039108571 && chmod a+rx $HOME/.ansible/tmp/ansible-1386703159.57-189216039108571 && echo $HOME/.ansible/tmp/ansible-1386703159.57-189216039108571']
<127.0.0.1> PUT /var/folders/FW/FWtcHQi9E5enrfES54KWe++++TI/-Tmp-/tmpZFZVGO TO /Users/alex/.ansible/tmp/ansible-1386703159.57-189216039108571/synchronize
<127.0.0.1> PUT /var/folders/FW/FWtcHQi9E5enrfES54KWe++++TI/-Tmp-/tmpCqD8hJ TO /Users/alex/.ansible/tmp/ansible-1386703159.57-189216039108571/arguments
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/alex/.ansible/tmp/ansible-1386703159.57-189216039108571/synchronize /Users/alex/.ansible/tmp/ansible-1386703159.57-189216039108571/arguments; rm -rf /Users/alex/.ansible/tmp/ansible-1386703159.57-189216039108571/ >/dev/null 2>&1']
failed: [default] => {"cmd": "rsync --delay-updates --compress --timeout=10 --recursive --rsh 'ssh  -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' ../sitedir /srv/www/site_dev/", "failed": true, "rc": 12}
msg: rsync: mkdir "/srv/www/site_dev" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at /SourceCache/rsync/rsync-40/rsync/main.c(544) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-40/rsync/io.c(452) [sender=2.6.9]
```

You can tell from the output that the module is attempting to sync between two local filesystem areas instead of from the local filesystem across the SSH tunnel to the proper destination.

I have attempted this with both plain ansible 1.4.1 and using the HEAD version (as of now) of the synchronize module.

**Comment by jctanner** [comment]
@AlexMax can we see how you've defined your hosts in inventory and the rest of the playbook ?

**Comment by leximayfield** [comment]
I use the Vagrant 1.3.5 ansible provisioner, which does not require an inventory.  I would prefer not to share my entire playbook, but if I cut the playbook to just this single task and replace the variable with a proper `site_dev` I get the exact same error.

```
---
- hosts: all
  tasks:
  - name: Rsync site to the destination machine
    synchronize: >
      src=../sitedir
      dest=/srv/www/site_dev/
      archive=no
      recursive=yes
```

**Comment by jctanner** [comment]
@AlexMax How are the hosts defined in inventory?

**Comment by leximayfield** [comment]
Again, I do not keep an inventory, Vagrant keeps track of that bookkeeping, I simply run `vagrant provision`.

However, from looking at line 30 of `synchronize.py`, it looks like `_process_origin` is quite naive in how it determines if it is appropriate to use the `user@host:path` form, and I'm not sure that the function is even reached judging from line 85's `if not dest_host is src_host:` check (since possible the source and destination could be identical when comparing the filesystem to a localhost ssh server).

**Comment by jctanner** [comment]
@AlexMax gothca, I wasn't following you until I just tried it out with a vagrant example.

**Comment by jctanner** [comment]
@AlexMax added some debugging statements to the action plugin. It's not actually calling _process_origin in this case. The issue must be elsewhere. I'm still digging though.

**Comment by jctanner** [comment]
@AlexMax I added dest_port to solve an issue where synchronize was not abiding by the ansible_ssh_port defined in inventory: d22761452948ffddfcadbafd3dd2db94c88e7337

That could have fixed this if vagrant connections were using something other than 127.0.0.1, but unfortunately that is how it works.

In order to make it work for your case, I had to write this patch:

```
diff --git a/lib/ansible/runner/action_plugins/synchronize.py b/lib/ansible/runner/action_plugins/syn
index 0d7fdf0..c6fd3c8 100644
--- a/lib/ansible/runner/action_plugins/synchronize.py
+++ b/lib/ansible/runner/action_plugins/synchronize.py
@@ -27,9 +27,8 @@ class ActionModule(object):
     def __init__(self, runner):
         self.runner = runner

-    def _process_origin(self, host, path, user):
-
-        if not host in ['127.0.0.1', 'localhost']:
+    def _process_origin(self, host, path, user, port=22):
+        if not host in ['127.0.0.1', 'localhost'] or port != 22:
             return '%s@%s:%s' % (user, host, path)
         else:
             return path
@@ -82,7 +81,7 @@ class ActionModule(object):

         if options.get('mode', 'push') == 'pull':
             (dest_host, src_host) = (src_host, dest_host)
-        if not dest_host is src_host:
+        if ( not dest_host is src_host ) or dest_port != 22:
             user = inject.get('ansible_ssh_user',
                               self.runner.remote_user)
             private_key = inject.get('ansible_ssh_private_key_file', self.runner.private_key_file)
@@ -91,7 +90,7 @@ class ActionModule(object):
                 options['private_key'] = private_key

             src = self._process_origin(src_host, src, user)
-            dest = self._process_origin(dest_host, dest, user)
+            dest = self._process_origin(dest_host, dest, user, port=dest_port)

         options['src'] = src
         options['dest'] = dest
```

I have to do some rigorous testing of other synchronize usecases before merging that, but I know it works for this playbook and vagrant:

```
- hosts: all
  tasks:
    - synchronize: src=/tmp/foo dest=/tmp/foo2 dest_port=2222
```

Please patch your checkout of HEAD with the patch above and verify I understand your problem correctly and have understood what would fix it.

**Comment by leximayfield** [comment]
This modification appears to work great!  The command appears to be adjusted correctly!  Thank you!

I am running into another error with this setup, however, dealing with the fact that the module does not appear to respect requests to be run as sudo (like `--rsync-path="sudo rsync"`).  Would you like me to open a new ticket, or can I update this one?

**Comment by jctanner** [comment]
@AlexMax sorry, missed your comment. Please open a new bug.

**Comment by jctanner** [comment]
The suggested patch breaks pull mode for non-localhost test cases. I'll have to rethink a solution for this.

```
TASK: [pull remote:x to remote:y.localhost] ***********************************
failed: [ahost] => {"cmd": "rsync --delay-updates --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' jtanner@127.0.0.2:/tmp/foosrc jtanner@127.0.0.1:/tmp/foodst.localhost", "failed": true, "rc": 1}
msg: The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1166) [Receiver=3.0.9]
```

**Comment by jctanner** [comment]
@AlexMax this should be fixed by 9ce46e5f41d6017f3f12780c97705d103e759dd3

**Comment by leonelgalan** [comment]
I'm on Vagrant and `ansible 1.8.2` and still experiencing the problem. Port 2222 on localhost is forwarded to 22 in the virtual machine.

Inventory

```
127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key 
```

tasks/main.yml

``` yaml
- name: rsync the FE app
  remote_user: deployer
  synchronize:
    src=/Users/username/Documents/workspace/project_fe/dist
    dest=/home/deployer/project_fe
  tags: [fe_deploy]
  register: fe_app_checkout
```

```
TASK: [frontend_deploy | rsync the FE app] ************************************
<127.0.0.1> ESTABLISH CONNECTION FOR USER: deployer
<127.0.0.1> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o Port=2222 -o IdentityFile="/Users/username/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deployer -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1423084658.31-76779962767509 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1423084658.31-76779962767509 && echo $HOME/.ansible/tmp/ansible-tmp-1423084658.31-76779962767509'
<127.0.0.1> PUT /var/folders/78/6351j8t926367p66t59zs71m0000gn/T/tmpaa5Ult TO /home/deployer/.ansible/tmp/ansible-tmp-1423084658.31-76779962767509/synchronize
<127.0.0.1> EXEC ssh -C -tt -vvv -o ForwardAgent=yes -o Port=2222 -o IdentityFile="/Users/username/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=deployer -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/deployer/.ansible/tmp/ansible-tmp-1423084658.31-76779962767509/synchronize; rm -rf /home/deployer/.ansible/tmp/ansible-tmp-1423084658.31-76779962767509/ >/dev/null 2>&1'
failed: [127.0.0.1 -> 127.0.0.1] => {"cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' \"/Users/username/Documents/workspace/project_web_frontend/dist/\" \"/home/deployer/project_fe\"", "failed": true, "rc": 23}
msg: rsync: change_dir "/Users/username/Documents/workspace/project_fe/dist" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]


FATAL: all hosts have already failed -- aborting
```

Because how _synchronize_ treats 127.0.0.1 and localhost, `rsync` is failing because the destination lacks user and host.

`rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' /Users/username/Documents/workspace/project_web_frontend/dist/ deployer@127.0.0.1:/home/deployer/project_fe` works.

**Comment by zpol** [comment]
Hi there! 
It's simple just put a hostname into /etc/hosts ;) 

127.0.0.1 mycoolhostname

**Comment by bitozoid** [comment]
It doesn't work for me. I patched like this to make it work:

``` patch
--- /home/bitozoid/synchronize.py   2015-06-29 15:42:05.831924630 +0100
+++ /usr/lib64/python2.7/site-packages/ansible/runner/action_plugins/synchronize.py 2015-06-29 15:37:36.752538804 +0100
@@ -145,7 +145,7 @@

         # COMPARE DELEGATE, HOST AND TRANSPORT
         process_args = False
-        if not dest_host is src_host and self.original_transport != 'local':
+        if ( ( not dest_host is src_host ) or dest_port != 22 ) and self.original_transport != 'local':
             # interpret and inject remote host info into src or dest
             process_args = True
```

```
$ vagrant --version
Vagrant 1.7.2
$ ansible --version
ansible 1.9.0.1
  configured module search path = None
```

**Comment by tima** [comment]
This might be OK, but I'm a bit concerned there are some sort of other edge cases getting missed. For instance, is there a scenario where the source and destination could be reversed and destination is 22, but source is 2222? If so, this solution would fail. Just a thought.

**Comment by aferrari-technisys** [comment]
Hi, some other way to fix this? I has the same issue.

**Comment by abadger** [comment]
https://github.com/ansible/ansible/pull/14140  should fix the problem of using localhost with alternate ports for different hosts.  That fix is in devel and stable-2.0 and should appear in the 2.0.1 release.

**Comment by ghost** [comment]
I was able to work around this by adding an unexpected entry to my `/etc/hosts` file.
I duplicated the localhost line and renamed it, I choose `localhost2`:

```
# /etc/hosts
127.0.0.1   localhost
127.0.0.1   localhost2
```

Change out the inventory to refer to my vagrant machine as `localhost2`, and synchronize worked.

**Comment by ryanli1994** [comment]
Still have this problem in Ansible 2.3.0.0.

Million thanks to the simple workaround of @ava-dylang !

**Comment by tima** [comment]
@ryanli1994: Please file a new issue with your details. Once an issue is closed any comments made won't show up on the developers' radar. Thanks.
