### ISSUE TITLE
apt_key module should support receiving keys from keyservers

### ISSUE THREAD

**Issue by dlee** [ansible/ansible#5485]
apt_key module should support the following scenario:

```
apt-key adv --keyserver keys.gnupg.net --recv-keys ABCDEF
```

**Comment by mpdehaan** [comment]
That sounds great (but is something we are unlikely to add in the near future), is this is something you would like to work on?

**Comment by resmo** [comment]
@dlee are you working on this? or should I take it?

**Comment by resmo** [comment]
Duplicate of #4810

**Comment by dlee** [comment]
@resmo no, not at the moment. You should take it.

**Comment by mpdehaan** [comment]
Seems like this is resolved via apt_key and such, let me know if you disagree on this, and we're happy to take pull requests for enhnacements too.

**Comment by resmo** [comment]
@mpdehaan No, it is not solved. You are not always able to download a key like the example showd by @shingara. As the cli `apt-key` has also an option for this, `--keyserver` I would like to have it implemented. See my PR #5589.  Thanks.

**Comment by mpdehaan** [comment]
# Closing This Ticket

Hi!

We believe that commits in Ansible 1.6 should resolve this question or problem for you.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
