### ISSUE TITLE
hosts defined in two groups in different inventory files each is used multiple times

### ISSUE THREAD

**Issue by g-k-r** [ansible/ansible#5749]
when using multiple inventory files defining different groups for the same hosts, ansible adds the hosts multiple times to the inventory list.

version: 1.4.4+dfsg-1 (from debian jessie)
same problem with current devel 00b3f627ebb2b8e9cf743671a9ddd2d8d8c9fe45

reproduce: 
- use files from https://gist.github.com/g-k-r/8599442
- run **ansible all --list**
- run **ansible group2 --list** and compare with **ansible type2 --list**

actual output:

``` shell
$ ansible all --list
    www.google.com
    www.yahoo.com
    www.yahoo.com
$ ansible group2 --list
    www.yahoo.com
$ ansible type2 --list
    www.yahoo.com
    www.yahoo.com
```

note when the group is defined in both files like [type1] this does not happen.

``` shell
$ ansible type1 --list
    www.google.com
```

expected output: www.yahoo.com shows up once only i.e.

``` shell
$ ansible all --list
    www.google.com
    www.yahoo.com
$ ansible group2 --list
    www.yahoo.com
$ ansible type2 --list
    www.yahoo.com
```

additional information:

to verify that tasks would actually be executed multiple times use

``` shell
$ ansible all -m debug -a '"msg=TEST {{inventory_hostname}}"'
www.google.com | success >> {
    "msg": "TEST www.google.com"
}

www.yahoo.com | success >> {
    "msg": "TEST www.yahoo.com"
}

www.yahoo.com | success >> {
    "msg": "TEST www.yahoo.com"
}
```

**Comment by sivel** [comment]
Per contributing.md can you please provide your ansible version?  (`ansible --version`)

If I remember correctly, this has been resolved in devel (1.5)

**Comment by jctanner** [comment]
Yes, this was resolved by https://github.com/ansible/ansible/commit/559e89036b98127510794125beeaeebc82e0c141

Please rebase and try again if you are running an older version.

**Comment by g-k-r** [comment]
@sivel: amended the report

**Comment by jctanner** [comment]
@g-k-r this is resolved in devel, and will be in the 1.5 release.

**Comment by g-k-r** [comment]
@jctanner: tested with devel, not solved, will provide unit test in PR based on devel

**Comment by mpdehaan** [comment]
Reopening for testing.

**Comment by jctanner** [comment]
@g-k-r unable to reproduce ...

```
jtanner@u1204:~/issues/5631-duplicate-task-runs$ ansible all -i inventory --list
    www.google.com
    www.yahoo.com
jtanner@u1204:~/issues/5631-duplicate-task-runs$ ansible group2 -i inventory --list
    www.yahoo.com
jtanner@u1204:~/issues/5631-duplicate-task-runs$ ansible type2 -i inventory --list
    www.yahoo.com
```

**Comment by jctanner** [comment]
@g-k-r how do you install ansible and how are you using the checkout to verify devel's behavior?

**Comment by g-k-r** [comment]
I do the following:

``` bash
git clone https://github.com/g-k-r/ansible.git
. ./hacking/env-setup
ansible --version
make tests
```

or instead of `make tests`

``` bash
PYTHONPATH=./lib ANSIBLE_LIBRARY=./library  nosetests -d -v test/TestInventory.py:TestInventory.test_dir_inventory_multiple_groups
```

what is strange, is that testing with the original reproduction tests from the first post on this issue do work as you say, while the test started by nosetests doesn't.

```
PYTHONPATH=./lib ANSIBLE_LIBRARY=./library  nosetests -d -v test/TestInventory.py:TestInventory.test_dir_inventory_multiple_groups
test_dir_inventory_multiple_groups (TestInventory.TestInventory) ... FAIL

======================================================================
FAIL: test_dir_inventory_multiple_groups (TestInventory.TestInventory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gkr/workspaces/ansible_issue_5749/ansible/test/TestInventory.py", line 423, in test_dir_inventory_multiple_groups
    assert actual_host_names == ['zeus','morpheus']
AssertionError: 
    <ansible.inventory.group.Group object at 0x208e2c0> = <ansible.inventory.Inventory object at 0x204c510>.get_group('major-god')
    ['zeus', 'morpheus', 'zeus', 'morpheus'] = [<ansible.inventory.host.Host object at 0x208d050>.name for <ansible.inventory.host.Host object at 0x208d050> in <ansible.inventory.group.Group object at 0x208e120>.get_hosts()];
    print "%s : %s " % (<ansible.inventory.group.Group object at 0x208e120>.name, ['zeus', 'morpheus', 'zeus', 'morpheus'])
>>  assert ['zeus', 'morpheus', 'zeus', 'morpheus'] == ['zeus','morpheus'] 

-------------------- >> begin captured stdout << ---------------------
greek : ['zeus', 'morpheus', 'zeus', 'morpheus'] 

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 0.009s
```

**Comment by g-k-r** [comment]
that is confusing, calling ansible directly succeeds:

```
cd tests
ansible greek --list -i inventory_dir
```

what doesn't work anymore is:

```
$ ansible all -i inventory_dir/ --list-hosts --limit greek
No hosts matched
```

with ansible 1.4.4 this results in:

```
$ ansible all -i inventory_dir/ --list -l greek
    zeus
    morpheus
    zeus
    morpheus
```

**Comment by g-k-r** [comment]
sorry about the many commits, i changed the test which now works identical to direct ansible calls, will now create a pull request, if you want to add the test to the code.
otherwise i think this issue is fixed already and I made a mistake during verification. 
Maybe you'd like to look into why get_group contains the hosts multiple times and why the --limit doesn't seem to work anymore, I could prepare a test again if needed.

thanks!

**Comment by jctanner** [comment]
@g-k-r i think you are mixing up installed ansible lib paths with the checkout lib paths. Can you please retest on a clean machine with a fresh checkout and no ansible packages installed?

**Comment by g-k-r** [comment]
ok i will test in a cleanrooom VM, hopefully tonight otherwise this needs to wait until the week after next

**Comment by g-k-r** [comment]
hi @jctanner i tested in a clean debian wheezy 
only installed ansible dependencies, but not ansible itself as it is not available in pure wheezy.

to test the initial implementation with get_group i had to checkout the second commit in my pull request. since the latest commit overwrites the test implementation to use get_hosts instead of get_group. 

```
$ git clone https://github.com/g-k-r/ansible.git
...
$ git checkout --track origin/test_hosts_defined_in_multiple_groups_in_different_files
...
$ git checkout 3fe1341990babde2b3dd5295bdd3072aac88fec2
...
$ make tests
...
======================================================================
FAIL: test_dir_inventory_multiple_groups (TestInventory.TestInventory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/g-k-r/issue_5749/ansible/test/TestInventory.py", line 423, in test_dir_inventory_multiple_groups
    assert actual_host_names == ['zeus','morpheus']
AssertionError: 
    <ansible.inventory.group.Group object at 0x28d5050> = <ansible.inventory.Inventory object at 0x2736510>.get_group('major-god')
    ['zeus', 'morpheus', 'zeus', 'morpheus'] = [<ansible.inventory.host.Host object at 0x28d2c68>.name for <ansible.inventory.host.Host object at 0x28d2c68> in <ansible.inventory.group.Group object at 0x2848e88>.get_hosts()];
    print "%s : %s " % (<ansible.inventory.group.Group object at 0x2848e88>.name, ['zeus', 'morpheus', 'zeus', 'morpheus'])
>>  assert ['zeus', 'morpheus', 'zeus', 'morpheus'] == ['zeus','morpheus'] 

-------------------- >> begin captured stdout << ---------------------
greek : ['zeus', 'morpheus', 'zeus', 'morpheus'] 

--------------------- >> end captured stdout << ----------------------
```

inventory.get_group is not behaving like i though it should. anyway the get_hosts version (HEAD of the pull request) works.

**Comment by risaacson** [comment]
It looks like there isn't any outstanding issues with this ticket so I am going to close it out based on your final comment here. I don't see the duplication that you are pointing out in the recent branches.

If you are continuing to see problems feel free to ping me @ansible.com and we can sort it out.

**Comment by mpdehaan** [comment]
This sounds like this comment was about a pull request that wasn't applied yet so I'm reopening this one for now, unless we can't reproduce this on head, etc.

**Comment by mpdehaan** [comment]
ok beat me to it, thanks!

**Comment by risaacson** [comment]
Pertaining to the original description of this thread as of 1.5 this is fixed and tests correct.
https://gist.github.com/risaacson/db81aa24b61455bd32e4

After comment 11 you have a few commits that end up being a part of GH-5837. We have made some changes around I cherry picked the changes off into a branch that I am working on un-commenting test_dir_inventory. Your test should be merged as a part of GH-6287. In which you will get credit for the test code.

This issue has wondered a bit but from what I can see there is one remaining question. That question is: Should get_groups return multiple entries?

The answer to this looks to be that based on how it is used internally in inventory/**init**.py that there is a level of reduplication that ends up happening so it isn’t an issue unless you are calling it directly.

So once my PR goes in it will pull in your PR. I hope that I have shed a little bit of light on this.

**Comment by g-k-r** [comment]
@risaacson thanks, information round up appreciated
