### ISSUE TITLE
Inconsistent expansion of the variables in the lookup 'with_items'

### ISSUE THREAD

**Issue by rhaido** [ansible/ansible#5994]
##### Issue Type:

Bug Report
##### Ansible Version:
- Production:

```
/usr/lib/python2.6/site-packages/ansible # ansible --version
ansible 1.4.1
```
- Fresh clone (13.02.2014)

```
 /local/home/mike/dev/ansible-latest/ansible # ansible --version
ansible 1.5 (devel 6f405c8970) last updated 2014/02/13 13:14:25 (GMT +200)
```
##### Environment:

```
# uname -a
Linux xxx.cern.ch 2.6.32-431.3.1.el6.x86_64 #1 SMP Mon Jan 6 11:34:51 CET 2014 x86_64 x86_64 x86_64 GNU/Linux

 # lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: ScientificCERNSLC
Description:    Scientific Linux CERN SLC release 6.5 (Carbon)
Release:    6.5
Codename:   Carbon
```
##### Summary:

Dear Ansible Dev Team,

While migrating code from old ${...} variable expansion to new Jinja2 style {{...}}, I've noticed some incompatibilities with the previous syntax, while I would expect {{...}} be a full equivalent of ${...}, i.e the following case should work just fine:

```
- name: Java JDK installation
  action: yum2 name="{{ item }}" enablerepo=acc-external-do state=installed
  with_items:
     -   - jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }} {{ jdk_next }}

```

where jdk_next is a list of values:

```
jdk_pro: 1.7.0_45
jdk_6: 1.6.0_43
jdk_7: 1.7.0_45
jdk_next:
  - jdk1.7.0_45
```

Unfortunately, **it does not work**.
##### Steps To Reproduce:
- Create the playbook, which uses roles, for example server.yml:

```
-
  hosts: server
  gather_facts: yes
  user: root
  vars:
    local_to_opt: yes
  roles:
    - base
```

And put the mentioned vars in role's "base" vars/ and mentioned task in role's "base" tasks/, as it should be.
- Execute ansible playbook.

```
 ansible-playbook --connection=local server.yml
```
##### Expected Results:

With previous syntax:

```
- name: Java JDK installation
  action: yum2 name="{{ item }}" enablerepo=acc-external-do state=installed
  with_items:
    - jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }} ${jdk_next}
```

\- the result is just fine:

```
PLAY [server] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [base | Java JDK installation] ****************************************** 
ok: [127.0.0.1] => (item=jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 jdk1.7.0_45)

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

With the code written in Jinja2 style, I've received with the bad result:

```
PLAY [server] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [base | Java JDK installation] ****************************************** 
failed: [127.0.0.1] => (item=jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 ['jdk1.7.0_45']) => {"failed": true, "item": "jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 ['jdk1.7.0_45']"}
msg: ['jdk1.7.0_45'] packages has been failed for installation;

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/server.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   
```

Then, even more interesting: I found, that it's not possible anymore specify variable enclosed in {{..}} as a first member of iteration sequence like this:

```
- name: Java JDK installation
  action: yum2 name="{{ item }}" enablerepo=acc-external-do state=installed
  with_items:
    - {{ jdk_next }} jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }}
```

The result is a syntax error:

```
ERROR: Syntax Error while loading YAML script, /var/lib/ansible/roles/base/tasks/main.yml
Note: The error may actually appear before this position: line 596, column 22

  with_items:
    - {{ jdk_next }} jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }} ${jdk_next}
```

While the old syntax was ok:

```
PLAY [server] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [base | Java JDK installation] ****************************************** 
ok: [127.0.0.1] => (item=jdk1.7.0_45 jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 jdk1.7.0_45)

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

Quick debug & hacking showed the following things:
- if you use original anisble syntax, the file expansion string, which arrives in the variable _varname_ of the template() function of utils/template.py, is `[u'jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 jdk1.7.0_45']`, which is correct
- if you use jinja2 syntax, the final expansion string, which arrives in the variable _varname_ of the template() function of utils/template.py is `[u"jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 ['jdk1.7.0_45']"]` which is incorrect.

I do not have comments about SyntaxError I've provided earlier as I have no time to debug it :(
##### Workaround

This hack is acceptable but still ugly - the idea is to use the join() Jinja2 filter, i.e. the following code:

```
- name: Java JDK installation
  action: yum2 name="{{ item }}" enablerepo=acc-external-do state=installed
  with_items:
    - jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }} {{ jdk_next | join(' ') }}
```

works:

```
PLAY [server] ***************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [base | Java JDK installation] ****************************************** 
ok: [127.0.0.1] => (item=jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 jdk1.7.0_45)

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
Looks like you have a weird list here:

```
     -   - jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }} {{ jdk_next }}
```

**Comment by mpdehaan** [comment]
As this is a rather long example and I'm having a little bit of trouble processing it, could you possibly put these into a gist that can demonstrate the expected behavior?

**Comment by rhaido** [comment]
Hello Michael,

**About the list**: it's the list of JDK rpms, which I install on our production machines: jdk{{ jdk_pro}} current production version, for example jdk1.7.0_45, then default jdk 1.6 for compat reasons, jdk 1.7 for future compatibility issues, and {{ jdk_next }} - this is the list of the JDKs rpms intented for testing.

**About the Gist** - let me do it tomorrow midday. I'll put there the "good" example and the "bad" one. 

But basically, the idea is the following: if one uses ${var} in with_items lookup like this:

```
- action: ...
  with_items:
    - xx yy zz ${var}
```

\- and if var is a list ['a','b','c','d'], it correctly expands in a string, i.e. "a b c d", i.e. the final result will be:

```
...
    - xx yy zz a b c d
```

While if the {{var}} is used, the result is a string: "['a','b','c','d']", i.e.

```
...
    - xx yy zz "['a','b','c','d']"
```

which is incompatible with original behaviour.

**Comment by rhaido** [comment]
https://gist.github.com/rhaido/9001645

**Comment by tonk** [comment]
I would like to add another inconsistency:

In a playbook I have

```
- hosts: all
   vars_files:
      - [
          "vars/{{ ansible_hostname }}",
          "vars/{{ ansible_os_family }}",
        ]

  tasks:
      - name: install ssh server
        action: ${ansible_pkg_mgr}
                pkg={{ ssh_pkg }}
                state=present

      - name: deploy ssh configuration
        template: src=sshd_config.j2
                  dest=/etc/ssh/sshd_config
                  owner=root
                  group=root
                  mode=0440
        notify: restart sshd

      - name: ensure sshd is running
        service: name={{ ssh_srv }}
                 state=started
```

This works when I use the variable as `${ansible_pkg_mgr}`, but because of consistency I would expect `{{ ansible_pkg_mgr }}`.

**Comment by efine** [comment]
Isn't some of this to do with valid YAML syntax?

```
action: {{ ansible_pkg_mgr }}
```

is invalid YAML because the opening brace at the start of the line makes YAML think it is going to see a dictionary. Try the above in http://yaml-online-parser.appspot.com/ and there will be a syntax error:

```
ERROR:

while constructing a mapping
  in "<unicode string>", line 1, column 9:
    action: {{ ansible_pkg_mgr }}
            ^
found unacceptable key (dict objects are unhashable)
  in "<unicode string>", line 1, column 10:
    action: {{ ansible_pkg_mgr }}
             ^
```

OTOH, this works fine:

```
action: "{{ ansible_pkg_mgr }}"
```

and so does this:

```
action: >
    {{ ansible_pkg_mgr }}
```

**Comment by tonk** [comment]
@efine: I tried

```
action: "{{ ansible_pkg_mgr }}"
    pkg={{ ssh_pkg }}
```

with result 

```
ERROR: Syntax Error while loading YAML script, /etc/ansible/playbooks/ssh/main.yml
Note: The error may actually appear before this position: line 15, column 17
```

So I tried the second option, you supplied

```
action: >
    {{ ansible_pkg_mgr }}
    pkg={{ ssh_pkg }}
```

and that works fine.

I'm not that into Yaml, but there seems to be a difference between your parsing engine and mine.

I use Python 2.6.6 on CentOS 6.5 (64 bit) and PyYAML 3.10-3

Thanks for the help. I'll read up on Yaml.

**Comment by efine** [comment]
Surrounding the whole expression with quotes fixes that issue. That is equivalent to using the `>` block literal construct, but messier. The online parser uses the [YAML 1.2](http://www.yaml.org/spec/1.2/spec.html) spec, which seems to be the latest, so if there is a difference, I'm not sure where it arises.

```
action: "{{ ansible_pkg_mgr }} pkg={{ ssh_pkg }}"
```

**Comment by efine** [comment]
@rhaido If you use `with_flattened` instead of `with`, it should solve the problem.

**Comment by rhaido** [comment]
Hello,

Let me test the proposed solutions, and I'll return with the report ASAP (preferably, tomorrow).

Thanks one more time!

**Comment by rhaido** [comment]
Dear colleagues,

Usage of `with_flattened` statement doesn't fix the initially described issue, i.e. the result is the following:

`failed: [127.0.0.1] => (item=jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 ['jdk1.7.0_45']) => {"failed": true, "item": "jdk1.7.0_45 jdk1.6.0_43 jdk1.7.0_45 ['jdk1.7.0_45']"}`

Please note, that {{ jdk_next }} is expanded as ['jdk1.7.0_45'], i.e. as a string representation of Python structure, either then a space-separated list of values, like it was before with ${} operator. Enclosing {{ jdk_next }} statement inside double quotes doesn't make any difference.

**Comment by mpdehaan** [comment]
Sorry for delay in response as we have a large queue and have been concentrating on some priority tickets.

So the above is most definitely a quoting issue with the brackets, which the system will warn about when it can.

"I would like to add another inconsistency"

Patches to add more inconsistencies will be accepted!   Just kidding.

The list pasted above is really botched up:

```
- name: Java JDK installation
  action: yum2 name="{{ item }}" enablerepo=acc-external-do state=installed
 with_items:
     -   - jdk{{ jdk_pro }} jdk{{ jdk_6 }} jdk{{ jdk_7 }} {{ jdk_next }}
```

First off, this should really be a list, and it's not, it's a list of strings with spaces in it that ends in a list.

Also this part:

```
where jdk_next is a list of values:
jdk_pro: 1.7.0_45
jdk_6: 1.6.0_43
jdk_7: 1.7.0_45
jdk_next:
  - jdk1.7.0_45
```

This defines all of the above as variables except jdk_next is itself a list.

As such, there's nothing sensible ansible can really do here given the random mix of string inputs and lists and everything.

In the future, if you have "how do I do this" kind of questions and want quicker resolution, I'd highly recommend the mailing list -- it does not look like there is a bug here.

**Comment by rhaido** [comment]
Dear Michael & Ansible team,

As you had stated correctly, jdk_next is itself the list. If you use
${jdk_next} within 'with_' lookup, it's converted to space-separated string
of list members, i.e. 'item1 item2 item3 etc', which is correct. If you use
{{ jdk_next }} statement, it's converted to the string '[ member1, member2,
member3, etc ]' in ansible - please, note the square brackets - which is
incorrect from ansible point of view, what error messages prove.\

So, as I've demonstrated, the behaviour changed in transition from ${ ... }
to {{ ... }}, that's why I've obviously called it "inconsistency". From my
point of view,  it's quite a serious change, as it breaks previous
production code, and is worth be at least mentioned somewhere; or to leave
the old-style ${ ... } variable expansion in place and do not remove it in
future.

Thank you for your understanding and have a good day!

Mikhail Grozak.
