### ISSUE TITLE
"No such file or directory" error when installing packages via the apt module

### ISSUE THREAD

**Issue by jorisvddonk** [ansible/ansible#6385]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
(error also occurs on 1.5, but not on 1.4.4)
##### Environment:

Running ansible from Ubuntu 12.10
Managing Ubuntu 12.10
(the host that's running ansible and the host that's being managed are the same host; this is a local playbook)
##### Summary:

Installing packages via the apt module seems to not work correctly, and returns with the following error: "[Errno 2] No such file or directory"
##### Steps To Reproduce:
1. Install Ansible 1.6/1.5 on a clean Ubuntu 12.10 machine
2. Run ansible-playbook with a task that uses the apt module. I used [this playbook](https://gist.github.com/jorisvddonk/9482514).
##### Expected Results:

No error occurred, and the package(s) are correctly installed. In the example above, I'd expect 'mc' to be installed.
##### Actual Results:

```
joris@host:~$ sudo ansible-playbook foo.yml --connection=local -i inventory

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [Install package via apt] ***********************************************
failed: [127.0.0.1] => {"cmd": "DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical /usr/bin/apt-get -y -o     Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install mc", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/joris/foo.retry

127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by lordfolken** [comment]
Exactly my problem as well. I think it tries to execute the cmd as a whole in quotation marks.

**Comment by sashka** [comment]
I've faced the same problem in Ansible 1.5.1. 
Ansible 1.5.0 doesn't have this problem.

**Comment by absoludity** [comment]
@lordfolken is close. The quotes around the package names are being escaped:

> /home/ubuntu/.ansible/tmp/ansible-tmp-1394531361.66-98224470549287/apt(266)install()
> -> if default_release:
> (Pdb) p cmd
> 'DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical /usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install \'unzip\' '
> (Pdb) p "%s" % packages
> "'unzip' "
> (Pdb) p '%s' % packages
> "'unzip' "
> (Pdb) p '"Something" %s' % packages
> '"Something" \'unzip\' '
> (Pdb) c
> {"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": ["DEBIAN_FRONTEND=noninteractive", "DEBIAN_PRIORITY=critical", "/usr/bin/apt-get", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "unzip"], "rc": 2}

**Comment by drybjed** [comment]
Confirming bug on current devel release, running on Ubuntu 12.04: https://travis-ci.org/ginas/ginas/builds/20390404

**Comment by mpdehaan** [comment]
I'm confused between a comment above saying this occurs on 1.5 -- I haven't heard the report of this -- and another above that says this does not, and also not seeing 'mc' escaped above.

Regardless, we are looking into this now.

**Comment by mpdehaan** [comment]
Ok, it appears the security fix to not run things through the shell did not consider how environment variables were being passed yet.  I'm disappointed with the testing from us here and we'll get to the bottom of why this was allowed to go out.  In the meantime, we can set the environment though os.environ and I'm working on making this happen.

**Comment by jorisvddonk** [comment]
@mpdehaan: regarding my report of this bug occurring on 1.5: the bug occurs on ansible from package _ansible=1.5.2-quantal-unstable1_ from [ppa:rquillo/ansible](https://launchpad.net/~rquillo/+archive/ansible), which claims to be "ansible 1.5" when asked for a version number via `ansible --version`.

**Comment by mpdehaan** [comment]
Rodney should not be packaging the 1.5.2 branch as at this time it was a release branch to prepare for future development.

What is happening is right now I've fixed the code on the development and 1.5.2 branches already and am working on a release.   This will be 1.5.2

I am VERY sorry about this and will address the test oversight with my team.   The apt module should always be at the absolute top of our list of things to verify, and in fact our automation should have caught this as well.

Again, very sorry and getting this release out as fast as I can and I will email the list.

**Comment by mpdehaan** [comment]
This release is now up on releases.ansible.com and pypi.

I'm going to leave this up for a while today to reduce any reports on the existing ticket for the short term, so people can see this.

Please try 1.5.2 via pip or releases.ansible.com if you are having any apt problems with 1.5.1 (which you will have).

If there is something in a PPA called 1.5.2 already hopefully that PPA can be updated -- but it sounds like what @jorisvddonk mentioned above isn't the right thing, and this may cause confusion.  We are going to be creating our own PPA soon so there's less confusion there.

**Comment by sashka** [comment]
@mpdehaan In a test Vagrant environment the bug is still in Ansible 1.5.2

```
asd@mokotemac ~/P/n/v/project:end-of-holidays> ansible --version
ansible 1.5.2
asd@mokotemac ~/P/n/v/project:end-of-holidays> vagrant provision
==> default: Running provisioner: ansible...

PLAY [Set the locale] ********************************************************* 

TASK: [create locale.gen] ***************************************************** 
ok: [default] => {"changed": false, "gid": 1000, "group": "vagrant", "mode": "0600", "owner": "vagrant", "path": "/etc/locale.gen", "size": 285, "state": "file", "uid": 1000}

PLAY [Set the time zone] ****************************************************** 

TASK: [set /etc/localtime to Europe/Moscow] *********************************** 
<127.0.0.1> REMOTE_MODULE command /bin/cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
changed: [default] => {"changed": true, "cmd": ["/bin/cp", "/usr/share/zoneinfo/Europe/Moscow", "/etc/localtime"], "delta": "0:00:00.001968", "end": "2014-03-11 17:10:19.972214", "rc": 0, "start": "2014-03-11 17:10:19.970246", "stderr": "", "stdout": ""}

TASK: [set /etc/timezone to Europe/Moscow] ************************************ 
ok: [default] => {"changed": false, "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/timezone", "size": 14, "state": "file", "uid": 0}

PLAY [Set repos and packages] ************************************************* 

GATHERING FACTS *************************************************************** 
<127.0.0.1> REMOTE_MODULE setup
ok: [default]

TASK: [apt update_cache=yes] ************************************************** 
<127.0.0.1> REMOTE_MODULE apt update_cache=yes
ok: [default] => {"changed": false}

TASK: [apt upgrade=yes] ******************************************************* 
<127.0.0.1> REMOTE_MODULE apt upgrade=yes
failed: [default] => {"cmd": ["DEBIAN_FRONTEND=noninteractive", "DEBIAN_PRIORITY=critical", "/usr/bin/aptitude", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "safe-upgrade"], "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/asd/initial-setup.yaml.retry

default                    : ok=5    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by pjan** [comment]
@mpdehaan I just updated to the latest build (pip), but the bug is still here (on vagrant, physical machine and travis.

Sample output:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [AnsiblesBox]

TASK: [Ansibles.cron | Cron | Make sure cron is installed] ******************** 
ok: [AnsiblesBox]

TASK: [Ansibles.cron | Cron | Make sure cron is enabled] ********************** 
changed: [AnsiblesBox]

TASK: [Ansibles.tmpreaper | Tmpreaper | Make sure tmpreaper is installed] ***** 
failed: [AnsiblesBox] => {"cmd": ["DEBIAN_FRONTEND=noninteractive", "DEBIAN_PRIORITY=critical", "/usr/bin/apt-get", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "tmpreaper"], "failed": true, "item": "", "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/pjan/vagrant.retry
```

**Comment by jorisvddonk** [comment]
@sashka @pjan @mpdehaan: can confirm that the bug still appears on 1.5.2 from PYPI.

**Comment by sivel** [comment]
From the looks of it, the fix from c09d4b1c7a8494f961ae9e071f89c95a4a944002 never made it into the 1.5.2 branch.  Seems as though 1.5.2 was largely the same code as 1.5.1 with a version bump.

https://github.com/ansible/ansible/compare/release1.5.1...release1.5.2

**Comment by python-consulting** [comment]
Bug still in 1.5.2 from pypi, just tested now.

**Comment by jctanner** [comment]
I have confirmed that the fix did not make it to 1.5.2. I will get this resolved.

**Comment by python-consulting** [comment]
There is a bug in the commit c09d4b1, the APT_ENVVARS is mispelled.

**Comment by dmourati** [comment]
What is a workaround, this is blocking my work today. I've tried pip install, git install, and source tarball install, all still fail for me.

**Comment by drybjed** [comment]
@dmourati If you really need, I think reverting back to v1.5.0 should be enough to make it work again.

**Comment by jjshoe** [comment]
@dmourati pip uninstall ansible ; pip install ansible==1.5.0

**Comment by sivel** [comment]
Per the last email, the 1.5.2 package on pypi was fixed.  Although I am unsure how long it may take to expire on the pypi CDN.

There is also releases.ansible.com. Pip can install a tar.gz file from any location.

**Comment by sashka** [comment]
Thanks! Tarball from releases.ansible.com perfectly works.

**Comment by mpdehaan** [comment]
Correct, this was updated about 10:50 eastern daylight time this morning and a new release pushed out to pypi after removing the old package to correct something missing in the cherry-pick

I'm hoping the CDN does the right thing for everyone soon.

**Comment by matteosister** [comment]
1.5.2 fixed the problem for me...

:+1: for an official ppa!

**Comment by mpdehaan** [comment]
Yep, working on that.

Rodney just mentioned he would update his PPA very soon as well.  I'm still going to leave this open for a bit just so people can read.

**Comment by jxdx** [comment]
I'm having the same issue on Ubuntu 12.04 using the latest branch.
If I use Ansible 1.6 I do not have the issue.

**Comment by mpdehaan** [comment]
"I'm having the same issue on Ubuntu 12.04 using the latest branch."

I'm not sure what you mean with the "latest branch", but I assume you mean the rquillo PPA?

I just got an email from Rodney that he had uploaded 1.5.2 so this should now be available there.

You can also get 1.5.2 from pip or releases.ansible.com if you are having trouble, but PPA should be updated now.

Let me know if you still have problems.

**Comment by mpdehaan** [comment]
This should be all fixed up now in both the 1.5.3 PPA and the devel branch.
