### ISSUE TITLE
1.5.1 breaks gathering facts with accelerate

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#6447]
##### Summary:

Gather facts doesn't work with accelerate mode anymore. ;( 
##### Steps To Reproduce:

Run any playbook with a gather_facts: true and acelerate: true.
##### Expected Results:

facts are gathered. 
##### Actual Results:

Traceback and failure. 

Note that on rawhide this fails with a slightly better message: 

GATHERING FACTS **************************************************************\* 
fatal: [td] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394647490.11-221539994973934 && echo $HOME/.ansible/tmp/ansible-tmp-1394647490.11-221539994973934, exited with result 127

**Comment by mpdehaan** [comment]
So 1.5.1/2 has a fair degree of issues about "~/" and the like being expanded which are now fixed on the development branch as a result of the security upgrades.

We are currently working on a 1.5.3 release that addresses this with the intent on releasing this tomorrow.

For now, this should be addressed on the development branch -- if you have a chance to test, we'd appreciate it.

**Comment by nirik** [comment]
I can confirm that devel works ok on rhel6 with accelerate here. 
Oddly, Fedora rawhide fails still with the same error, but that might be an unrelated issue... will dig more as time permits.

**Comment by mgcrea** [comment]
It's not working for me on latest OSX:

``` bash
$ ansible-playbook --version
ansible-playbook 1.6
```

regular playbook

``` bash
$ ansible-playbook -i inventory playbook.yml --tag accelerated --limit cubieboard

PLAY [Setup ansible accelerated mode] ***************************************** 

GATHERING FACTS *************************************************************** 
ok: [cubieboard-a]
ok: [cubieboard-b]
```

accelerated playbook

``` bash
$ ansible-playbook -i inventory playbook.yml --tag player

PLAY [Execute app playbook] *************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [cubieboard-a] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394734712.05-175358078816456 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1394734712.05-175358078816456 && echo $HOME/.ansible/tmp/ansible-tmp-1394734712.05-175358078816456, exited with result 2
fatal: [cubieboard-b] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1394734712.06-219121998963827 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1394734712.06-219121998963827 && echo $HOME/.ansible/tmp/ansible-tmp-1394734712.06-219121998963827, exited with result 2
```

Tried `rm -rf ~/.ansible` or switching to `/tmp` with no lucky

Failing commands do work if I copy/paste them in bash

**Comment by mpdehaan** [comment]
This should be resolved on 1.5.3 already, in queue to triple check and verify.

(1.6 is the development version so may not have all commits at the point in time tested)

**Comment by nirik** [comment]
Oddly, I am still seeing the failure on rawhide, even with 1.5.3... will try and dig in and see if it's some local breakage or what...

**Comment by mgcrea** [comment]
I do confirm that it is not fixed in latest 1.5.3, I'm also having weird `host not found` issues when trying to use the `--connection accelerate` flag.

**Comment by jctanner** [comment]
The fix for this appears to be 0556c53f7878c9ac2a59100c2752785482e806aa which hasn't made it into a release quite yet.

**Comment by jctanner** [comment]
@mgcrea and @nirik are either of you able to test with 0556c53 applied or with the latest devel to confirm the fix?

**Comment by nirik** [comment]
I can confirm the fix here. With latest devel both el6 and fedora rawhide work with accelerate again. ;)

**Comment by jctanner** [comment]
@nirik great, @jimi-c will slate this for the next bugfix release. Thanks for testing.

**Comment by mgcrea** [comment]
@jctanner still not working for me:

``` bash
PLAY [Execute base playbook] ************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [player-a] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1396431655.06-174981569529308 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1396431655.06-174981569529308 && echo $HOME/.ansible/tmp/ansible-tmp-1396431655.06-174981569529308, exited with result 2
```

``` bash
$ ansible --version
ansible 1.5.4
```

I'm using macports SSH on latest mavericks (not sure if it can have an impact

```
$ ssh -V
OpenSSH_6.6p1, OpenSSL 1.0.1f 6 Jan 2014
```

---

Edit: just found out that `v1.5.4` does not appear to have the fix. However it was release 12h ago?

**Comment by shtirlic** [comment]
Ubuntu 14.04 remote, maverick host with ansible 1.5.5, same problem when accelerated enabled.

**Comment by jimi-c** [comment]
@shtirlic we're going to be releasing 1.6.0 before the end of the month, which should include this fix.

**Comment by mgcrea** [comment]
@jimi-c Using `1.6.1` I'm still having issues with accelerated mode:
- acceletare: true

``` bash
$ ansible-playbook -c ssh -i inventory playbook.yml --limit player --tag setup

PLAY [Execute base playbook] ************************************************** 

GATHERING FACTS *************************************************************** 
failed: [player-a] => {"failed": true, "parsed": false}
invalid output was: [sudo via ansible, key=uarxvlqtbguyhrxgrliuektbkoymkgky] password: 
```
- acceletare: false

``` bash
$ ansible-playbook -c ssh -i inventory playbook.yml --limit player --tag setup

PLAY [Execute base playbook] ************************************************** 

GATHERING FACTS *************************************************************** 
ok: [player-a]
```

**Comment by jimi-c** [comment]
@mgcrea could you please open a new issue for this, with details on your configuration and any other info that might be helpful in reproducing it? Thanks!

**Comment by mpdehaan** [comment]
This seems to be accelerated mode not having support for --ask-sudo-pass.

Which I believe is still the case, right?

I agree it's something we ought to look into, though accelerate mode is still a nice stopgap until RHEL everwhere can have new enough SSH to where it's no longer needed due to ControlMaster/ControlPersist :)

C'mon RHEL7!

**Comment by mgcrea** [comment]
@mpdehaan, indeed, thought I'm not using `--ask-sudo-pass`, I do have a `groups_vars/all.yml` with `ansible_sudo_pass: "foobar"`.
