### ISSUE TITLE
ansible-playbook ignores --limit option

### ISSUE THREAD

**Issue by ovcharenko** [ansible/ansible#6449]
##### Issue Type:

BugReport
##### Ansible Version:

ansible 1.6 (d37f0c6d12)
##### Environment:

N/A
##### Summary:

ansible-playbook ignores --limit option.
##### Steps To Reproduce:

ansible-playbook hosts.yaml --limit=boo
##### Expected Results:

PLAY [Localhost] **************************************************************
skipping: no hosts matched

PLAY [All servers] ************************************************************
##### Actual Results:

PLAY [Localhost] **************************************************************

TASK: [setup] *****************************************************************
ok: [localhost]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by mpdehaan** [comment]
Can you please share your playbook?

**Comment by ovcharenko** [comment]
It's pretty simple:

```
- name: Localhost
  hosts: localhost
  sudo: no
  gather_facts: false
  tasks:
    - action: setup

- name: All hosts
  hosts: all
  sudo: no
  gather_facts: false
  tasks:
    - action: setup
```

**Comment by gildegoma** [comment]
I confirm that this bug is present since Ansible 1.5.0.
I think that this bug only affects `localhost` target, in its two variants:
- "implicit" `localhost` (new feature #3129)
- `localhost` defined in the inventory

**Little Tip:** 
You can add `localhost` to the `--limit` (e.g. `--limit='group1:localhost'`) to avoid the fatal abortion of the `localhost` play. That can help if your `--limit` is intended to filter other plays than localhost ones...

**Comment by risaacson** [comment]
Based on the playbook above I have confirmed that running on an OS X 10.9.2 host the following:

```
WORKS ansible 1.5 (release1.5.0 6221a2740f) last updated 2014/03/13 16:51:49 (GMT -500)
FAILS ansible 1.5.1 (release1.5.1 7ad9598fe8) last updated 2014/03/13 16:52:50 (GMT -500)
FAILS ansible 1.5.2 (release1.5.2 a9762357f9) last updated 2014/03/13 16:53:01 (GMT -500)
WORKS ansible 1.5.3 (release1.5.3 fc02883017) last updated 2014/03/13 17:03:42 (GMT -500)
WORKS ansible 1.6 (devel 316d1ca977) last updated 2014/03/13 16:46:55 (GMT -500)
```

This should be fixed as of the release today. Can you confirm on your system or pass on information for what you are running it on?

**Comment by gildegoma** [comment]
I've verified ansible 1.5.3 and 1.6 (devel 9eb3f8779c), and the same error remains:

`FATAL: all hosts have already failed -- aborting` when `localhost` plays are executed with a `--limit` argument.

I've also created #6479, which includes a first possible fix, which should also help to confirm the expected behavior. Hope it helps...

**Comment by risaacson** [comment]
What OSes and versions are you running this on?

**Comment by risaacson** [comment]
I see the error. Hmm. . . Will look at the PR today.

**Comment by gildegoma** [comment]
With https://github.com/risaacson/ansible/compare/devel...inventory_localhost_in_subset (up to 44b0a75), I observe following problems:

`--limit=all` (or any valid limit, e.g. `--limit=machine1` if machine1 is in the inventory): still not working

```
PLAY [Localhost] ************************************************************** 

TASK: [setup] ***************************************************************** 
ok: [localhost]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

`--limit=localhost` : The second play ([All hosts]) should be skipped, as an implicit localhost is not member of `all` in [Ansible 1.5+](http://blog.ansibleworks.com/2014/02/28/ansible-1-5-released/)

```
PLAY [Localhost] ************************************************************** 

TASK: [setup] ***************************************************************** 
ok: [localhost]

PLAY [All hosts] ************************************************************** 

TASK: [setup] ***************************************************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by risaacson** [comment]
I need to think about what the fix for --limit=all would be though it seems like a problem that only one or two people would end up hitting and they would be wrong to do it that way. It is a fair edge case though.

--limit=localhost should work as shown. When an implicit localhost is created and added to the inventory in the ungrouped group which follows while ungrouped should be apart of the all group.

**Comment by gildegoma** [comment]
Maybe I'm missing something, but I do think that both are true problems. I try to explain it better:

> I need to think about what the fix for --limit=all [...]

As mentioned above, the error is not specific to `--limit=all`. For instance, you get the same problem with `--limit=machine1` (assuming that machine1 is in your inventory).

> --limit=localhost should work as shown. [...]

The `localhost` target is not part of [All hosts] hosts, and I don't think that the purpose of `--limit=localhost` is to modify the host list of this play.
Such result is also not coherent with the case where ansible-playbook is executed without any `--limit` argument:

```
PLAY [Localhost] ************************************************************** 

TASK: [setup] ***************************************************************** 
ok: [localhost]

PLAY [All hosts] ************************************************************** 

TASK: [setup] ***************************************************************** 
ok: [machine2]
ok: [machine1]

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
machine1                   : ok=1    changed=0    unreachable=0    failed=0   
machine2                   : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by mikehaas763** [comment]
Just want to be subscribed to this issue, not sure how else to do it.

**Comment by hkariti** [comment]
Update for 1.8.4 and latest dev: --limit on localhost plays doesn't fail anymore, but --limit is simply ignored and the play is run anyway

**Comment by jimi-c** [comment]
As far as I can tell, this appears to be working as expected in the current devel branch (v2/ansible 2.0). 

<pre>
# ansible-playbook -vv 6449.yml --limit=awxlocal
2 plays in 6449.yml
PLAY: Localhost *****************************************************************
skipping: no hosts matched
PLAY: All hosts *****************************************************************
TASK [setup] ********************************************************************
ok: [awxlocal]
PLAY RECAP **********************************************************************
awxlocal                   : ok=1    changed=0    unreachable=0    failed=0   
</pre>

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by elfassy** [comment]
same issue: ansible-playbook ingnores the --limit option
(ansible 1.8.4)

**Comment by jaddison** [comment]
This is still an issue in ansible 1.9.3. Can this be re-opened?

**Comment by jimi-c** [comment]
Per our usual policy, we close issues when they have been resolved in the devel branch.
