### ISSUE TITLE
add_host only executed for the first host

### ISSUE THREAD

**Issue by flyinva** [ansible/ansible#6912]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

debian 7.4
##### Summary:

Task `add_host` is only executed on first host from inventory.
##### Steps To Reproduce:

With the playbook `addhost.yml` :

``` yaml

---
- hosts: all
  tasks:
    - name: add host in group
      add_host: name={{ inventory_hostname}} groups=newgrp
    - name: debug groups
      debug: var=groups
```

and inventory file `addhost_inventory`

```
vm1
vm2
```

Launch `ansible-playbook -i addhost_inventory addhost.yml`
##### Expected Results:

`vm1` and `vm2` should be added to group `newgrp`
##### Actual Results:

Task `add_host` is only executed on first and only first host (vm1) is added to `newgrp`. I also tried adding two new hosts and only the first one is created.

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [vm1]
ok: [vm2]

TASK: [add host in group] ***************************************************** 
ok: [vm1]

TASK: [debug groups] ********************************************************** 
ok: [vm1] => {
    "groups": {
        "all": [
            "vm1", 
            "vm2"
        ], 
        "newgrp": [
            "vm1"
        ], 
        "ungrouped": [
            "vm1", 
            "vm2"
        ]
    }
}
ok: [vm2] => {
    "groups": {
        "all": [
            "vm1", 
            "vm2"
        ], 
        "newgrp": [
            "vm1"
        ], 
        "ungrouped": [
            "vm1", 
            "vm2"
        ]
    }
}

PLAY RECAP ******************************************************************** 
vm1                        : ok=3    changed=0    unreachable=0    failed=0   
vm2                        : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
The add_host module is something called "bypass host loop" and is intended for use in plays of the form:

```
- hosts: localhost
  tasks:
     - provisioning_module: ...
       register: instances
     - add_host: foo ...
       with_items: instances
```

This is because of the way the non-shared memory architecture must work.

If you'd like to set variables in a group, you can use "set_fact"

Another amazing module is group by, so

```
- hosts: web
  tasks:
     - set_fact: asdf=0
     - set_fact: asdf=1
       when: x == 2
     - group_by: key=asdf-{{ asdf }}

- hosts: asdf-0
  tasks:
     - shell: echo on this host asdf was equal to 0

- hosts: asdf-1
  tasks:
     - shell: echo on this host asdf was equal to 1
```

This will achieve your purpose above.

In general, "add_host" is for niche provisioning cases only, and can't be made to work in the above fashion, even if we'd want it to.

I'll consider how to make this a bit more apparent in the docs.

**Comment by flyinva** [comment]
Thank's a lot, set_fact seems the right way. 

You're explanation about "bypass host loop" modules could appear in the docs to avoid misunderstanding.

**Comment by jimi-c** [comment]
I'm going to go ahead and close this as it seems your issue has been resolved. If you'd like to open another issue regarding the documentation feel free. If you have any other questions related to this issue let us know, thanks!

**Comment by m-o-e** [comment]
+1 for adding a visible disclaimer to the docs.

This behavior leads to subtle bugs
that can easily go unnoticed. 

In my case I had this sequence:
1. ec2 exact_count=n (...) / register ec2results
2. wait_for / with_items ec2results.instances
3. add_host / with_items ec2results.instances
4. command / with_items ec2results.instances

2 and 4 saw all instances.

3 only saw the instances from the first invocation of 1.

**Comment by jjaone** [comment]
In my `ansible-playbook` I encountered this problem where `add_host` does not see the whole inventory. 
I still don't understand how to achieve the same dynamic behavior where new hosts should be added to groups using `set_facts` and `group-by`..
Specifically, which facts should I set to achieve the same as with `add_host`, that in my case is used like this:

```
- name: Register new LXCs to inventory`
    add_host:
      ansible_user: "{{ item.item.value.operuser }}"
      name: "{{ item.lxc_container.ips.0 }}"
      groups: "lxcs"
      srvname: "{{ ansible_host }}"
  with_items: "{{ lxcs_info.results }}"
```

The `lxs_info.results` var has all the data needed for this task to run, but the "add_host" does not run for the rest of the hosts, but only to first in the inventory.

So please, how can I do this with `set_facts` + `group_by` -method as suggested by @mpdehaan, thanks! 

ping: @jimi-c

**Comment by jimi-c** [comment]
@jjaone this is more of a question for the mailing list:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

**Comment by toadjaune** [comment]
@jjaone : I just encountered a similar issue, but since I had to do it from _within_ a role, there was no way for me to use `set_facts` and `group_by`.

Here is how I worked around it :

```
- name: My task
  add_host: 
    name: "{{ item }}"
    groups: my-group
  with_items: "{{ ansible_play_hosts }}"
```

Which will apply this task to every host the play applies to ... which is basically the same thing as if the task wasn't bypassing the host loop.
Be careful however, I guess this may cause issues with things such as conditional inclusions or limited maximum simultaneous hosts.

The great thing is that you can even add a condition depending on the host you're trying to add ; for example, I did something like this : 

```
- name: My task
  add_host: 
    name: "{{ item }}"
    groups: my-group
  when: hostvars[item]['my-variable']
  with_items: "{{ ansible_play_hosts }}"
```

Which allow me to do what I wanted : inside a role, check the value of a variable, and if it is true, dynamically add the host to an inventory.

**Comment by jjaone** [comment]
@toadjaune Thanks for your suggestion, but I don't still see how that could resolve my aim to be able to add "new hosts dynamically to inventories and groups"..? 

In your task, the "ansible_play_hosts" contains all the existing hosts (from the static inventory of the playbook) and they get added to the "my-group" in th My-Task, right?  

Where as my example code above depicts a case where the playbook before this task has constructed a list of LXCs (the defintions of which are in the lxcs_info.results var), from which I want to dynamically and inside the playbook to add to a group of their own.

Please note, that in http://docs.ansible.com/ansible/playbooks_variables.html it is said that:
"[the variable} 'ansible_play_hosts' is the full list of all hosts still active in the current play.", so how could it be used to add new hosts to any groups or the inventory of the playbook?

Based on that, your code just "adds" all the existing hosts to a new group, but still only in one of the hosts in inventory (which is exactly the problem in the OP too), so it seems that your solution it is not preventing it bypassing the host loop after all..!? Maybe I'm understanding your code wrongly, any clarification is highly appreciated though, if u care to answer ;)

@jimi-c  I agree that this discussion should have been continued in those groups that you linked to but I just wanted to answer the above comment here, so as to make sure that my reply reaches the other members that have been writing here. 

Edit: posted this question here_ https://groups.google.com/forum/#!topic/ansible-project/o8RFljC5UYI

**Comment by kvaps** [comment]
+1
Why it so limited by one host? - I think that this is wrong behavior.
What if I need to ad all vms discovered from hipervisors?
[This](https://github.com/ansible/ansible/issues/6912#issuecomment-253176893) trick will not help in this case.

**Comment by kvaps** [comment]
Hi, I fond the solution:

```yaml
#!/usr/bin/ansible-playbook
---

- name: Generating hosts
  hosts: hypervisors
  gather_facts: no
  tasks:

    - name: Exclude skip_nodes
      shell:
        cmd: onevm list -l NAME,IP --csv | tail -n +2 | sed s/^/{{inventory_hostname}},/g
      changed_when: false
      register: onevm

    - add_host:
        name: "{{ name }}"
        groups: "{{hypervisor}}:vms"
        ansible_ssh_host: "{{ ip }}"
      vars:
        hypervisor: "{{ item.split(',')[0] }}"
        name: "{{ item.split(',')[1] }}"
        ip: "{{ item.split(',')[2] }}"
      with_items: "{{ hostvars | json_query('*.onevm.stdout_lines') | regex_replace('\"') }}"
      changed_when: false

- name: Executing tasks
  hosts: "*vms"
  gather_facts: no
  tasks:

    - debug: msg="whoa!"
```
