### ISSUE TITLE
lineinfile should follow symlinks

### ISSUE THREAD

**Issue by lfrancke** [ansible/ansible#6986]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

CentOS 6.5
##### Summary:

When using the `lineinfile` mode to edit a symlink it "materializes that file destroying the symlink.
##### Steps To Reproduce:

```
- name: Ensure that transparent hugepage compaction is turned off on reboot
  lineinfile: dest=/etc/rc.d/rc.local regexp='^.*transparent_hugepage.*$' line='echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag'
```
##### Expected Results:

Change of the existing file at `/etc/rc.d/rc.local` which is symlinked to `/etc/rc.local` or a warning.
##### Actual Results:

On a CentOS/RHEL machine `/etc/rc.local` is usually a symlink to `/etc/rc.d/rc.local`. When using the `lineinfile` module to change `/etc/rc.local` it destroys the symlink and instead creates a new _normal_ file with the correct content.

**Comment by timrobertson100** [comment]
+1

**Comment by jeanregisser** [comment]
+1

**Comment by rishid** [comment]
I have been burned by this as well while modifying /etc/rc.local

**Comment by bcoca** [comment]
This should already be fixed by 3770813c (in 1.6.0), as it uses os.path.realpath which is symlink aware.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by rahul0705** [comment]
@bcoca just wanted to leave this comment for future people who are using older versions. This is not fixed in 1.6.0, according to your link it is fixed for 1.7.0+ (at least according to the tags)
