### ISSUE TITLE
ec2_group always detects a change even if there is none

### ISSUE THREAD

**Issue by jaimegago** [ansible/ansible#7309]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 12.04
##### Summary:

Tasks running the ec2_group module always detect a change even when there is none
##### Steps To Reproduce:

Running this playbook more than once:

```

---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "testing change detection"
      ec2_group:
        description: "foo"
        name: "bar"
        state: "present"
        rules:
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: "0.0.0.0/0"
        vpc_id: "vpc-12345678"
        region: us-east-1
```
##### Expected Results:

I would have expected only the first run (when the group is being created) to be a change but not the second run or any other after the first one. 
##### Actual Results:

The runs always shows the task as detecting a change.

**Comment by jaimegago** [comment]
More on this, the change is detected because I have not specified rules_egress but I do have a vpc specified. Security groups in VPC always have an rules_egress set, so the fix here would be to check when vpc_id is specified but no rules_egress is specified then don't detect a change (or something amongst these lines...)
In any case the following playbook works (as in it doesn't detect a change when run the second time) 

```
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "testing adding rules to existing sec group"
      ec2_group:
        description: "foo"
        name: "bar"
        state: "present"
        vpc_id: "vpc-1234567"
        region: "us-east-1"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "0.0.0.0/0"
        rules_egress:
        - proto: all
          cidr_ip: "0.0.0.0/0"
```

**Comment by jimi-c** [comment]
Wish I had seen your comment earlier, it would have saved me some chasing. The above patch should resolve this issue for you. If you continue having any problems with this, please let us know. Thanks!

**Comment by jmou** [comment]
I appear to still have this issue on ansible 1.9.1. Specifying rules_egress works around the issue.

**Comment by glnds** [comment]
Subscribing.
This is idd pretty annoying. Especially since in my use case i first create all groups and only afterwards assign rules to them.  Using this approach the tasks are being flagged as changed all the time. 

```
- name: ensure the elastic loadbalancer security group is present
  ec2_group:
    name: ELBSG
    description: ELB security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    purge_rules: False
    purge_rules_egress: False
  register: elb_sg
```
The rules are only defined after all groups are created, needed for group referral
```
- name: ensure the elastic loadbalancer securty group rules are configured
  ec2_group:
    name: ELBSG
    description: ELB security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ webserver_sg.group_id }}"
      - proto: tcp
        from_port: 8443
        to_port: 8443
        group_id: "{{ webserver_sg.group_id }}"
```

**Comment by xenithorb** [comment]
Indeed, @jimi-c  this seems to be happening again with: https://github.com/ansible/ansible/issues/20120
