### ISSUE TITLE
vSphere_guest  Config mismatch for vm_disk: size_gb

### ISSUE THREAD

**Issue by oheinz** [ansible/ansible#7385]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.1
devel branch
##### Environment:

Debian wheezy 7.5
##### Summary:

Some similar int casting bugs have already been fixed in pull/7190.
##### Steps To Reproduce:

Use a variable for Disk size:

```
   vm_disk:
     disk1:
       size_gb: "{{ vm_disk_size }}"
```
##### Expected Results:

Create a guest with specified disk size.
##### Actual Results:

Play fails with error:
msg: Config mismatch for vm_disk on [('size_gb', <type 'int'>)]

**Comment by mpdehaan** [comment]
Suspect this is because the module isn't casting.

**Comment by jimi-c** [comment]
The above patch should fix this issue. If you continue having problems related to this issue, please let us know. Thanks!

**Comment by oheinz** [comment]
Sorry, with current devel branch  I still get the exact same error.

The error is raised in config_check. To me  it seems as if config_check still checks if the value is int as defined in main's proto_vm_disk.

When i change the proto_vm_disk type for size_gb from int to basestring it works. But I'm not sure if this is the right solution. Though I don't understand why it seems to work for 
        'memory_mb': int,
        'num_cpus': int,
although I pass them as Jinga substituted variables as well ?! But as I don't speak python there is a lot of guessing involved.

**Comment by jimi-c** [comment]
I've also merged in the above patch to address the config check issue. The check will now attempt to cast the value to the type specified and will only mark the value as missing if that fails as well. Please let us know if you are still seeing any problems related to this issue after testing this patch. Thanks!
