### ISSUE TITLE
Daisychaining incompatible with argument checking

### ISSUE THREAD

**Issue by Ernest0x** [ansible/ansible#746]
Commit 8700de9 introduces a bug for any module that daisychains to another module (e.g. 'copy' module daisychaining to 'file' module), because they don't include in the legal inputs the arguments of the module next in the daisychain. For example, when using the 'group'  argument in the 'copy' module, we get an  "unsupported parameter for module: group" error.

**Comment by mpdehaan** [comment]
Oh, that new stuff about argument checking.   Point.    That's from last night, I'll temporarily disable that part until I can figure out what to do with it.

**Comment by mpdehaan** [comment]
done, fixed it the right way too -- file module now ignores "bonus" arguments.

**Comment by Ernest0x** [comment]
I' m afraid it is not fixed yet for modules that daisychain to file. Check it with the copy module. The checks running e.g. inside 'copy' module are not aware of 'file' module args.

**Comment by Ernest0x** [comment]
To fix this (and possibly other problems of similar nature), I propose the following, rather small, changes in modules:
- Make argument_spec a global var of the module.
- Modules that daisychain to another module can then import agument_spec from that module and merge it with their own argument_spec. This requires that both modules of the daisychain are copied to the targets, before the execution of the first module (in case this does not work as so, already).
- Modules like the 'file' module that are the ones to which other modules chain to, are fixed the way you fixed file module (ignoring bonus args).

**Comment by mpdehaan** [comment]
Are you sure? 

I checked it with template and set the owner just fine.

**Comment by mpdehaan** [comment]
On Wednesday, August 1, 2012 at 8:57 AM, Petros Moisiadis wrote:

> To fix this (and possibly other problems of similar nature), I propose the following, rather small, changes in modules:
> - Make argument_spec a global var of the module.

strongly dislike globals.

> - Modules that daisychain to another module can then import agument_spec from that module and merge it with their own argument_spec. This requires that both modules of the daisychain are copied to the targets, before the execution of the first module (in case this does not work as so, already).

modules intentionally don't require other modules, so imports aren't possible like that, unfortunately.   But it's also useful or performance the way things work, and I don't want to change that.

**Comment by mpdehaan** [comment]
Here is the commit:

https://github.com/ansible/ansible/commit/0a3ebdb6d54ce19d492334ed79aecc2aa97876de

I tried copy src=/tmp/splat dest=/tmp/splat1 owner=mdehaan
and it worked fine

also with owner=root

The copy module doesn't understand "owner", file does, so that seems
to pass through fine.

I also passed the file module a random argument that is not real
"blippy=foo" and it took that fine.

On Wed, Aug 1, 2012 at 8:22 AM, Petros Moisiadis
reply@reply.github.com
wrote:

**Comment by Ernest0x** [comment]
I have applied the patch but I still get "unsupported parameter for module: group" in copy module. For me, it makes sense that it _does_ not work, because the 'self._legal_inputs' list inside 'copy' module is populated from the argument_spec of the 'copy' module which does not contain the args for 'file' module.

**Comment by Ernest0x** [comment]
> modules intentionally don't require other modules, so imports aren't possible like that, unfortunately.   But it's also useful >or performance the way things work, and I don't want to change that.

Then maybe some magic that injects the arguments of the last in the daisychain module inside the argument_spec of the first module, before transfering it to the targets, should do the trick.

**Comment by mpdehaan** [comment]
I see, we need to disable checking for the _copy_ module as well, because that was yelling about invalid arguments.

Not sure what I was testing wrong, but I've commented this out for now.

**Comment by mpdehaan** [comment]
Petros, 

I think the problem in my testing is I was using a dest= that already existed, so the copy module didn't need to trigger, and it daisy chained directly into file.

Sorry for the oversight.

We can add the valid file parameters to the copy/template/get_url module or something to get this back operational.
