### ISSUE TITLE
zypper_repository running a second time gives an error message

### ISSUE THREAD

**Issue by valentinogagliardi** [ansible/ansible#7689]
Seems that zypper_repository is not idempotent as expected. Running a zypper_repository task multiple times gives:

"Repository named 'reponame' already exists. Please use another alias."

P.S.: I'm aware that the error can be bypassed with ignore_errors: yes

**Comment by jimi-c** [comment]
Could you run the command `/usr/bin/zypper lr --uri` and share the output and return code? Also, on what version of SuSE/opensuse are you running this module?

**Comment by valentinogagliardi** [comment]
Hello.
Platform: OpenSuse 13.1 x64.

Running the playbook for the first time and all works fine:

```
TASK: [icinga2-ansible | Get Icinga2 RPM Key on Suse OS family] *************** 
changed: [suse]

TASK: [icinga2-ansible | Get Icinga2 Repo on Suse OS family] ****************** 
changed: [suse]
```

Second run of the playbook raise the error (in the meantime I'm using ignore_errors: yes):

```
TASK: [icinga2-ansible | Get Icinga2 RPM Key on Suse OS family] *************** 
ok: [suse]

TASK: [icinga2-ansible | Get Icinga2 Repo on Suse OS family] ****************** 
failed: [suse] => {"failed": true, "item": ""}
msg: Repository named 'icinga-stable-release' already exists. Please use another alias.

...ignoring
```

Output of `/usr/bin/zypper lr --uri`

```
#  | Alias                         | Nome                                  | Abilitato | Aggiornamento | URI                                                            
---+-------------------------------+---------------------------------------+-----------+---------------+----------------------------------------------------------------
 1 | download.opensuse.org-non-oss | Main Repository (NON-OSS)             | Sì        | Sì            | http://download.opensuse.org/distribution/13.1/repo/non-oss/   
 2 | download.opensuse.org-oss     | Main Repository (OSS)                 | Sì        | Sì            | http://download.opensuse.org/distribution/13.1/repo/oss/       
 3 | download.opensuse.org-update  | Main Update Repository                | Sì        | Sì            | http://download.opensuse.org/update/13.1/                      
 4 | icinga-stable-release         | ICINGA (stable release for openSUSE1) | Sì        | Sì            | http://packages.icinga.org/openSUSE/13.1/release/              
 5 | openSUSE-13.1-1.10            | openSUSE-13.1-1.10                    | Sì        | Sì            | http://download.opensuse.org/distribution/13.1/repo/oss/       
 6 | repo-debug                    | openSUSE-13.1-Debug                   | No        | Sì            | http://download.opensuse.org/debug/distribution/13.1/repo/oss/ 
 7 | repo-debug-update             | openSUSE-13.1-Update-Debug            | No        | Sì            | http://download.opensuse.org/debug/update/13.1/                
 8 | repo-debug-update-non-oss     | openSUSE-13.1-Update-Debug-Non-Oss    | No        | Sì            | http://download.opensuse.org/debug/update/13.1-non-oss/        
 9 | repo-source                   | openSUSE-13.1-Source                  | No        | Sì            | http://download.opensuse.org/source/distribution/13.1/repo/oss/
10 | repo-update-non-oss           | openSUSE-13.1-Update-Non-Oss          | Sì        | Sì            | http://download.opensuse.org/update/13.1-non-oss/ 
```

Kind regards.

**Comment by jimi-c** [comment]
And what was the return code of the zypper command?

**Comment by valentinogagliardi** [comment]
```
# echo $?
0
```

**Comment by hacosta** [comment]
This may be a duplicate of:

https://github.com/ansible/ansible/pull/7914

@valentinogagliardi can you test that patch?

**Comment by photoninger** [comment]
I ran into the same problem today.
The patch in https://github.com/ansible/ansible/pull/7914 looks good on my SLES11.3 machine.

**Comment by jimi-c** [comment]
Based on @photoninger's feedback, I've gone ahead and merged in #7914, so this issue should be resolved. Please let us know if you continue seeing any problems related to this issue. Thanks!

**Comment by uhmfa** [comment]
Hi, this is still failing, on SLES 12_SP2, using ansible 2.1.0.0.
fatal: [sles12sp2]: FAILED! => {"changed": false, "failed": true, "msg": "Repository named 'server_monitoring_zabbix' already exists. Please use another alias.\n"}

**Comment by jctanner** [comment]
@fedealaimo this issue is closed. Please open a new issue in https://github.com/ansible/ansible-modules-core/issues
