### ISSUE TITLE
debug: var=ansible_facts traceback

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#7732]
##### Summary:

I just created a task to check if there's an ansible_facts variable, and it breaks Ansible.
##### Steps To Reproduce:

Running this playbook:

```
- hosts: localhost
  tasks:
    - debug: var=ansible_facts
```
##### Expected Results:

message from debug and normal exit
##### Actual Results:

```
$ ansible-playbook -i localhost_inv ansible_facts.yml

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [debug var=ansible_facts] *********************************************** 
ok: [localhost] => {
    "ansible_facts": "{{ ansible_facts }}"
}
Traceback (most recent call last):
  File "/home/tomek/ansible/ansible/bin/ansible-playbook", line 320, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/tomek/ansible/ansible/bin/ansible-playbook", line 260, in main
    pb.run()
  File "/home/tomek/ansible/ansible/lib/ansible/playbook/__init__.py", line 323, in run
    if not self._run_play(play):
  File "/home/tomek/ansible/ansible/lib/ansible/playbook/__init__.py", line 677, in _run_play
    if not self._run_task(play, task, False):
  File "/home/tomek/ansible/ansible/lib/ansible/playbook/__init__.py", line 475, in _run_task
    self.SETUP_CACHE[host].update(facts)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by mscherer** [comment]
Indeed, i can reproduce on git HEAD. The problem is there:

https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/debug.py#L55

Since ansible_facts is used to communicate facts from modules ( http://jpmens.net/2012/07/15/ansible-it-s-a-fact/ ), the debug module should use a different way ( ie, not foo=value ). But doing this would break the interface. This is however not documented ( http://docs.ansible.com/debug_module.html ).

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by tazle** [comment]
The original problem (unable to debug var=ansible_facts) seems to still occur with 2.0.1.0

**Comment by listx** [comment]
It also happens with 2.1.1.0. Here is what I get back with -vvv:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 486, in _execute
    vars_copy.update(result['ansible_facts'])
ValueError: dictionary update sequence element #0 has length 1; 2 is required

fatal: [mongo]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

**Comment by mscherer** [comment]
Can people reopen a new issue ?

**Comment by netvisao** [comment]
:+1:  Occurs on ansible 2.1.2.0

```
ansible all -i hosts -b -m debug -a 'var=ansible_facts' -vvv -f 4 --check
Using /etc/ansible/ansible.cfg as config file
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 498, in _execute
    vars_copy.update(result['ansible_facts'])
ValueError: dictionary update sequence element #0 has length 1; 2 is required

<host> | FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```
