### ISSUE TITLE
ec2_vpc without subnets results in traceback error

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#7905]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Ansible is running on Fedora 20 targetting the AWS API.
##### Summary:

Running an ec2_vpc task without subnets results in a traceback error even though the documentation says it's not required.
##### Steps To Reproduce:

Run a task like this:

``` yaml
    - name: Get VPC information for new servers
      local_action:
        module: ec2_vpc
        state: present
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
```
##### Expected Results:

Different things depending on what's already in AWS, but it shouldn't fail with a traceback.
##### Actual Results:

Fails with a traceback like:

```
invalid output was: Traceback (most recent call last):
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403545469.33-20457236170147/ec2_vpc", line 2030, in <module>
    main()
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403545469.33-20457236170147/ec2_vpc", line 601, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403545469.33-20457236170147/ec2_vpc", line 337, in create_vpc
    for subnet in subnets:
TypeError: 'NoneType' object is not iterable
```

It seems the module expects a list of subnets to exist, but the documentation clearly says they aren't required.

**Comment by jimi-c** [comment]
Have you tried this with devel? I believe we've fixed this issue there.

**Comment by mpeters** [comment]
Nope, still a problem:

```
$ ansible --version
ansible 1.7 (devel 52c7d50f1e) last updated 2014/06/23 15:30:30 (GMT -400)
```

test.yml has

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get VPC information for new servers
      local_action:
        module: ec2_vpc
        state: present
        vpc_id: "{{ vpc_id }}"
        region: "us-east-1"
```

Still results in this:

```
$ ansible-playbook test.yml -e 'vpc_id=vpc-bca270d9'

PLAY [localhost] ************************************************************** 

TASK: [Get VPC information for new servers] *********************************** 
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403553204.71-8966695626261/ec2_vpc", line 2100, in <module>
    main()
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403553204.71-8966695626261/ec2_vpc", line 601, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/home/mpeters/.ansible/tmp/ansible-tmp-1403553204.71-8966695626261/ec2_vpc", line 337, in create_vpc
    for subnet in subnets:
TypeError: 'NoneType' object is not iterable


FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
You're right, there's another issue related to the route_tables option, and something else was fixed regarding both of these fields. A similar fix to that in #7712 should be all that's required. I'll look into fixing both of these at once.

**Comment by jimi-c** [comment]
Actually, I believe the fix is to simply assign a default value for both:

<pre>
diff --git a/library/cloud/ec2_vpc b/library/cloud/ec2_vpc
index 5383f38..e161ff0 100644
--- a/library/cloud/ec2_vpc
+++ b/library/cloud/ec2_vpc
@@ -408,7 +408,7 @@ def create_vpc(module, vpc_conn):
     if route_tables and not isinstance(route_tables, list):
         module.fail_json(msg='route tables need to be a list of dictionaries')
     
-# Work through each route table and update/create to match dictionary array
+    # Work through each route table and update/create to match dictionary array
     all_route_tables = []
     for rt in route_tables:
         try:
@@ -561,11 +561,11 @@ def main():
             wait_timeout = dict(default=300),
             dns_support = dict(type='bool', default=True),
             dns_hostnames = dict(type='bool', default=True),
-            subnets = dict(type='list'),
+            subnets = dict(type='list', default=[]),
             vpc_id = dict(),
             internet_gateway = dict(type='bool', default=False),
             resource_tags = dict(type='dict'),
-            route_tables = dict(type='list'),
+            route_tables = dict(type='list', default=[]),
             state = dict(choices=['present', 'absent'], default='present'),
         )
     )
</pre>

Let me know if that gets you past the above error.

**Comment by mpeters** [comment]
That does get past the error, but I think it misses a bigger opportunity: to clarify/distinguish what it means to not provide a list of subnets/route_tables vs providing an empty list for both. Otherwise it becomes next to impossible to get information about an existing VPC without already having a lot of information about it.

See https://groups.google.com/forum/#!topic/ansible-devel/Xzc_Sq9SF24

**Comment by jimi-c** [comment]
Yep, I saw your email, though I believe that is something of a different issue from a traceback. I think https://github.com/ansible/ansible/pull/7327 is more along the lines of what you're wanting, and should be a separate issue from this. Ideally, if you simply specify `state=present` and nothing needs to be changed, the returned data would contain all of the relevant info about the vpc.

Again, that would be a feature request, and not a bug, so please open a second issue if that's more along the lines of what you're looking for. I will get the above patch merged in ASAP to correct the bugs.

**Comment by mpeters** [comment]
I agree that the 2 are separate issues, but since this bug blocks the module from actually being used with no subnets fixing it this way defines what having no subnets means... which is exactly the same as having an empty list of subnets. But you're right, doing anything but fixing it this way is a feature request and would require more discussion about how to do it. I'll add more information to my email to ansible-devel.

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!
