### ISSUE TITLE
problem when using apt_key module with keyserver

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#7936]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Ubuntu 14.04
##### Summary:

Trying to use apt_key module to get the equivalent of `sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9` fails with an error.

I've put what goes into recv-keys above into the id attribute, because there is no recv-keys attribute of the module. Should there be?
##### Steps To Reproduce:

Add key for Docker repository

```
- name: Add Docker key
  sudo: true
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
```
##### Expected Results:

No error message in Ansible run and apt key for Docker has been added
##### Actual Results:

```
failed: [localhost] => {"failed": true, "id": "36A1D7869245C8950F966E92D8576A8BA88D21E9", "item": ""}
msg: key does not seem to have been added

FATAL: all hosts have already failed -- aborting
```

**Comment by rightaway** [comment]
There should really be a `recv-keys` parameter added to `apt_key` module, so that it acts like the `apt-key` command. `id` parameter should be used to specify the key id found by `apt-key list` so that Ansible knows that the system already has the key specified in `recv-keys` parameter.

**Comment by mpdehaan** [comment]
I'm not sure it needs a new option at all, but we can try to replicate this and see what the problem is.

**Comment by mpdehaan** [comment]
Should be fixed per the linked ticket above, let us know if not, thanks!

**Comment by cespare** [comment]
In case anyone else is having trouble finding the "linked ticket" (it's not actually linked), the relevant PR is #7949.

**Comment by cespare** [comment]
FWIW, even after merging #7949 I still can't get this to work. I'm running the exact same command as the OP (trying to add the Docker apt key) and I get

```
failed: [my.host.example.com] => {"failed": true, "traceback": "Traceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1413919946.57-259947856296250/apt_key\", line 158, in download_key\n    return rsp.read()\nAttributeError: 'NoneType' object has no attribute 'read'\n"}
msg: error getting key id from url: hkp://keyserver.ubuntu.com:80
```
