### ISSUE TITLE
Issue with printing unicode non-english characters

### ISSUE THREAD

**Issue by alozovskoy** [ansible/ansible#8425]
##### Issue Type:

Bug Report
##### Ansible Version:

$ ansible --version
1.7
##### Environment:

RHEL 5
##### Summary:

Ansible cant correctly print an non-english characters, returned UnicodeDecodeError.
##### Steps To Reproduce:

Use non-english characters to printing in, f.e., debug module. A similar problem was in issue #6842.
##### Expected Results:

```
$ ansible 127.0.0.1 -m debug -a "msg=АБВГД"
127.0.0.1 | success >> {
    "msg": "АБВГД"
}
```
##### Actual Results:

```
$ ansible 127.0.0.1 -m debug -a "msg=АБВГД"
127.0.0.1 | FAILED => Traceback (most recent call last):
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/__init__.py", line 558, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/__init__.py", line 663, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/__init__.py", line 881, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/action_plugins/debug.py", line 41, in run
    kv = utils.parse_kv(module_args)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/utils/__init__.py", line 698, in parse_kv
    args = args.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4: ordinal not in range(128)
```

**Comment by mpdehaan** [comment]
Thanks, we're on it!

**Comment by jimi-c** [comment]
You're using the devel branch, however what is your most recent commit? I believe we fixed this here: 63bcbd0af253c1f82354962f7df6570b431f47e8

**Comment by mpdehaan** [comment]
I can still reproduce this.

**Comment by jimi-c** [comment]
Yes I see where the issue is. I've got a patch for this, which I'm testing now.

**Comment by jimi-c** [comment]
I have pushed the above commit, which should resolve this issue. If you continue seeing any problems related to this issue, please let us know. Thanks!

**Comment by alozovskoy** [comment]
@jimi-c
First, now i've got this error:

```
$ ansible local -m debug -a "msg=АБВГД"
localhost | FAILED => Traceback (most recent call last):
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/__init__.py", line 557, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/__init__.py", line 662, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/__init__.py", line 833, in _executor_internal_inner
    conn = self.connector.connect(actual_host, actual_port, actual_user, actual_pass, actual_transport, actual_private_key_file)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/connection.py", line 31, in connect
    conn = utils.plugins.connection_loader.get(transport, self.runner, host, port, user=user, password=password, private_key_file=private_key_file)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/utils/plugins.py", line 180, in get
    self._module_cache[path] = imp.load_source('.'.join([self.package, name]), path)
  File "/home/ansible/ansible/lib/python2.6/site-packages/ansible-1.7-py2.6.egg/ansible/runner/connection_plugins/paramiko_ssh.py", line 42, in <module>
    from ansible.module_utils.basic import atomic_move
ImportError: cannot import name atomic_move
```

Second, a commit not solved this problem:

```
$ ansible local -m debug -a "msg=ABCDE" --connection=local
127.0.0.1 | success >> {
    "msg": "ABCDE"
}

localhost | success >> {
    "msg": "ABCDE"
}

$ ansible local -m debug -a "msg=АБВГД" --connection=local
127.0.0.1 | success >> {
    "msg": "\u0410\u0411\u0412\u0413\u0414"
}

localhost | success >> {
    "msg": "\u0410\u0411\u0412\u0413\u0414"
}
```

P.S. I used virtualenv if this important.

**Comment by alozovskoy** [comment]
If replase in ansible/runner/connection_plugins/paramiko_ssh.py

```
from ansible.module_utils.basic import atomic_move
```

on this

```
import ansible.module_utils.basic
```

I don't get privous exeption, but now i get

```
Traceback (most recent call last):
  File "<...my ansible path...>ansible/runner/connection_plugins/paramiko_ssh.py", line 388, in close
    tmp_keyfile = tempfile.NamedTemporaryFile()
NameError: global name 'tempfile' is not defined
```

Also, in this case paramiko worked well in first look. Ssh connection type also worked well all time.

**Comment by jimi-c** [comment]
@alozovskoy yes sorry about that, that was a bug from another issue we were working on. It should be resolved now.

**Comment by alozovskoy** [comment]
Yes, first problem was resolved in #8433. A second problem still actual.

**Comment by alozovskoy** [comment]
```
$ ansible 127.0.0.1 -m debug -a "msg=АБВГД"
127.0.0.1 | success >> {
    "msg": "\u0410\u0411\u0412\u0413\u0414"
}
```

```
$ ansible --version
ansible 1.7

$ git log --pretty=oneline -n1
4e6685d77297a85565650abd630e6cda536643bb Merge pull request #8442 from Jmainguy/rpm_key_8424

```

**Comment by mpdehaan** [comment]
Thanks, reopening this one and looking at your ticket!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
