### ISSUE TITLE
group_vars not evaluated for hosts added to group dynamically (edit: add_host module)

### ISSUE THREAD

**Issue by quentinsf** [ansible/ansible#8605]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Mac OS X 10.9.4
Python 2.7.5
##### Summary:

group_vars files do not appear to be evaluated for hosts added to a group dynamically - either using add_hosts or from a dynamic inventory such as ec2.py
##### Steps To Reproduce:

Here's a minimal demo:

```
- hosts: localhost
  tasks:
   - add_host: name=localhost
               groups=demo_group

- hosts: demo_group
  roles:
   # Localhost will ignore group_vars/demo_group 
   # when running this.
   - demo_role
```
##### Expected Results:

If a host is added to a group dynamically, either using the add_host module or by a dynamic inventory such as ec2.py, it will be in that group for the later plays in the playbook, and get assigned appropriate roles etc. It will run the tasks in the roles, and it will get variable values in roles/*/defaults directories.

I would expect it also to get the values from group_vars directories in the same way as if it came from a static inventory file, but it doesn't seem to.
##### Actual Results:

Variables from the role's 'defaults' directory do exist, but any variables defined in group_vars directories do not override them as described in the docs for variable precedence.  The only way I can change them is by using -e on the command line.

I'm guessing the group_vars directories are loaded at the time of loading traditional static inventory files, and are not applied after any more dynamic changes?

This means, for example, that groups defined by ec2.py are fundamentally different from groups defined in an inventory file.  To me, this is unexpected.  But if it is by design, or hard to fix, it should probably be documented.

I'm guessing this may be related to issue #6563 

Many thanks!

**Comment by quentinsf** [comment]
As a neat workaround, I can import the group_vars explicitly in this case:

```
- hosts: localhost
  tasks:
   - add_host: name=localhost
               groups=demo_group
   - include_vars: group_vars/demo_group
```

Slightly more complex if the groups come from a dynamic inventory, though.

And if the inventory and group_vars are in a subdirectory, I'm still stuck: I don't know the path to the groups_vars directory because I don't know which inventory was specified on the command line.

**Comment by mpdehaan** [comment]
The path is available as

{{ inventory_dir }}

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this question or problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by konobi** [comment]
I'm still having an issue with this. I'm adding 2 groups and neither group has been pre-declared using the inventory file.

**Comment by a-chernykh** [comment]
Yeah, still an issue for me as well. I have to run `include_vars` after every `add_host`. I store my group vars in subfolders (`groups_vars/demo/config.yml`), may be that's the reason I am still having it?

**Comment by mgasner** [comment]
also still seeing this issue

**Comment by srgvg** [comment]
Please report a new ticket, with all information on how to reproduce this. Please also confirm which version of ansible you use. Thanks.

**Comment by srgvg** [comment]
@andreychernih subfolders should work fine, this will probably be another issue.
