### ISSUE TITLE
Playbook variables ignored when used vars_files + ansible_os_family

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible#8638]
##### Summary:

Playbook level variable are ignored when we use vars_files with filename defined with {{ansible_os_family}}

If we import variable file with static name (RedHat.yml for example) - no issue
##### Steps To Reproduce:

Test playbook

``` yaml

---

- name: 'Test Precedence'
  hosts: vagrantcentos
  user: vagrant
  sudo: yes

  vars:
    some_var: "foo"

  vars_files:
    - vars/{{ ansible_os_family }}.yml
    #- vars/RedHat.yml
    - vars/other_vars.yml

  tasks: 
    - debug: msg={{some_var}}
      tags:
        - test
```

and additional files
group_vars/all

``` yaml
some_var: "bar"
```

vars/RedHat.yml

``` yaml
useless_var: "oops"
```

vars/other_vars.yml

``` yaml
other_var: "woot"
```
##### Expected Results:

debug message should be
`"msg": "foo"`
this result returned when I comment
`- vars/{{ ansible_os_family }}.yml` line
##### Actual Results:

Unexpectedly we got:
`"msg": "bar"`

**Comment by jimi-c** [comment]
Bisected to 8851ceaa9e9ad6e5052ba8186094fe4fc605f9a2

**Comment by jimi-c** [comment]
@akuznecov I've created the above commit, which resolves the issue in my testing, if you'd like to test it before I merge it in.

**Comment by akuznecov** [comment]
@jimi-c just installed Ansible from your fork (issue_8638_var_precedence_fix branch) and, unfortunately, i still have this bug
group_vars/all + vars_files( with ansible_os_family) + playbook --- value taken from group_vars/all instead of playbook

**Comment by jimi-c** [comment]
@akuznecov that is odd, because when I run a slightly modified version of your example above with my patch, it works as expected:

<pre>
# cat site.yml
---
- name: 'Test Precedence'
  hosts: localhost
  connection: local
  vars:
    some_var: "foo"
  vars_files:
    - vars/{{var_file_var}}.yml
    - vars/{{ ansible_os_family }}.yml
    #- vars/RedHat.yml
    - vars/other_vars.yml
  tasks: 
    - debug: var=some_var
    - debug: var=foo_var
# cat group_vars/all
---
some_var: "bar"
# cat vars/foo.yml
---
some_var: "this is from foo"
foo_var: "this is from foo too"
# cat other_vars.yml
---
var_file_var: "foo"
some_var: "in other vars"
# cat vars/RedHat.yml
---
bad_var: "in RedHat"
</pre>

When run:

<pre>
# ansible-playbook -vv site.yml
PLAY [Test Precedence] ******************************************************** 
GATHERING FACTS *************************************************************** 
<127.0.0.1> REMOTE_MODULE setup
ok: [127.0.0.1]
127.0.0.1: importing vars/RedHat.yml
TASK: [debug var=some_var] **************************************************** 
ok: [127.0.0.1] => {
    "some_var": "in other vars"
}
TASK: [debug var=foo_var] ***************************************************** 
ok: [127.0.0.1] => {
    "foo_var": "this is from foo too"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0
</pre>

**Comment by akuznecov** [comment]
@jimi-c just leave `- vars/{{ ansible_os_family }}.yml` alone

``` yaml
---
- name: 'Test Precedence'
  hosts: localhost
  connection: local
  vars:
    some_var: "foo"

  vars_files:
    #- vars/{{var_file_var}}.yml
    - vars/{{ ansible_os_family }}.yml
    #- vars/RedHat.yml
    #- vars/other_vars.yml

  tasks: 
    - debug: var=some_var
    - debug: var=foo_var
```

and you will see

```
TASK: [debug var=some_var] **************************************************** 
ok: [localhost] => {
    "some_var": "bar"
}

TASK: [debug var=foo_var] ***************************************************** 
ok: [localhost] => {
    "foo_var": "{{ foo_var }}"
}
```

**Comment by jimi-c** [comment]
@akuznecov this is what I would expect, since the RedHat.yml I listed above does not define `some_var`. If I add `some_var: "in RedHat"` to the file, I get the following:

<pre>
TASK: [debug var=some_var] **************************************************** 
ok: [127.0.0.1] => {
    "some_var": "in RedHat"
}
</pre>

which is correct.

**Comment by akuznecov** [comment]
@jimi-c it is correct for specific order, but if you will change order inside of vars_files

``` yaml
---
- name: 'Test Precedence'
  hosts: localhost
  connection: local

  vars:
    some_var: "foo"

  vars_files:
    - vars/{{var_file_var}}.yml
    - vars/other_vars.yml
    - vars/{{ ansible_os_family }}.yml
    #- vars/RedHat.yml


  tasks: 
    - debug: var=some_var
    - debug: var=foo_var
```

you will get negative result
any variable from  `ansible_` family flushes previous definitions 

moreover, with:

``` yaml
---
- name: 'Test Precedence'
  hosts: localhost
  connection: local

  vars:
    some_var: "foo"

  vars_files:
    #- vars/{{var_file_var}}.yml
    #- vars/other_vars.yml
    - vars/{{ some_var }}.yml
    #- vars/RedHat.yml


  tasks: 
    - debug: var=some_var
    - debug: var=foo_var
```

I have funny results:

```
» ansible-playbook -i hosts.akuznecov test-precendence.yml  
ERROR: file could not read: /xxxxxxxx/yyyyyy/vars/this is from foo.yml
```

actually Ansible loaded `vars/foo.yml` :-)

**Comment by jimi-c** [comment]
In your first example, I get the expected result (the some_var from RedHat.yml):

<pre>
$ cat site2.yml 
---
- name: 'Test Precedence'
  hosts: localhost
  connection: local
  vars:
    some_var: "foo"
  vars_files:
    - vars/{{var_file_var}}.yml
    - vars/other_vars.yml
    - vars/{{ ansible_os_family }}.yml
    #- vars/RedHat.yml
  tasks: 
    - debug: var=some_var
$ ansible-playbook -vv site2.yml 
PLAY [Test Precedence] ******************************************************** 
GATHERING FACTS *************************************************************** 
<127.0.0.1> REMOTE_MODULE setup
ok: [127.0.0.1]
127.0.0.1: importing /root/testing/8638/vars/RedHat.yml
TASK: [debug var=some_var] **************************************************** 
ok: [127.0.0.1] => {
    "some_var": "in RedHat"
}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

Your second example is definitely odd. Ansible does multiple passes while templating vars_files, since some variables may be from inventory and tied to a specific host (ie. ansible_os_family). But in this case, when `vars/{{some_var}}.yml` is run through the template engine, `some_var` is set to `foo` since it is in the `vars:` section. But once templated, it should not be run through again, which it appears is the case? I will look into this one.

**Comment by jimi-c** [comment]
@akuznecov I've updated my commit above, if you'd like to test this version out. It resolves the issue you raised with your last example, and works with the rest too.

**Comment by akuznecov** [comment]
@jimi-c great!! i cannot reproduce problems anymore!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dene14** [comment]
Ansible 1.9.4 affected as well

I like the way ansible maintainers solving the issues in... I have already found like 10 dependency cycles when you're going through the chain:
1. "you doing the stuff wrong", please do this in a different way
2. different way, works differently, your stuff doesn't fit it, please use workaround
3. workaround doesn't work... just because.
4. fix proposed and merged
5. fix reverted, like 5 other features just bombed out
6. close with won't fix
7. reopen "guys we really want that fixed"
8. added to the 2.0 milestone

For those who are frustrated as well and want at least a silly workaround right away:
Create another playbook with only this stuff inside:

```
---
- include: your_playbook.yml
```

This will load vars_files as expected.

**Comment by akam-it** [comment]
issue still not resolved (ansible 2.1.0.0)

```
- hosts: test
  vars_files:
    - vars/{{ ansible_os_family }}.yml
  roles:
  ...
```

ERROR! vars file vars/{{ ansible_os_family }}.yml was not found

**Comment by jimi-c** [comment]
@akam-it I cannot reproduce the issue. Using the original playbook example above, this works as expected on my system:

<pre>
ansible-playbook 2.1.1.0 (stable-2.1 6bcdb575e8) last updated 2016/07/04 11:26:11 (GMT -500)
  lib/ansible/modules/core: (detached HEAD a97f4232f6) last updated 2016/07/05 07:50:16 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD 59941469e6) last updated 2016/07/05 07:50:16 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
# cat site.yml 
---
- name: 'Test Precedence'
  hosts: localhost
  connection: local
  vars:
    some_var: "foo"
  vars_files:
    - vars/{{ ansible_os_family }}.yml
    - vars/other_vars.yml
  tasks: 
    - debug: var=some_var
# ansible-playbook -vv site.yml 
Using /etc/ansible/ansible.cfg as config file
PLAYBOOK: site.yml *************************************************************
1 plays in site.yml
PLAY [Test Precedence] *********************************************************
TASK [setup] *******************************************************************
ok: [localhost]
TASK [debug] *******************************************************************
task path: /root/testing/8638/site.yml:16
ok: [localhost] => {
    "some_var": "in other vars"
}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

The `ansible_os_family` fact may be a mix of upper and lower case, can you please confirm that your files match the result of that variable, and also ensure that you have that file for each possible value for all hosts in your inventory?
