### ISSUE TITLE
no_log does not control syslog and not valid at play level

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#8647]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel f4d649bea0) last updated 2014/08/16 20:00:09 (GMT +200)
##### Environment:

Debian GNU/Linux jessie/sid
##### Summary:

`no_log` seems to be broken and still logs to syslog
##### Steps To Reproduce:

Playbook:

```

---
- name: test
  gather_facts: no
  hosts: 127.0.0.1

  tasks:
    - name: testing
      copy: dest=/tmp/test content=123
      no_log: True
```
##### Expected Results:

Nothing in syslog
##### Actual Results:

Syslog says:

```
Aug 16 20:26:00 apollo13 ansible-file[26574]: Invoked with directory_mode=None force=False remote_src=None path=/tmp/test owner=None group=None serole=None content=123 state=None diff_peek=None setype=None dest=/tmp/test selevel=None original_basename=tmpAdXCKS regexp=None validate=None src=tmpAdXCKS seuser=None recurse=False delimiter=None mode=None backup=None
```

Additionally: no_log on the play itself throws: ERROR: no_log is not a legal parameter at this level in an Ansible Playbook -- even though I am running latest devel

**Comment by mpdehaan** [comment]
I can confirm I'm seeing the no_log at play level thing.

We need to look into the syslog handling which may have been damaged in recent parser upgrade use cases.

**Comment by jimi-c** [comment]
@apollo13 can you test with the latest pull from devel? I fixed an error related to check-mode in the copy module yesterday, which also would have affected no_log. Testing this today, and I no longer see the error when no_log is specified on the task:

<pre>
# ansible-playbook -vv 8647.yml 
PLAY [test] ******************************************************************* 
TASK: [testing] *************************************************************** 
ok: [127.0.0.1] => {"censored": "results hidden due to no_log parameter", "changed": false}
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

I also see nothing in syslog.

I do however, still see the issue when no_log is specified at the play level, and am working on correcting that now.

**Comment by apollo13** [comment]
Jupp, nothing in syslog anymore -- though without no_log content still shows up, shouldn't it be hidden all the time: https://github.com/ansible/ansible/blob/devel/library/files/copy#L140 ? Also, could you add tests for sensitive sections like that?

**Comment by jimi-c** [comment]
@apollo13 I've actually tracked that down to another bug, which I've also fixed now as well as added check in the test_copy integration role.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bcoca** [comment]
pr #6117 added at play level, also to config file and docs, it was never merged
