### ISSUE TITLE
s3 module returns NameError: name 'module' is not defined

### ISSUE THREAD

**Issue by davidvasandani** [ansible/ansible#8698]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.1
##### Environment:

CentOS 6.5
##### Summary:

S3 module returns `NameError: name 'module' is not defined`
##### Steps To Reproduce:

```
/opt/wp/virtualenv/hegemon/bin/ansible --inventory /opt/wp/app/hegemon/ansible/hosts.prod --user mozart --private-key /root/.ssh/keys/prod p-backup01 -m s3 -a "aws_access_key=****** aws_secret_key=****** bucket=wp_confluence_backup src=/backup/confluence mode=put"
```
##### Expected Results:

Files are moved to S3.
##### Actual Results:

```
p-backup01 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"<stdin>\", line 132, in <module>\nNameError: name 'module' is not defined\n", 
    "parsed": false
}
```

**Comment by mpdehaan** [comment]
Sounds like the module import is in the wrong spot.  Easy to deal with, thanks!

**Comment by jimi-c** [comment]
@davidneudorfer this error is being triggered because you do not have boto installed. If you install it, you will get past this issue. I am also about to commit a fix for the above traceback.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by davidvasandani** [comment]
@jimi-c I've installed boto but I still have the same issue.

```
(hegemon)[root@m-warp01 hegemon]# ansible --version
ansible 1.7.1
(hegemon)[root@m-warp01 hegemon]# pip install boto
Downloading/unpacking boto
  Downloading boto-2.32.1.tar.gz (7.2MB): 7.2MB downloaded
  Running setup.py egg_info for package boto

    warning: no files found matching 'boto/mturk/test/*.doctest'
    warning: no files found matching 'boto/mturk/test/.gitignore'
Installing collected packages: boto
  Running setup.py install for boto
  ...
Successfully installed boto
Cleaning up...
(hegemon)[root@m-warp01 hegemon]# ansible --inventory /opt/wp/app/hegemon/ansible/hosts.prod --user mozart --private-key /root/.ssh/keys/prod p-backup01 -m s3
p-backup01 | FAILED >> {
    "failed": true, 
    "msg": "Traceback (most recent call last):\n  File \"<stdin>\", line 132, in <module>\nNameError: name 'module' is not defined\n", 
    "parsed": false
}
```

**Comment by davidvasandani** [comment]
@mpdehaan I specified the full path to the module

`ansible --inventory /opt/wp/app/hegemon/ansible/hosts.prod --user mozart --private-key /root/.ssh/keys/prod p-backup01 -m /opt/wp/virtualenv/hegemon/share/ansible/cloud/s3 -a "aws_access_key=****** aws_secret_key=****** bucket=wp_confluence_backup src=/backup/confluence mode=put"`

And still received the same error.

**Comment by jimi-c** [comment]
@davidneudorfer if you grab the source of the s3 module from the devel branch, do you continue to see the issue?

**Comment by davidvasandani** [comment]
Thanks @jimi-c the error is much more clear now.

```
p-backup01 | FAILED >> {
    "failed": true, 
    "msg": "boto required for this module"
}
```

boto and ansible are both in the virtualenv. Any suggestions how I might fix it?

```
(hegemon)[root@m-warp01 hegemon]# pip install boto --upgrade
Requirement already up-to-date: boto in /opt/wp/virtualenv/hegemon/lib/python2.7/site-packages
Cleaning up...
(hegemon)[root@m-warp01 hegemon]# which python
/opt/wp/virtualenv/hegemon/bin/python
(hegemon)[root@m-warp01 hegemon]# which ansible
/opt/wp/virtualenv/hegemon/bin/ansible
```

**Comment by davidvasandani** [comment]
I'll continue this in the Google Group:
https://groups.google.com/forum/#!topic/ansible-project/MZAmhWaI9bY

It seems similar to:
 https://groups.google.com/forum/#!msg/ansible-project/ftlmfIC1DHk/ZAQ9Nj4xPLsJ

**Comment by jimi-c** [comment]
@davidneudorfer sounds good, but first guess would be that you may need to set ansible_python_interpreter to point to the virtualenv as James Martin mentions in that thread.
