### ISSUE TITLE
ansible-galaxy install fails with non-galaxy(.ansible.com) role dependencies

### ISSUE THREAD

**Issue by cspicer** [ansible/ansible#9173]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8 (devel 6af5455edc) last updated 2014/09/25 23:42:37 (GMT -700)
##### Environment:

Mac OS X 10.9.4
##### Summary:

If requirements.yml includes a non-galaxy (ie GitHub) dependency that itself has further non-galaxy dependencies defined in it's metadata the install operation will fail when running `ansible-galaxy install -r requirements.yml`.
##### Steps To Reproduce:
- Run `ansible-galaxy install -r requirements.yml` on a requirements file that has the following example contents:

```

---
- src: https://github.com/cspicer/ansible-test1
  name: test1
  path: vagrant/roles/

- src: https://github.com/cspicer/ansible-test2
  name: test2
  path: vagrant/roles/
```

There are three example repos used to reproduce this issue if needed: [1](https://github.com/cspicer/ansible-test1), [2](https://github.com/cspicer/ansible-test2) and [3](https://github.com/cspicer/ansible-test3)
##### Expected Results:

Successful installation of all roles defined in requirements.yml
##### Actual Results:

```
$ ansible-galaxy install -r requirements.yml
- executing: git clone https://github.com/cspicer/ansible-test1 test1
- executing: git archive --prefix=test1/ --output=/var/folders/20/c6ln5wl56hq5pf99gs09c9n80000gp/T/tmpUvlWy2.tar HEAD
- extracting test1 to vagrant/roles/test1
- test1 was installed successfully
- executing: git clone https://github.com/cspicer/ansible-test2 test2
- executing: git archive --prefix=test2/ --output=/var/folders/20/c6ln5wl56hq5pf99gs09c9n80000gp/T/tmpjjbDmU.tar HEAD
- extracting test2 to vagrant/roles/test2
- test2 was installed successfully
Traceback (most recent call last):
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 901, in <module>
    main()
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 895, in main
    fn(args, options, parser)
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 796, in execute_install
    dep = ansible.utils.role_yaml_parse(dep)
  File "/Users/spicy/Development/oss/ansible/lib/ansible/utils/__init__.py", line 418, in role_yaml_parse
    if 'github.com' in role["src"] and 'http' in role["src"] and '+' not in role["src"] and not role["src"].endswith('.tar.gz'):
KeyError: 'src'
```

**Comment by abadger** [comment]
After talking this over with @jimi-c it looks like 1.8 is going to change the syntax of role dependencies slightly.  I'll have to update the documentation to reflect that.  Try one of these two syntaxes and see if they work for you:

In your ansible-test2 repo, https://github.com/cspicer/ansible-test2/blob/master/meta/main.yml

```
---
dependencies:
  - "cspicer.apt,,apt"
  - src: https://github.com/cspicer/ansible-test2
    name: test2
```

Note: it's not special that one is a galaxy role and the other is github, you should also be able to write them like:

```
---
dependencies:
  - "https://github.com/cspicer/ansible-test2,,test2"
  - src: cspicer.apt
    name: apt
```

Working on a documentation patch now.  Let me know if the updated syntax works for you.

**Comment by abadger** [comment]
Actually, although it would be good to know if that worked, second round of talks about this has us thinking it's important to preserve backwards compat here.  I'm going to see if the new changes can continue to work while still supporting the old syntax.

**Comment by cspicer** [comment]
I'm getting a different error with the updated syntax:

Version:

```
$ ansible --version
ansible 1.8 (devel ad9ab8e033) last updated 2014/10/07 12:23:14 (GMT -700)
  lib/ansible/modules/core: (detached HEAD db5668b84c) last updated 2014/10/01 12:01:20 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 110250d344) last updated 2014/10/01 12:01:23 (GMT -700)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/07 12:30:15 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/07 12:30:31 (GMT -700)
  configured module search path = None
```

Error:

```
Traceback (most recent call last):
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 901, in <module>
    main()
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 895, in main
    fn(args, options, parser)
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 711, in execute_install
    roles_left = map(ansible.utils.role_yaml_parse, yaml.safe_load(f))
  File "/Users/spicy/Development/oss/ansible/lib/ansible/utils/__init__.py", line 418, in role_yaml_parse
    if 'github.com' in role["src"] and 'http' in role["src"] and '+' not in role["src"] and not role["src"].endswith('.tar.gz'):
TypeError: string indices must be integers, not str
```

requirements.yml:

```
---
dependencies:
  - "https://github.com/cspicer/ansible-test2,,test2"
```

**Comment by abadger** [comment]
It doesn't look like  https://github.com/cspicer/ansible-test2/blob/master/meta/main.yml was updated to me?  It still has

```
---
dependencies:
  - role: apt
  - role: test2
```

I'm just about to push a change which I think will make the old syntax work.  Note that the old syntax is:

```
---
dependencies:
  - role: cspicer.apt,,apt
  - role: https://github.com/cspicer/ansible-test2,,test2
```

So you still have to update your ansible-test2 meta/main.yml file for it to work with the change.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by cspicer** [comment]
I've posted on the mailing list for this issue as well, but I am still experiencing the problem noted above before the issue was closed. I've removed the sample repositories linked above since all that is really needed to replicate this issue is this [requirements.yml](https://gist.github.com/cspicer/7c3c37eaf8eff386f9ce)

with the following error output:

```
$ ansible-galaxy install -r requirements.yml
Traceback (most recent call last):
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 901, in <module>
    main()
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 895, in main
    fn(args, options, parser)
  File "/Users/spicy/Development/oss/ansible/bin/ansible-galaxy", line 711, in execute_install
    roles_left = map(ansible.utils.role_yaml_parse, yaml.safe_load(f))
  File "/Users/spicy/Development/oss/ansible/lib/ansible/utils/__init__.py", line 432, in role_yaml_parse
    if 'github.com' in role["src"] and 'http' in role["src"] and '+' not in role["src"] and not role["src"].endswith('.tar.gz'):
TypeError: string indices must be integers, not str
```

**Comment by mahmoudimus** [comment]
I am still seeing this issue.
