### ISSUE TITLE
Ansible doesn't work properly with connection:local and sudo:yes

### ISSUE THREAD

**Issue by pashinin** [ansible/ansible#9383]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 14.04 desktop
##### Summary:

I think I've tried every combination of params to **run Ansible locally and perform sudo actions**. It just doesn't give permissions to do it. Ether with `--ask-sudo-pass`, `--sudo`, `sudo ...` or not.
##### Steps To Reproduce:

```
ansible-playbook ansible/desktop.yml
```

```
- hosts: localhost
  connection: local
  ...
  tasks:
    - apt_repository: repo='ppa:alexey-smirnov/deadbeef'
      sudo: yes
```
##### Expected Results:

No errors
##### Actual Results:

```
failed: [localhost] => {"failed": true}
msg: [Errno 13] Permission denied
```

http://stackoverflow.com/questions/26460067/can-i-use-sudo-in-ansible-with-connection-local

**Comment by jimi-c** [comment]
Hi @pashinin, I've tested this on both 1.7.2 and devel (albeit on a Fedora-based system) and could not reproduce it. 

My thought is that there is some other error here beyond the sudo, though. Could you please include the full output of the playbook run as well as any other configuration changes you may have made? It might also be useful if you could use `strace` or some other tracing utility to ID the source of the permission denied error you're seeing.

**Comment by pashinin** [comment]
Another example. Output:

```
$ ansible-playbook ansible/desktop.yml

PLAY [localhost] ************************************************************** 

TASK: [KVM-Qemu] ************************************************************** 
failed: [localhost] => (item=kvm) => {"failed": true, "item": "kvm"}
stderr: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

msg: 'apt-get install 'kvm' ' failed: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/my_user_name/desktop.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1 
```

desktop.yml:

```
---
- hosts: localhost
  gather_facts: no
  connection: local
  sudo_user: my_user_name
  tasks:
    - name: KVM-Qemu
      apt: name={{item}} state=installed
      sudo: yes
      with_items:
        - kvm
```

Any thoughts? Because I don't understand why this happens.

**Comment by jimi-c** [comment]
@pashinin if you change the connection type to ssh, and execute it over that connection type, does it work or continue to fail?

**Comment by pashinin** [comment]
absolutely the same output

**Comment by pashinin** [comment]
It only works in 1 case - when I set up `.ssh/config` file to `ssh localhost` directly as root using keys. Not even close to a working "sudo" option

**Comment by pashinin** [comment]
As it always happens, now it works (but with `ssh` as you said + `--ask-sudo-pass`) + I've done key auth for both user and root@localhost. I'll leave it open as `connection:local` fucked my brain pretty well (and hey, I could have no sshd up and running on a desktop)

**Comment by RiaanBurger** [comment]
May have something similar:

desktop.yml

``` yaml
- hosts: 127.0.0.1
  connection: local
  remote_user: '{{ ansible_env.USER }}'
  roles:
    - youtube-dl
```

roles/youtube-dl/tasks/main.yml

``` yaml
- name: 'Add the PPA for youtube-dl'
  apt_repository: repo='ppa:nilarimogard/webupd8'
  sudo: yes
```

Output:

```
TASK: [youtube-dl | Add the PPA for youtube-dl] ******************************* 
<127.0.0.1> REMOTE_MODULE apt_repository repo='ppa:nilarimogard/webupd8' validate_certs=no
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1414883616.5-251237391729976 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1414883616.5-251237391729976 && echo $HOME/.ansible/tmp/ansible-tmp-1414883616.5-251237391729976']
<127.0.0.1> PUT /tmp/tmpDtBe8P TO /home/riaan/.ansible/tmp/ansible-tmp-1414883616.5-251237391729976/apt_repository
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=ikrwijnkyvzmiyksxkrqwavskqwjccfb] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-ikrwijnkyvzmiyksxkrqwavskqwjccfb; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/riaan/.ansible/tmp/ansible-tmp-1414883616.5-251237391729976/apt_repository; rm -rf /home/riaan/.ansible/tmp/ansible-tmp-1414883616.5-251237391729976/ >/dev/null 2>&1'"'"''
failed: [127.0.0.1] => {"failed": true}
msg: Invalid repository string: ppa:nilarimogard/webupd8

FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
@RiaanBurger that does not appear to be related, instead it's complaining about the repository string and doesn't appear to be caused by sudo.

**Comment by RiaanBurger** [comment]
Apologies and thank you: Your reply led be down a different troubleshooting path and using the CLI used in this issue #6133 I tried:

``` bash
ansible localhost -i "localhost," -m "apt_repository" -a "repo=ppa:nilarimogard/webupd8" -c local
```

Result:

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "Invalid repository string: ppa:nilarimogard/webupd8"
}
```

A few internet searches later, turns out the problem is that I'm installing on Mint which doesn't support PPAs for apt_repository as per this issue: #4587

Hope that helps someone coming across this in future searches.

Now to find a workaround.

PS: Very friendly support here at Ansible GitHub issues; Been reading a lot of them, thanks.

**Comment by denvut** [comment]
I faced a similar problem, and me help this:  sudo_user: root

example:

``` ansible
  - hosts: localhost
    tasks:
    - name: svninstall
      apt: name=subversion state=installed 
      sudo_user: root
```

**Comment by jimi-c** [comment]
Hi @denvut, we're currently working on correcting local+su on the devel branch, hope to have something done this week. Thanks!

**Comment by bcoca** [comment]
Sudo should now work properly in current devel.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe this issue has been resolved in the current devel branch, and will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by sunshine69** [comment]
I still see then problems with 2.1.0 so obviously it is not fixed.

**Comment by jimi-c** [comment]
@sunshine69 please open a new issue with an example demonstrating how this does not work. This bug is a year old, so you may be hitting some new situation and not this one exactly.

**Comment by pawelprazak** [comment]
I see similar issue with ansible 2.1.1.0
