### ISSUE TITLE
Extra var not present when host var evaluated

### ISSUE THREAD

**Issue by jscheid** [ansible/ansible#9667]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.0 (bug introduced by https://github.com/ansible/ansible/commit/f1267c0b053e5975dc08c151530c802015902242#diff-af869caf5f6f46706dbf35970e39c686R1166)
##### Environment:

N/A
##### Summary:

Can't rely anymore on extra variables being present when host variables are evaluated.
##### Steps To Reproduce:

Run the playbook in https://gist.github.com/jscheid/fac33da8580ad1880606

More generally:
- Define a host variable that applies `to_json` to an extra variable
- Use the `template` action 
##### Expected Results:

Extra variables should always be set when host variables are being evaluated.

Output with 716f3eb6d98af14dc896f4bd3b551c7c85febb6c:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [template src=/dev/null dest=/dev/null] ********************************* 
ok: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

Extra variables aren't always set when host variables are being evaluated.

Output with f1267c0b053e5975dc08c151530c802015902242:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [template src=/dev/null dest=/dev/null] ********************************* 
fatal: [127.0.0.1] => an unexpected type error occurred. Error was Undefined is not JSON serializable

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/redacted/playbook.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0   
```

**Comment by jscheid** [comment]
To clarify, this issue is also present in 1.8.1 and current HEAD (34ec877fe374413dfcacbbb05214e975ed43200c)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jscheid** [comment]
Hi, and thanks for the quick fix. Unfortunately, while it does fix the test case I had put together for this, our playbook is still broken with latest HEAD. I've submitted a new issue at #9684. Thanks again!
