### ISSUE TITLE
delegate_to templating problem when using 'groups' var

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#9855]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Ubuntu 14.04
##### Summary:

When using delegate_to with an inventory variable that uses another variable that includes the 'group' variable, the delegate_to host isn't templated correctly.

If the variable is defined in the playbook, or if it's using the 'group' var directly, it works as expected.
##### Steps To Reproduce:

inv:

```
server1 ansible_connection=local
server2 ansible_connection=local
```

group_vars/all:

```
server_list: "{{ groups.all }}"
first_server: "{{ server_list | first }}"
```

playbook.yml:

```

---
- hosts: server1
  tasks:
    - debug: var=first_server  # Variable is templated correctly here

    - ping:
      delegate_to: "{{ first_server }}"
```
##### Expected Results:

```
TASK: [debug var=first_server] ************************************************ 
ok: [server2] => {
    "first_server": "server1"
}

TASK: [ping ] ***************************************************************** 
ok: [server2 -> server1] 
```
##### Actual Results:

```
TASK: [debug var=first_server] ************************************************ 
ok: [server2] => {
    "first_server": "server1"
}

TASK: [ping ] ***************************************************************** 
fatal: [server2 -> {] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

FATAL: all hosts have already failed -- aborting
```

**Comment by redbaron** [comment]
duplicate or related to https://github.com/ansible/ansible/issues/9838

**Comment by abadger** [comment]
Agreed.

@hkariti I think this was fixed in: https://github.com/ansible/ansible/commit/3269a349f32a2b5c1fc079a2d174e01c541f444b  If you'd like to try the patch  to lib/ansible/runner/**init**.py  I think that will solve this issue.  If not, I need to know so that I can find out what is still borken :-)

That fix will be included when we make our next ansible release.

**Comment by hkariti** [comment]
@abadger just tried it on HEAD and on 3269a34 specifically. Still broken.

**Comment by hkariti** [comment]
any progress on this one?

**Comment by azimut** [comment]
+1

**Comment by tftm** [comment]
+1

**Comment by ynnt** [comment]
+1

**Comment by asedeno** [comment]
This just bit me too.

**Comment by conorsch** [comment]
+1

**Comment by conorsch** [comment]
After revisiting this issue and trying to find a workaround, I've concluded the problem is due to a common inventory misconfiguration, and **not** a bug in Ansible. The code for `delegate_to` definitely supports handling expressions, at least in v1.9.4. 

When using a hybrid inventory where group membership is specified in a static hosts file, it's possible for the group membership to be overlooked when specifying a dynamic inventory source directly. Take the following directory structure as an example:

```
inventory/
├── hosts
└── vagrant
```

```
$ cat inventory/hosts
[ossec_manager]
test-ossec-server

[ossec_agents]
test-apt-server
```

The `vagrant` file is the dynamic inventory script from `./contrib/inventory/vagrant.py` in the main Ansible repo. When invoking a playbook that uses `delegate_to: "{{ groups.ossec_manager | first }}"` and specifying `-i inventory/vagrant`, the playbook will fail with this error:

```
TASK: [ossec-agent | Copy OSSEC configuration] **** 
fatal: [test-apt-server] => {'msg': "AnsibleUndefinedVariable: One or more 
undefined variables: 'dict object' has no attribute 'ossec_manager'", 'failed': 
True}
fatal: [test-apt-server] => {'msg': "AnsibleUndefinedVariable: One or more 
undefined variables: 'dict object' has no attribute 'ossec_manager'", 'failed': 
True}

FATAL: all hosts have already failed -- aborting
```

However, the playbook succeeds when passing `-i inventory` to the script, since Ansible reads both the dynamic and static inventory sources. In the case of OP's report, it looks like the solution is to force reading the `group_vars/all` file via `vars_files` in the playbook, which is sometimes necessary when using dynamic inventories. (The problem usually arises when `group_vars` is [not adjacent to the playbook that's being invoked](https://github.com/ansible/ansible/issues/11238).)

@hkariti, @azimut, @tftm, @ynnt Can you check your configs to see if the suggestion above resolves the issue? Ensure that:
- group membership is being provided by the inventory
- the `group_vars` directory is adjacent to the playbook, _or_ manually source it via `group_vars/all` or similar.

and you should be ready to rock.

**Comment by hkariti** [comment]
Dont have time to check now, but my first instinct is that it won't help:
- While I do use inventory directories, I _never_ use the inventory files
  directly, always the dir. Plus, my example in the op didn't use an
  inventory dir.
- The bug description mentions that it happens when the variable in the
  delegate_to option uses _another_ var that uses `groups`. Also that other
  var should be an inventory, not playbook, variable.

Does my original example still reproduce the bug? Are you able to make it
not to?

Thanks

**Comment by hkariti** [comment]
this appears to be fixed in devel, closing.
